import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import {CarIcon, MoonIcon, PawIcon, BabyIcon} from '@/components/icons';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SocialLinks from '@/components/SocialLinks';
import Feature from '@/components/Feature';
import SectionTitle from '@/components/SectionTitle';

export const metadata:Metadata={
  title:'Appartements près de Venise',description:'Rossi Apartment et Dimora Castelli à Marghera : parking privé, liaisons avec Venise 24 h/24, accueil Pet Friendly et Family Friendly.',
  openGraph:{title:'Marghera Venice Apartments | Votre séjour près de Venise',description:'Deux appartements à Marghera avec parking privé et liaisons avec Venise 24 h/24.',images:[{url:'/images/home-rialto-vincenzo-landino.webp',alt:'Venise n’est que le début.'}],type:'website'},
  twitter:{card:'summary_large_image',title:'Marghera Venice Apartments',description:'Deux appartements à Marghera avec parking privé et liaisons avec Venise 24 h/24.',images:['/images/home-rialto-vincenzo-landino.webp']},
  alternates:{canonical:'/fr',languages:{'it-IT':'/','en-GB':'/en','de-DE':'/de','fr-FR':'/fr','es-ES':'/es','zh-CN':'/zh','x-default':'/'}}
};
const inspiration=[
 {title:'Découvrir Venise',text:'Îles, événements et conseils locaux pour découvrir Venise avec curiosité.',image:'/images/scopri-venezia-michael-heise.webp',alt:'Bassin de Saint-Marc à Venise',href:'/fr/discover-venice'},
 {title:'Découvrir la Vénétie',text:'Riviera del Brenta, collines du Prosecco et belles villes d’art.',image:'/images/valdobbiadene.webp',alt:'Collines et vignobles du Prosecco à Valdobbiadene',href:'/fr/discover-veneto'},
 {title:'Expériences',text:'Balades en gondole, transferts privés, domaines viticoles et expériences sélectionnées.',image:'/images/gondola.webp',alt:'Gondole naviguant sur les canaux de Venise',href:'/fr/experiences'},
 {title:'Guides & Événements',text:'Redentore, Carnaval, Biennale et informations pratiques.',image:'/images/redentore.webp',alt:'Fête du Redentore dans la lagune de Venise',href:'/fr/journal'},
];
const journal=[
 {title:'Rejoindre Venise depuis Marghera',text:'Bus et trains, informations utiles et liberté de rentrer même la nuit.',image:'/images/home-come-raggiungere-venezia.webp',alt:'Liaisons en bus et en train entre Marghera et Venise',href:'/fr/getting-to-venice'},
 {title:'La Riviera del Brenta en une journée',text:'Villas vénitiennes, art et nature à quelques minutes en voiture.',image:'/images/veneto-riviera-brenta-final.webp',alt:'Paysage de la Riviera del Brenta',href:'/fr/guide/riviera-del-brenta'},
 {title:'Venise avec des enfants',text:'Musées, activités et conseils pour une agréable journée en famille.',image:'/images/venezia-bambini-museo-storia-naturale.webp',alt:'Musée d’Histoire naturelle de Venise pour les familles',href:'/fr/journal/venezia-con-bambini'},
];
export default function Home(){return <><Header lang="fr"/><main>
<section className="relative min-h-[88vh] overflow-hidden pt-20"><Image src="/images/home-rialto-vincenzo-landino.webp" alt='Venise n’est que le début.' fill priority sizes="100vw" className="object-cover object-center"/><div className="hero-overlay absolute inset-0"/><p className="absolute bottom-4 right-5 z-20 text-[11px] text-white/90 drop-shadow-md">Foto: Vincenzo Landino – Unsplash</p><div className="relative mx-auto flex min-h-[calc(88vh-5rem)] max-w-7xl items-center px-5 py-20 lg:px-8"><div className="max-w-4xl text-white"><p className="text-xs font-black uppercase tracking-[.25em] text-gold">Marghera · Venise</p><h1 className="mt-5 font-serif text-6xl leading-[.95] md:text-8xl">Venise n’est que le début.</h1><p className="mt-7 max-w-2xl text-xl text-white/85">Deux appartements avec parking privé, liaisons avec Venise 24 h/24 et un accueil chaleureux pensé pour les familles et les compagnons à quatre pattes.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#case" className="rounded-full bg-gold px-7 py-4 font-bold text-navy transition hover:-translate-y-1">Découvrir nos appartements</a><a href='https://wa.me/393514462261?text=Bonjour%2C%20je%20visite%20le%20site%20Marghera%20Venice%20Apartments%20et%20je%20souhaite%20v%C3%A9rifier%20les%20disponibilit%C3%A9s.%20Mes%20dates%20sont%20%3A%20' target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/60 px-7 py-4 font-bold text-white transition hover:bg-white hover:text-navy">Vérifier les disponibilités sur WhatsApp</a></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm font-bold text-white/90"><span>Parking privé</span><span>Venise 24 h/24</span><span>Pet Friendly</span><span>Family Friendly</span></div></div></div></section>
<section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Pourquoi nous choisir' title='Plus de liberté, moins de soucis' text='Séjournez près de Venise sans renoncer à votre voiture, à l’espace d’un vrai logement ni aux petites attentions qui rendent le voyage plus simple.'/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Feature icon={<CarIcon/>} title='Parking privé' text='Votre voiture reste sur une place privée réservée pendant que vous visitez Venise.'/><Feature icon={<MoonIcon/>} title='Venise 24 h/24' text='Les liaisons de jour comme de nuit vous permettent de profiter de Venise et de rentrer quand vous le souhaitez.'/><Feature icon={<PawIcon/>} title='Pet Friendly' text='Un couchage ainsi que des gamelles pour l’eau et la nourriture sont disponibles gratuitement pour votre compagnon de voyage.'/><Feature icon={<BabyIcon/>} title='Family Friendly' text='Un lit bébé ou un petit lit avec linge est disponible gratuitement sur demande dans les deux appartements.'/></div></div></section>
<section id="case" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Nos appartements' title='Choisissez votre espace près de Venise' text='Deux appartements authentiques, photographiés exactement comme vous les trouverez à votre arrivée.'/><div className="grid gap-8 lg:grid-cols-2">{[
 {title:'Rossi Apartment',sub:'Jusqu’à 7 personnes · idéal pour les familles et les groupes',image:'/images/rossi-card.webp',alt:'Rossi Apartment Marghera Venice',href:'/fr/apartments/rossi-apartment'},
 {title:'Dimora Castelli',sub:'Jusqu’à 5 personnes · intime, accueillant et relaxant',image:'/images/castelli-card.webp',alt:'Dimora Castelli Marghera Venice',href:'/fr/apartments/dimora-castelli'}
].map(x=><article key={x.title} className="group overflow-hidden rounded-[2rem] bg-white shadow-soft"><div className="relative h-[420px] overflow-hidden"><Image src={x.image} alt={x.alt} fill sizes="(min-width:1280px) 25vw, (min-width:768px) 50vw, 100vw" className="card-image object-cover"/></div><div className="p-8"><h3 className="font-serif text-4xl text-navy">{x.title}</h3><p className="mt-2 text-slate-600">{x.sub}</p><div className="mt-6 flex flex-wrap gap-2 text-xs font-bold text-navy"><span className="rounded-full bg-cream px-3 py-2">Parking privé</span><span className="rounded-full bg-cream px-3 py-2">Pet Friendly</span><span className="rounded-full bg-cream px-3 py-2">Family Friendly</span></div><Link href={x.href} className="mt-7 inline-block font-bold text-gold">Découvrir l’appartement →</Link></div></article>)}</div></div></section>
<section id="ispirazione" className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Laissez-vous inspirer' title='Le voyage commence avant votre arrivée' text='Venise, la Vénétie et les expériences que nous recommandons à nos voyageurs.' center/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{inspiration.map(x=><article key={x.title} className="group overflow-hidden rounded-3xl bg-white shadow-soft"><div className="relative h-56 overflow-hidden"><Image src={x.image} alt={x.alt} fill sizes="(min-width:1280px) 25vw, (min-width:768px) 50vw, 100vw" className="card-image object-cover"/></div><div className="p-6"><h3 className="font-serif text-3xl text-navy">{x.title}</h3><p className="mt-3 text-slate-600">{x.text}</p><Link href={x.href} className="mt-5 inline-block font-bold text-gold">En savoir plus →</Link></div></article>)}</div></div></section>
<section id="pet-family" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Pet & Family" title='Chaque voyageur est vraiment le bienvenu' text='Des services gratuits sur demande, pensés pour rendre le voyage plus facile.'/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[['/images/pet-dog-clean.webp', 'Compagnons à quatre pattes', 'Couchage et gamelles pour l’eau et la nourriture.', 'Chien accueilli dans un appartement Pet Friendly près de Venise'],['/images/family-culla-reale.webp', 'Lit bébé gratuit', 'Avec matelas et linge de lit.', 'Lit bébé gratuit avec matelas et linge'],['/images/family-lettino-reale.webp', 'Petit lit gratuit', 'Prêt pour le repos des plus petits.', 'Petit lit gratuit sur demande'],['/images/family-together-clean.webp', 'De l’espace pour la famille', 'Pièces spacieuses et cuisine entièrement équipée.', 'Famille dans un appartement spacieux près de Venise']].map(([img,title,text,alt])=><article key={title} className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="relative h-52"><Image src={img} alt={alt} fill sizes="(min-width:1280px) 25vw, (min-width:768px) 50vw, 100vw" className="object-cover"/></div><div className="p-6"><h3 className="font-serif text-2xl text-navy">{title}</h3><p className="mt-2 text-slate-600">{text}</p></div></article>)}</div></div></section>
<section id="journal" className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Journal' title='Des guides vraiment utiles' text='Des contenus locaux et pratiques pour organiser votre voyage en toute sérénité.'/><div className="grid gap-6 lg:grid-cols-3">{journal.map(x=><article key={x.title} className="overflow-hidden rounded-3xl bg-white shadow-soft"><div className="relative h-60"><Image src={x.image} alt={x.alt} fill sizes="(min-width:1024px) 33vw, 100vw" className="object-cover object-center"/></div><div className="p-7"><h3 className="font-serif text-3xl text-navy">{x.title}</h3><p className="mt-3 text-slate-600">{x.text}</p><Link href={x.href} className="mt-5 inline-block font-bold text-gold transition hover:translate-x-1">Lire le guide →</Link></div></article>)}</div><div className="mt-10 text-center"><Link href="/fr/journal" className="inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white transition hover:-translate-y-1 hover:bg-navy/90">Découvrir tout le Journal →</Link></div></div></section>
<section id="mappa" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Tout à portée de main' title='Un point de départ, une multitude de destinations' text='Notre carte illustrée montre la position réelle de Venise, de la lagune et des principales destinations de la Vénétie.'/><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-cream shadow-soft"><Image src="/images/mappa-veneto-definitiva.webp" alt='Carte illustrée des principales destinations accessibles depuis Marghera entre Venise, la lagune et la Vénétie' width={1536} height={1024} className="h-auto w-full"/></div></div></section>
<section id="direct-contact" className="scroll-mt-20 bg-navy py-20 text-center text-white"><div className="mx-auto max-w-3xl px-5"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Contact direct</p><h2 className="mt-3 font-serif text-5xl">Parlez-nous de votre voyage</h2><p className="mt-5 text-lg text-white/75">Envoyez-nous vos dates et le nombre de voyageurs : nous vous répondrons personnellement avec les disponibilités et toutes les informations utiles pour votre séjour.</p><a href='https://wa.me/393514462261?text=Bonjour%2C%20je%20visite%20le%20site%20Marghera%20Venice%20Apartments%20et%20je%20souhaite%20v%C3%A9rifier%20les%20disponibilit%C3%A9s.%20Mes%20dates%20sont%20%3A%20' target="_blank" rel="noopener noreferrer" className="mt-8 inline-block rounded-full bg-gold px-8 py-4 font-bold text-navy">Vérifier les disponibilités</a><div className="mt-7 flex justify-center"><SocialLinks className="justify-center text-white/80" lang="fr"/></div></div></section>
</main><Footer lang="fr"/></>}
