import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata:Metadata={title:'Venice Travel Journal | Events, Food & Local Tips',description:'Venice events, traditions, family travel, food, transport and practical local advice from Marghera Venice Apartments.',alternates:{canonical:'/en/journal',languages:{'it-IT':'/journal','en-GB':'/en/journal','de-DE':'/de/journal','fr-FR':'/fr/journal','es-ES':'/es/journal','zh-CN':'/zh/journal','x-default':'/journal'}},openGraph:{title:'Venice Travel Journal',description:'Events, traditions and practical ideas for experiencing Venice with more local context.',url:'/en/journal',locale:'en_GB',type:'website',images:['/images/home-rialto-vincenzo-landino.webp']},twitter:{card:'summary_large_image',images:['/images/home-rialto-vincenzo-landino.webp']}};
const articles=[
['Venice Historical Regatta 2026','Events','Sunday 6 September: historical water parade, Voga alla Veneta and rowing races on the Grand Canal.','/images/journal-regata-storica-2026.webp','Historic boats during the Venice Regata Storica on the Grand Canal','regata-storica-2026','6 SEPTEMBER 2026'],
['The Venice Glass Week 2026','Art & Culture','The tenth edition celebrates glassmaking with more than 200 events across Venice, Mestre and Murano.','/images/journal-venice-glass-week-2026-card.webp','Official artwork for the tenth edition of The Venice Glass Week 2026','venice-glass-week-2026','12–20 SEPTEMBER 2026'],
['Vogalonga in Venice: the great lagoon rowing celebration','Events','A 30-kilometre non-competitive route through the lagoon, islands and Grand Canal, celebrating rowing and Venice.','/images/journal-vogalonga-2027-card.webp','Rowing boats during the Vogalonga in the Venice Lagoon','vogalonga-2027','MAY 2027'],
['Venice Carnival','Events','Masks, parades, performances and a city that changes character for a few extraordinary weeks.','/images/journal-carnevale.webp','Masks and atmosphere during Venice Carnival','carnevale-di-venezia','23 JANUARY – 9 FEBRUARY 2027'],
['Festa del Redentore','Events','One of the nights Venetians care about most: tradition, boats and fireworks over the lagoon.','/images/journal-redentore.webp','Boats in the Venetian Lagoon during the Redentore celebration','festa-del-redentore','17 JULY 2027'],
['Christmas & New Year in Venice','Events','Winter lights, quieter calli and New Year celebrations in the heart of the lagoon.','/images/journal-natale-capodanno.webp','Venice illuminated during Christmas and New Year','natale-capodanno-venezia'],
['Venice Film Festival','Art & Culture','The Lido becomes an international cinema hub for premieres, screenings and the red carpet.','/images/journal-mostra-cinema.webp','Venice International Film Festival atmosphere on the Lido','mostra-del-cinema','2–12 SEPTEMBER 2026'],
['Homo Faber 2026: An Island of Light','Art & Culture','From 1 to 30 September, San Giorgio Maggiore celebrates contemporary craftsmanship from around the world.','/images/journal-homo-faber-2026-card.webp','Official artwork for Homo Faber 2026 An Island of Light','homo-faber-2026','1–30 SEPTEMBER 2026'],
['Venice Biennale','Art & Culture','Giardini, Arsenale and exhibitions across the city bring art, architecture and creativity to Venice.','/images/journal-biennale.webp','Contemporary art exhibition at the Venice Biennale','biennale-di-venezia','9 MAY – 22 NOVEMBER 2026'],
['Venice with children','Families','Squares, museums, vaporetto rides, green spaces and well-timed breaks can make Venice wonderful for children.','/images/venezia-bambini-campo-nuova.webp','Children playing in a Venetian campo','venezia-con-bambini'],
['Venice with your dog','Pet Friendly','Exploring calli and campi with your dog is possible with a little practical planning.','/images/journal-venezia-cane.webp','Visiting Venice with a dog','venezia-con-il-cane'],
['Acqua alta in Venice: what to know','Practical Venice','What acqua alta really is, how long it lasts, why some areas flood first and how MOSE works.','/images/journal-acqua-alta.webp','High water in a pedestrian area of Venice','acqua-alta-a-venezia'],
['Where to park when visiting Venice','Transport','Apartment parking, Piazzale Roma or Tronchetto: understand the main options when arriving by car.','/images/journal-parcheggi-venezia.webp','Parking and road access for visitors arriving in Venice by car','dove-parcheggiare-venezia'],
['The Venetian Spritz','Food & Traditions','For much of the world it is a cocktail. For Venetians, it is simply aperitivo.','/images/journal-spritz.webp','Venetian Spritz served for aperitivo','spritz-veneziano'],
['Venetian cicchetti','Food & Traditions','Baccalà, sarde in saor, meatballs and crostini: small bites that belong to Venice’s bacaro culture.','/images/journal-cicchetti.webp','Selection of Venetian cicchetti in a bacaro','cicchetti-veneziani'],
['How to enjoy Venice respectfully','Living Venice','Simple local etiquette for enjoying the city while remembering that Venice is also someone’s home.','/images/journal-buone-maniere.webp','Visitors walking through Venice while respecting local life','buone-maniere-a-venezia']];
export default function Journal(){return <><Header lang="en"/><main>
<section className="bg-navy px-5 pb-20 pt-36 text-white lg:px-8"><div className="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="mb-6 flex gap-2 text-sm text-white/70"><Link href="/en">Home</Link><span>›</span><span className="text-gold">Journal</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Venice, events and lagoon life</p><h1 className="mt-4 max-w-5xl font-serif text-6xl leading-none md:text-8xl">The Marghera Venice Apartments Journal</h1><p className="mt-6 max-w-3xl text-xl text-white/75">Events, traditions, practical information and local inspiration to help you experience Venice with more confidence and context.</p></div></section>
<section className="bg-cream py-12"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-wrap gap-3">{['Events','Art & Culture','Families','Pet Friendly','Practical Venice','Transport','Food & Traditions','Living Venice'].map(x=><span key={x} className="rounded-full border border-navy/15 bg-white px-4 py-2 text-sm font-bold text-navy">{x}</span>)}</div></div></section>
<section className="bg-cream pb-24"><div className="mx-auto grid max-w-7xl gap-7 px-5 md:grid-cols-2 xl:grid-cols-3 lg:px-8">{articles.map(([title,category,text,image,alt,slug,eventDate])=><article key={slug} className="group overflow-hidden rounded-[2rem] bg-white shadow-soft"><Link href={`/en/journal/${slug}`} className="block"><div className="relative h-64 overflow-hidden"><Image src={image} alt={alt} fill sizes="(min-width:1280px) 33vw, (min-width:768px) 50vw, 100vw" className="card-image object-cover"/></div><div className="p-7">{eventDate&&<p className="mb-3 inline-flex rounded-full bg-navy px-3 py-1.5 text-[11px] font-black uppercase leading-4 tracking-[.14em] text-white">{eventDate}</p>}<p className="text-xs font-black uppercase tracking-[.18em] text-gold">{category}</p><h2 className="mt-3 font-serif text-4xl text-navy">{title}</h2><p className="mt-4 text-slate-600">{text}</p><span className="mt-6 inline-flex rounded-full bg-gold px-5 py-3 font-bold text-navy">Read article</span></div></Link></article>)}</div></section>
<section className="py-20"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Keep exploring</p><h2 className="mt-3 font-serif text-5xl text-navy">Looking for a specific destination?</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-slate-600">Our Guides focus on Venice, the islands and day trips across Veneto, while the Journal covers events, traditions and practical travel advice.</p><Link href="/en/guide" className="mt-7 inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white">Open all guides</Link></div></section>
</main><Footer lang="en"/></>}
