import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import {CarIcon, MoonIcon, PawIcon, BabyIcon} from '@/components/icons';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SocialLinks from '@/components/SocialLinks';
import Feature from '@/components/Feature';
import SectionTitle from '@/components/SectionTitle';

export const metadata:Metadata={
  title:'Apartments nahe Venedig',description:'Rossi Apartment und Dimora Castelli in Marghera: privater Parkplatz, Verbindungen nach Venedig rund um die Uhr sowie tier- und familienfreundliche Gastfreundschaft.',
  openGraph:{title:'Marghera Venice Apartments | Ihr Aufenthalt nahe Venedig',description:'Zwei Apartments in Marghera mit privatem Parkplatz und Verbindungen nach Venedig rund um die Uhr.',images:[{url:'/images/home-rialto-vincenzo-landino.webp',alt:'Venedig ist erst der Anfang.'}],type:'website'},
  twitter:{card:'summary_large_image',title:'Marghera Venice Apartments',description:'Zwei Apartments in Marghera mit privatem Parkplatz und Verbindungen nach Venedig rund um die Uhr.',images:['/images/home-rialto-vincenzo-landino.webp']},
  alternates:{canonical:'/de',languages:{'it-IT':'/','en-GB':'/en','de-DE':'/de','fr-FR':'/fr','es-ES':'/es','zh-CN':'/zh','x-default':'/'}}
};
const inspiration=[
 {title:'Venedig entdecken',text:'Inseln, Veranstaltungen und lokale Tipps, um Venedig neugierig zu erleben.',image:'/images/scopri-venezia-michael-heise.webp',alt:'Markusplatz und Lagune von Venedig',href:'/de/discover-venice'},
 {title:'Venetien entdecken',text:'Brenta-Riviera, Prosecco-Hügel und wunderschöne Kunststädte.',image:'/images/valdobbiadene.webp',alt:'Prosecco-Hügel und Weinberge bei Valdobbiadene',href:'/de/discover-veneto'},
 {title:'Erlebnisse',text:'Gondelfahrten, private Transfers, Weingüter und ausgewählte Erlebnisse.',image:'/images/gondola.webp',alt:'Gondel in den Kanälen von Venedig',href:'/de/experiences'},
 {title:'Guides & Events',text:'Redentore, Karneval, Biennale und praktische Reiseinformationen.',image:'/images/redentore.webp',alt:'Redentore-Fest in der Lagune von Venedig',href:'/de/journal'},
];
const journal=[
 {title:'Von Marghera nach Venedig',text:'Busse und Züge, nützliche Informationen und die Freiheit, auch nachts zurückzukehren.',image:'/images/home-come-raggiungere-venezia.webp',alt:'Bus- und Bahnverbindungen zwischen Marghera und Venedig',href:'/de/getting-to-venice'},
 {title:'Brenta-Riviera an einem Tag',text:'Venezianische Villen, Kunst und Natur nur eine kurze Autofahrt entfernt.',image:'/images/veneto-riviera-brenta-final.webp',alt:'Landschaft der Brenta-Riviera',href:'/de/guide/riviera-del-brenta'},
 {title:'Venedig mit Kindern',text:'Museen, Aktivitäten und Tipps für einen schönen Familientag.',image:'/images/venezia-bambini-museo-storia-naturale.webp',alt:'Naturkundemuseum in Venedig für Familien',href:'/de/journal/venezia-con-bambini'},
];
export default function Home(){return <><Header lang="de"/><main>
<section className="relative min-h-[88vh] overflow-hidden pt-20"><Image src="/images/home-rialto-vincenzo-landino.webp" alt='Venedig ist erst der Anfang.' fill priority sizes="100vw" className="object-cover object-center"/><div className="hero-overlay absolute inset-0"/><p className="absolute bottom-4 right-5 z-20 text-[11px] text-white/90 drop-shadow-md">Foto: Vincenzo Landino – Unsplash</p><div className="relative mx-auto flex min-h-[calc(88vh-5rem)] max-w-7xl items-center px-5 py-20 lg:px-8"><div className="max-w-4xl text-white"><p className="text-xs font-black uppercase tracking-[.25em] text-gold">Marghera · Venedig</p><h1 className="mt-5 font-serif text-6xl leading-[.95] md:text-8xl">Venedig ist erst der Anfang.</h1><p className="mt-7 max-w-2xl text-xl text-white/85">Zwei Apartments mit privatem Parkplatz, Verbindungen nach Venedig rund um die Uhr und einer herzlichen Gastfreundschaft für Familien und vierbeinige Reisebegleiter.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#case" className="rounded-full bg-gold px-7 py-4 font-bold text-navy transition hover:-translate-y-1">Unsere Apartments entdecken</a><a href='https://wa.me/393514462261?text=Hallo%2C%20ich%20besuche%20die%20Website%20von%20Marghera%20Venice%20Apartments%20und%20m%C3%B6chte%20die%20Verf%C3%BCgbarkeit%20pr%C3%BCfen.%20Meine%20Reisedaten%20sind%3A%20' target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/60 px-7 py-4 font-bold text-white transition hover:bg-white hover:text-navy">Verfügbarkeit über WhatsApp prüfen</a></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm font-bold text-white/90"><span>Privater Parkplatz</span><span>Venedig rund um die Uhr</span><span>Haustierfreundlich</span><span>Familienfreundlich</span></div></div></div></section>
<section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Warum bei uns übernachten' title='Mehr Freiheit, weniger Sorgen' text='Übernachten Sie nahe Venedig, ohne auf Ihr Auto, den Platz einer echten Wohnung oder die kleinen Aufmerksamkeiten zu verzichten, die das Reisen einfacher machen.'/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Feature icon={<CarIcon/>} title='Privater Parkplatz' text='Ihr Auto bleibt auf einem reservierten Privatstellplatz, während Sie Venedig erkunden.'/><Feature icon={<MoonIcon/>} title='Venedig rund um die Uhr' text='Verbindungen am Tag und in der Nacht ermöglichen Ihnen, Venedig frei zu genießen und zurückzukehren, wann Sie möchten.'/><Feature icon={<PawIcon/>} title='Haustierfreundlich' text='Hundebett sowie Futter- und Wassernäpfe stehen für Ihren Reisebegleiter kostenlos bereit.'/><Feature icon={<BabyIcon/>} title='Familienfreundlich' text='Babybett oder Kinderbett mit Bettwäsche sind in beiden Apartments auf Anfrage kostenlos verfügbar.'/></div></div></section>
<section id="case" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Unsere Apartments' title='Wählen Sie Ihr Zuhause nahe Venedig' text='Zwei authentische Apartments, fotografiert genau so, wie Sie sie bei Ihrer Ankunft vorfinden.'/><div className="grid gap-8 lg:grid-cols-2">{[
 {title:'Rossi Apartment',sub:'Bis zu 7 Gäste · ideal für Familien und Gruppen',image:'/images/rossi-card.webp',alt:'Rossi Apartment Marghera Venice',href:'/de/apartments/rossi-apartment'},
 {title:'Dimora Castelli',sub:'Bis zu 5 Gäste · gemütlich, einladend und entspannend',image:'/images/castelli-card.webp',alt:'Dimora Castelli Marghera Venice',href:'/de/apartments/dimora-castelli'}
].map(x=><article key={x.title} className="group overflow-hidden rounded-[2rem] bg-white shadow-soft"><div className="relative h-[420px] overflow-hidden"><Image src={x.image} alt={x.alt} fill sizes="(min-width:1280px) 25vw, (min-width:768px) 50vw, 100vw" className="card-image object-cover"/></div><div className="p-8"><h3 className="font-serif text-4xl text-navy">{x.title}</h3><p className="mt-2 text-slate-600">{x.sub}</p><div className="mt-6 flex flex-wrap gap-2 text-xs font-bold text-navy"><span className="rounded-full bg-cream px-3 py-2">Privater Parkplatz</span><span className="rounded-full bg-cream px-3 py-2">Pet Friendly</span><span className="rounded-full bg-cream px-3 py-2">Family Friendly</span></div><Link href={x.href} className="mt-7 inline-block font-bold text-gold">Apartment entdecken →</Link></div></article>)}</div></div></section>
<section id="ispirazione" className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Lassen Sie sich inspirieren' title='Die Reise beginnt schon vor der Ankunft' text='Venedig, Venetien und Erlebnisse, die wir unseren Gästen empfehlen.' center/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{inspiration.map(x=><article key={x.title} className="group overflow-hidden rounded-3xl bg-white shadow-soft"><div className="relative h-56 overflow-hidden"><Image src={x.image} alt={x.alt} fill sizes="(min-width:1280px) 25vw, (min-width:768px) 50vw, 100vw" className="card-image object-cover"/></div><div className="p-6"><h3 className="font-serif text-3xl text-navy">{x.title}</h3><p className="mt-3 text-slate-600">{x.text}</p><Link href={x.href} className="mt-5 inline-block font-bold text-gold">Mehr entdecken →</Link></div></article>)}</div></div></section>
<section id="pet-family" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Pet & Family" title='Jeder Gast ist wirklich willkommen' text='Kostenlose Services auf Anfrage, die das Reisen leichter machen.'/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[['/images/pet-dog-clean.webp', 'Vierbeinige Freunde', 'Hundebett sowie Futter- und Wassernäpfe.', 'Hund als Gast in einem haustierfreundlichen Apartment nahe Venedig'],['/images/family-culla-reale.webp', 'Kostenloses Babybett', 'Mit Matratze und Bettwäsche.', 'Kostenloses Babybett mit Matratze und Bettwäsche'],['/images/family-lettino-reale.webp', 'Kostenloses Kinderbett', 'Bereit für die Erholung der Kleinsten.', 'Kostenloses Kinderbett auf Anfrage'],['/images/family-together-clean.webp', 'Platz für die Familie', 'Großzügige Räume und eine voll ausgestattete Küche.', 'Familie in einer großzügigen Wohnung nahe Venedig']].map(([img,title,text,alt])=><article key={title} className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="relative h-52"><Image src={img} alt={alt} fill sizes="(min-width:1280px) 25vw, (min-width:768px) 50vw, 100vw" className="object-cover"/></div><div className="p-6"><h3 className="font-serif text-2xl text-navy">{title}</h3><p className="mt-2 text-slate-600">{text}</p></div></article>)}</div></div></section>
<section id="journal" className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Journal' title='Guides, die wirklich helfen' text='Praktische lokale Inhalte, damit Sie Ihre Reise sicher und entspannt planen können.'/><div className="grid gap-6 lg:grid-cols-3">{journal.map(x=><article key={x.title} className="overflow-hidden rounded-3xl bg-white shadow-soft"><div className="relative h-60"><Image src={x.image} alt={x.alt} fill sizes="(min-width:1024px) 33vw, 100vw" className="object-cover object-center"/></div><div className="p-7"><h3 className="font-serif text-3xl text-navy">{x.title}</h3><p className="mt-3 text-slate-600">{x.text}</p><Link href={x.href} className="mt-5 inline-block font-bold text-gold transition hover:translate-x-1">Guide lesen →</Link></div></article>)}</div><div className="mt-10 text-center"><Link href="/de/journal" className="inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white transition hover:-translate-y-1 hover:bg-navy/90">Das ganze Journal entdecken →</Link></div></div></section>
<section id="mappa" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Alles in Reichweite' title='Eine Basis, unzählige Ziele' text='Unsere illustrierte Karte zeigt die tatsächliche Lage von Venedig, der Lagune und den wichtigsten Zielen in Venetien.'/><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-cream shadow-soft"><Image src="/images/mappa-veneto-definitiva.webp" alt='Illustrierte Karte der von Marghera erreichbaren Ziele in Venedig, der Lagune und Venetien' width={1536} height={1024} className="h-auto w-full"/></div></div></section>
<section id="direct-contact" className="scroll-mt-20 bg-navy py-20 text-center text-white"><div className="mx-auto max-w-3xl px-5"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Direkter Kontakt</p><h2 className="mt-3 font-serif text-5xl">Erzählen Sie uns von Ihrer Reise</h2><p className="mt-5 text-lg text-white/75">Senden Sie uns Ihre Reisedaten und die Anzahl der Gäste: Wir antworten persönlich mit Verfügbarkeit und allen wichtigen Informationen für Ihren Aufenthalt.</p><a href='https://wa.me/393514462261?text=Hallo%2C%20ich%20besuche%20die%20Website%20von%20Marghera%20Venice%20Apartments%20und%20m%C3%B6chte%20die%20Verf%C3%BCgbarkeit%20pr%C3%BCfen.%20Meine%20Reisedaten%20sind%3A%20' target="_blank" rel="noopener noreferrer" className="mt-8 inline-block rounded-full bg-gold px-8 py-4 font-bold text-navy">Verfügbarkeit prüfen</a><div className="mt-7 flex justify-center"><SocialLinks className="justify-center text-white/80" lang="de"/></div></div></section>
</main><Footer lang="de"/></>}
