import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import {CarIcon, MoonIcon, PawIcon, BabyIcon} from '@/components/icons';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SocialLinks from '@/components/SocialLinks';
import Feature from '@/components/Feature';
import SectionTitle from '@/components/SectionTitle';

export const metadata:Metadata={
  title:'Apartamentos cerca de Venecia',description:'Rossi Apartment y Dimora Castelli en Marghera: aparcamiento privado, conexiones con Venecia 24 horas, alojamiento pensado para mascotas y familias.',
  openGraph:{title:'Marghera Venice Apartments | Tu estancia cerca de Venecia',description:'Dos apartamentos en Marghera con aparcamiento privado y conexiones con Venecia las 24 horas.',images:[{url:'/images/home-rialto-vincenzo-landino.webp',alt:'Venecia es solo el comienzo.'}],type:'website'},
  twitter:{card:'summary_large_image',title:'Marghera Venice Apartments',description:'Dos apartamentos en Marghera con aparcamiento privado y conexiones con Venecia las 24 horas.',images:['/images/home-rialto-vincenzo-landino.webp']},
  alternates:{canonical:'/es',languages:{'it-IT':'/','en-GB':'/en','de-DE':'/de','fr-FR':'/fr','es-ES':'/es','zh-CN':'/zh','x-default':'/'}}
};
const inspiration=[
 {title:'Descubrir Venecia',text:'Islas, eventos y consejos locales para descubrir Venecia con curiosidad.',image:'/images/scopri-venezia-michael-heise.webp',alt:'Cuenca de San Marcos en Venecia',href:'/es/discover-venice'},
 {title:'Descubrir Véneto',text:'Riviera del Brenta, colinas del Prosecco y hermosas ciudades de arte.',image:'/images/valdobbiadene.webp',alt:'Colinas y viñedos del Prosecco en Valdobbiadene',href:'/es/discover-veneto'},
 {title:'Experiencias',text:'Paseos en góndola, traslados privados, bodegas y experiencias seleccionadas.',image:'/images/gondola.webp',alt:'Góndola navegando por los canales de Venecia',href:'/es/experiences'},
 {title:'Guías & Eventos',text:'Redentore, Carnaval, Biennale e información práctica para el viaje.',image:'/images/redentore.webp',alt:'Fiesta del Redentore en la laguna de Venecia',href:'/es/journal'},
];
const journal=[
 {title:'Cómo llegar a Venecia desde Marghera',text:'Autobuses y trenes, información útil y libertad para volver incluso de noche.',image:'/images/home-come-raggiungere-venezia.webp',alt:'Conexiones de autobús y tren entre Marghera y Venecia',href:'/es/getting-to-venice'},
 {title:'Riviera del Brenta en un día',text:'Villas venecianas, arte y naturaleza a pocos minutos en coche.',image:'/images/veneto-riviera-brenta-final.webp',alt:'Paisaje de la Riviera del Brenta',href:'/es/guide/riviera-del-brenta'},
 {title:'Venecia con niños',text:'Museos, actividades y consejos para disfrutar de un día en familia.',image:'/images/venezia-bambini-museo-storia-naturale.webp',alt:'Museo de Historia Natural de Venecia para familias',href:'/es/journal/venezia-con-bambini'},
];
export default function Home(){return <><Header lang="es"/><main>
<section className="relative min-h-[88vh] overflow-hidden pt-20"><Image src="/images/home-rialto-vincenzo-landino.webp" alt='Venecia es solo el comienzo.' fill priority sizes="100vw" className="object-cover object-center"/><div className="hero-overlay absolute inset-0"/><p className="absolute bottom-4 right-5 z-20 text-[11px] text-white/90 drop-shadow-md">Foto: Vincenzo Landino – Unsplash</p><div className="relative mx-auto flex min-h-[calc(88vh-5rem)] max-w-7xl items-center px-5 py-20 lg:px-8"><div className="max-w-4xl text-white"><p className="text-xs font-black uppercase tracking-[.25em] text-gold">Marghera · Venecia</p><h1 className="mt-5 break-words font-serif text-[clamp(3rem,8vw,6rem)] leading-[.98]">Venecia es solo el comienzo.</h1><p className="mt-7 max-w-2xl text-xl text-white/85">Dos apartamentos con aparcamiento privado, conexiones con Venecia las 24 horas y una acogida pensada para familias y compañeros de viaje de cuatro patas.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#case" className="rounded-full bg-gold px-7 py-4 font-bold text-navy transition hover:-translate-y-1">Descubre nuestros apartamentos</a><a href='https://wa.me/393514462261?text=Hola%2C%20estoy%20visitando%20la%20web%20de%20Marghera%20Venice%20Apartments%20y%20me%20gustar%C3%ADa%20consultar%20disponibilidad.%20Mis%20fechas%20son%3A%20' target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/60 px-7 py-4 font-bold text-white transition hover:bg-white hover:text-navy">Consultar disponibilidad por WhatsApp</a></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm font-bold text-white/90"><span>Aparcamiento privado</span><span>Venecia 24 h</span><span>Mascotas bienvenidas</span><span>Ideal para familias</span></div></div></div></section>
<section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Por qué elegirnos' title='Más libertad, menos preocupaciones' text='Alójate cerca de Venecia sin renunciar al coche, al espacio de una vivienda de verdad ni a esos detalles que hacen el viaje más fácil.'/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Feature icon={<CarIcon/>} title='Aparcamiento privado' text='Tu coche permanece en una plaza privada reservada mientras visitas Venecia.'/><Feature icon={<MoonIcon/>} title='Venecia 24 h' text='Las conexiones diurnas y nocturnas te permiten disfrutar de Venecia y volver cuando quieras.'/><Feature icon={<PawIcon/>} title='Mascotas bienvenidas' text='Cama para mascota y cuencos para agua y comida disponibles gratuitamente para tu compañero de viaje.'/><Feature icon={<BabyIcon/>} title='Ideal para familias' text='Cuna o cama infantil con ropa de cama, gratis bajo petición en ambos apartamentos.'/></div></div></section>
<section id="case" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Nuestros apartamentos' title='Elige tu espacio cerca de Venecia' text='Dos apartamentos auténticos, fotografiados tal y como los encontrarás al llegar.'/><div className="grid gap-8 lg:grid-cols-2">{[
 {title:'Rossi Apartment',sub:'Hasta 7 huéspedes · ideal para familias y grupos',image:'/images/rossi-card.webp',alt:'Rossi Apartment Marghera Venice',href:'/es/apartments/rossi-apartment'},
 {title:'Dimora Castelli',sub:'Hasta 5 huéspedes · acogedor, íntimo y relajante',image:'/images/castelli-card.webp',alt:'Dimora Castelli Marghera Venice',href:'/es/apartments/dimora-castelli'}
].map(x=><article key={x.title} className="group overflow-hidden rounded-[2rem] bg-white shadow-soft"><div className="relative h-[420px] overflow-hidden"><Image src={x.image} alt={x.alt} fill sizes="(min-width:1280px) 25vw, (min-width:768px) 50vw, 100vw" className="card-image object-cover"/></div><div className="p-8"><h3 className="font-serif text-4xl text-navy">{x.title}</h3><p className="mt-2 text-slate-600">{x.sub}</p><div className="mt-6 flex flex-wrap gap-2 text-xs font-bold text-navy"><span className="rounded-full bg-cream px-3 py-2">Aparcamiento privado</span><span className="rounded-full bg-cream px-3 py-2">Mascotas bienvenidas</span><span className="rounded-full bg-cream px-3 py-2">Ideal para familias</span></div><Link href={x.href} className="mt-7 inline-block font-bold text-gold">Descubre el apartamento →</Link></div></article>)}</div></div></section>
<section id="ispirazione" className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Déjate inspirar' title='El viaje empieza antes de llegar' text='Venecia, el Véneto y las experiencias que recomendamos a nuestros huéspedes.' center/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{inspiration.map(x=><article key={x.title} className="group overflow-hidden rounded-3xl bg-white shadow-soft"><div className="relative h-56 overflow-hidden"><Image src={x.image} alt={x.alt} fill sizes="(min-width:1280px) 25vw, (min-width:768px) 50vw, 100vw" className="card-image object-cover"/></div><div className="p-6"><h3 className="font-serif text-3xl text-navy">{x.title}</h3><p className="mt-3 text-slate-600">{x.text}</p><Link href={x.href} className="mt-5 inline-block font-bold text-gold">Descubre más →</Link></div></article>)}</div></div></section>
<section id="pet-family" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Mascotas & Familias" title='Cada huésped es realmente bienvenido' text='Servicios gratuitos bajo petición, pensados para hacer el viaje más fácil.'/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[['/images/pet-dog-clean.webp', 'Amigos de cuatro patas', 'Cama para mascota y cuencos para agua y comida.', 'Perro alojado en un apartamento que admite mascotas cerca de Venecia'],['/images/family-culla-reale.webp', 'Cuna gratuita', 'Con colchón y ropa de cama.', 'Cuna gratuita con colchón y ropa de cama'],['/images/family-lettino-reale.webp', 'Cama infantil gratuita', 'Lista para el descanso de los más pequeños.', 'Cama infantil gratuita bajo petición'],['/images/family-together-clean.webp', 'Espacio para la familia', 'Estancias amplias y cocina totalmente equipada.', 'Familia en un apartamento espacioso cerca de Venecia']].map(([img,title,text,alt])=><article key={title} className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="relative h-52"><Image src={img} alt={alt} fill sizes="(min-width:1280px) 25vw, (min-width:768px) 50vw, 100vw" className="object-cover"/></div><div className="p-6"><h3 className="font-serif text-2xl text-navy">{title}</h3><p className="mt-2 text-slate-600">{text}</p></div></article>)}</div></div></section>
<section id="journal" className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Journal' title='Guías que ayudan de verdad' text='Contenido local y práctico para organizar tu viaje con mayor tranquilidad.'/><div className="grid gap-6 lg:grid-cols-3">{journal.map(x=><article key={x.title} className="overflow-hidden rounded-3xl bg-white shadow-soft"><div className="relative h-60"><Image src={x.image} alt={x.alt} fill sizes="(min-width:1024px) 33vw, 100vw" className={`object-cover ${x.image === '/images/home-come-raggiungere-venezia.webp' ? 'object-top' : 'object-center'}`}/></div><div className="p-7"><h3 className="font-serif text-3xl text-navy">{x.title}</h3><p className="mt-3 text-slate-600">{x.text}</p><Link href={x.href} className="mt-5 inline-block font-bold text-gold transition hover:translate-x-1">Leer la guía →</Link></div></article>)}</div><div className="mt-10 text-center"><Link href="/es/journal" className="inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white transition hover:-translate-y-1 hover:bg-navy/90">Descubre todo el Journal →</Link></div></div></section>
<section id="mappa" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow='Todo al alcance' title='Una base, muchísimos destinos' text='Nuestro mapa ilustrado muestra la posición real de Venecia, la laguna y los principales destinos del Véneto.'/><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-cream shadow-soft"><Image src="/images/mappa-veneto-definitiva.webp" alt='Mapa ilustrado de los principales destinos accesibles desde Marghera entre Venecia, la laguna y el Véneto' width={1536} height={1024} className="h-auto w-full"/></div></div></section>
<section id="direct-contact" className="scroll-mt-20 bg-navy py-20 text-center text-white"><div className="mx-auto max-w-3xl px-5"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Contacto directo</p><h2 className="mt-3 font-serif text-5xl">Cuéntanos tu viaje</h2><p className="mt-5 text-lg text-white/75">Envíanos tus fechas y el número de huéspedes: te responderemos personalmente con disponibilidad y toda la información útil para tu estancia.</p><a href='https://wa.me/393514462261?text=Hola%2C%20estoy%20visitando%20la%20web%20de%20Marghera%20Venice%20Apartments%20y%20me%20gustar%C3%ADa%20consultar%20disponibilidad.%20Mis%20fechas%20son%3A%20' target="_blank" rel="noopener noreferrer" className="mt-8 inline-block rounded-full bg-gold px-8 py-4 font-bold text-navy">Consultar disponibilidad</a><div className="mt-7 flex justify-center"><SocialLinks className="justify-center text-white/80" lang="es"/></div></div></section>
</main><Footer lang="es"/></>}
