import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import {CarIcon, MoonIcon, PawIcon, BabyIcon} from '@/components/icons';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SocialLinks from '@/components/SocialLinks';
import Feature from '@/components/Feature';
import SectionTitle from '@/components/SectionTitle';


export const metadata:Metadata={
  title:'Marghera Venice Apartments | Appartamenti vicino a Venezia',
  description:'Rossi Apartment e Dimora Castelli a Marghera: parcheggio privato, collegamenti H24 per Venezia, accoglienza Pet Friendly e Family Friendly.',
  openGraph:{
    title:'Marghera Venice Apartments | Il tuo soggiorno vicino a Venezia',
    description:'Due appartamenti a Marghera con parcheggio privato e collegamenti H24 per Venezia.',
    images:[{url:'/images/home-rialto-vincenzo-landino.webp',alt:'Ponte di Rialto e Canal Grande a Venezia'}],
    type:'website'
  },
  twitter:{
    card:'summary_large_image',
    title:'Marghera Venice Apartments',
    description:'Due appartamenti a Marghera con parcheggio privato e collegamenti H24 per Venezia.',
    images:['/images/home-rialto-vincenzo-landino.webp']
  },
  alternates:{canonical:'/',languages:{'it-IT':'/','en-GB':'/en','de-DE':'/de','fr-FR':'/fr','es-ES':'/es','zh-CN':'/zh','x-default':'/'}}
};

const inspiration=[
 {title:'Scopri Venezia',text:'Itinerari, isole, eventi e consigli per vivere la città con curiosità.',image:'/images/scopri-venezia-michael-heise.webp',alt:'Bacino di San Marco a Venezia con Palazzo Ducale e Campanile',href:'/scopri-venezia'},
 {title:'Scopri il Veneto',text:'Riviera del Brenta, colline del Prosecco e città d’arte.',image:'/images/valdobbiadene.webp',alt:'Colline e vigneti del Prosecco nel territorio di Valdobbiadene',href:'/scopri-il-veneto'},
 {title:'Esperienze',text:'Gondola, NCC, cantine e attività selezionate.',image:'/images/gondola.webp',alt:'Gondola veneziana durante una navigazione tra i canali di Venezia',href:'/collaborazioni'},
 {title:'Guide & Eventi',text:'Redentore, Carnevale, Biennale e informazioni pratiche.',image:'/images/redentore.webp',alt:'Festa del Redentore a Venezia con barche e celebrazioni in laguna',href:'/journal'}
];
const journal=[
 {title:'Come raggiungere Venezia da Marghera',text:'Bus e treni, orari utili e libertà di rientrare anche di notte.',image:'/images/home-come-raggiungere-venezia.webp',alt:'Autobus e collegamenti pubblici tra Marghera e Venezia',href:'/come-raggiungere-venezia'},
 {title:'Riviera del Brenta in un giorno',text:'Ville venete, arte, natura e itinerari a pochi minuti in auto.',image:'/images/veneto-riviera-brenta-final.webp',alt:'Paesaggio della Riviera del Brenta con canale e case storiche',href:'/guide/riviera-del-brenta'},
 {title:'Venezia con bambini',text:'Musei, attività e consigli per una giornata piacevole in famiglia.',image:'/images/venezia-bambini-museo-storia-naturale.webp',alt:'Museo di Storia Naturale di Venezia, attività adatta alle famiglie con bambini',href:'/journal/venezia-con-bambini'}
];
export default function Home(){return <><Header/><main>
<section className="relative min-h-[88vh] overflow-hidden pt-20"><Image src="/images/home-rialto-vincenzo-landino.webp" alt="Ponte di Rialto a Venezia. Foto di Vincenzo Landino – Unsplash" fill priority sizes="100vw" className="object-cover object-center"/><div className="hero-overlay absolute inset-0"/><p className="absolute bottom-4 right-5 z-20 text-[11px] text-white/90 drop-shadow-md">Foto di Vincenzo Landino – Unsplash</p><div className="relative mx-auto flex min-h-[calc(88vh-5rem)] max-w-7xl items-center px-5 py-20 lg:px-8"><div className="max-w-4xl text-white"><p className="text-xs font-black uppercase tracking-[.25em] text-gold">Marghera · Venezia</p><h1 className="mt-5 font-serif text-6xl leading-[.95] md:text-8xl">Venezia è solo l’inizio.</h1><p className="mt-7 max-w-2xl text-xl text-white/85">Due appartamenti con parcheggio privato, collegamenti con Venezia 24 ore su 24 e un’accoglienza pensata per famiglie e amici a quattro zampe.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#case" className="rounded-full bg-gold px-7 py-4 font-bold text-navy transition hover:-translate-y-1">Scopri le nostre case</a><a href="https://wa.me/393514462261?text=Ciao%2C%20sto%20visitando%20il%20sito%20Marghera%20Venice%20Apartments%20e%20vorrei%20ricevere%20informazioni%20sulla%20disponibilit%C3%A0." target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/60 px-7 py-4 font-bold text-white transition hover:bg-white hover:text-navy">Verifica disponibilità su WhatsApp</a></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm font-bold text-white/90"><span>Parcheggio privato</span><span>Venezia H24</span><span>Pet Friendly</span><span>Family Friendly</span></div></div></div></section>
<section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Perché sceglierci" title="Più libertà, meno pensieri" text="Soggiorna vicino a Venezia senza rinunciare all’auto, agli spazi di una casa e alle attenzioni che rendono il viaggio più semplice."/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Feature icon={<CarIcon/>} title="Parcheggio privato" text="La tua auto rimane in uno spazio riservato mentre visiti Venezia."/><Feature icon={<MoonIcon/>} title="Venezia H24" text="Collegamenti diurni e notturni per vivere la città e rientrare quando vuoi."/><Feature icon={<PawIcon/>} title="Pet Friendly" text="Cuccia e ciotole disponibili gratuitamente per il tuo compagno di viaggio."/><Feature icon={<BabyIcon/>} title="Family Friendly" text="Culla o lettino con biancheria, gratuiti su richiesta in entrambe le case."/></div></div></section>
<section id="case" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Le nostre case" title="Scegli il tuo spazio vicino a Venezia" text="Due appartamenti autentici, fotografati così come li troverai al tuo arrivo."/><div className="grid gap-8 lg:grid-cols-2">{[
 {title:'Rossi Apartment',sub:'Fino a 7 ospiti · ideale per famiglie e gruppi',image:'/images/rossi-card.webp',alt:'Camera luminosa di Rossi Apartment a Marghera vicino a Venezia',href:'/case/rossi-apartment'},
 {title:'Dimora Castelli',sub:'Fino a 5 ospiti · raccolta, accogliente e rilassante',image:'/images/castelli-card.webp',alt:'Camera di Dimora Castelli a Marghera vicino a Venezia',href:'/case/dimora-castelli'}
].map(x=><article key={x.title} className="group overflow-hidden rounded-[2rem] bg-white shadow-soft"><div className="relative h-[420px] overflow-hidden"><Image src={x.image} alt={x.alt || x.title} fill sizes="(min-width:1280px) 25vw, (min-width:768px) 50vw, 100vw" className="card-image object-cover"/></div><div className="p-8"><h3 className="font-serif text-4xl text-navy">{x.title}</h3><p className="mt-2 text-slate-600">{x.sub}</p><div className="mt-6 flex flex-wrap gap-2 text-xs font-bold text-navy"><span className="rounded-full bg-cream px-3 py-2">Parcheggio privato</span><span className="rounded-full bg-cream px-3 py-2">Pet Friendly</span><span className="rounded-full bg-cream px-3 py-2">Family Friendly</span></div><Link href={x.href} className="mt-7 inline-block font-bold text-gold">Scopri la casa →</Link></div></article>)}</div></div></section>
<section id="ispirazione" className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Lasciati ispirare" title="Il viaggio comincia prima dell’arrivo" text="Venezia, il Veneto e le esperienze che consigliamo ai nostri ospiti." center/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{inspiration.map(x=><article key={x.title} className="group overflow-hidden rounded-3xl bg-white shadow-soft"><div className="relative h-56 overflow-hidden"><Image src={x.image} alt={x.alt || x.title} fill sizes="(min-width:1280px) 25vw, (min-width:768px) 50vw, 100vw" className="card-image object-cover"/></div><div className="p-6"><h3 className="font-serif text-3xl text-navy">{x.title}</h3><p className="mt-3 text-slate-600">{x.text}</p><Link href={x.href} className="mt-5 inline-block font-bold text-gold">Scopri di più →</Link></div></article>)}</div></div></section>
<section id="pet-family" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Pet & Family" title="Ogni ospite è davvero il benvenuto" text="Servizi gratuiti su richiesta, pensati per rendere più leggero il viaggio."/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[
 ['/images/pet-dog-clean.webp','Amici a quattro zampe','Cuccia e ciotole per acqua e cibo.','Cane ospite in un appartamento Pet Friendly vicino a Venezia'],['/images/family-culla-reale.webp','Culla gratuita','Completa di materasso e biancheria.','Culla gratuita con materasso e biancheria disponibile negli appartamenti'],['/images/family-lettino-reale.webp','Lettino gratuito','Pronto per il riposo dei più piccoli.','Lettino gratuito per bambini disponibile su richiesta negli appartamenti'],['/images/family-together-clean.webp','Spazio per la famiglia','Ambienti ampi e cucina attrezzata.','Famiglia in un ambiente spazioso e accogliente vicino a Venezia']
].map(([img,title,text,alt])=><article key={title} className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="relative h-52"><Image src={img} alt={alt || title} fill sizes="(min-width:1280px) 25vw, (min-width:768px) 50vw, 100vw" className="object-cover"/></div><div className="p-6"><h3 className="font-serif text-2xl text-navy">{title}</h3><p className="mt-2 text-slate-600">{text}</p></div></article>)}</div></div></section>
<section id="journal" className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Journal" title="Guide che aiutano davvero" text="Contenuti locali, pratici e pensati per organizzare il viaggio con più consapevolezza."/><div className="grid gap-6 lg:grid-cols-3">{journal.map(x=><article key={x.title} className="overflow-hidden rounded-3xl bg-white shadow-soft"><div className="relative h-60"><Image
  src={x.image}
  alt={x.alt || x.title}
  fill
  sizes="(min-width:1024px) 33vw, 100vw"
  className={`object-cover ${x.title === 'Come raggiungere Venezia da Marghera' ? 'object-top' : 'object-center'}`}
/></div><div className="p-7"><h3 className="font-serif text-3xl text-navy">{x.title}</h3><p className="mt-3 text-slate-600">{x.text}</p><Link href={x.href} className="mt-5 inline-block font-bold text-gold transition hover:translate-x-1">Leggi la guida →</Link></div></article>)}</div><div className="mt-10 text-center"><Link href="/journal" className="inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white transition hover:-translate-y-1 hover:bg-navy/90">Scopri tutto il Journal →</Link></div></div></section>
<section id="mappa" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Tutto a portata di mano" title="Una base, moltissime destinazioni" text="La mappa illustrata mostra la reale disposizione di Venezia, della laguna e delle principali località del Veneto."/><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-cream shadow-soft"><Image src="/images/mappa-veneto-definitiva.webp" alt="Mappa illustrata delle principali destinazioni raggiungibili da Marghera, tra Venezia, laguna e Veneto" width={1536} height={1024} className="h-auto w-full"/></div></div></section>
<section id="contatto-diretto" className="scroll-mt-20 bg-navy py-20 text-center text-white"><div className="mx-auto max-w-3xl px-5"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Contatto diretto</p><h2 className="mt-3 font-serif text-5xl">Raccontaci il tuo viaggio</h2><p className="mt-5 text-lg text-white/75">Scrivici le date e il numero di ospiti: ti rispondiamo personalmente con disponibilità e informazioni per il soggiorno.</p><a href="https://wa.me/393514462261?text=Ciao%2C%20sto%20visitando%20il%20sito%20Marghera%20Venice%20Apartments%20e%20vorrei%20verificare%20la%20disponibilit%C3%A0.%20Le%20mie%20date%20sono%3A%20" target="_blank" rel="noopener noreferrer" className="mt-8 inline-block rounded-full bg-gold px-8 py-4 font-bold text-navy">Verifica disponibilità</a><div className="mt-7 flex justify-center"><SocialLinks className="justify-center text-white/80"/></div></div></section>
</main><Footer/></>}
