import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

type Locale='it'|'en'|'de'|'fr'|'es'|'zh';
type Section={title:string;text:string};
type Content={
  home:string;journal:string;category:string;eventDate:string;title:string;subtitle:string;lead:string;
  quoteLabel:string;quote:string;quoteText:string;sections:Section[];
  practicalTitle:string;practicalIntro:string;practical:[string,string][];faqTitle:string;faqs:[string,string][];
  updateLabel:string;updateText:string;tipLabel:string;tip:string;
  officialTitle:string;officialText:string;tourLabel:string;navyLabel:string;closing:string;
  moreLabel:string;moreTitle:string;related:[string,string][];back:string;
  imageAlt:{cover:string;sails:string;tricolor:string;night:string};
};

const content:Record<Locale,Content>={
  it:{
    home:'Home',journal:'Journal',category:'Eventi',eventDate:'2–8 OTTOBRE 2026',
    title:'Amerigo Vespucci torna a Venezia',
    subtitle:'La “nave più bella del mondo” torna in Laguna. Dal 2 all’8 ottobre 2026 Venezia riabbraccia la Signora dei Mari.',
    lead:'Ci sono arrivi che non sono semplicemente una tappa di viaggio. Quando l’Amerigo Vespucci entra nella Laguna di Venezia, due storie profondamente legate al mare si incontrano nello stesso paesaggio. Per noi veneziani è difficile immaginare uno spettacolo più emozionante.',
    quoteLabel:'UNA FRASE DIVENTATA LEGGENDA',quote:'“Siete la nave più bella del mondo.”',
    quoteText:'Nel 1962 la portaerei statunitense USS Independence incrociò il Vespucci nel Mediterraneo e, dopo averne chiesto l’identificazione, lo salutò con queste parole. Sessant’anni dopo, nel 2022, la USS George H.W. Bush ribadì il verdetto: “After 60 years you’re still the most beautiful ship in the world”.',
    sections:[
      {title:'Bentornata a Venezia, Signora dei Mari',text:'Dal 2 all’8 ottobre 2026 Nave Amerigo Vespucci sarà nuovamente a Venezia. L’ormeggio annunciato è in Riva di San Biasio, davanti al Museo Storico Navale, nel sestiere di Castello. La partenza è prevista l’8 ottobre verso Trieste, ultima tappa della Campagna Nord America 2026.'},
      {title:'95 anni e non sentirli',text:'Varata il 22 febbraio 1931 a Castellammare di Stabia, l’Amerigo Vespucci è oggi l’unità più anziana ancora in servizio nella Marina Militare Italiana. Nel 2026 ha compiuto 95 anni. La Marina ricorda 89 campagne addestrative e oltre 800.000 miglia nautiche percorse: numeri enormi per una nave che continua a formare generazioni di allievi ufficiali senza aver perso un grammo del proprio fascino.'},
      {title:'Un capolavoro che naviga davvero',text:'Non è un museo galleggiante. È una nave scuola operativa, lunga circa 101 metri da poppa a bompresso, armata a nave con tre alberi e circa 2.635 metri quadrati di velatura. Il suo profilo richiama i grandi vascelli tra Settecento e Ottocento, ma a bordo la tradizione marinara continua a essere insegnata e vissuta ogni giorno.'},
      {title:'Dall’Atlantico alla Laguna',text:'La Campagna Nord America 2026 è partita da Genova il 9 maggio e ha portato il Vespucci tra Stati Uniti, Canada, Atlantico ed Europa. Il programma ufficiale prevede 13 soste complessive e oltre 12.000 miglia nautiche. Venezia è una delle ultime tappe, prima del rientro finale a Trieste.'},
      {title:'Venezia e il Vespucci parlano la stessa lingua',text:'Venezia deve al mare una parte enorme della propria storia. L’Arsenale, le rotte della Serenissima, la cantieristica, la voga, la navigazione: qui il mare non è uno sfondo, è identità. Vedere il Vespucci ormeggiato a pochi passi dall’Arsenale significa mettere nello stesso fotogramma due simboli che sembrano fatti per capirsi.'},
      {title:'Come visitare l’Amerigo Vespucci a Venezia nel 2026',text:'Sì: durante la tappa veneziana sono previste visite a bordo. Al 5 settembre 2026, però, per Venezia non sono ancora stati pubblicati giorni, orari, modalità di accesso o un’eventuale procedura di prenotazione. Se stai cercando come visitare o prenotare l’Amerigo Vespucci a Venezia, questa è la pagina da tenere d’occhio: la aggiorneremo appena il Tour Vespucci comunicherà le istruzioni ufficiali.'},
      {title:'Come arrivare da Marghera Venice Apartments',text:'Il modo più semplice è lasciare l’auto nel parcheggio privato dell’appartamento e raggiungere Venezia in autobus o in treno. Da Piazzale Roma o dalla stazione di Venezia Santa Lucia si può proseguire verso Castello e la fermata Arsenale in vaporetto, quindi raggiungere Riva di San Biasio a piedi. Prima di partire consigliamo di controllare eventuali modifiche al servizio ACTV legate all’evento.'},
      {title:'Un appuntamento che vale il viaggio',text:'Anche senza riuscire a trovare un posto per la visita a bordo, vedere l’Amerigo Vespucci a Venezia merita una passeggiata. E se avrete la fortuna di assistere al suo arrivo o alla partenza, probabilmente vi porterete a casa uno di quei ricordi che non hanno bisogno di filtri: una nave di 95 anni, ancora viva e operativa, che attraversa la laguna di una città che ha il mare dentro la propria storia.'}
    ],
    practicalTitle:'Amerigo Vespucci Venezia 2026: visite, orari e prenotazioni',practicalIntro:'Cerchi come visitare o prenotare l’Amerigo Vespucci a Venezia? Qui raccogliamo le informazioni confermate e aggiorneremo questa guida non appena saranno pubblicate le modalità definitive.',
    practical:[['📅 Quando','2–8 ottobre 2026'],['📍 Dove','Riva di San Biasio, Castello – davanti al Museo Storico Navale'],['⚓ Visite a bordo','Previste durante la tappa veneziana'],['🎟️ Prenotazione','Al 5 settembre non è ancora pubblicata una procedura specifica per Venezia'],['⏰ Orari visite','Non ancora comunicati'],['🚤 Fermata comoda','Arsenale, poi pochi minuti a piedi'],['➡️ Partenza','8 ottobre verso Trieste']],
    faqTitle:'Come visitare e prenotare Amerigo Vespucci a Venezia: domande frequenti',
    faqs:[['Serve prenotare la visita all’Amerigo Vespucci a Venezia?','Al 5 settembre 2026 il Tour Vespucci non ha ancora pubblicato una procedura specifica di prenotazione per la tappa di Venezia. Non è quindi possibile confermare oggi se l’accesso richiederà prenotazione anticipata. Appena usciranno le modalità ufficiali aggiorneremo questa pagina.'],['Quando aprono le prenotazioni per Amerigo Vespucci a Venezia?','Non è stata ancora annunciata una data di apertura delle prenotazioni per Venezia. Il sito ufficiale comunica che i dettagli delle visite nelle tappe italiane vengono pubblicati progressivamente.'],['Dove sarà possibile visitare l’Amerigo Vespucci a Venezia?','L’ormeggio annunciato è a Riva di San Biasio, nel sestiere di Castello, davanti al Museo Storico Navale e a pochi passi dall’Arsenale.'],['Gli orari delle visite a bordo sono già disponibili?','No. Al 5 settembre 2026 gli orari e gli eventuali slot di accesso per Venezia non risultano ancora pubblicati.']],
    updateLabel:'AGGIORNAMENTO • 5 SETTEMBRE 2026',updateText:'Il Tour Vespucci ufficiale conferma Venezia dal 2 all’8 ottobre. Per la tappa veneziana non risultano ancora pubblicati orari, slot o una procedura specifica di prenotazione. Non acquistare servizi o “biglietti” da siti non ufficiali: verifica sempre prima il portale del Tour Vespucci.',
    tipLabel:'IL NOSTRO CONSIGLIO',tip:'Se vuoi vedere la nave con un po’ di calma, non limitarti a San Marco. Riva di San Biasio e l’area dell’Arsenale sono già bellissime di loro: con il Vespucci ormeggiato davanti diventano uno dei luoghi più speciali di Venezia in quei giorni.',
    officialTitle:'Informazioni ufficiali',officialText:'Date, orari e modalità di visita possono cambiare per esigenze operative della nave. Prima di organizzare la giornata verifica sempre gli aggiornamenti ufficiali.',tourLabel:'Tour Vespucci – sito ufficiale',navyLabel:'Marina Militare – Amerigo Vespucci',closing:'Amerigo Vespucci, 95 anni di mare. Venezia, più di mille anni di storia sull’acqua. In ottobre si incontrano di nuovo. ❤️⚓',
    moreLabel:'Continua a esplorare',moreTitle:'Venezia, mare e grandi tradizioni',related:[['Regata Storica di Venezia 2026','/journal/regata-storica-2026'],['The Venice Glass Week 2026','/journal/venice-glass-week-2026']],back:'Torna al Journal',
    imageAlt:{cover:'Nave Amerigo Vespucci ormeggiata a Venezia lungo la riva',sails:'Nave Amerigo Vespucci in navigazione a vele spiegate',tricolor:'Nave Amerigo Vespucci con le Frecce Tricolori in volo',night:'Amerigo Vespucci ormeggiata a Venezia illuminata di sera'}
  },
  en:{
    home:'Home',journal:'Journal',category:'Events',eventDate:'2–8 OCTOBER 2026',title:'Amerigo Vespucci returns to Venice',
    subtitle:'The “most beautiful ship in the world” returns to the Lagoon. From 2 to 8 October 2026, Venice welcomes back the Lady of the Seas.',
    lead:'Some arrivals are more than just another stop on a route. When Amerigo Vespucci enters the Venice Lagoon, two stories shaped by the sea meet in the same landscape. It is hard to imagine a more fitting setting for this extraordinary ship.',
    quoteLabel:'A SENTENCE THAT BECAME LEGEND',quote:'“You are the most beautiful ship in the world.”',quoteText:'In 1962, the US aircraft carrier USS Independence met Vespucci in the Mediterranean and, after asking the sailing ship to identify herself, sent the now-famous compliment. Sixty years later, in 2022, USS George H.W. Bush repeated the verdict: “After 60 years you’re still the most beautiful ship in the world”.',
    sections:[
      {title:'Welcome back to Venice, Lady of the Seas',text:'From 2 to 8 October 2026, Amerigo Vespucci will once again be in Venice. The announced berth is at Riva di San Biasio, opposite the Naval History Museum in Castello. Departure is scheduled for 8 October towards Trieste, the final stop of the 2026 North America Campaign.'},
      {title:'95 years young',text:'Launched on 22 February 1931 in Castellammare di Stabia, Amerigo Vespucci is the oldest ship still in service with the Italian Navy. She turned 95 in 2026. The Navy records 89 training campaigns and more than 800,000 nautical miles sailed: remarkable figures for a ship that still trains generations of officer cadets.'},
      {title:'A masterpiece that still sails',text:'This is not a floating museum. Vespucci is an active training ship, around 101 metres long from stern to bowsprit, ship-rigged with three masts and approximately 2,635 square metres of sail. Her silhouette recalls the great sailing vessels of the late eighteenth and early nineteenth centuries, while life on board remains firmly connected to modern naval training.'},
      {title:'From the Atlantic to the Lagoon',text:'The 2026 North America Campaign left Genoa on 9 May and has taken Vespucci through the United States, Canada, the Atlantic and back to Europe. The official programme includes 13 stops and more than 12,000 nautical miles. Venice is one of the final calls before the campaign concludes in Trieste.'},
      {title:'Venice and Vespucci speak the same language',text:'Venice owes an enormous part of its history to the sea. The Arsenale, the routes of the Serenissima, shipbuilding, rowing and navigation are not simply background stories here: they are part of the city’s identity. Seeing Vespucci moored close to the Arsenale brings two maritime symbols into the same frame.'},
      {title:'How to visit Amerigo Vespucci in Venice in 2026',text:'Yes. Onboard visits are planned during the Venice stop. As of 5 September 2026, however, Venice-specific days, visiting hours, access rules and any booking procedure have not yet been published. If you are searching for how to visit or book Amerigo Vespucci in Venice, keep this page handy: we will update it as soon as Tour Vespucci publishes the official instructions.'},
      {title:'How to get there from Marghera Venice Apartments',text:'The easiest option is to leave your car in the apartment’s private parking area and reach Venice by bus or train. From Piazzale Roma or Venezia Santa Lucia station, continue towards Castello and the Arsenale vaporetto stop, then walk to Riva di San Biasio. Check ACTV updates before travelling in case the event affects waterbus services.'},
      {title:'An encounter worth seeing',text:'Even if you cannot secure a place on an onboard visit, seeing Amerigo Vespucci in Venice is worth the walk. And if you happen to watch her arrive or depart, it may become one of those Venice memories that needs no filter: a 95-year-old ship, still active, moving through the lagoon of a city whose history has always been tied to the sea.'}
    ],
    practicalTitle:'Amerigo Vespucci Venice 2026: visits, times and booking',practicalIntro:'Looking for how to visit or book Amerigo Vespucci in Venice? Here we collect confirmed information and will update this guide as soon as the final access arrangements are published.',
    practical:[['📅 Dates','2–8 October 2026'],['📍 Berth','Riva di San Biasio, Castello – opposite the Naval History Museum'],['⚓ Onboard visits','Planned during the Venice stop'],['🎟️ Booking','As of 5 September, no Venice-specific booking procedure has been published'],['⏰ Visiting times','Not yet announced'],['🚤 Convenient stop','Arsenale, then a short walk'],['➡️ Departure','8 October towards Trieste']],
    faqTitle:'How to visit and book Amerigo Vespucci in Venice: FAQ',
    faqs:[['Do I need to book a visit to Amerigo Vespucci in Venice?','As of 5 September 2026, Tour Vespucci has not published a Venice-specific booking procedure. It is therefore not yet possible to confirm whether advance booking will be required. We will update this page as soon as the official access rules are released.'],['When will bookings open for Amerigo Vespucci in Venice?','No booking opening date has yet been announced for Venice. The official website says details for the Italian stops will be released progressively.'],['Where will Amerigo Vespucci be in Venice?','The announced berth is Riva di San Biasio in Castello, opposite the Naval History Museum and close to the Arsenale.'],['Are the onboard visiting times already available?','No. As of 5 September 2026, visiting hours and any access slots for Venice have not yet been published.']],
    updateLabel:'UPDATE • 5 SEPTEMBER 2026',updateText:'The official Tour Vespucci website confirms Venice from 2 to 8 October. Venice-specific visiting times, slots and booking procedures have not yet been published. Do not pay for unofficial “tickets” or services before checking the official Tour Vespucci portal.',
    tipLabel:'OUR TIP',tip:'Do not think only about St Mark’s Square. Riva di San Biasio and the Arsenale area are already among Venice’s most atmospheric waterfronts. With Vespucci moored there, they become something very special.',
    officialTitle:'Official information',officialText:'Dates, times and public access arrangements may change for operational reasons. Always check the official sources before organising your visit.',tourLabel:'Tour Vespucci – official website',navyLabel:'Italian Navy – Amerigo Vespucci',closing:'Amerigo Vespucci: 95 years at sea. Venice: more than a thousand years of history on the water. In October, they meet again. ❤️⚓',
    moreLabel:'Keep exploring',moreTitle:'Venice, the sea and great traditions',related:[['Venice Historical Regatta 2026','/en/journal/regata-storica-2026'],['The Venice Glass Week 2026','/en/journal/venice-glass-week-2026']],back:'Back to Journal',
    imageAlt:{cover:'Amerigo Vespucci moored on the waterfront in Venice',sails:'Amerigo Vespucci sailing under canvas at sea',tricolor:'Amerigo Vespucci with the Frecce Tricolori flying overhead',night:'Amerigo Vespucci moored in Venice and illuminated at dusk'}
  },
  de:{
    home:'Startseite',journal:'Journal',category:'Veranstaltungen',eventDate:'2.–8. OKTOBER 2026',title:'Amerigo Vespucci kehrt nach Venedig zurück',
    subtitle:'Das „schönste Schiff der Welt“ kehrt in die Lagune zurück. Vom 2. bis 8. Oktober 2026 heißt Venedig die „Signora dei Mari“ wieder willkommen.',
    lead:'Manche Ankünfte sind mehr als nur eine weitere Etappe. Wenn die Amerigo Vespucci in die Lagune von Venedig einläuft, treffen zwei Geschichten aufeinander, die vom Meer geprägt sind. Für dieses außergewöhnliche Schiff könnte es kaum eine passendere Kulisse geben.',
    quoteLabel:'EIN SATZ WURDE ZUR LEGENDE',quote:'„Sie sind das schönste Schiff der Welt.“',quoteText:'1962 begegnete der US-Flugzeugträger USS Independence der Vespucci im Mittelmeer. Nachdem er um Identifizierung gebeten hatte, folgte das berühmte Kompliment. Sechzig Jahre später bestätigte die USS George H.W. Bush den Satz erneut: „After 60 years you’re still the most beautiful ship in the world“.',
    sections:[
      {title:'Willkommen zurück in Venedig, Signora dei Mari',text:'Vom 2. bis 8. Oktober 2026 liegt die Amerigo Vespucci wieder in Venedig. Als Liegeplatz wurde Riva di San Biasio gegenüber dem Museo Storico Navale im Stadtteil Castello angekündigt. Am 8. Oktober soll die Reise nach Triest weitergehen, der letzten Station der Nordamerika-Kampagne 2026.'},
      {title:'95 Jahre – und noch immer im Dienst',text:'Die Amerigo Vespucci wurde am 22. Februar 1931 in Castellammare di Stabia vom Stapel gelassen und ist heute das älteste noch im Dienst befindliche Schiff der italienischen Marine. 2026 wurde sie 95 Jahre alt. Die Marine nennt 89 Ausbildungskampagnen und mehr als 800.000 Seemeilen.'},
      {title:'Ein Meisterwerk, das wirklich segelt',text:'Die Vespucci ist kein schwimmendes Museum, sondern ein aktives Schulschiff. Sie misst rund 101 Meter von Heck bis Bugspriet, trägt drei Masten und etwa 2.635 Quadratmeter Segelfläche. Ihre Linien erinnern an große Segelschiffe des späten 18. und frühen 19. Jahrhunderts, doch an Bord wird bis heute moderne Marineausbildung mit klassischer Seemannschaft verbunden.'},
      {title:'Vom Atlantik in die Lagune',text:'Die Nordamerika-Kampagne 2026 startete am 9. Mai in Genua und führte die Vespucci durch die USA, Kanada, den Atlantik und zurück nach Europa. Das offizielle Programm umfasst 13 Stopps und mehr als 12.000 Seemeilen. Venedig gehört zu den letzten Stationen vor dem Abschluss in Triest.'},
      {title:'Venedig und Vespucci sprechen dieselbe Sprache',text:'Venedig verdankt dem Meer einen großen Teil seiner Geschichte. Arsenale, Handelsrouten der Serenissima, Schiffbau, Rudern und Navigation sind hier keine bloße Kulisse, sondern Identität. Die Vespucci nur wenige Schritte vom Arsenale entfernt zu sehen, bringt zwei maritime Symbole in ein einziges Bild.'},
      {title:'So besucht man die Amerigo Vespucci 2026 in Venedig',text:'Ja. Während des Aufenthalts in Venedig sind Besichtigungen an Bord vorgesehen. Am 5. September 2026 sind für Venedig jedoch noch keine Besuchstage, Uhrzeiten, Zugangsregeln oder eine mögliche Buchungsprozedur veröffentlicht. Wer nach Besuch oder Reservierung der Amerigo Vespucci in Venedig sucht, sollte diese Seite speichern: Wir aktualisieren sie, sobald Tour Vespucci die offiziellen Hinweise veröffentlicht.'},
      {title:'Anreise von Marghera Venice Apartments',text:'Am einfachsten bleibt das Auto auf dem privaten Parkplatz der Unterkunft. Fahren Sie mit Bus oder Zug nach Venedig und von Piazzale Roma oder dem Bahnhof Venezia Santa Lucia weiter Richtung Castello und Vaporetto-Haltestelle Arsenale. Von dort sind es nur wenige Minuten zu Fuß bis Riva di San Biasio.'},
      {title:'Ein Anblick, der den Weg wert ist',text:'Auch ohne Platz für eine Bordbesichtigung lohnt es sich, die Amerigo Vespucci in Venedig zu sehen. Wer ihre Ankunft oder Abfahrt erlebt, nimmt vielleicht eine jener Erinnerungen mit, die keinen Filter brauchen: ein 95 Jahre altes, noch immer aktives Schiff in einer Lagune, deren Stadtgeschichte seit Jahrhunderten vom Meer erzählt.'}
    ],
    practicalTitle:'Amerigo Vespucci Venedig 2026: Besichtigung, Zeiten und Reservierung',practicalIntro:'Sie möchten wissen, wie man die Amerigo Vespucci in Venedig besucht oder reserviert? Hier sammeln wir die bestätigten Informationen und aktualisieren den Guide, sobald die endgültigen Zugangsmodalitäten veröffentlicht werden.',
    practical:[['📅 Zeitraum','2.–8. Oktober 2026'],['📍 Liegeplatz','Riva di San Biasio, Castello – gegenüber dem Museo Storico Navale'],['⚓ Bordbesichtigungen','Während des Aufenthalts in Venedig vorgesehen'],['🎟️ Reservierung','Am 5. September ist noch kein spezielles Buchungsverfahren für Venedig veröffentlicht'],['⏰ Besuchszeiten','Noch nicht bekannt gegeben'],['🚤 Praktische Haltestelle','Arsenale, danach wenige Minuten zu Fuß'],['➡️ Abfahrt','8. Oktober Richtung Triest']],
    faqTitle:'Amerigo Vespucci in Venedig besuchen und reservieren: FAQ',
    faqs:[['Muss man den Besuch der Amerigo Vespucci in Venedig reservieren?','Am 5. September 2026 hat Tour Vespucci noch kein spezielles Buchungsverfahren für Venedig veröffentlicht. Daher lässt sich derzeit nicht bestätigen, ob eine Vorabreservierung erforderlich sein wird. Sobald die offiziellen Regeln erscheinen, aktualisieren wir diese Seite.'],['Wann öffnen die Reservierungen für die Amerigo Vespucci in Venedig?','Für Venedig wurde noch kein Datum für den Start der Reservierungen bekannt gegeben. Laut offizieller Website werden die Details für die italienischen Stationen schrittweise veröffentlicht.'],['Wo liegt die Amerigo Vespucci in Venedig?','Der angekündigte Liegeplatz ist Riva di San Biasio in Castello, gegenüber dem Museo Storico Navale und nahe dem Arsenale.'],['Sind die Besuchszeiten bereits bekannt?','Nein. Am 5. September 2026 sind die Besuchszeiten und mögliche Zeitfenster für Venedig noch nicht veröffentlicht.']],
    updateLabel:'UPDATE • 5. SEPTEMBER 2026',updateText:'Die offizielle Tour-Vespucci-Website bestätigt Venedig vom 2. bis 8. Oktober. Für Venedig wurden noch keine Besuchszeiten, Zeitfenster oder ein spezielles Buchungsverfahren veröffentlicht. Prüfen Sie vor Zahlungen für inoffizielle Angebote immer zuerst das offizielle Tour-Vespucci-Portal.',
    tipLabel:'UNSER TIPP',tip:'Denken Sie nicht nur an den Markusplatz. Riva di San Biasio und das Arsenale gehören ohnehin zu den eindrucksvollsten Uferbereichen Venedigs. Mit der Vespucci davor wird dieser Teil der Stadt in diesen Tagen besonders.',
    officialTitle:'Offizielle Informationen',officialText:'Termine, Uhrzeiten und Zugangsmodalitäten können sich aus operativen Gründen ändern. Prüfen Sie vor Ihrem Besuch immer die offiziellen Quellen.',tourLabel:'Tour Vespucci – offizielle Website',navyLabel:'Italienische Marine – Amerigo Vespucci',closing:'Amerigo Vespucci: 95 Jahre auf See. Venedig: mehr als tausend Jahre Geschichte auf dem Wasser. Im Oktober begegnen sie sich wieder. ❤️⚓',
    moreLabel:'Weiter entdecken',moreTitle:'Venedig, Meer und große Traditionen',related:[['Regata Storica Venedig 2026','/de/journal/regata-storica-2026'],['The Venice Glass Week 2026','/de/journal/venice-glass-week-2026']],back:'Zurück zum Journal',
    imageAlt:{cover:'Amerigo Vespucci am Ufer von Venedig',sails:'Amerigo Vespucci unter Segeln auf See',tricolor:'Amerigo Vespucci mit den Frecce Tricolori am Himmel',night:'Amerigo Vespucci abends beleuchtet in Venedig'}
  },
  fr:{
    home:'Accueil',journal:'Journal',category:'Événements',eventDate:'2–8 OCTOBRE 2026',title:'L’Amerigo Vespucci revient à Venise',
    subtitle:'Le « plus beau navire du monde » revient dans la lagune. Du 2 au 8 octobre 2026, Venise accueille à nouveau la Dame des Mers.',
    lead:'Certaines arrivées sont bien plus qu’une simple escale. Lorsque l’Amerigo Vespucci entre dans la lagune de Venise, deux histoires façonnées par la mer se rencontrent dans un même paysage. Difficile d’imaginer un décor plus juste pour ce navire extraordinaire.',
    quoteLabel:'UNE PHRASE DEVENUE LÉGENDAIRE',quote:'« Vous êtes le plus beau navire du monde. »',quoteText:'En 1962, le porte-avions américain USS Independence croisa le Vespucci en Méditerranée et, après lui avoir demandé de s’identifier, lui adressa ce compliment devenu célèbre. Soixante ans plus tard, en 2022, l’USS George H.W. Bush confirma le verdict : « After 60 years you’re still the most beautiful ship in the world ».',
    sections:[
      {title:'Bon retour à Venise, Signora dei Mari',text:'Du 2 au 8 octobre 2026, l’Amerigo Vespucci sera de nouveau à Venise. L’amarrage annoncé se trouve à Riva di San Biasio, face au Musée historique naval, dans le sestiere de Castello. Le départ est prévu le 8 octobre vers Trieste, dernière étape de la campagne Amérique du Nord 2026.'},
      {title:'95 ans et toujours en service',text:'Mis à l’eau le 22 février 1931 à Castellammare di Stabia, l’Amerigo Vespucci est aujourd’hui le plus ancien navire encore en service dans la Marine militaire italienne. Il a fêté ses 95 ans en 2026. La Marine comptabilise 89 campagnes de formation et plus de 800 000 milles nautiques parcourus.'},
      {title:'Un chef-d’œuvre qui navigue vraiment',text:'Ce n’est pas un musée flottant. Le Vespucci reste un navire-école opérationnel, long d’environ 101 mètres de la poupe au beaupré, gréé en trois-mâts avec près de 2 635 m² de voilure. Sa silhouette rappelle les grands voiliers de la fin du XVIIIe et du début du XIXe siècle, tandis que la formation navale se poursuit à bord aujourd’hui.'},
      {title:'De l’Atlantique à la lagune',text:'La campagne Amérique du Nord 2026 a quitté Gênes le 9 mai et conduit le Vespucci aux États-Unis, au Canada, à travers l’Atlantique puis vers l’Europe. Le programme officiel comprend 13 escales et plus de 12 000 milles nautiques. Venise figure parmi les dernières étapes avant l’arrivée finale à Trieste.'},
      {title:'Venise et le Vespucci parlent la même langue',text:'Venise doit une immense partie de son histoire à la mer. L’Arsenal, les routes de la Sérénissime, la construction navale, la rame et la navigation ne sont pas un décor : ils font partie de l’identité de la ville. Voir le Vespucci amarré à quelques pas de l’Arsenal réunit deux symboles maritimes dans la même image.'},
      {title:'Comment visiter l’Amerigo Vespucci à Venise en 2026',text:'Oui. Des visites à bord sont prévues pendant l’escale vénitienne. Au 5 septembre 2026, les jours, horaires, modalités d’accès et une éventuelle procédure de réservation propres à Venise ne sont toutefois pas encore publiés. Si vous cherchez comment visiter ou réserver l’Amerigo Vespucci à Venise, gardez cette page : nous la mettrons à jour dès la publication des instructions officielles.'},
      {title:'Comment venir depuis Marghera Venice Apartments',text:'Le plus simple est de laisser la voiture sur le parking privé de l’appartement et de rejoindre Venise en bus ou en train. Depuis Piazzale Roma ou la gare Venezia Santa Lucia, continuez vers Castello et l’arrêt de vaporetto Arsenale, puis rejoignez Riva di San Biasio à pied.'},
      {title:'Un rendez-vous qui vaut le détour',text:'Même sans place pour une visite à bord, voir l’Amerigo Vespucci à Venise mérite le déplacement. Et si vous assistez à son arrivée ou à son départ, vous garderez peut-être l’un de ces souvenirs de Venise qui n’ont besoin d’aucun filtre : un navire de 95 ans, toujours en activité, traversant la lagune d’une ville intimement liée à la mer.'}
    ],
    practicalTitle:'Amerigo Vespucci Venise 2026 : visites, horaires et réservation',practicalIntro:'Vous cherchez comment visiter ou réserver l’Amerigo Vespucci à Venise ? Nous rassemblons ici les informations confirmées et mettrons ce guide à jour dès la publication des modalités définitives.',
    practical:[['📅 Dates','2–8 octobre 2026'],['📍 Lieu','Riva di San Biasio, Castello – devant le Musée historique naval'],['⚓ Visites à bord','Prévues pendant l’escale à Venise'],['🎟️ Réservation','Au 5 septembre, aucune procédure spécifique à Venise n’est encore publiée'],['⏰ Horaires de visite','Pas encore annoncés'],['🚤 Vaporetto','Arrêt Arsenale, puis quelques minutes à pied'],['➡️ Départ','8 octobre vers Trieste']],
    faqTitle:'Visiter et réserver l’Amerigo Vespucci à Venise : questions fréquentes',
    faqs:[['Faut-il réserver la visite de l’Amerigo Vespucci à Venise ?','Au 5 septembre 2026, Tour Vespucci n’a pas encore publié de procédure de réservation spécifique à Venise. Il n’est donc pas encore possible de confirmer si une réservation préalable sera obligatoire. Nous mettrons cette page à jour dès la publication des règles officielles.'],['Quand ouvrent les réservations pour l’Amerigo Vespucci à Venise ?','Aucune date d’ouverture des réservations n’a encore été annoncée pour Venise. Le site officiel indique que les informations pour les escales italiennes seront communiquées progressivement.'],['Où sera l’Amerigo Vespucci à Venise ?','L’amarrage annoncé est à Riva di San Biasio, dans le sestiere de Castello, devant le Musée historique naval et près de l’Arsenale.'],['Les horaires des visites à bord sont-ils déjà disponibles ?','Non. Au 5 septembre 2026, les horaires et éventuels créneaux de visite pour Venise ne sont pas encore publiés.']],
    updateLabel:'MISE À JOUR • 5 SEPTEMBRE 2026',updateText:'Le site officiel Tour Vespucci confirme Venise du 2 au 8 octobre. Les horaires, créneaux et modalités de réservation spécifiques à Venise ne sont pas encore publiés. Ne payez aucun “billet” ou service non officiel avant d’avoir vérifié le portail Tour Vespucci.',
    tipLabel:'NOTRE CONSEIL',tip:'Ne pensez pas uniquement à la place Saint-Marc. Riva di San Biasio et le secteur de l’Arsenal comptent déjà parmi les plus beaux fronts de lagune de Venise. Avec le Vespucci amarré devant eux, l’atmosphère sera exceptionnelle.',
    officialTitle:'Informations officielles',officialText:'Dates, horaires et modalités d’accès peuvent changer pour des raisons opérationnelles. Consultez toujours les sources officielles avant votre visite.',tourLabel:'Tour Vespucci – site officiel',navyLabel:'Marine italienne – Amerigo Vespucci',closing:'Amerigo Vespucci : 95 ans de mer. Venise : plus de mille ans d’histoire sur l’eau. En octobre, elles se retrouvent. ❤️⚓',
    moreLabel:'Continuer à explorer',moreTitle:'Venise, la mer et les grandes traditions',related:[['Regata Storica de Venise 2026','/fr/journal/regata-storica-2026'],['The Venice Glass Week 2026','/fr/journal/venice-glass-week-2026']],back:'Retour au Journal',
    imageAlt:{cover:'Amerigo Vespucci amarré sur les quais de Venise',sails:'Amerigo Vespucci naviguant toutes voiles dehors',tricolor:'Amerigo Vespucci avec les Frecce Tricolori dans le ciel',night:'Amerigo Vespucci illuminé à Venise au crépuscule'}
  },
  es:{
    home:'Inicio',journal:'Journal',category:'Eventos',eventDate:'2–8 OCTUBRE 2026',title:'El Amerigo Vespucci vuelve a Venecia',
    subtitle:'El “barco más bonito del mundo” vuelve a la laguna. Del 2 al 8 de octubre de 2026, Venecia recibe de nuevo a la Señora de los Mares.',
    lead:'Hay llegadas que son mucho más que una escala. Cuando el Amerigo Vespucci entra en la laguna de Venecia, dos historias marcadas por el mar se encuentran en un mismo paisaje. Es difícil imaginar un escenario más apropiado para este barco extraordinario.',
    quoteLabel:'UNA FRASE QUE SE VOLVIÓ LEYENDA',quote:'«Sois el barco más bonito del mundo.»',quoteText:'En 1962, el portaaviones estadounidense USS Independence se cruzó con el Vespucci en el Mediterráneo y, tras pedirle que se identificara, le envió el famoso elogio. Sesenta años después, en 2022, el USS George H.W. Bush confirmó el veredicto: «After 60 years you’re still the most beautiful ship in the world».',
    sections:[
      {title:'Bienvenida de nuevo a Venecia, Signora dei Mari',text:'Del 2 al 8 de octubre de 2026, el Amerigo Vespucci volverá a estar en Venecia. El atraque anunciado es Riva di San Biasio, frente al Museo Histórico Naval, en Castello. La salida está prevista para el 8 de octubre rumbo a Trieste, última etapa de la Campaña Norteamérica 2026.'},
      {title:'95 años y todavía en servicio',text:'Botado el 22 de febrero de 1931 en Castellammare di Stabia, el Amerigo Vespucci es hoy la unidad más antigua todavía en servicio en la Marina Militar Italiana. En 2026 cumplió 95 años. La Marina registra 89 campañas de formación y más de 800.000 millas náuticas navegadas.'},
      {title:'Una obra maestra que sigue navegando',text:'No es un museo flotante. El Vespucci sigue siendo un buque escuela operativo, de unos 101 metros de popa a bauprés, con tres mástiles y aproximadamente 2.635 m² de superficie vélica. Su silueta recuerda a los grandes navíos de finales del siglo XVIII y comienzos del XIX, mientras la formación naval continúa a bordo en pleno siglo XXI.'},
      {title:'Del Atlántico a la laguna',text:'La Campaña Norteamérica 2026 partió de Génova el 9 de mayo y ha llevado al Vespucci por Estados Unidos, Canadá, el Atlántico y de regreso a Europa. El programa oficial contempla 13 escalas y más de 12.000 millas náuticas. Venecia es una de las últimas paradas antes de finalizar en Trieste.'},
      {title:'Venecia y el Vespucci hablan el mismo idioma',text:'Venecia debe al mar una parte inmensa de su historia. El Arsenale, las rutas de la Serenissima, la construcción naval, el remo y la navegación no son un decorado: forman parte de la identidad de la ciudad. Ver al Vespucci amarrado a pocos pasos del Arsenale reúne dos símbolos marítimos en una sola imagen.'},
      {title:'Cómo visitar el Amerigo Vespucci en Venecia en 2026',text:'Sí. Se prevén visitas a bordo durante la escala veneciana. A 5 de septiembre de 2026, sin embargo, todavía no se han publicado para Venecia los días, horarios, normas de acceso ni un eventual procedimiento de reserva. Si buscas cómo visitar o reservar el Amerigo Vespucci en Venecia, guarda esta página: la actualizaremos en cuanto Tour Vespucci publique las instrucciones oficiales.'},
      {title:'Cómo llegar desde Marghera Venice Apartments',text:'Lo más sencillo es dejar el coche en el aparcamiento privado del apartamento y llegar a Venecia en autobús o tren. Desde Piazzale Roma o la estación Venezia Santa Lucia, continúa hacia Castello y la parada de vaporetto Arsenale; desde allí, Riva di San Biasio queda a pocos minutos a pie.'},
      {title:'Una cita que merece la pena',text:'Aunque no consigas plaza para subir a bordo, ver el Amerigo Vespucci en Venecia merece el paseo. Y si tienes la suerte de presenciar su llegada o salida, quizá te lleves uno de esos recuerdos de Venecia que no necesitan filtros: un barco de 95 años, todavía en activo, atravesando la laguna de una ciudad cuya historia siempre ha estado unida al mar.'}
    ],
    practicalTitle:'Amerigo Vespucci Venecia 2026: visitas, horarios y reservas',practicalIntro:'¿Buscas cómo visitar o reservar el Amerigo Vespucci en Venecia? Aquí reunimos la información confirmada y actualizaremos esta guía cuando se publiquen las modalidades definitivas.',
    practical:[['📅 Fechas','2–8 de octubre de 2026'],['📍 Atraque','Riva di San Biasio, Castello – frente al Museo Histórico Naval'],['⚓ Visitas a bordo','Previstas durante la escala en Venecia'],['🎟️ Reserva','A 5 de septiembre todavía no se ha publicado un procedimiento específico para Venecia'],['⏰ Horarios de visita','Aún no anunciados'],['🚤 Parada cómoda','Arsenale, después unos minutos a pie'],['➡️ Salida','8 de octubre rumbo a Trieste']],
    faqTitle:'Cómo visitar y reservar el Amerigo Vespucci en Venecia: preguntas frecuentes',
    faqs:[['¿Hay que reservar la visita al Amerigo Vespucci en Venecia?','A 5 de septiembre de 2026, Tour Vespucci todavía no ha publicado un procedimiento de reserva específico para Venecia. Por tanto, aún no se puede confirmar si será necesaria una reserva anticipada. Actualizaremos esta página cuando se publiquen las normas oficiales.'],['¿Cuándo abren las reservas para el Amerigo Vespucci en Venecia?','Todavía no se ha anunciado una fecha de apertura de reservas para Venecia. La web oficial indica que los detalles de las escalas italianas se publicarán progresivamente.'],['¿Dónde estará el Amerigo Vespucci en Venecia?','El atraque anunciado es Riva di San Biasio, en Castello, frente al Museo Histórico Naval y cerca del Arsenale.'],['¿Ya están disponibles los horarios de las visitas a bordo?','No. A 5 de septiembre de 2026 todavía no se han publicado los horarios ni los posibles turnos de acceso para Venecia.']],
    updateLabel:'ACTUALIZACIÓN • 5 SEPTIEMBRE 2026',updateText:'La web oficial Tour Vespucci confirma Venecia del 2 al 8 de octubre. Todavía no se han publicado para Venecia horarios, turnos ni un procedimiento específico de reserva. No pagues “entradas” o servicios no oficiales sin comprobar antes el portal Tour Vespucci.',
    tipLabel:'NUESTRO CONSEJO',tip:'No pienses solo en San Marcos. Riva di San Biasio y la zona del Arsenale ya son algunos de los paseos marítimos más bonitos de Venecia. Con el Vespucci amarrado delante, esos días tendrán algo realmente especial.',
    officialTitle:'Información oficial',officialText:'Fechas, horarios y modalidades de acceso pueden cambiar por necesidades operativas. Consulta siempre las fuentes oficiales antes de organizar la visita.',tourLabel:'Tour Vespucci – web oficial',navyLabel:'Marina Militar Italiana – Amerigo Vespucci',closing:'Amerigo Vespucci: 95 años de mar. Venecia: más de mil años de historia sobre el agua. En octubre vuelven a encontrarse. ❤️⚓',
    moreLabel:'Seguir explorando',moreTitle:'Venecia, el mar y sus grandes tradiciones',related:[['Regata Storica de Venecia 2026','/es/journal/regata-storica-2026'],['The Venice Glass Week 2026','/es/journal/venice-glass-week-2026']],back:'Volver al Journal',
    imageAlt:{cover:'Amerigo Vespucci amarrado en Venecia',sails:'Amerigo Vespucci navegando a vela',tricolor:'Amerigo Vespucci con las Frecce Tricolori sobre el barco',night:'Amerigo Vespucci iluminado al atardecer en Venecia'}
  },
  zh:{
    home:'首页',journal:'旅行日志',category:'活动',eventDate:'2026年10月2–8日',title:'“阿美利哥·韦斯普奇”号重返威尼斯',
    subtitle:'被誉为“世界上最美丽的船”的 Amerigo Vespucci 将再次驶入威尼斯泻湖。2026年10月2日至8日，威尼斯将再次迎接这位“海上女王”。',
    lead:'有些抵达不只是航程中的一站。当 Amerigo Vespucci 驶入威尼斯泻湖，两段都由海洋塑造的历史会在同一幅风景中相遇。对于这艘传奇帆船来说，很难想象还有比威尼斯更合适的舞台。',
    quoteLabel:'一句成为传奇的话',quote:'“你们是世界上最美丽的船。”',quoteText:'1962年，美国航空母舰 USS Independence 在地中海与 Vespucci 相遇。确认对方身份后，它发出了这句后来广为流传的赞美。60年后的2022年，USS George H.W. Bush 再次表示：“After 60 years you’re still the most beautiful ship in the world”。',
    sections:[
      {title:'欢迎重返威尼斯，海上女王',text:'2026年10月2日至8日，Amerigo Vespucci 将再次停靠威尼斯。已公布的停泊位置是 Castello 区的 Riva di San Biasio，正对威尼斯海军历史博物馆。10月8日计划启程前往的里雅斯特，完成2026北美航行的最后阶段。'},
      {title:'95岁，依然在服役',text:'Amerigo Vespucci 于1931年2月22日在 Castellammare di Stabia 下水，如今是意大利海军仍在服役的最古老舰艇。2026年它迎来95岁生日。意大利海军公布的资料显示，这艘船已经完成89次训练航行，累计航程超过80万海里。'},
      {title:'真正仍在航行的艺术品',text:'它不是一座漂浮的博物馆，而是一艘仍在执行任务的训练舰。从船尾到船首斜桅全长约101米，拥有三根桅杆和约2,635平方米的帆面积。外形令人想起18世纪末至19世纪初的大型帆船，而船上的航海训练至今仍在继续。'},
      {title:'从大西洋回到泻湖',text:'2026北美航行于5月9日从热那亚出发，航线经过美国、加拿大、大西洋并返回欧洲。官方行程包括13个停靠港，航程超过12,000海里。威尼斯是抵达的里雅斯特结束整段航行前的最后几站之一。'},
      {title:'威尼斯与 Vespucci 说着同一种“海的语言”',text:'威尼斯的大部分历史都离不开海洋。Arsenale 造船厂、Serenissima 的海上航线、造船、划船与航海并不是旅游背景，而是这座城市的身份。Vespucci 停在 Arsenale 附近时，两个海洋象征会真正出现在同一幅画面里。'},
      {title:'2026年如何在威尼斯参观 Amerigo Vespucci？',text:'可以。威尼斯停靠期间计划安排公众登船参观。不过截至2026年9月5日，威尼斯站的具体参观日期、时间、入场规则以及是否需要预约和预约方式仍未公布。如果你正在搜索如何参观或预约威尼斯的 Amerigo Vespucci，请收藏本页：Tour Vespucci 发布官方说明后，我们会立即更新。'},
      {title:'从 Marghera Venice Apartments 怎么去',text:'最轻松的方式是把车留在公寓的私人停车位，乘公交或火车进入威尼斯。从 Piazzale Roma 或 Venezia Santa Lucia 火车站继续前往 Castello 和 Arsenale 水上巴士站，再步行几分钟即可到 Riva di San Biasio。活动期间请提前查看 ACTV 是否有临时调整。'},
      {title:'即使不登船，也值得专程去看',text:'就算没有预约到登船名额，在威尼斯近距离看到 Amerigo Vespucci 也值得专程前往。如果还能亲眼看到它驶入或离开泻湖，那很可能会成为无需滤镜的威尼斯记忆：一艘95岁的现役帆船，驶过一座千百年来与海洋命运相连的城市。'}
    ],
    practicalTitle:'2026 Amerigo Vespucci 威尼斯：参观、时间与预约',practicalIntro:'想知道如何参观或预约威尼斯的 Amerigo Vespucci？这里汇总已经确认的信息；官方最终公布入场方式后，我们会更新本指南。',
    practical:[['📅 日期','2026年10月2–8日'],['📍 停泊位置','Riva di San Biasio，Castello – 海军历史博物馆前'],['⚓ 登船参观','威尼斯停靠期间计划开放'],['🎟️ 预约','截至9月5日尚未公布威尼斯站专门的预约流程'],['⏰ 参观时间','尚未公布'],['🚤 方便的水上巴士站','Arsenale，下船后步行几分钟'],['➡️ 离港','10月8日前往的里雅斯特']],
    faqTitle:'如何参观和预约威尼斯 Amerigo Vespucci：常见问题',
    faqs:[['参观威尼斯的 Amerigo Vespucci 需要预约吗？','截至2026年9月5日，Tour Vespucci 尚未公布威尼斯站专门的预约流程，因此目前还不能确认是否必须提前预约。官方规则发布后，我们会更新本页。'],['Amerigo Vespucci 威尼斯站什么时候开放预约？','目前尚未公布威尼斯站预约开放日期。官方网站表示，意大利各站的参观详情将逐步发布。'],['Amerigo Vespucci 在威尼斯停靠在哪里？','已公布的停靠地点为 Castello 区 Riva di San Biasio，位于海军历史博物馆前，靠近 Arsenale。'],['登船参观时间已经公布了吗？','还没有。截至2026年9月5日，威尼斯站的参观时间和可能的入场时段尚未公布。']],
    updateLabel:'更新 • 2026年9月5日',updateText:'Tour Vespucci 官方网站确认威尼斯站为10月2日至8日。威尼斯站的参观时间、入场时段以及专门预约流程尚未公布。购买任何第三方所谓“门票”或服务之前，请先查看 Tour Vespucci 官方网站。',
    tipLabel:'我们的建议',tip:'不要只想到圣马可广场。Riva di San Biasio 和 Arsenale 一带本来就是威尼斯非常有海洋气息的区域；当 Vespucci 停在那里时，这几天会格外值得一去。',
    officialTitle:'官方信息',officialText:'出于舰船运行需要，日期、时间和公众开放方式都有可能调整。出发前请务必再次查看官方来源。',tourLabel:'Tour Vespucci 官方网站',navyLabel:'意大利海军 – Amerigo Vespucci',closing:'Amerigo Vespucci：95年的海上航行。威尼斯：一千多年的水上历史。这个十月，它们再次相遇。❤️⚓',
    moreLabel:'继续探索',moreTitle:'威尼斯、海洋与传统',related:[['2026威尼斯历史赛舟会','/zh/journal/regata-storica-2026'],['The Venice Glass Week 2026','/zh/journal/venice-glass-week-2026']],back:'返回旅行日志',
    imageAlt:{cover:'Amerigo Vespucci 停靠在威尼斯水岸',sails:'Amerigo Vespucci 张帆航行',tricolor:'Amerigo Vespucci 与意大利三色箭飞行表演队',night:'夜幕中的 Amerigo Vespucci 停靠威尼斯'}
  }
};

const images={
  cover:'/images/journal-amerigo-vespucci-venezia-2026-cover.webp',
  sails:'/images/journal-amerigo-vespucci-venezia-2026-vele.webp',
  tricolor:'/images/journal-amerigo-vespucci-venezia-2026-tricolore.webp',
  night:'/images/journal-amerigo-vespucci-venezia-2026-notte.webp'
};

export default function AmerigoVespucciArticle({lang}:{lang:Locale}){
  const c=content[lang];
  const prefix=lang==='it'?'':`/${lang}`;
  const canonical=`https://www.margheraveniceapartments.com${prefix}/journal/amerigo-vespucci-venezia-2026`;
  const graph={
    '@context':'https://schema.org',
    '@graph':[
      {
        '@type':'Event',name:c.title,startDate:'2026-10-02',endDate:'2026-10-08',eventStatus:'https://schema.org/EventScheduled',eventAttendanceMode:'https://schema.org/OfflineEventAttendanceMode',
        location:{'@type':'Place',name:'Riva di San Biasio – Museo Storico Navale',address:{'@type':'PostalAddress',addressLocality:'Venezia',addressRegion:'VE',addressCountry:'IT'}},
        image:[`https://www.margheraveniceapartments.com${images.cover}`],description:c.subtitle,
        organizer:{'@type':'Organization',name:'Marina Militare Italiana',url:'https://www.marina.difesa.it/'},url:canonical
      },
      {
        '@type':'Article',headline:c.title,description:c.subtitle,datePublished:'2026-09-05',dateModified:'2026-09-05',inLanguage:lang==='it'?'it-IT':lang==='en'?'en-GB':lang==='de'?'de-DE':lang==='fr'?'fr-FR':lang==='es'?'es-ES':'zh-CN',
        image:[`https://www.margheraveniceapartments.com${images.cover}`],mainEntityOfPage:canonical,
        publisher:{'@type':'Organization',name:'Marghera Venice Apartments',url:'https://www.margheraveniceapartments.com'}
      },
      {
        '@type':'FAQPage',mainEntity:c.faqs.map(([question,answer])=>({'@type':'Question',name:question,acceptedAnswer:{'@type':'Answer',text:answer}}))
      }
    ]
  };

  return <><Header lang={lang}/><main><article>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(graph)}}/>

    <section className="bg-navy pt-20 text-white">
      <div className="mx-auto max-w-7xl px-5 pb-10 pt-12 lg:px-8">
        <nav aria-label="Breadcrumb" className="mb-5 flex flex-wrap gap-2 text-sm text-white/70"><Link href={prefix||'/'}>{c.home}</Link><span>›</span><Link href={`${prefix}/journal`}>{c.journal}</Link><span>›</span><span className="text-gold">Amerigo Vespucci</span></nav>
        <p className="text-xs font-black uppercase tracking-[.22em] text-gold">{c.category} • {c.eventDate}</p>
        <h1 className="mt-4 max-w-6xl font-serif text-[clamp(3rem,8vw,6rem)] leading-[.95]">{c.title}</h1>
        <p className="mt-6 max-w-4xl text-xl leading-8 text-white/80">{c.subtitle}</p>
      </div>
      <div className="mx-auto max-w-7xl px-5 pb-16 lg:px-8"><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem] shadow-soft md:aspect-[16/9]"><Image src={images.cover} alt={c.imageAlt.cover} fill priority sizes="100vw" className="object-cover object-center"/></div></div>
    </section>

    <section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8">
      <p className="font-serif text-3xl leading-relaxed text-navy">{c.lead}</p>
      <div className="mt-12 rounded-[2rem] bg-gold p-8 text-navy md:p-10"><p className="text-xs font-black uppercase tracking-[.22em]">{c.quoteLabel}</p><blockquote className="mt-4 font-serif text-4xl leading-tight md:text-5xl">{c.quote}</blockquote><p className="mt-5 text-lg leading-8 text-navy/80">{c.quoteText}</p></div>
    </div></section>

    <section className="pb-20"><div className="mx-auto max-w-4xl space-y-12 px-5 lg:px-8">
      {c.sections.slice(0,3).map((s,i)=><section key={s.title} className="grid gap-5 md:grid-cols-[70px_1fr]"><div className="font-serif text-5xl text-gold">{String(i+1).padStart(2,'0')}</div><div><h2 className="font-serif text-4xl text-navy">{s.title}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{s.text}</p></div></section>)}
    </div></section>

    <section className="bg-cream py-16"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="relative aspect-[3/2] overflow-hidden rounded-[2rem] shadow-soft md:aspect-[16/9]"><Image src={images.sails} alt={c.imageAlt.sails} fill sizes="100vw" className="object-cover"/></div></div></section>

    <section className="py-20"><div className="mx-auto max-w-4xl space-y-12 px-5 lg:px-8">
      {c.sections.slice(3,5).map((s,i)=><section key={s.title} className="grid gap-5 md:grid-cols-[70px_1fr]"><div className="font-serif text-5xl text-gold">{String(i+4).padStart(2,'0')}</div><div><h2 className="font-serif text-4xl text-navy">{s.title}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{s.text}</p></div></section>)}
    </div></section>

    <section className="bg-navy py-16"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="relative aspect-[3/2] overflow-hidden rounded-[2rem] shadow-soft md:aspect-[16/9]"><Image src={images.tricolor} alt={c.imageAlt.tricolor} fill sizes="100vw" className="object-cover"/></div></div></section>

    <section className="py-20"><div className="mx-auto max-w-4xl space-y-12 px-5 lg:px-8">
      {c.sections.slice(5,7).map((s,i)=><section key={s.title} className="grid gap-5 md:grid-cols-[70px_1fr]"><div className="font-serif text-5xl text-gold">{String(i+6).padStart(2,'0')}</div><div><h2 className="font-serif text-4xl text-navy">{s.title}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{s.text}</p></div></section>)}
    </div></section>

    <section className="bg-cream py-16"><div className="mx-auto max-w-5xl px-5 lg:px-8">
      <div className="rounded-[2rem] bg-white p-8 shadow-soft md:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{c.updateLabel}</p><h2 className="mt-3 font-serif text-4xl text-navy">{c.practicalTitle}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{c.practicalIntro}</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{c.practical.map(([label,value])=><div key={label} className="rounded-2xl border border-navy/10 bg-cream p-5"><p className="text-sm font-black uppercase tracking-[.12em] text-gold">{label}</p><p className="mt-2 font-semibold leading-7 text-navy">{value}</p></div>)}</div><div className="mt-7 rounded-2xl bg-navy p-6 text-white"><p className="leading-7 text-white/85">{c.updateText}</p></div></div>
      <div className="mt-8 rounded-[2rem] bg-gold p-8 text-navy"><p className="text-xs font-black uppercase tracking-[.22em]">{c.tipLabel}</p><p className="mt-4 font-serif text-3xl leading-snug">{c.tip}</p></div>
    </div></section>

    <section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">FAQ • AMERIGO VESPUCCI VENEZIA 2026</p><h2 className="mt-3 font-serif text-4xl text-navy">{c.faqTitle}</h2><div className="mt-8 space-y-4">{c.faqs.map(([question,answer])=><details key={question} className="group rounded-2xl border border-navy/10 bg-cream p-6"><summary className="cursor-pointer list-none pr-8 font-serif text-2xl text-navy">{question}<span className="float-right font-sans text-gold transition group-open:rotate-45">+</span></summary><p className="mt-4 text-lg leading-8 text-slate-600">{answer}</p></details>)}</div></div></section>

    <section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><section className="grid gap-5 md:grid-cols-[70px_1fr]"><div className="font-serif text-5xl text-gold">08</div><div><h2 className="font-serif text-4xl text-navy">{c.sections[7].title}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{c.sections[7].text}</p></div></section></div></section>

    <section className="bg-navy py-16"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="relative aspect-[3/2] overflow-hidden rounded-[2rem] shadow-soft md:aspect-[16/9]"><Image src={images.night} alt={c.imageAlt.night} fill sizes="100vw" className="object-cover object-center"/></div><div className="mx-auto mt-10 max-w-4xl text-center text-white"><p className="text-xs font-black uppercase tracking-[.24em] text-gold">NON CHI COMINCIA MA QUEL CHE PERSEVERA</p><p className="mt-5 font-serif text-4xl leading-tight md:text-5xl">{c.closing}</p></div></div></section>

    <section className="bg-cream py-16"><div className="mx-auto max-w-4xl px-5 lg:px-8"><div className="rounded-[2rem] bg-white p-8 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{c.officialTitle}</p><p className="mt-3 leading-7 text-slate-600">{c.officialText}</p><div className="mt-6 flex flex-wrap gap-3"><a href="https://tourvespucci.it/" target="_blank" rel="noopener noreferrer" className="rounded-full bg-navy px-6 py-3 font-bold text-white">{c.tourLabel} ↗</a><a href="https://www.marina.difesa.it/noi-siamo-la-marina/pilastro-operativo/mezzi/forze-navali/Pagine/Vespucci.aspx" target="_blank" rel="noopener noreferrer" className="rounded-full border border-navy px-6 py-3 font-bold text-navy">{c.navyLabel} ↗</a></div></div></div></section>

    <section className="py-20"><div className="mx-auto max-w-5xl px-5 lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{c.moreLabel}</p><h2 className="mt-3 font-serif text-4xl text-navy">{c.moreTitle}</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{c.related.map(([label,href])=><Link key={href} href={href} className="rounded-3xl border border-slate-200 p-6 font-serif text-2xl text-navy transition hover:-translate-y-1 hover:shadow-soft">{label} <span className="text-gold">→</span></Link>)}</div><div className="mt-10 text-center"><Link href={`${prefix}/journal`} className="inline-flex rounded-full bg-gold px-7 py-4 font-bold text-navy">{c.back}</Link></div></div></section>
  </article></main><Footer lang={lang}/></>;
}
