import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import EditorialHero from '@/components/EditorialHero';
import EditorialStayCta from '@/components/EditorialStayCta';
import {amerigoVespucci2026Audit,type VespucciAuditLang} from '@/data/amerigoVespucci2026Audit';
import {hreflang,localePath} from '@/lib/i18n';

const BASE='https://www.margheraveniceapartments.com';
const IMAGE='/images/journal-amerigo-vespucci-venezia-2026-cover.webp';
export default function AuditedAmerigoVespucciArticle({lang}:{lang:VespucciAuditLang}){
 const c=amerigoVespucci2026Audit[lang]; const logical='/journal/amerigo-vespucci-venezia-2026'; const path=localePath(logical,lang); const url=`${BASE}${path}`;
 const org={'@type':'Organization',name:'Marghera Venice Apartments',url:BASE,logo:{'@type':'ImageObject',url:`${BASE}/images/logo.png`}};
 const event={'@context':'https://schema.org','@type':'Event',name:c.title,description:c.description,startDate:'2026-10-02',endDate:'2026-10-07',eventStatus:'https://schema.org/EventScheduled',eventAttendanceMode:'https://schema.org/OfflineEventAttendanceMode',inLanguage:hreflang[lang],image:[`${BASE}${IMAGE}`],url,location:{'@type':'City',name:'Venezia',address:{'@type':'PostalAddress',addressLocality:'Venezia',addressCountry:'IT'}},organizer:{'@type':'Organization',name:'Marina Militare Italiana',url:'https://www.marina.difesa.it/'}};
 const article={'@context':'https://schema.org','@type':'Article',headline:c.title,description:c.description,inLanguage:hreflang[lang],image:[`${BASE}${IMAGE}`],datePublished:'2026-09-05',dateModified:'2026-09-11',url,mainEntityOfPage:{'@type':'WebPage','@id':url},author:org,publisher:org};
 const faq={'@context':'https://schema.org','@type':'FAQPage',mainEntity:c.faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))};
 const crumbs={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:c.labels.home,item:`${BASE}${localePath('/',lang)}`},{'@type':'ListItem',position:2,name:c.labels.journal,item:`${BASE}${localePath('/journal',lang)}`},{'@type':'ListItem',position:3,name:c.title,item:url}]};
 return <><Header lang={lang}/><main><article className="editorial-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(article)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(event)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faq)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(crumbs)}}/>
  <EditorialHero image={IMAGE} imageAlt={c.title} crumbs={[{label:c.labels.home,href:localePath('/',lang)},{label:c.labels.journal,href:localePath('/journal',lang)},{label:'Amerigo Vespucci'}]} eyebrow={<>Events • {c.eventDate}</>} title={c.title} subtitle={c.subtitle} strongShade/>
  <section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><p className="font-serif text-3xl leading-relaxed text-navy">{c.lead}</p><div className="mt-14 space-y-12">{c.sections.map(([title,text],i)=><section key={title} className="editorial-section-row grid grid-cols-[34px_1fr] gap-3 sm:grid-cols-[42px_1fr] sm:gap-4"><div className="font-serif text-5xl text-gold">{String(i+1).padStart(2,'0')}</div><div><h2 className="font-serif text-4xl text-navy">{title}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{text}</p></div></section>)}</div></div></section>
  <section className="bg-cream py-16"><div className="mx-auto max-w-5xl px-5 lg:px-8"><div className="rounded-[2rem] bg-white p-8 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{c.labels.practical}</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{c.practical.map(([label,value])=><div key={label} className="rounded-2xl bg-cream p-5"><p className="font-bold text-navy">{label}</p><p className="mt-2 leading-7 text-slate-600">{value}</p></div>)}</div></div><div className="mt-7 rounded-[2rem] bg-gold p-8 text-navy"><p className="font-serif text-3xl leading-snug">{c.tip}</p></div></div></section>
  <section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><h2 className="font-serif text-4xl text-navy">{c.labels.faq}</h2><div className="mt-8 space-y-4">{c.faq.map(([q,a])=><details key={q} className="rounded-2xl border border-slate-200 p-6"><summary className="cursor-pointer font-serif text-2xl text-navy">{q}</summary><p className="mt-4 leading-7 text-slate-600">{a}</p></details>)}</div></div></section>
  <section className="bg-navy py-16 text-white"><div className="mx-auto max-w-4xl px-5 lg:px-8"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{c.labels.official}</p><p className="mt-4 leading-7 text-white/75">{c.labels.source}</p><div className="mt-6 flex flex-wrap gap-3"><a href="https://tourvespucci.it/" target="_blank" rel="noopener noreferrer" className="rounded-full bg-gold px-6 py-3 font-bold text-navy">Tour Vespucci ↗</a><a href="https://www.marina.difesa.it/" target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/30 px-6 py-3 font-bold text-white">Marina Militare ↗</a></div></div></section>
  <EditorialStayCta lang={lang} context="journal"/>
  <section className="py-16"><div className="mx-auto max-w-5xl px-5 lg:px-8"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{c.labels.more}</p><div className="mt-6 grid gap-4 md:grid-cols-2">{c.related.map(([label,href])=><Link key={href} href={href} className="rounded-3xl border border-slate-200 p-6 font-serif text-2xl text-navy">{label} <span className="text-gold">→</span></Link>)}</div><div className="mt-10 text-center"><Link href={localePath('/journal',lang)} className="inline-flex rounded-full bg-gold px-7 py-4 font-bold text-navy">{c.labels.back}</Link></div></div></section>
 </article></main><Footer lang={lang}/></>;
}
