import Image from 'next/image'; import Link from 'next/link'; import SocialLinks from './SocialLinks';
type Lang='it'|'en'|'de'|'fr'|'es'|'zh';
const c={
it:{journal:'Journal',desc:'La tua casa per scoprire Venezia e il Veneto, con parcheggio privato, collegamenti H24 e accoglienza Pet & Family.',plan:'Pianifica',homes:'Le nostre case',veneto:'Scopri il Veneto',faq:'Domande frequenti',getting:'Come arrivare',useful:'Link utili',contact:'Contatti',follow:'Seguici',cin:'Codici CIN',privacy:'Privacy Policy',cookies:'Cookie Policy'},
en:{journal:'Journal',desc:'Your home for discovering Venice and Veneto, with private parking, 24/7 connections and Pet & Family Friendly hospitality.',plan:'Plan your stay',homes:'Our apartments',veneto:'Discover Veneto',faq:'Frequently asked questions',getting:'Getting here',useful:'Useful links',contact:'Contact',follow:'Follow us',cin:'CIN codes',privacy:'Privacy Policy',cookies:'Cookie Policy'},
de:{journal:'Journal',desc:'Ihr Zuhause, um Venedig und Venetien zu entdecken – mit privatem Parkplatz, Verbindungen rund um die Uhr und haustier- sowie familienfreundlicher Gastfreundschaft.',plan:'Aufenthalt planen',homes:'Unsere Apartments',veneto:'Venetien entdecken',faq:'Häufige Fragen',getting:'Anreise',useful:'Nützliche Links',contact:'Kontakt',follow:'Folgen Sie uns',cin:'CIN-Codes',privacy:'Datenschutzerklärung',cookies:'Cookie-Richtlinie'},
fr:{journal:'Journal',desc:'Votre point de départ pour découvrir Venise et la Vénétie, avec parking privé, liaisons 24h/24 et accueil adapté aux familles et aux animaux.',plan:'Planifiez votre séjour',homes:'Nos appartements',veneto:'Découvrir la Vénétie',faq:'Questions fréquentes',getting:'Comment arriver',useful:'Liens utiles',contact:'Contact',follow:'Suivez-nous',cin:'Codes CIN',privacy:'Politique de confidentialité',cookies:'Politique relative aux cookies'},
zh:{desc:'以马尔盖拉为家，轻松探索威尼斯与威尼托：私人停车位、全天候交通连接，并欢迎家庭与宠物。',plan:'规划行程',homes:'我们的公寓',veneto:'探索威尼托',journal:'旅行日志',faq:'常见问题',getting:'如何前往',useful:'实用链接',contact:'联系方式',follow:'关注我们',cin:'CIN 登记代码',privacy:'隐私政策',cookies:'Cookie 政策'},
es:{journal:'Journal',desc:'Tu punto de partida para descubrir Venecia y Véneto, con aparcamiento privado, conexiones 24/7 y una acogida pensada para familias y mascotas.',plan:'Planifica tu estancia',homes:'Nuestros apartamentos',veneto:'Descubrir Véneto',faq:'Preguntas frecuentes',getting:'Cómo llegar',useful:'Enlaces útiles',contact:'Contacto',follow:'Síguenos',cin:'Códigos CIN',privacy:'Política de privacidad',cookies:'Política de cookies'}} as const;
const base:Record<Lang,string>={it:'',en:'/en',de:'/de',fr:'/fr',es:'/es',zh:'/zh'};
export default function Footer({lang='it'}:{lang?:Lang}){const t=c[lang],b=base[lang];return <footer id="contatti" className="bg-navy py-16 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 md:grid-cols-2 xl:grid-cols-4 lg:px-8"><div><div className="flex items-center gap-3"><Image src="/images/logo.png" alt="Marghera Venice Apartments" width={58} height={58} className="h-[58px] w-[58px] rounded-full bg-cream object-contain"/><div className="font-serif tracking-widest">MARGHERA<br/><span className="text-xs">VENICE APARTMENTS</span></div></div><p className="mt-5 max-w-sm text-white/70">{t.desc}</p></div><div><h4 className="font-bold text-gold">{t.plan}</h4><div className="mt-4 grid gap-2 text-white/70"><Link href={`${b}/#case`}>{t.homes}</Link><Link href={`${b}/${lang==='it'?'scopri-il-veneto':'discover-veneto'}`}>{t.veneto}</Link><Link href={`${b}/journal`}>{t.journal}</Link><Link href={`${b}/faq`}>{t.faq}</Link><Link href={`${b}/${lang==='it'?'come-raggiungere-venezia':'getting-to-venice'}`}>{t.getting}</Link><Link href={`${b}/${lang==='it'?'link-utili':'useful-links'}`}>{t.useful}</Link></div></div><div><h4 className="font-bold text-gold">{t.contact}</h4><div className="mt-4 grid gap-2 text-white/70"><a href="tel:+393514462261">+39 351 446 2261</a><a className="break-all" href="mailto:rossiapartmentvenice@gmail.com">rossiapartmentvenice@gmail.com</a><a className="break-all" href="mailto:dimoracastelli22@gmail.com">dimoracastelli22@gmail.com</a></div><p className="mt-6 text-xs font-black uppercase tracking-[.18em] text-gold">{t.follow}</p><SocialLinks className="mt-3 text-white/80" showWhatsApp={lang!=='zh'} compact lang={lang}/></div><div><h4 className="font-bold text-gold">{t.cin}</h4><p className="mt-4 break-all text-sm text-white/70">Rossi Apartment<br/>IT027042C2EDHHAM7Z<br/><br/>Dimora Castelli<br/>IT027042C2YOUCUFM2</p></div></div><div className="mx-auto mt-12 flex max-w-7xl flex-col gap-3 border-t border-white/10 px-5 pt-6 text-sm text-white/50 md:flex-row md:justify-between lg:px-8"><span>© 2026 Marghera Venice Apartments</span><span><Link href={`${b}/privacy-policy`} className="hover:text-white">{t.privacy}</Link> · <Link href={`${b}/cookie-policy`} className="hover:text-white">{t.cookies}</Link></span></div></footer>}
