import Image from 'next/image';
import Link from 'next/link';
import SocialLinks from './SocialLinks';
import type {ReactNode} from 'react';
import CookieSettingsButton from './CookieSettingsButton';

type Lang='it'|'en'|'de'|'fr'|'es'|'zh';

type FooterCopy={
  desc:string;explore:string;stay:string;useful:string;contact:string;follow:string;cin:string;privacy:string;cookies:string;cookieSettings:string;imageCredits:string;
  venice:string;veneto:string;guides:string;journal:string;experiences:string;rossi:string;dimora:string;getting:string;faq:string;contactLink:string;food:string;services:string;links:string;
};
const c:Record<Lang,FooterCopy>={
 it:{desc:'La tua casa per scoprire Venezia e il Veneto, con parcheggio privato, collegamenti H24 e accoglienza Pet & Family.',explore:'Esplora',stay:'Soggiorna',useful:'Utile',contact:'Contatti',follow:'Seguici',cin:'Codici CIN',privacy:'Privacy Policy',cookies:'Cookie Policy',cookieSettings:'Preferenze cookie',imageCredits:'Crediti immagini',venice:'Scopri Venezia',veneto:'Scopri il Veneto',guides:'Guide',journal:'Journal',experiences:'Esperienze',rossi:'Rossi Apartment',dimora:'Dimora Castelli',getting:'Come arrivare',faq:'FAQ',contactLink:'Contatti',food:'Dove mangiare',services:'Servizi in zona',links:'Link utili'},
 en:{desc:'Your home for discovering Venice and Veneto, with private parking, 24/7 connections and Pet & Family Friendly hospitality.',explore:'Explore',stay:'Stay',useful:'Useful',contact:'Contact',follow:'Follow us',cin:'CIN codes',privacy:'Privacy Policy',cookies:'Cookie Policy',cookieSettings:'Cookie settings',imageCredits:'Image credits',venice:'Discover Venice',veneto:'Discover Veneto',guides:'Guides',journal:'Journal',experiences:'Experiences',rossi:'Rossi Apartment',dimora:'Dimora Castelli',getting:'Getting here',faq:'FAQ',contactLink:'Contact',food:'Where to eat',services:'Services nearby',links:'Useful links'},
 de:{desc:'Ihr Zuhause, um Venedig und Venetien zu entdecken – mit privatem Parkplatz, Verbindungen rund um die Uhr und haustier- sowie familienfreundlicher Gastfreundschaft.',explore:'Entdecken',stay:'Übernachten',useful:'Nützlich',contact:'Kontakt',follow:'Folgen Sie uns',cin:'CIN-Codes',privacy:'Datenschutzerklärung',cookies:'Cookie-Richtlinie',cookieSettings:'Cookie-Einstellungen',imageCredits:'Bildnachweise',venice:'Venedig entdecken',veneto:'Venetien entdecken',guides:'Reiseführer',journal:'Journal',experiences:'Erlebnisse',rossi:'Rossi Apartment',dimora:'Dimora Castelli',getting:'Anreise',faq:'FAQ',contactLink:'Kontakt',food:'Essen gehen',services:'Services in der Nähe',links:'Nützliche Links'},
 fr:{desc:'Votre point de départ pour découvrir Venise et la Vénétie, avec parking privé, liaisons 24h/24 et accueil adapté aux familles et aux animaux.',explore:'Explorer',stay:'Séjourner',useful:'Utile',contact:'Contact',follow:'Suivez-nous',cin:'Codes CIN',privacy:'Politique de confidentialité',cookies:'Politique relative aux cookies',cookieSettings:'Préférences cookies',imageCredits:'Crédits images',venice:'Découvrir Venise',veneto:'Découvrir la Vénétie',guides:'Guides',journal:'Journal',experiences:'Expériences',rossi:'Rossi Apartment',dimora:'Dimora Castelli',getting:'Comment arriver',faq:'FAQ',contactLink:'Contact',food:'Où manger',services:'Services à proximité',links:'Liens utiles'},
 es:{desc:'Tu punto de partida para descubrir Venecia y Véneto, con aparcamiento privado, conexiones 24/7 y una acogida pensada para familias y mascotas.',explore:'Explorar',stay:'Alojarse',useful:'Útil',contact:'Contacto',follow:'Síguenos',cin:'Códigos CIN',privacy:'Política de privacidad',cookies:'Política de cookies',cookieSettings:'Preferencias de cookies',imageCredits:'Créditos de imágenes',venice:'Descubrir Venecia',veneto:'Descubrir Véneto',guides:'Guías',journal:'Journal',experiences:'Experiencias',rossi:'Rossi Apartment',dimora:'Dimora Castelli',getting:'Cómo llegar',faq:'FAQ',contactLink:'Contacto',food:'Dónde comer',services:'Servicios cercanos',links:'Enlaces útiles'},
 zh:{desc:'以马尔盖拉为家，轻松探索威尼斯与威尼托：私人停车位、全天候交通连接，并欢迎家庭与宠物。',explore:'探索',stay:'住宿',useful:'实用',contact:'联系方式',follow:'关注我们',cin:'CIN 登记代码',privacy:'隐私政策',cookies:'Cookie 政策',cookieSettings:'Cookie 设置',imageCredits:'图片版权信息',venice:'探索威尼斯',veneto:'探索威尼托',guides:'旅行指南',journal:'旅行日志',experiences:'精选体验',rossi:'Rossi Apartment',dimora:'Dimora Castelli',getting:'如何前往',faq:'常见问题',contactLink:'联系我们',food:'餐饮推荐',services:'附近服务',links:'实用链接'}
};
const base:Record<Lang,string>={it:'',en:'/en',de:'/de',fr:'/fr',es:'/es',zh:'/zh'};
function route(lang:Lang,key:'venice'|'veneto'|'guides'|'journal'|'experiences'|'getting'|'faq'|'contact'|'food'|'services'|'links'|'rossi'|'dimora'|'credits'){
 const b=base[lang];
 const routes={
  venice:lang==='it'?'/scopri-venezia':`${b}/discover-venice`,veneto:lang==='it'?'/scopri-il-veneto':`${b}/discover-veneto`,guides:lang==='it'?'/guide':`${b}/guide`,journal:`${b}/journal`,experiences:lang==='it'?'/collaborazioni':`${b}/experiences`,getting:lang==='it'?'/come-raggiungere-venezia':`${b}/getting-to-venice`,faq:`${b}/faq`,contact:lang==='it'?'/#contatto-diretto':`${b}/#direct-contact`,food:lang==='it'?'/dove-mangiare':`${b}/where-to-eat`,services:lang==='it'?'/servizi-in-zona':`${b}/services-nearby`,links:lang==='it'?'/link-utili':`${b}/useful-links`,rossi:lang==='it'?'/case/rossi-apartment':`${b}/apartments/rossi-apartment`,dimora:lang==='it'?'/case/dimora-castelli':`${b}/apartments/dimora-castelli`,credits:{it:'/crediti-immagini',en:'/en/image-credits',de:'/de/bildnachweise',fr:'/fr/credits-images',es:'/es/creditos-imagenes',zh:'/zh/image-credits'}[lang]
 } as const;
 return routes[key];
}
function FooterLink({href,children}:{href:string;children:ReactNode}){return <Link href={href} className="transition hover:text-white">{children}</Link>}
export default function Footer({lang='it'}:{lang?:Lang}){
 const t=c[lang];
 return <footer id="contatti" className="bg-navy py-16 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 md:grid-cols-2 xl:grid-cols-5 lg:px-8">
  <div className="xl:col-span-2"><div className="flex items-center gap-3"><Image src="/images/logo.png" alt="Marghera Venice Apartments" width={58} height={58} className="h-[58px] w-[58px] rounded-full bg-cream object-contain"/><div className="font-serif tracking-widest">MARGHERA<br/><span className="text-xs">VENICE APARTMENTS</span></div></div><p className="mt-5 max-w-sm text-white/70">{t.desc}</p><p className="mt-6 text-xs font-black uppercase tracking-[.18em] text-gold">{t.follow}</p><SocialLinks className="mt-3 text-white/80" showWhatsApp={lang!=='zh'} compact lang={lang}/></div>
  <div><h4 className="font-bold text-gold">{t.explore}</h4><div className="mt-4 grid gap-2 text-white/70"><FooterLink href={route(lang,'venice')}>{t.venice}</FooterLink><FooterLink href={route(lang,'veneto')}>{t.veneto}</FooterLink><FooterLink href={route(lang,'guides')}>{t.guides}</FooterLink><FooterLink href={route(lang,'journal')}>{t.journal}</FooterLink><FooterLink href={route(lang,'experiences')}>{t.experiences}</FooterLink></div></div>
  <div><h4 className="font-bold text-gold">{t.stay}</h4><div className="mt-4 grid gap-2 text-white/70"><FooterLink href={route(lang,'rossi')}>{t.rossi}</FooterLink><FooterLink href={route(lang,'dimora')}>{t.dimora}</FooterLink><FooterLink href={route(lang,'getting')}>{t.getting}</FooterLink><FooterLink href={route(lang,'faq')}>{t.faq}</FooterLink><FooterLink href={route(lang,'contact')}>{t.contactLink}</FooterLink></div></div>
  <div><h4 className="font-bold text-gold">{t.useful}</h4><div className="mt-4 grid gap-2 text-white/70"><FooterLink href={route(lang,'food')}>{t.food}</FooterLink><FooterLink href={route(lang,'services')}>{t.services}</FooterLink><FooterLink href={route(lang,'links')}>{t.links}</FooterLink></div><h4 className="mt-8 font-bold text-gold">{t.contact}</h4><div className="mt-4 grid gap-2 text-sm text-white/70"><a href="tel:+393514462261">+39 351 446 2261</a><a className="break-all" href="mailto:info@margheraveniceapartments.com">info@margheraveniceapartments.com</a></div><p className="mt-7 text-xs font-black uppercase tracking-[.16em] text-gold">{t.cin}</p><p className="mt-3 break-all text-xs leading-5 text-white/55">Rossi: IT027042C2EDHHAM7Z<br/>Castelli: IT027042C2YOUCUFM2</p></div>
 </div>
 <div className="mx-auto mt-12 flex max-w-7xl flex-col gap-3 border-t border-white/10 px-5 pt-6 text-sm text-white/50 md:flex-row md:items-center md:justify-between lg:px-8"><span>© 2026 Marghera Venice Apartments</span><span className="flex flex-wrap gap-x-2 gap-y-1"><FooterLink href={`${base[lang]}/privacy-policy`}>{t.privacy}</FooterLink><span>·</span><FooterLink href={`${base[lang]}/cookie-policy`}>{t.cookies}</FooterLink><span>·</span><FooterLink href={route(lang,'credits')}>{t.imageCredits}</FooterLink><span>·</span><CookieSettingsButton label={t.cookieSettings}/></span></div>
 </footer>;
}
