import Image from 'next/image';
import Link from 'next/link';
import {cultureIndexPath} from '@/data/cultureTranslations';
import {localePath,type SiteLang} from '@/lib/i18n';
type Lang=SiteLang;
const sections={it:['Check-in / Check-out','Wi-Fi','Parcheggio','Appartamento ed elettrodomestici','Rifiuti e raccolta differenziata','Link utili'],en:['Check-in / Check-out','Wi-Fi','Parking','Apartment & appliances','Waste & recycling','Useful links'],de:['Check-in / Check-out','WLAN','Parkplatz','Apartment & Geräte','Müll & Recycling','Nützliche Links'],fr:['Check-in / Check-out','Wi-Fi','Parking','Appartement & appareils','Déchets & tri','Liens utiles'],es:['Check-in / Check-out','Wi-Fi','Aparcamiento','Apartamento y electrodomésticos','Residuos y reciclaje','Enlaces útiles'],zh:['入住 / 退房','Wi-Fi','停车','公寓与电器','垃圾与分类','实用链接']} as const;
const publicGuides={it:['Guide pubbliche utili durante il soggiorno','Musei, monumenti e chiese','Cosa vedere in Veneto','Gondola Tour','Venezia con bambini','Come raggiungere Venezia','Contributo di Accesso'],en:['Useful public guides for your stay','Museums, monuments and churches','What to see in Veneto','Venice Gondola Tour','Venice with children','Getting to Venice','Venice Access Fee'],de:['Nützliche öffentliche Guides für Ihren Aufenthalt','Museen, Monumente und Kirchen','Sehenswürdigkeiten in Venetien','Gondelfahrt in Venedig','Venedig mit Kindern','Anreise nach Venedig','Zutrittsgebühr Venedig'],fr:['Guides publics utiles pendant votre séjour','Musées, monuments et églises','Que voir en Vénétie','Tour en gondole','Venise avec des enfants','Rejoindre Venise','Contribution d’accès à Venise'],es:['Guías públicas útiles durante tu estancia','Museos, monumentos e iglesias','Qué ver en el Véneto','Paseo en góndola','Venecia con niños','Cómo llegar a Venecia','Tasa de acceso a Venecia'],zh:['住宿期间实用的公开指南','威尼斯博物馆、古迹与教堂','威尼托值得参观的地方','威尼斯贡多拉指南','带孩子游威尼斯','如何前往威尼斯','威尼斯入城费']} as const;
const t={it:['Benvenuti','La guida privata dell’appartamento è pronta per essere completata. Qui inseriremo solo informazioni operative approvate: check-in, Wi-Fi, parcheggio, elettrodomestici, rifiuti e istruzioni utili.','Contenuti operativi in preparazione','Cambia lingua'],en:['Welcome','Your private apartment guide is ready to be completed. This area will contain only approved practical information: check-in, Wi-Fi, parking, appliances, waste instructions and useful house guidance.','Practical content coming soon','Change language'],de:['Willkommen','Der private Apartment-Guide ist vorbereitet. Hier erscheinen ausschließlich freigegebene praktische Angaben zu Check-in, WLAN, Parkplatz, Geräten, Mülltrennung und Hausinformationen.','Praktische Inhalte in Vorbereitung','Sprache ändern'],fr:['Bienvenue','Le guide privé de l’appartement est prêt à être complété. Seules des informations pratiques validées y seront ajoutées : check-in, Wi-Fi, parking, appareils, déchets et consignes utiles.','Informations pratiques en préparation','Changer de langue'],es:['Bienvenidos','La guía privada del apartamento está preparada para completarse. Aquí añadiremos únicamente información práctica aprobada: check-in, Wi-Fi, aparcamiento, electrodomésticos, residuos e instrucciones útiles.','Contenido práctico en preparación','Cambiar idioma'],zh:['欢迎','公寓私人指南的结构已经准备好。这里仅会加入已确认的实用信息，包括入住、Wi-Fi、停车、电器、垃圾分类和公寓使用说明。','实用内容准备中','更改语言']} as const;
export default function GuestPlaceholder({lang,apartment}:{lang:Lang;apartment:'rossi'|'dimora-castelli'}){
 const x=t[lang],g=publicGuides[lang],name=apartment==='rossi'?'Rossi Apartment':'Dimora Castelli';
 const useful=[[g[3],localePath('/guide/gondola-tour-venezia',lang)],[g[4],localePath('/journal/venezia-con-bambini',lang)],[g[5],localePath('/come-raggiungere-venezia',lang)],[g[6],localePath('/journal/contributo-accesso-venezia',lang)]] as const;
 return <main className="min-h-screen bg-cream px-5 py-10 text-navy"><div className="mx-auto max-w-2xl"><div className="text-center"><Image src="/images/logo.png" alt="Marghera Venice Apartments" width={88} height={88} className="mx-auto rounded-full bg-white"/><p className="mt-5 text-xs font-black uppercase tracking-[.22em] text-gold">{name}</p><h1 className="mt-3 font-serif text-5xl">{x[0]}</h1><p className="mx-auto mt-4 max-w-xl text-lg leading-8 text-slate-600">{x[1]}</p></div><section className="mt-10 rounded-[2rem] bg-white p-7 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{x[2]}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{sections[lang].map(i=><div key={i} className="rounded-2xl bg-cream p-4 font-semibold text-navy/70">{i}</div>)}</div></section><section className="mt-7 rounded-[2rem] bg-navy p-7 text-white shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{g[0]}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link href={cultureIndexPath('venice',lang)} className="rounded-2xl bg-white px-5 py-4 font-bold text-navy">🏛️ {g[1]}</Link><Link href={cultureIndexPath('veneto',lang)} className="rounded-2xl border border-white/30 px-5 py-4 font-bold text-white">🗺️ {g[2]}</Link>{useful.map(([label,href])=><Link key={href} href={href} className="rounded-2xl border border-white/30 px-5 py-4 font-bold text-white">→ {label}</Link>)}</div></section><div className="mt-7 text-center"><Link href={`/guest/${apartment}`} className="inline-flex rounded-full bg-navy px-6 py-3 font-bold text-white">{x[3]}</Link></div></div></main>;
}
