import Image from 'next/image';
import Link from 'next/link';
import Script from 'next/script';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SectionTitle from '@/components/SectionTitle';
import type {GuideData} from '@/components/GuideTemplate';

type Lang='de'|'fr'|'es'|'zh';
const ui={
 de:{home:'Startseite',guides:'Reiseführer',plan:'Besuch planen',back:'← Zurück zu den Reiseführern',before:'Vor der Abfahrt',beforeTitle:'Aktuelle Informationen immer prüfen',beforeText:'Fahrpläne, Preise, Zugangsregeln und Servicebedingungen können sich ändern. Nutzen Sie diese Seite für die Planung und prüfen Sie offizielle Quellen kurz vor dem Ausflug.',miss:'Nicht verpassen',six:(x:string)=>`Sechs Arten, ${x} zu entdecken`,sixText:'Eine ausgewogene Auswahl aus Orten, Landschaften und Erlebnissen.',exp:'Erlebnisse',expTitle:'Gestalten Sie den Tag in Ihrem eigenen Tempo',expText:'Nicht nur Sehenswürdigkeiten, sondern verschiedene Arten, das Reiseziel zu erleben.',itin:'Vorgeschlagene Route',itinTitle:(x:string)=>`Ein Tag in ${x}`,itinText:'Ein flexibler Ablauf, den Sie an Jahreszeit, Wetter und Verkehr anpassen können.',tip:'Unser praktischer Tipp',heart:'Ein Ort, den Einheimische lieben',history:'Eine Geschichte aus der Region',faq:'Häufig gestellte Fragen',faqTitle:(x:string)=>`Vor Ihrem Besuch in ${x}`,faqText:'Kurze Antworten auf häufige Fragen.',related:'Verwandte Reiseführer',relatedTitle:'Weiter entdecken'},
 fr:{home:'Accueil',guides:'Guides',plan:'Organiser la visite',back:'← Retour aux guides',before:'Avant de partir',beforeTitle:'Vérifiez toujours les informations à jour',beforeText:'Horaires, tarifs, accès et conditions de service peuvent évoluer. Utilisez ce guide pour préparer votre journée, puis vérifiez les sources officielles peu avant le départ.',miss:'À ne pas manquer',six:(x:string)=>`Six façons de découvrir ${x}`,sixText:'Une sélection équilibrée de lieux, paysages et expériences.',exp:'Expériences',expTitle:'Composez la journée à votre rythme',expText:'Pas seulement des choses à voir, mais différentes façons de vivre la destination.',itin:'Itinéraire conseillé',itinTitle:(x:string)=>`Une journée à ${x}`,itinText:'Un programme flexible à adapter à la saison, à la météo et aux transports.',tip:'Notre conseil pratique',heart:'Un lieu apprécié des habitants',history:'Une histoire du territoire',faq:'Questions fréquentes',faqTitle:(x:string)=>`Avant de visiter ${x}`,faqText:'Des réponses rapides aux questions les plus courantes.',related:'Guides associés',relatedTitle:'Continuer à explorer'},
 es:{home:'Inicio',guides:'Guías',plan:'Organizar la visita',back:'← Volver a las guías',before:'Antes de salir',beforeTitle:'Comprueba siempre la información actualizada',beforeText:'Horarios, tarifas, accesos y condiciones del servicio pueden cambiar. Usa esta guía para planificar el día y verifica las fuentes oficiales poco antes de salir.',miss:'No te lo pierdas',six:(x:string)=>`Seis formas de descubrir ${x}`,sixText:'Una selección equilibrada de lugares, paisajes y experiencias.',exp:'Experiencias',expTitle:'Organiza el día a tu propio ritmo',expText:'No solo cosas que ver, sino distintas maneras de vivir el destino.',itin:'Itinerario recomendado',itinTitle:(x:string)=>`Un día en ${x}`,itinText:'Un programa flexible que puedes adaptar a la temporada, al tiempo y al transporte.',tip:'Nuestro consejo práctico',heart:'Un lugar que encanta a los locales',history:'Una historia del territorio',faq:'Preguntas frecuentes',faqTitle:(x:string)=>`Antes de visitar ${x}`,faqText:'Respuestas rápidas a las dudas más habituales.',related:'Guías relacionadas',relatedTitle:'Sigue explorando'},
 zh:{home:'首页',guides:'旅行指南',plan:'规划行程',back:'← 返回旅行指南',before:'出发前',beforeTitle:'请始终核对最新信息',beforeText:'时刻、票价、开放条件和服务安排都可能变化。可先用本指南规划行程，并在出发前通过官方来源再次确认。',miss:'不容错过',six:(x:string)=>`发现${x}的六种方式`,sixText:'从景点、风景到体验，给您一个更均衡的选择。',exp:'体验方式',expTitle:'按照自己的节奏安排一天',expText:'不仅是“看什么”，也包括用不同方式感受目的地。',itin:'推荐行程',itinTitle:(x:string)=>`${x}一日行程`,itinText:'可根据季节、天气和交通情况灵活调整。',tip:'我们的实用建议',heart:'当地人喜欢的角落',history:'当地故事',faq:'常见问题',faqTitle:(x:string)=>`前往${x}之前`,faqText:'快速解答最常见的问题。',related:'相关指南',relatedTitle:'继续探索'}
} as const;

const relatedCandidates:Record<Lang,[string,string][]>={
 de:[['Murano','/guide/murano'],['Burano','/guide/burano'],['Lido di Venezia','/guide/lido-di-venezia'],['Pellestrina','/guide/pellestrina'],['Chioggia','/guide/chioggia'],['Padua','/guide/padova'],['Treviso','/guide/treviso'],['Verona','/guide/verona'],['Dolomiten','/guide/dolomiti']],
 fr:[['Murano','/guide/murano'],['Burano','/guide/burano'],['Lido de Venise','/guide/lido-di-venezia'],['Pellestrina','/guide/pellestrina'],['Chioggia','/guide/chioggia'],['Padoue','/guide/padova'],['Trévise','/guide/treviso'],['Vérone','/guide/verona'],['Dolomites','/guide/dolomiti']],
 es:[['Murano','/guide/murano'],['Burano','/guide/burano'],['Lido de Venecia','/guide/lido-di-venezia'],['Pellestrina','/guide/pellestrina'],['Chioggia','/guide/chioggia'],['Padua','/guide/padova'],['Treviso','/guide/treviso'],['Verona','/guide/verona'],['Dolomitas','/guide/dolomiti']],
 zh:[['Murano 穆拉诺','/guide/murano'],['Burano 布拉诺','/guide/burano'],['威尼斯丽都','/guide/lido-di-venezia'],['Pellestrina','/guide/pellestrina'],['Chioggia 基奥贾','/guide/chioggia'],['Padova 帕多瓦','/guide/padova'],['Treviso 特雷维索','/guide/treviso'],['Verona 维罗纳','/guide/verona'],['多洛米蒂','/guide/dolomiti']]
};
const lagoonSlugs=new Set(['murano','burano','lido-di-venezia','pellestrina','certosa','sant-erasmo']);

const faqFallback:Record<Lang,[string,string][]>= {
 de:[['Wie viel Zeit sollte ich einplanen?','Für die meisten Ziele ist mindestens ein halber Tag sinnvoll; mit einem ganzen Tag bleibt mehr Zeit für Pausen und spontane Entdeckungen.'],['Ist das Ziel für Familien geeignet?','Ja. Planen Sie realistische Etappen, Pausen und prüfen Sie bei Attraktionen die aktuellen Zugangsbedingungen.'],['Kann ich mit einem Hund hinfahren?','Außenbereiche sind häufig gut geeignet. Prüfen Sie vorab die Regeln für öffentliche Verkehrsmittel, Museen und einzelne Sehenswürdigkeiten.'],['Sollte ich im Voraus reservieren?','Für Museen, besondere Erlebnisse und stark besuchte Zeiten ist eine Reservierung empfehlenswert.']],
 fr:[['Combien de temps faut-il prévoir ?','Pour la plupart des destinations, prévoyez au minimum une demi-journée ; une journée complète laisse davantage de temps pour les pauses et les découvertes spontanées.'],['La destination convient-elle aux familles ?','Oui. Prévoyez des étapes réalistes, des pauses et vérifiez les conditions d’accès des attractions.'],['Peut-on venir avec un chien ?','Les espaces extérieurs sont souvent adaptés. Vérifiez auparavant les règles des transports, musées et sites visités.'],['Faut-il réserver à l’avance ?','Pour les musées, les expériences particulières et les périodes très fréquentées, la réservation est recommandée.']],
 es:[['¿Cuánto tiempo conviene dedicar?','Para la mayoría de destinos recomendamos al menos medio día; una jornada completa permite hacer pausas y descubrir el lugar sin prisas.'],['¿Es adecuado para familias?','Sí. Organiza etapas realistas, haz pausas y comprueba las condiciones de acceso de cada atracción.'],['¿Se puede visitar con perro?','Los espacios exteriores suelen ser adecuados. Comprueba antes las normas del transporte público, museos y lugares concretos.'],['¿Hay que reservar con antelación?','Para museos, experiencias especiales y periodos de mucha afluencia es recomendable reservar.']],
 zh:[['建议预留多长时间？','大多数目的地至少安排半天会更从容；如果有一整天，还能留出休息和临时探索的时间。'],['适合家庭和孩子吗？','适合。建议减少赶路，安排休息，并提前确认景点的最新开放与入场规定。'],['可以带狗前往吗？','多数户外区域较方便，但请提前确认公共交通、博物馆和具体景点的宠物规定。'],['需要提前预订吗？','博物馆、特别体验以及游客较多的时期，建议提前预约或购票。']]
};
const pellestrinaHistory:Record<Lang,[string,string]>={
 de:['Die Murazzi und die Acqua Granda von 1966','Die Murazzi wurden zum Schutz von Lido und Pellestrina vor dem Meer errichtet. Das außergewöhnliche Hochwasser vom 4. November 1966 stellte die Küstenschutzanlagen schwer auf die Probe und ist bis heute Teil der venezianischen Erinnerung.'],
 fr:['Les Murazzi et l’Acqua Granda de 1966','Les Murazzi ont été construits pour protéger le Lido et Pellestrina de la mer. La crue exceptionnelle du 4 novembre 1966 a durement éprouvé les défenses côtières et reste profondément ancrée dans la mémoire vénitienne.'],
 es:['Los Murazzi y el Acqua Granda de 1966','Los Murazzi se construyeron para proteger el Lido y Pellestrina del mar. La excepcional inundación del 4 de noviembre de 1966 puso a prueba las defensas costeras y sigue formando parte de la memoria veneciana.'],
 zh:['Murazzi 海堤与 1966 年的 Acqua Granda','Murazzi 海堤最初用于保护丽都和 Pellestrina 免受海浪侵袭。1966 年 11 月 4 日的特大洪水严重考验了海岸防护设施，至今仍是威尼斯集体记忆的一部分。']
};
export default function GuideTemplateLocalized({lang,data}:{lang:Lang;data:GuideData}){
 const t=ui[lang];
 const officialLinks=(data.officialLinks&&data.officialLinks.length)?data.officialLinks:(lagoonSlugs.has(data.slug)?[['Venezia Unica','https://www.veneziaunica.it/en/'],['ACTV / AVM','https://avm.avmspa.it/en']]:[['Veneto.eu','https://www.veneto.eu/en/'],['Trenitalia','https://www.trenitalia.com/en.html']]);
 const related=(data.related&&data.related.length)?data.related:relatedCandidates[lang].filter(([,href])=>!href.endsWith('/'+data.slug)).slice(0,3);
 const highlights=data.highlights.length>=6?data.highlights.slice(0,6):[...data.highlights,...data.experiences.filter(([title])=>!data.highlights.some(([existing])=>existing===title))].slice(0,6);
 const experiences=data.experiences.length>=6?data.experiences.slice(0,6):[...data.experiences,...data.highlights.filter(([title])=>!data.experiences.some(([existing])=>existing===title))].slice(0,6);
 const faq=data.faq.length>=4?data.faq.slice(0,4):[...data.faq,...faqFallback[lang].filter(([question])=>!data.faq.some(([existing])=>existing===question))].slice(0,4);
 const history=data.historyText&&data.historyTitle?[data.historyTitle,data.historyText] as [string,string]:(data.slug==='pellestrina'?pellestrinaHistory[lang]:undefined);
 const localizedHref=(href:string)=>href.startsWith(`/${lang}/`)||href===`/${lang}`?href:`/${lang}${href.startsWith('/')?href:`/${href}`}`;
 return <><Header lang={lang}/><main data-guide={data.slug}>
  <section className="relative min-h-[84vh] overflow-hidden pt-20"><Image src={data.image} alt={data.imageAlt} fill priority sizes="100vw" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-t from-navy via-navy/50 to-navy/10"/>{data.slug==='dolomiti'&&<p className="absolute bottom-4 right-5 z-20 text-[11px] text-white/90 drop-shadow-md">Photo: Stefano Bazzoli / Unsplash</p>}<div className="relative mx-auto flex min-h-[calc(84vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-24 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap items-center gap-2 text-sm text-white/75"><Link href={`/${lang}`}>{t.home}</Link><span>›</span><Link href={`/${lang}/guide`}>{t.guides}</Link><span>›</span><span className="text-gold">{data.title}</span></nav><p className="text-xs font-black uppercase tracking-[.25em] text-gold">{data.kicker}</p><h1 className="mt-4 break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{data.title}</h1><p className="mt-4 font-serif text-3xl">{data.subtitle}</p><p className="mt-6 max-w-3xl text-xl text-white/80">{data.description}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#itinerary" className="rounded-full bg-gold px-7 py-4 font-bold text-navy">{t.plan}</a><Link href={`/${lang}/guide`} className="rounded-full border border-white/60 px-7 py-4 font-bold text-white">{t.back}</Link></div></div></div></section>
  <section className="relative z-10 -mt-8 px-5 lg:px-8"><div className="mx-auto grid max-w-7xl gap-4 rounded-[2rem] bg-white p-6 shadow-soft sm:grid-cols-2 lg:grid-cols-4">{data.badges.map(([a,b])=><div key={a} className="rounded-2xl bg-cream p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-gold">{a}</p><p className="mt-2 font-serif text-2xl text-navy">{b}</p></div>)}</div></section>
  <section className="py-16"><div className="mx-auto grid max-w-7xl gap-14 px-5 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Marghera Venice Guide</p><h2 className="mt-3 font-serif text-5xl text-navy">{data.introTitle}</h2><div className="mt-7 space-y-5 text-lg leading-8 text-slate-600">{data.intro.map(p=><p key={p}>{p}</p>)}</div></div><aside className="rounded-[2rem] bg-navy p-8 text-white shadow-soft"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.before}</p><h2 className="mt-3 font-serif text-4xl">{t.beforeTitle}</h2><p className="mt-5 text-white/75">{t.beforeText}</p><div className="mt-7 grid gap-3">{officialLinks.map(([label,url])=><a key={url} href={url} target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/40 px-5 py-3 text-center font-bold first:bg-white first:text-navy">{label} ↗</a>)}</div></aside></div></section>
  <section className="bg-cream py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={t.miss} title={t.six(data.title)} text={t.sixText}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{highlights.map(([a,b])=><article key={a} className="rounded-[2rem] bg-white p-8 shadow-soft"><div className="text-2xl text-gold">✦</div><h2 className="mt-4 font-serif text-3xl text-navy">{a}</h2><p className="mt-3 text-slate-600">{b}</p></article>)}</div></div></section>
  <section className="py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={t.exp} title={t.expTitle} text={t.expText}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{experiences.map(([a,b])=><article key={a} className="rounded-[2rem] border border-slate-200 bg-white p-8"><h2 className="font-serif text-3xl text-navy">{a}</h2><p className="mt-3 text-slate-600">{b}</p></article>)}</div></div></section>
  <section id="itinerary" className="bg-navy py-16 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={t.itin} title={t.itinTitle(data.title)} text={t.itinText}/><div className="grid gap-4">{data.itinerary.map(([time,a,b])=><article key={time+a} className="grid gap-4 rounded-[2rem] bg-white/10 p-7 md:grid-cols-[110px_1fr]"><div className="font-black tracking-[.14em] text-gold">{time}</div><div><h2 className="font-serif text-3xl">{a}</h2><p className="mt-2 text-white/70">{b}</p></div></article>)}</div></div></section>
  <section className="py-16"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div className="relative min-h-[420px] overflow-hidden rounded-[2rem] shadow-soft"><Image src={data.image} alt={data.imageAlt} fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover"/></div><div className="flex flex-col justify-center"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.tip}</p><h2 className="mt-3 font-serif text-5xl text-navy">{data.adviceTitle}</h2><p className="mt-6 text-lg text-slate-600">{data.advice}</p>{data.heartText&&<div className="mt-8 rounded-[2rem] border-l-4 border-aqua bg-cream p-7"><p className="font-bold text-navy">❤️ {data.heartTitle||t.heart}</p><p className="mt-2 text-slate-600">{data.heartText}</p></div>}</div></div></section>
  {history&&<section className="bg-gold py-16 text-navy"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em]">{t.history}</p><h2 className="mt-4 font-serif text-5xl">{history[0]}</h2><p className="mx-auto mt-5 max-w-3xl text-lg text-navy/75">{history[1]}</p></div></section>}
  <section className="py-16"><div className="mx-auto max-w-5xl px-5 lg:px-8"><SectionTitle eyebrow={t.faq} title={t.faqTitle(data.title)} text={t.faqText}/><div className="space-y-4">{faq.map(([q,a])=><details key={q} className="group rounded-3xl border border-slate-200 bg-white p-6"><summary className="flex cursor-pointer list-none items-start justify-between gap-4 font-serif text-2xl text-navy"><span className="min-w-0">{q}</span><span className="shrink-0 text-gold transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 max-w-4xl text-slate-600">{a}</p></details>)}</div></div></section>
  <section className="bg-cream py-16"><div className="mx-auto max-w-6xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.related}</p><h2 className="mt-3 font-serif text-5xl text-navy">{t.relatedTitle}</h2><div className="mt-8 flex flex-wrap justify-center gap-3">{related.map(([label,href])=><Link key={href} href={localizedHref(href)} className="rounded-full border border-navy px-6 py-3 font-bold text-navy">{label}</Link>)}</div><div className="mt-12 flex flex-wrap justify-center gap-3"><Link href={`/${lang}/apartments/rossi-apartment`} className="rounded-full bg-gold px-8 py-4 font-bold text-navy">Rossi Apartment</Link><Link href={`/${lang}/apartments/dimora-castelli`} className="rounded-full border border-navy px-8 py-4 font-bold text-navy">Dimora Castelli</Link></div></div></section>
 </main><Footer lang={lang}/><Script id={`${data.slug}-schema-${lang}`} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'TouristDestination',name:data.title,description:data.description,containedInPlace:{'@type':'AdministrativeArea',name:'Veneto'}})}}/></>;
}
