import Image from 'next/image';
import Link from 'next/link';
import type {CultureLang} from '@/data/culturePlaces';
import {cultureIndexPath} from '@/data/cultureTranslations';
import {seoGuideItems} from '@/data/seoEvergreenContent';

export type GuideDirectoryItem={slug:string;title:string;subtitle:string;text:string;image:string;alt:string};

type SectionDef={key:'practical'|'lagoon'|'veneto'|'culture';title:string;text:string;icon:string};
const copy:Record<CultureLang,{sections:SectionDef[];open:string;practical:[string,string,string,string][];culture:[string,string,string][]}>={
 it:{sections:[
  {key:'practical',title:'Guide pratiche',text:'Le informazioni che servono davvero prima e durante il soggiorno.',icon:'🧭'},
  {key:'lagoon',title:'Venezia e Laguna',text:'Isole e luoghi da vivere con più tempo, contesto e curiosità.',icon:'🌊'},
  {key:'veneto',title:'Esplora il Veneto',text:'Città d’arte, ville, colline, mare e montagna partendo da Marghera.',icon:'🌿'},
  {key:'culture',title:'Arte e cultura',text:'Directory complete per scegliere musei, monumenti, chiese, ville e castelli.',icon:'🏛️'}],open:'Apri la guida',practical:[['Come raggiungere Venezia','Bus, treno, biglietti e collegamenti utili.','/come-raggiungere-venezia','🚍'],['Dove mangiare','Ristoranti, bacari e indirizzi selezionati.','/dove-mangiare','🍝'],['Servizi in zona','Supermercati, farmacie e servizi vicini agli appartamenti.','/servizi-in-zona','📍'],['Link utili','Fonti ufficiali e strumenti per organizzare il viaggio.','/link-utili','🔗']],culture:[['Musei, monumenti e chiese di Venezia','80 luoghi con tempi medi, prezzi, accesso e link ufficiali.','venice'],['Cultura in Veneto','Musei, ville, castelli e luoghi culturali nelle sette province.','veneto']]},
 en:{sections:[{key:'practical',title:'Practical guides',text:'The information you actually need before and during your stay.',icon:'🧭'},{key:'lagoon',title:'Venice & Lagoon',text:'Islands and places to understand with more time and context.',icon:'🌊'},{key:'veneto',title:'Explore Veneto',text:'Art cities, villas, hills, coast and mountains from Marghera.',icon:'🌿'},{key:'culture',title:'Art & culture',text:'Complete directories for museums, monuments, churches, villas and castles.',icon:'🏛️'}],open:'Open guide',practical:[['Getting to Venice','Bus, train, tickets and useful connections.','/en/getting-to-venice','🚍'],['Where to eat','Selected restaurants, bacari and useful addresses.','/en/where-to-eat','🍝'],['Services nearby','Supermarkets, pharmacies and local services.','/en/services-nearby','📍'],['Useful links','Official sources and trip-planning tools.','/en/useful-links','🔗']],culture:[['Venice museums, monuments & churches','80 places with timing, prices, access and official links.','venice'],['Culture in Veneto','Museums, villas, castles and cultural sites across all seven provinces.','veneto']]},
 de:{sections:[{key:'practical',title:'Praktische Reiseführer',text:'Informationen, die vor und während des Aufenthalts wirklich helfen.',icon:'🧭'},{key:'lagoon',title:'Venedig & Lagune',text:'Inseln und Orte mit mehr Kontext und Zeit entdecken.',icon:'🌊'},{key:'veneto',title:'Venetien entdecken',text:'Kunststädte, Villen, Hügel, Küste und Berge ab Marghera.',icon:'🌿'},{key:'culture',title:'Kunst & Kultur',text:'Verzeichnisse für Museen, Denkmäler, Kirchen, Villen und Burgen.',icon:'🏛️'}],open:'Reiseführer öffnen',practical:[['Nach Venedig','Bus, Zug, Tickets und Verbindungen.','/de/getting-to-venice','🚍'],['Essen gehen','Ausgewählte Restaurants, Bacari und Adressen.','/de/where-to-eat','🍝'],['Services in der Nähe','Supermärkte, Apotheken und lokale Dienste.','/de/services-nearby','📍'],['Nützliche Links','Offizielle Quellen und Planungstools.','/de/useful-links','🔗']],culture:[['Museen, Denkmäler & Kirchen in Venedig','80 Orte mit Dauer, Preisen, Zugang und offiziellen Links.','venice'],['Kultur in Venetien','Museen, Villen, Burgen und Kulturorte in allen sieben Provinzen.','veneto']]},
 fr:{sections:[{key:'practical',title:'Guides pratiques',text:'Les informations réellement utiles avant et pendant le séjour.',icon:'🧭'},{key:'lagoon',title:'Venise & Lagune',text:'Des îles et des lieux à découvrir avec davantage de contexte.',icon:'🌊'},{key:'veneto',title:'Explorer la Vénétie',text:'Villes d’art, villas, collines, mer et montagne depuis Marghera.',icon:'🌿'},{key:'culture',title:'Art & culture',text:'Répertoires de musées, monuments, églises, villas et châteaux.',icon:'🏛️'}],open:'Ouvrir le guide',practical:[['Rejoindre Venise','Bus, train, billets et liaisons utiles.','/fr/getting-to-venice','🚍'],['Où manger','Restaurants, bacari et adresses sélectionnés.','/fr/where-to-eat','🍝'],['Services à proximité','Supermarchés, pharmacies et services locaux.','/fr/services-nearby','📍'],['Liens utiles','Sources officielles et outils de préparation.','/fr/useful-links','🔗']],culture:[['Musées, monuments & églises de Venise','80 lieux avec durée, tarifs, accès et liens officiels.','venice'],['Culture en Vénétie','Musées, villas, châteaux et sites culturels dans les sept provinces.','veneto']]},
 es:{sections:[{key:'practical',title:'Guías prácticas',text:'La información que realmente necesitas antes y durante la estancia.',icon:'🧭'},{key:'lagoon',title:'Venecia y Laguna',text:'Islas y lugares para descubrir con más contexto y tiempo.',icon:'🌊'},{key:'veneto',title:'Explorar Véneto',text:'Ciudades de arte, villas, colinas, mar y montaña desde Marghera.',icon:'🌿'},{key:'culture',title:'Arte y cultura',text:'Directorios de museos, monumentos, iglesias, villas y castillos.',icon:'🏛️'}],open:'Abrir la guía',practical:[['Cómo llegar a Venecia','Autobús, tren, billetes y conexiones útiles.','/es/getting-to-venice','🚍'],['Dónde comer','Restaurantes, bacari y direcciones seleccionadas.','/es/where-to-eat','🍝'],['Servicios cercanos','Supermercados, farmacias y servicios locales.','/es/services-nearby','📍'],['Enlaces útiles','Fuentes oficiales y herramientas para organizar el viaje.','/es/useful-links','🔗']],culture:[['Museos, monumentos e iglesias de Venecia','80 lugares con duración, precios, acceso y enlaces oficiales.','venice'],['Cultura en el Véneto','Museos, villas, castillos y lugares culturales en las siete provincias.','veneto']]},
 zh:{sections:[{key:'practical',title:'实用指南',text:'入住前和旅行中真正需要的信息。',icon:'🧭'},{key:'lagoon',title:'威尼斯与潟湖',text:'用更多背景与更从容的节奏认识岛屿。',icon:'🌊'},{key:'veneto',title:'探索威尼托',text:'从Marghera出发前往艺术城市、别墅、丘陵、海岸与山区。',icon:'🌿'},{key:'culture',title:'艺术与文化',text:'博物馆、古迹、教堂、别墅与城堡的完整目录。',icon:'🏛️'}],open:'打开指南',practical:[['前往威尼斯','公交、火车、车票与实用交通信息。','/zh/getting-to-venice','🚍'],['去哪里吃','精选餐厅、bacaro与实用地址。','/zh/where-to-eat','🍝'],['附近服务','超市、药房与公寓周边服务。','/zh/services-nearby','📍'],['实用链接','官方来源与旅行规划工具。','/zh/useful-links','🔗']],culture:[['威尼斯博物馆、古迹与教堂','80个地点，包含时长、票价、入场与官方链接。','venice'],['威尼托文化景点','覆盖七个省份的博物馆、别墅、城堡与文化地点。','veneto']]}
};
const accessPractical:Record<CultureLang,[string,string,string,string]>={
 it:['Contributo di accesso Venezia','Stato attuale 2026/2027: quando si paga e cosa verificare.','/journal/contributo-accesso-venezia','🎟️'],
 en:['Venice Access Fee','Current 2026/2027 status, payment rules and official updates.','/en/journal/contributo-accesso-venezia','🎟️'],
 de:['Venedig Zugangsbeitrag','Aktueller Stand 2026/2027, Zahlung und offizielle Updates.','/de/journal/contributo-accesso-venezia','🎟️'],
 fr:["Contribution d’Accès à Venise",'Situation 2026/2027, paiement et mises à jour officielles.','/fr/journal/contributo-accesso-venezia','🎟️'],
 es:['Tarifa de Acceso a Venecia','Estado 2026/2027, pagos y novedades oficiales.','/es/journal/contributo-accesso-venezia','🎟️'],
 zh:['威尼斯入城费','2026/2027当前状态、是否付费以及官方更新。','/zh/journal/contributo-accesso-venezia','🎟️']
};
const lagoon=new Set(['murano','burano','lido-di-venezia','pellestrina','certosa','sant-erasmo','venezia-nascosta']);
const veneto=new Set(['chioggia','riviera-del-brenta','padova','treviso','verona','colline-del-prosecco','dolomiti','jesolo','veneto-in-bicicletta']);
function guideHref(lang:CultureLang,slug:string){return lang==='it'?`/guide/${slug}`:`/${lang}/guide/${slug}`}
function Card({g,lang,label}:{g:GuideDirectoryItem;lang:CultureLang;label:string}){return <article className="overflow-hidden rounded-[2rem] bg-white shadow-soft ring-1 ring-black/5"><div className="relative h-56 sm:h-64"><Image src={g.image} alt={g.alt} fill sizes="(min-width:1280px) 31vw, (min-width:768px) 48vw, 100vw" className="object-cover"/></div><div className="p-6"><p className="text-xs font-black uppercase tracking-[.16em] text-gold">{g.subtitle}</p><h3 className="mt-3 font-serif text-3xl text-navy">{g.title}</h3><p className="mt-3 leading-7 text-slate-600">{g.text}</p><Link href={guideHref(lang,g.slug)} className="mt-6 inline-flex rounded-full bg-navy px-5 py-3 font-bold text-white hover:bg-gold hover:text-navy">{label}</Link></div></article>}
export default function GuideDirectoryIndex({lang,items}:{lang:CultureLang;items:GuideDirectoryItem[]}){
 const t=copy[lang];
 const mergedItems=[...items,...seoGuideItems(lang)].filter((item,index,all)=>all.findIndex(x=>x.slug===item.slug)===index);
 const lagoonItems=mergedItems.filter(x=>lagoon.has(x.slug)); const venetoItems=mergedItems.filter(x=>veneto.has(x.slug));
 const practicalItems=[...t.practical,accessPractical[lang]];
 const sectionBody=(key:SectionDef['key'])=> key==='practical'?<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{practicalItems.map(([title,text,href,icon])=><Link href={href} key={href} className="rounded-[1.75rem] bg-white p-6 shadow-soft ring-1 ring-black/5"><span className="text-3xl">{icon}</span><h3 className="mt-4 font-serif text-3xl text-navy">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></Link>)}</div>:key==='culture'?<div className="grid gap-6 lg:grid-cols-2">{t.culture.map(([title,text,scope])=><Link key={scope} href={cultureIndexPath(scope as 'venice'|'veneto',lang)} className="rounded-[2rem] bg-navy p-8 text-white shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">🏛️ {t.sections.find(x=>x.key==='culture')?.title}</p><h3 className="mt-3 font-serif text-4xl">{title}</h3><p className="mt-4 text-white/70">{text}</p><span className="mt-6 inline-flex rounded-full bg-gold px-5 py-3 font-bold text-navy">{t.open}</span></Link>)}</div>:<div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{(key==='lagoon'?lagoonItems:venetoItems).map(g=><Card key={g.slug} g={g} lang={lang} label={t.open}/>)}</div>;
 return <div className="bg-cream py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8">
   <div className="space-y-5 lg:hidden">{t.sections.map((section,i)=><details key={section.key} open={i===0} className="group overflow-hidden rounded-[1.75rem] bg-white shadow-soft"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-6"><span><span className="mr-3 text-2xl">{section.icon}</span><strong className="font-serif text-2xl text-navy">{section.title}</strong><span className="mt-2 block text-sm leading-6 text-slate-500">{section.text}</span></span><span className="text-2xl text-gold transition-transform group-open:rotate-45">+</span></summary><div className="border-t border-slate-100 bg-cream/60 p-5">{sectionBody(section.key)}</div></details>)}</div>
   <div className="hidden space-y-12 lg:block">{t.sections.map(section=><section key={section.key}><div className="mb-8 max-w-3xl"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{section.icon} {section.title}</p><h2 className="mt-3 font-serif text-5xl text-navy">{section.title}</h2><p className="mt-4 text-lg text-slate-600">{section.text}</p></div>{sectionBody(section.key)}</section>)}</div>
 </div></div>;
}
