import Image from 'next/image';
import Link from 'next/link';
import Script from 'next/script';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SectionTitle from '@/components/SectionTitle';
import type {GuideData} from '@/components/GuideTemplate';

export default function GuideTemplateDe({data}:{data:GuideData}){
  return <><Header lang="de"/><main data-guide={data.slug}>
    <section className="relative min-h-[84vh] overflow-hidden pt-20"><Image src={data.image} alt={data.imageAlt} fill priority sizes="100vw" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-t from-navy via-navy/50 to-navy/10"/>{data.slug==='dolomiti'&&<p className="absolute bottom-4 right-5 z-20 text-[11px] text-white/90 drop-shadow-md">Photo by Stefano Bazzoli on Unsplash</p>}<div className="relative mx-auto flex min-h-[calc(84vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-24 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap items-center gap-2 text-sm text-white/75"><Link href="/de">Startseite</Link><span>›</span><Link href="/de/guide">Reiseführer</Link><span>›</span><span className="text-gold">{data.title}</span></nav><p className="text-xs font-black uppercase tracking-[.25em] text-gold">Marghera Venice Reiseführer</p><h1 className="mt-4 font-serif text-6xl leading-none md:text-8xl">{data.title}</h1><p className="mt-4 font-serif text-3xl">{data.subtitle}</p><p className="mt-6 max-w-3xl text-xl text-white/80">{data.description}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#itinerary" className="rounded-full bg-gold px-7 py-4 font-bold text-navy">Besuch planen</a><Link href="/de/guide" className="rounded-full border border-white/60 px-7 py-4 font-bold text-white">← Zurück zu den Reiseführern</Link></div></div></div></section>
    <section className="relative z-10 -mt-8 px-5 lg:px-8"><div className="mx-auto grid max-w-7xl gap-4 rounded-[2rem] bg-white p-6 shadow-soft sm:grid-cols-2 lg:grid-cols-4">{data.badges.map(([t,x])=><div key={t} className="rounded-2xl bg-cream p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-gold">{t}</p><p className="mt-2 font-serif text-2xl text-navy">{x}</p></div>)}</div></section>
    <section className="py-16"><div className="mx-auto grid max-w-7xl gap-14 px-5 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Marghera Venice Reiseführer</p><h2 className="mt-3 font-serif text-5xl text-navy">{data.introTitle}</h2><div className="mt-7 space-y-5 text-lg leading-8 text-slate-600">{data.intro.map(p=><p key={p}>{p}</p>)}</div></div><aside className="rounded-[2rem] bg-navy p-8 text-white shadow-soft"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Vor der Abreise</p><h2 className="mt-3 font-serif text-4xl">Aktuelle Informationen prüfen</h2><p className="mt-5 text-white/75">Fahrpläne, Preise, Zugangsregeln und Beförderungsbedingungen können sich ändern. Nutzen Sie diesen Reiseführer zur Planung und prüfen Sie kurz vor der Reise die offiziellen Quellen.</p><div className="mt-7 grid gap-3">{(data.officialLinks||[]).map(([label,url])=><a key={url} href={url} target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/40 px-5 py-3 text-center font-bold first:bg-white first:text-navy">{label} ↗</a>)}</div></aside></div></section>
    <section className="bg-cream py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Nicht verpassen" title={`Sechs Möglichkeiten, ${data.title}`} text="Eine ausgewogene Auswahl an Orten, Landschaften und Erlebnissen."/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data.highlights.map(([t,x])=><article key={t} className="rounded-[2rem] bg-white p-8 shadow-soft"><div className="text-2xl text-gold">✦</div><h2 className="mt-4 font-serif text-3xl text-navy">{t}</h2><p className="mt-3 text-slate-600">{x}</p></article>)}</div></div></section>
    <section className="py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Erlebnisse" title="Gestalten Sie den Tag in Ihrem eigenen Tempo" text="Nicht nur Sehenswürdigkeiten, sondern verschiedene Arten, das Reiseziel zu erleben."/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data.experiences.map(([t,x])=><article key={t} className="rounded-[2rem] border border-slate-200 bg-white p-8"><h2 className="font-serif text-3xl text-navy">{t}</h2><p className="mt-3 text-slate-600">{x}</p></article>)}</div></div></section>
    <section id="itinerary" className="bg-navy py-16 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Vorgeschlagene Route" title={`Ein Tag in ${data.title}`} text="Ein flexibler Vorschlag, den Sie an Jahreszeit, Wetter und Verkehrsmittel anpassen können."/><div className="grid gap-4">{data.itinerary.map(([time,t,x])=><article key={time} className="grid gap-4 rounded-[2rem] bg-white/10 p-7 md:grid-cols-[110px_1fr]"><div className="font-black tracking-[.14em] text-gold">{time}</div><div><h2 className="font-serif text-3xl">{t}</h2><p className="mt-2 text-white/70">{x}</p></div></article>)}</div></div></section>
    <section className="py-16"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div className="relative min-h-[420px] overflow-hidden rounded-[2rem] shadow-soft"><Image src={data.image} alt={data.imageAlt} fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover"/></div><div className="flex flex-col justify-center"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Unser praktischer Tipp</p><h2 className="mt-3 font-serif text-5xl text-navy">{data.adviceTitle}</h2><p className="mt-6 text-lg text-slate-600">{data.advice}</p>{data.heartText&&<div className="mt-8 rounded-[2rem] border-l-4 border-aqua bg-cream p-7"><p className="font-bold text-navy">❤️ {data.heartTitle||'Ein Ort, den Einheimische lieben'}</p><p className="mt-2 text-slate-600">{data.heartText}</p></div>}</div></div></section>
    {data.historyText&&<section className="bg-gold py-16 text-navy"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em]">Eine Geschichte aus der Region</p><h2 className="mt-4 font-serif text-5xl">{data.historyTitle}</h2><p className="mx-auto mt-5 max-w-3xl text-lg text-navy/75">{data.historyText}</p></div></section>}
    <section className="py-16"><div className="mx-auto max-w-5xl px-5 lg:px-8"><SectionTitle eyebrow="Häufige Fragen" title={`Vor dem Besuch von ${data.title}`} text="Kurze Antworten auf häufige Fragen."/><div className="space-y-4">{data.faq.map(([q,a])=><details key={q} className="group rounded-3xl border border-slate-200 bg-white p-6"><summary className="cursor-pointer list-none font-serif text-2xl text-navy">{q}<span className="float-right text-gold group-open:rotate-45">+</span></summary><p className="mt-4 max-w-4xl text-slate-600">{a}</p></details>)}</div></div></section>
    <section className="bg-cream py-16"><div className="mx-auto max-w-6xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Weitere Reiseführer</p><h2 className="mt-3 font-serif text-5xl text-navy">Mehr entdecken</h2><div className="mt-8 flex flex-wrap justify-center gap-3">{data.related.map(([label,href])=><Link key={href} href={`/de${href}`} className="rounded-full border border-navy px-6 py-3 font-bold text-navy">{label}</Link>)}</div><div className="mt-12 flex flex-wrap justify-center gap-3"><Link href="/de/apartments/rossi-apartment" className="rounded-full bg-gold px-8 py-4 font-bold text-navy">Rossi Apartment</Link><Link href="/de/apartments/dimora-castelli" className="rounded-full border border-navy px-8 py-4 font-bold text-navy">Dimora Castelli</Link></div></div></section>
  </main><Footer lang="de"/><Script id={`${data.slug}-schema-de`} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'TouristDestination',name:data.title,description:data.description,containedInPlace:{'@type':'AdministrativeArea',name:'Veneto'}})}}/></>;
}
