'use client';
import {useState} from 'react';
import {usePathname} from 'next/navigation';
import {localePath} from '@/lib/i18n';
import Image from 'next/image';
import Link from 'next/link';

type Lang='it'|'en'|'de'|'fr'|'es'|'zh';
const links:Record<Lang,[string,string][]>={
 it:[['Le nostre case','/#case'],['Scopri Venezia','/scopri-venezia'],['Scopri il Veneto','/scopri-il-veneto'],['Come arrivare','/come-raggiungere-venezia'],['Esperienze','/collaborazioni'],['Guide','/guide'],['Journal','/journal'],['FAQ','/faq'],['Pet & Family','/#pet-family'],['Contatti','/#direct-contact']],
 en:[['Our apartments','/en/#case'],['Discover Venice','/en/discover-venice'],['Discover Veneto','/en/discover-veneto'],['Getting to Venice','/en/getting-to-venice'],['Experiences','/en/experiences'],['Guides','/en/guide'],['Journal','/en/journal'],['FAQ','/en/faq'],['Pet & Family','/en/#pet-family'],['Contact','/en/#direct-contact']],
 de:[['Unsere Apartments','/de/#case'],['Venedig entdecken','/de/discover-venice'],['Venetien entdecken','/de/discover-veneto'],['Nach Venedig','/de/getting-to-venice'],['Erlebnisse','/de/experiences'],['Reiseführer','/de/guide'],['Journal','/de/journal'],['FAQ','/de/faq'],['Haustiere & Familien','/de/#pet-family'],['Kontakt','/de/#direct-contact']],
 fr:[['Nos appartements','/fr/#case'],['Découvrir Venise','/fr/discover-venice'],['Découvrir la Vénétie','/fr/discover-veneto'],['Rejoindre Venise','/fr/getting-to-venice'],['Expériences','/fr/experiences'],['Guides','/fr/guide'],['Journal','/fr/journal'],['FAQ','/fr/faq'],['Animaux & Familles','/fr/#pet-family'],['Contact','/fr/#direct-contact']],
 zh:[['我们的公寓','/zh/#case'],['探索威尼斯','/zh/discover-venice'],['探索威尼托','/zh/discover-veneto'],['前往威尼斯','/zh/getting-to-venice'],['精选体验','/zh/experiences'],['旅行指南','/zh/guide'],['旅行日志','/zh/journal'],['常见问题','/zh/faq'],['宠物与家庭','/zh/#pet-family'],['联系我们','/zh/#direct-contact']],
 es:[['Nuestros apartamentos','/es/#case'],['Descubrir Venecia','/es/discover-venice'],['Descubrir Véneto','/es/discover-veneto'],['Cómo llegar a Venecia','/es/getting-to-venice'],['Experiencias','/es/experiences'],['Guías','/es/guide'],['Journal','/es/journal'],['FAQ','/es/faq'],['Mascotas & Familias','/es/#pet-family'],['Contacto','/es/#direct-contact']]
};
const home:Record<Lang,string>={it:'/',en:'/en',de:'/de',fr:'/fr',es:'/es',zh:'/zh'};
const aria:Record<Lang,[string,string,string]>={zh:['主导航','打开菜单','关闭菜单'],it:['Navigazione principale','Apri il menu','Chiudi il menu'],en:['Main navigation','Open menu','Close menu'],de:['Hauptnavigation','Menü öffnen','Menü schließen'],fr:['Navigation principale','Ouvrir le menu','Fermer le menu'],es:['Navegación principal','Abrir el menú','Cerrar el menú']};
const wa:Record<Lang,string>={zh:'您好，我想了解 Marghera Venice Apartments 的住宿信息。',it:'Ciao, vorrei ricevere informazioni su Marghera Venice Apartments.',en:"Hello, I'd like information about Marghera Venice Apartments.",de:'Hallo, ich möchte Informationen zu Marghera Venice Apartments.',fr:'Bonjour, je souhaite recevoir des informations sur Marghera Venice Apartments.',es:'Hola, me gustaría recibir información sobre Marghera Venice Apartments.'};
export default function Header({lang='it'}:{lang?:Lang}){
 const [open,setOpen]=useState(false); const nav=links[lang]; const pathname=usePathname();
 const waUrl='https://wa.me/393514462261?text='+encodeURIComponent(wa[lang]+' ');
 return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-navy/95 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 lg:px-8">
 <Link href={home[lang]} className="flex items-center gap-3 text-white" onClick={()=>setOpen(false)}><Image src="/images/logo.png" alt="Marghera Venice Apartments" width={58} height={58} priority className="h-[58px] w-[58px] rounded-full bg-cream object-contain shadow-sm"/><span className="hidden font-serif tracking-[.16em] sm:block">MARGHERA<br/><span className="text-xs tracking-[.25em]">VENICE APARTMENTS</span></span></Link>
 <nav aria-label={aria[lang][0]} className="hidden items-center gap-5 text-[13px] text-white/90 xl:flex">{nav.map(([label,href])=><Link key={label} href={href} className="whitespace-nowrap transition hover:text-gold">{label}</Link>)}</nav>
 <div className="ml-8 flex shrink-0 items-center gap-3"><div className="hidden items-center gap-1 rounded-full border border-white/25 p-1 text-[11px] font-black text-white sm:flex">{(['it','en','de','fr','es','zh'] as Lang[]).map(l=><Link key={l} href={localePath(pathname,l)} hrefLang={l} className={`rounded-full px-2 py-1 ${lang===l?'bg-gold text-navy':'hover:text-gold'}`}>{l.toUpperCase()}</Link>)}</div>
 {lang==='zh'?<Link href="/zh/#direct-contact" className="hidden rounded-full bg-gold px-5 py-3 text-sm font-bold text-navy shadow-lg transition hover:-translate-y-0.5 sm:inline-flex">微信 WeChat</Link>:<a href={waUrl} target="_blank" rel="noopener noreferrer" className="hidden rounded-full bg-gold px-5 py-3 text-sm font-bold text-navy shadow-lg transition hover:-translate-y-0.5 sm:inline-flex">WhatsApp</a>}
 <button type="button" aria-label={open?aria[lang][2]:aria[lang][1]} aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>setOpen(!open)} className="grid h-11 w-11 place-items-center rounded-full border border-white/20 text-white xl:hidden"><span className="text-2xl leading-none">{open?'×':'☰'}</span></button></div></div>
 {open&&<div className="max-h-[calc(100vh-5rem)] overflow-y-auto border-t border-white/10 bg-navy px-5 py-5 xl:hidden"><nav id="mobile-navigation" aria-label={aria[lang][0]} className="mx-auto grid max-w-7xl gap-1"><div className="mb-3 flex flex-wrap gap-2 border-b border-white/10 pb-4 sm:hidden">{(['it','en','de','fr','es','zh'] as Lang[]).map(l=><Link key={l} href={localePath(pathname,l)} hrefLang={l} onClick={()=>setOpen(false)} className={`rounded-full border px-3 py-2 text-xs font-black ${lang===l?'border-gold bg-gold text-navy':'border-white/25 text-white'}`}>{l.toUpperCase()}</Link>)}</div>{nav.map(([label,href])=><Link key={label} href={href} onClick={()=>setOpen(false)} className="rounded-xl px-4 py-3 font-semibold text-white/90 transition hover:bg-white/10 hover:text-gold">{label}</Link>)}{lang==='zh'?<Link href="/zh/#direct-contact" onClick={()=>setOpen(false)} className="mt-3 rounded-full bg-gold px-5 py-3 text-center font-bold text-navy">微信 WeChat</Link>:<a href={waUrl} target="_blank" rel="noopener noreferrer" className="mt-3 rounded-full bg-gold px-5 py-3 text-center font-bold text-navy">WhatsApp</a>}</nav></div>}</header>;
}
