import Link from 'next/link';
import CultureCard from '@/components/CultureCard';
import SectionTitle from '@/components/SectionTitle';
import {culturePlaces,type CultureLang,type CultureScope} from '@/data/culturePlaces';
import {cultureIndexPath} from '@/data/cultureTranslations';

const picks={
 venice:['palazzo-ducale','basilica-san-marco','campanile-san-marco','gallerie-dell-accademia','peggy-guggenheim','scuola-grande-san-rocco'],
 veneto:['cappella-scrovegni','arena-verona','teatro-olimpico','villa-pisani-stra','castelvecchio','museo-canova-possagno']
} as const;
const copy:Record<CultureLang,Record<CultureScope,{eyebrow:string;title:string;text:string;cta:string}>>={
 it:{venice:{eyebrow:'Cosa vedere a Venezia',title:'Musei, monumenti e chiese: scegli cosa vale il tuo tempo',text:'Non una lista infinita: sei luoghi per orientarti, poi una directory completa con durata media, prezzi, accesso e fonti ufficiali.',cta:'Esplora tutti i luoghi culturali di Venezia'},veneto:{eyebrow:'Arte e cultura in Veneto',title:'Capolavori che meritano una gita dedicata',text:'Ville, musei, teatri, castelli e siti d’arte entrano finalmente dentro il viaggio in Veneto, non in una sezione separata e nascosta.',cta:'Esplora tutti i luoghi culturali del Veneto'}},
 en:{venice:{eyebrow:'What to see in Venice',title:'Museums, monuments and churches: choose what deserves your time',text:'Not an endless list: start with six places, then use the full directory for average visit time, prices, access and official sources.',cta:'Explore all Venice cultural sites'},veneto:{eyebrow:'Art & culture in Veneto',title:'Masterpieces worth a dedicated day trip',text:'Villas, museums, theatres, castles and art sites now sit inside the Veneto journey instead of being hidden in a separate directory.',cta:'Explore all Veneto cultural sites'}},
 de:{venice:{eyebrow:'Sehenswertes in Venedig',title:'Museen, Denkmäler und Kirchen: Wählen Sie, was Ihre Zeit verdient',text:'Keine endlose Liste: Starten Sie mit sechs Orten und nutzen Sie danach das vollständige Verzeichnis mit Dauer, Preisen, Zugang und offiziellen Quellen.',cta:'Alle Kulturorte in Venedig entdecken'},veneto:{eyebrow:'Kunst & Kultur in Venetien',title:'Meisterwerke für einen eigenen Tagesausflug',text:'Villen, Museen, Theater, Burgen und Kunstorte werden direkt Teil Ihrer Venetien-Planung.',cta:'Alle Kulturorte in Venetien entdecken'}},
 fr:{venice:{eyebrow:'Que voir à Venise',title:'Musées, monuments et églises : choisissez ce qui mérite votre temps',text:'Pas une liste interminable : commencez par six lieux, puis utilisez le répertoire complet avec durée, tarifs, accès et sources officielles.',cta:'Explorer tous les lieux culturels de Venise'},veneto:{eyebrow:'Art & culture en Vénétie',title:'Des chefs-d’œuvre qui méritent une excursion',text:'Villas, musées, théâtres, châteaux et sites d’art font désormais partie du voyage en Vénétie.',cta:'Explorer tous les lieux culturels de Vénétie'}},
 es:{venice:{eyebrow:'Qué ver en Venecia',title:'Museos, monumentos e iglesias: elige lo que merece tu tiempo',text:'No una lista infinita: empieza con seis lugares y después usa el directorio completo con duración, precios, acceso y fuentes oficiales.',cta:'Explorar todos los lugares culturales de Venecia'},veneto:{eyebrow:'Arte y cultura en el Véneto',title:'Obras maestras que merecen una excursión',text:'Villas, museos, teatros, castillos y lugares artísticos forman parte del viaje por Véneto, no de una sección escondida.',cta:'Explorar todos los lugares culturales del Véneto'}},
 zh:{venice:{eyebrow:'威尼斯看什么',title:'博物馆、古迹与教堂：把时间留给真正值得看的地方',text:'不是无穷无尽的清单：先从六个重点开始，再进入完整目录查看平均参观时长、票价、入场和官方来源。',cta:'查看全部威尼斯文化景点'},veneto:{eyebrow:'威尼托艺术与文化',title:'值得专门安排一日游的杰作',text:'别墅、博物馆、剧院、城堡与艺术场馆现在直接融入威尼托旅行规划。',cta:'查看全部威尼托文化景点'}}
};
export default function HubCultureSection({scope,lang='it'}:{scope:CultureScope;lang?:CultureLang}){
 const t=copy[lang][scope]; const selected=picks[scope].map(slug=>culturePlaces.find(p=>p.slug===slug)).filter(Boolean);
 return <section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={t.eyebrow} title={t.title} text={t.text}/><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{selected.map(place=><CultureCard key={place!.slug} place={place!} lang={lang} scope={scope}/>)}</div><div className="mt-10 text-center"><Link href={cultureIndexPath(scope,lang)} className="inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white hover:bg-gold hover:text-navy">{t.cta} →</Link></div></div></section>;
}
