import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

type Lang='it'|'en'|'de'|'fr'|'es'|'zh';
type Section={title:string;text:string};
type Copy={
 home:string;experiences:string;kicker:string;title:string;subtitle:string;lead:string;
 sections:Section[];awardsTitle:string;awards:string;awardsNote:string;
 tastingTitle:string;tastingIntro:string;tastings:{name:string;wines:string}[];included:string;
 whyTitle:string;why:string;perfect:string;adviceTitle:string;advice:string;advance:string;
 infoTitle:string;info:{label:string;value:string}[];cta:string;official:string;back:string;
};

const copy:Record<Lang,Copy>={
 it:{
  home:'Home',experiences:'Esperienze',kicker:'Wine Experience • Val d’Illasi',
  title:'Degustazione in cantina tra Valpolicella e Monti Lessini',
  subtitle:'Azienda Agricola I Campi – Flavio Prà',
  lead:'Un viaggio nel vino veronese, tra vigneti, cantina e alcune delle denominazioni più rappresentative del Veneto.',
  sections:[
   {title:'Una cantina che racconta il territorio',text:'A Cellore d’Illasi, nel Veronese, si trova Azienda Agricola I Campi, realtà vitivinicola guidata dall’enologo Flavio Prà, quarta generazione di una famiglia di vignaioli. Un progetto costruito nel tempo attraverso esperienza, ricerca e un forte legame con la terra.'},
   {title:'“Ogni vino vuole la sua terra”',text:'Per ogni vitigno vengono ricercati i vigneti più vocati, anche in alta collina, con l’obiettivo di ottenere vini riconoscibili, eleganti e profondamente legati al luogo da cui nascono.'},
   {title:'Val d’Illasi, tra vigneti e Monti Lessini',text:'La cantina sorge nella Val d’Illasi, nella parte orientale della Valpolicella. Pietra, legno, tecnologia e competenza enologica convivono in un progetto che mette al centro qualità, autenticità dei vini e sostenibilità.'}
  ],
  awardsTitle:'Vini premiati, identità riconosciuta',
  awards:'Il lavoro de I Campi ha ottenuto negli anni importanti riconoscimenti da guide e critici nazionali e internazionali. Il Soave Classico DOC “Campo Vulcano” ha ricevuto i Tre Bicchieri del Gambero Rosso e 94/100 da James Suckling; il Valpolicella Ripasso Superiore DOC “Campo Ciotoli” ha raggiunto 93/100 da James Suckling; l’Amarone della Valpolicella DOCG “Campi Lunghi” ha ottenuto 93/100 da James Suckling e, in altre annate, riconoscimenti da Falstaff, Vinous, Asia Wine Trophy e Berliner Wine Trophy.',
  awardsNote:'I premi citati si riferiscono a specifiche etichette e annate e non implicano che la degustazione includa necessariamente le medesime annate.',
  tastingTitle:'Scegli il tuo percorso di degustazione',tastingIntro:'È possibile scegliere tra quattro proposte, con un unico percorso per tutto il gruppo:',
  tastings:[
   {name:'Nuovi Orizzonti',wines:'Lugana DOC, Pinot Grigio delle Venezie DOC e Soave DOC.'},
   {name:'Immersione nella Valpolicella',wines:'Valpolicella Superiore DOC, Ripasso DOC e Amarone della Valpolicella DOCG.'},
   {name:'Doppio Confronto',wines:'Lugana DOC, Soave DOC, Valpolicella Superiore DOC e Ripasso DOC.'},
   {name:'Percorso Completo',wines:'Lugana DOC, Soave DOC, Pinot Grigio delle Venezie DOC, Valpolicella Superiore DOC, Ripasso DOC e Amarone della Valpolicella DOCG.'}
  ],
  included:'La degustazione comprende un assaggio di formaggi e salumi del territorio e, compatibilmente con il periodo della visita, la possibilità di visitare la cantina.',
  whyTitle:'Perché la consigliamo',why:'Abbiamo scelto I Campi perché qui la degustazione diventa un modo per conoscere davvero il territorio. Non solo vini da assaggiare, ma una storia, una filosofia produttiva e una realtà veronese che ha saputo costruire un’identità precisa e riconosciuta. È un’esperienza che consigliamo a chi vuole scoprire un Veneto diverso da Venezia, fatto di colline, vigneti, grandi denominazioni e sapori locali.',
  perfect:'Perfetta per: coppie • gruppi di amici • appassionati di vino • chi vuole scoprire il Veneto oltre Venezia',
  adviceTitle:'Il nostro consiglio',advice:'Non sai quale percorso scegliere? Scrivici su WhatsApp e raccontaci che tipo di vini preferisci: ti aiutiamo volentieri a orientarti tra le proposte e a verificare la disponibilità con la cantina.',advance:'Prenotazione richiesta con almeno 48 ore di anticipo.',
  infoTitle:'Informazioni pratiche',info:[
   {label:'Dove',value:'Azienda Agricola I Campi – Via delle Pezzole, 3, Località Allodola, Cellore d’Illasi (VR)'},
   {label:'Durata',value:'circa 1 ora e 30 minuti / 2 ore'},
   {label:'Prenotazione',value:'almeno 48 ore prima, previa verifica della disponibilità'},
   {label:'Gruppo',value:'un’unica proposta di degustazione scelta per tutto il gruppo'},
   {label:'Incluso',value:'degustazione, assaggio di formaggi e salumi del territorio e visita della cantina quando compatibile con il periodo'},
   {label:'Allergie o intolleranze',value:'da comunicare preventivamente'}
  ],cta:'Chiedici informazioni sull’esperienza',official:'Sito ufficiale I Campi',back:'Torna alle Esperienze'
 },
 en:{
  home:'Home',experiences:'Experiences',kicker:'Wine Experience • Val d’Illasi',title:'Winery tasting between Valpolicella and the Lessini Mountains',subtitle:'Azienda Agricola I Campi – Flavio Prà',lead:'A journey through Veronese wine, vineyards and some of Veneto’s most representative denominations.',
  sections:[{title:'A winery that tells the story of its land',text:'In Cellore d’Illasi, near Verona, Azienda Agricola I Campi is led by oenologist Flavio Prà, the fourth generation of a winegrowing family. The project has grown through experience, research and a strong bond with the land.'},{title:'“Every wine wants its own land”',text:'For each grape variety, the estate seeks out the most suitable vineyards, including high-hill sites, with the aim of producing distinctive, elegant wines deeply connected to their place of origin.'},{title:'Val d’Illasi, between vineyards and the Lessini Mountains',text:'The winery lies in Val d’Illasi, in the eastern part of Valpolicella. Stone, wood, technology and winemaking expertise come together in a project centred on quality, authenticity and sustainability.'}],
  awardsTitle:'Award-winning wines, a recognised identity',awards:'Over the years, I Campi has received important recognition from national and international guides and critics. Soave Classico DOC “Campo Vulcano” received Tre Bicchieri from Gambero Rosso and 94/100 from James Suckling; Valpolicella Ripasso Superiore DOC “Campo Ciotoli” reached 93/100 from James Suckling; Amarone della Valpolicella DOCG “Campi Lunghi” received 93/100 from James Suckling and, in other vintages, awards from Falstaff, Vinous, Asia Wine Trophy and Berliner Wine Trophy.',awardsNote:'The awards mentioned refer to specific labels and vintages and do not imply that the tasting will necessarily include those same vintages.',
  tastingTitle:'Choose your tasting journey',tastingIntro:'Four options are available, with one tasting journey selected for the whole group:',tastings:[{name:'New Horizons',wines:'Lugana DOC, Pinot Grigio delle Venezie DOC and Soave DOC.'},{name:'Immersion in Valpolicella',wines:'Valpolicella Superiore DOC, Ripasso DOC and Amarone della Valpolicella DOCG.'},{name:'Double Comparison',wines:'Lugana DOC, Soave DOC, Valpolicella Superiore DOC and Ripasso DOC.'},{name:'Complete Journey',wines:'Lugana DOC, Soave DOC, Pinot Grigio delle Venezie DOC, Valpolicella Superiore DOC, Ripasso DOC and Amarone della Valpolicella DOCG.'}],included:'The tasting includes a selection of local cheeses and cured meats and, depending on the period of the visit, the possibility of visiting the winery.',
  whyTitle:'Why we recommend it',why:'We chose I Campi because the tasting becomes a way to truly understand the territory: not only wines to taste, but a story, a production philosophy and a Veronese estate with a precise and recognised identity. We recommend it to guests who want to discover a Veneto beyond Venice, made of hills, vineyards, great denominations and local flavours.',perfect:'Perfect for: couples • groups of friends • wine lovers • travellers who want to discover Veneto beyond Venice',adviceTitle:'Our tip',advice:'Not sure which tasting to choose? Message us on WhatsApp and tell us what kind of wines you prefer. We will gladly help you understand the options and check availability with the winery.',advance:'Booking is required at least 48 hours in advance.',
  infoTitle:'Practical information',info:[{label:'Where',value:'Azienda Agricola I Campi – Via delle Pezzole, 3, Località Allodola, Cellore d’Illasi (VR)'},{label:'Duration',value:'about 1 hour 30 minutes / 2 hours'},{label:'Booking',value:'at least 48 hours in advance, subject to availability'},{label:'Group',value:'one tasting journey chosen for the entire group'},{label:'Included',value:'wine tasting, local cheeses and cured meats, plus a winery visit when compatible with the period'},{label:'Allergies or intolerances',value:'must be communicated in advance'}],cta:'Ask us about this experience',official:'Official I Campi website',back:'Back to Experiences'
 },
 de:{
  home:'Startseite',experiences:'Erlebnisse',kicker:'Wine Experience • Val d’Illasi',title:'Weinverkostung zwischen Valpolicella und den Monti Lessini',subtitle:'Azienda Agricola I Campi – Flavio Prà',lead:'Eine Reise durch die Weine des Veroneser Landes, zwischen Weinbergen, Keller und einigen der bekanntesten Herkunftsbezeichnungen Venetiens.',
  sections:[{title:'Ein Weingut, das von seiner Region erzählt',text:'In Cellore d’Illasi bei Verona liegt die Azienda Agricola I Campi, geführt vom Önologen Flavio Prà, der vierten Generation einer Winzerfamilie. Das Projekt ist über Jahre durch Erfahrung, Forschung und eine starke Verbundenheit mit dem Boden gewachsen.'},{title:'„Jeder Wein braucht seinen eigenen Boden“',text:'Für jede Rebsorte werden besonders geeignete Weinberge gesucht, auch in höheren Hügellagen, um unverwechselbare, elegante und eng mit ihrem Herkunftsort verbundene Weine zu erzeugen.'},{title:'Val d’Illasi zwischen Weinbergen und Monti Lessini',text:'Das Weingut liegt im Val d’Illasi, im östlichen Teil des Valpolicella-Gebiets. Stein, Holz, Technologie und önologisches Know-how verbinden sich in einem Projekt, das Qualität, Authentizität und Nachhaltigkeit in den Mittelpunkt stellt.'}],
  awardsTitle:'Prämierte Weine, anerkannte Identität',awards:'Die Arbeit von I Campi wurde im Laufe der Jahre von nationalen und internationalen Führern und Kritikern ausgezeichnet. Der Soave Classico DOC „Campo Vulcano“ erhielt Tre Bicchieri von Gambero Rosso und 94/100 von James Suckling; der Valpolicella Ripasso Superiore DOC „Campo Ciotoli“ erreichte 93/100 von James Suckling; der Amarone della Valpolicella DOCG „Campi Lunghi“ erhielt 93/100 von James Suckling sowie in anderen Jahrgängen Anerkennungen von Falstaff, Vinous, Asia Wine Trophy und Berliner Wine Trophy.',awardsNote:'Die genannten Auszeichnungen beziehen sich auf bestimmte Etiketten und Jahrgänge und bedeuten nicht, dass bei der Verkostung zwingend dieselben Jahrgänge ausgeschenkt werden.',
  tastingTitle:'Wählen Sie Ihren Verkostungsweg',tastingIntro:'Es stehen vier Möglichkeiten zur Auswahl; die gesamte Gruppe wählt gemeinsam einen Verkostungsweg:',tastings:[{name:'Neue Horizonte',wines:'Lugana DOC, Pinot Grigio delle Venezie DOC und Soave DOC.'},{name:'Eintauchen in Valpolicella',wines:'Valpolicella Superiore DOC, Ripasso DOC und Amarone della Valpolicella DOCG.'},{name:'Doppelter Vergleich',wines:'Lugana DOC, Soave DOC, Valpolicella Superiore DOC und Ripasso DOC.'},{name:'Kompletter Weg',wines:'Lugana DOC, Soave DOC, Pinot Grigio delle Venezie DOC, Valpolicella Superiore DOC, Ripasso DOC und Amarone della Valpolicella DOCG.'}],included:'Die Verkostung umfasst eine Auswahl regionaler Käse- und Wurstspezialitäten und, je nach Besuchszeitraum, die Möglichkeit einer Kellerbesichtigung.',
  whyTitle:'Warum wir diese Erfahrung empfehlen',why:'Wir haben I Campi ausgewählt, weil die Verkostung hier zu einer echten Entdeckung der Region wird: nicht nur Weine, sondern auch Geschichte, Produktionsphilosophie und ein Veroneser Weingut mit klarer, anerkannter Identität. Ideal für alle, die ein anderes Venetien jenseits von Venedig kennenlernen möchten.',perfect:'Ideal für: Paare • Freundesgruppen • Weinliebhaber • alle, die Venetien jenseits von Venedig entdecken möchten',adviceTitle:'Unser Tipp',advice:'Sie wissen nicht, welchen Verkostungsweg Sie wählen sollen? Schreiben Sie uns auf WhatsApp und sagen Sie uns, welche Weine Sie mögen. Wir helfen gerne bei der Auswahl und prüfen die Verfügbarkeit mit dem Weingut.',advance:'Reservierung mindestens 48 Stunden im Voraus erforderlich.',
  infoTitle:'Praktische Informationen',info:[{label:'Wo',value:'Azienda Agricola I Campi – Via delle Pezzole, 3, Località Allodola, Cellore d’Illasi (VR)'},{label:'Dauer',value:'ca. 1 Stunde 30 Minuten / 2 Stunden'},{label:'Reservierung',value:'mindestens 48 Stunden im Voraus, nach Verfügbarkeitsprüfung'},{label:'Gruppe',value:'ein gemeinsamer Verkostungsweg für die gesamte Gruppe'},{label:'Inklusive',value:'Verkostung, regionale Käse- und Wurstspezialitäten sowie Kellerbesichtigung, wenn der Zeitraum dies erlaubt'},{label:'Allergien oder Unverträglichkeiten',value:'bitte vorab mitteilen'}],cta:'Informationen zur Erfahrung anfragen',official:'Offizielle Website von I Campi',back:'Zurück zu den Erlebnissen'
 },
 fr:{
  home:'Accueil',experiences:'Expériences',kicker:'Wine Experience • Val d’Illasi',title:'Dégustation en cave entre Valpolicella et monts Lessini',subtitle:'Azienda Agricola I Campi – Flavio Prà',lead:'Un voyage dans les vins du Véronais, entre vignobles, cave et quelques-unes des appellations les plus représentatives de la Vénétie.',
  sections:[{title:'Une cave qui raconte son territoire',text:'À Cellore d’Illasi, dans la province de Vérone, Azienda Agricola I Campi est dirigée par l’œnologue Flavio Prà, quatrième génération d’une famille de vignerons. Un projet construit au fil du temps grâce à l’expérience, la recherche et un lien profond avec la terre.'},{title:'« Chaque vin veut sa terre »',text:'Pour chaque cépage, l’entreprise recherche les vignobles les plus adaptés, y compris en haute colline, afin d’obtenir des vins reconnaissables, élégants et profondément liés à leur lieu d’origine.'},{title:'Val d’Illasi, entre vignobles et monts Lessini',text:'La cave se trouve dans la Val d’Illasi, dans la partie orientale de la Valpolicella. Pierre, bois, technologie et savoir-faire œnologique se rencontrent dans un projet centré sur la qualité, l’authenticité et la durabilité.'}],
  awardsTitle:'Des vins récompensés, une identité reconnue',awards:'Le travail de I Campi a reçu au fil des années d’importantes distinctions de guides et critiques nationaux et internationaux. Le Soave Classico DOC « Campo Vulcano » a reçu les Tre Bicchieri du Gambero Rosso et 94/100 de James Suckling ; le Valpolicella Ripasso Superiore DOC « Campo Ciotoli » a obtenu 93/100 de James Suckling ; l’Amarone della Valpolicella DOCG « Campi Lunghi » a reçu 93/100 de James Suckling ainsi que, sur d’autres millésimes, des distinctions de Falstaff, Vinous, Asia Wine Trophy et Berliner Wine Trophy.',awardsNote:'Les récompenses citées concernent des étiquettes et millésimes précis et ne signifient pas que la dégustation comprendra nécessairement ces mêmes millésimes.',
  tastingTitle:'Choisissez votre parcours de dégustation',tastingIntro:'Quatre formules sont proposées, avec un seul parcours choisi pour l’ensemble du groupe :',tastings:[{name:'Nouveaux Horizons',wines:'Lugana DOC, Pinot Grigio delle Venezie DOC et Soave DOC.'},{name:'Immersion en Valpolicella',wines:'Valpolicella Superiore DOC, Ripasso DOC et Amarone della Valpolicella DOCG.'},{name:'Double Comparaison',wines:'Lugana DOC, Soave DOC, Valpolicella Superiore DOC et Ripasso DOC.'},{name:'Parcours Complet',wines:'Lugana DOC, Soave DOC, Pinot Grigio delle Venezie DOC, Valpolicella Superiore DOC, Ripasso DOC et Amarone della Valpolicella DOCG.'}],included:'La dégustation comprend une sélection de fromages et charcuteries du territoire et, selon la période de la visite, la possibilité de visiter la cave.',
  whyTitle:'Pourquoi nous la recommandons',why:'Nous avons choisi I Campi parce qu’ici la dégustation devient une manière de comprendre réellement le territoire. Il ne s’agit pas seulement de goûter des vins, mais de découvrir une histoire, une philosophie de production et une réalité véronaise à l’identité précise et reconnue. Une belle façon de découvrir une autre Vénétie, au-delà de Venise.',perfect:'Parfaite pour : couples • groupes d’amis • amateurs de vin • voyageurs souhaitant découvrir la Vénétie au-delà de Venise',adviceTitle:'Notre conseil',advice:'Vous ne savez pas quel parcours choisir ? Écrivez-nous sur WhatsApp et dites-nous quels vins vous aimez : nous vous aiderons volontiers à vous orienter et à vérifier les disponibilités avec la cave.',advance:'Réservation demandée au moins 48 heures à l’avance.',
  infoTitle:'Informations pratiques',info:[{label:'Où',value:'Azienda Agricola I Campi – Via delle Pezzole, 3, Località Allodola, Cellore d’Illasi (VR)'},{label:'Durée',value:'environ 1 h 30 / 2 h'},{label:'Réservation',value:'au moins 48 heures à l’avance, sous réserve de disponibilité'},{label:'Groupe',value:'un seul parcours de dégustation choisi pour l’ensemble du groupe'},{label:'Inclus',value:'dégustation, fromages et charcuteries du territoire et visite de la cave lorsque la période le permet'},{label:'Allergies ou intolérances',value:'à signaler à l’avance'}],cta:'Demandez-nous des informations',official:'Site officiel I Campi',back:'Retour aux Expériences'
 },
 es:{
  home:'Inicio',experiences:'Experiencias',kicker:'Wine Experience • Val d’Illasi',title:'Degustación en bodega entre Valpolicella y los Montes Lessini',subtitle:'Azienda Agricola I Campi – Flavio Prà',lead:'Un viaje por el vino de Verona, entre viñedos, bodega y algunas de las denominaciones más representativas del Véneto.',
  sections:[{title:'Una bodega que cuenta su territorio',text:'En Cellore d’Illasi, en la provincia de Verona, se encuentra Azienda Agricola I Campi, dirigida por el enólogo Flavio Prà, cuarta generación de una familia de viticultores. Un proyecto construido con experiencia, investigación y un fuerte vínculo con la tierra.'},{title:'«Cada vino quiere su tierra»',text:'Para cada variedad se buscan los viñedos más adecuados, también en zonas altas de colina, con el objetivo de obtener vinos reconocibles, elegantes y profundamente ligados al lugar del que nacen.'},{title:'Val d’Illasi, entre viñedos y Montes Lessini',text:'La bodega se encuentra en Val d’Illasi, en la parte oriental de Valpolicella. Piedra, madera, tecnología y conocimiento enológico conviven en un proyecto centrado en la calidad, la autenticidad y la sostenibilidad.'}],
  awardsTitle:'Vinos premiados, identidad reconocida',awards:'El trabajo de I Campi ha recibido importantes reconocimientos de guías y críticos nacionales e internacionales. El Soave Classico DOC “Campo Vulcano” obtuvo Tre Bicchieri de Gambero Rosso y 94/100 de James Suckling; el Valpolicella Ripasso Superiore DOC “Campo Ciotoli” alcanzó 93/100 de James Suckling; el Amarone della Valpolicella DOCG “Campi Lunghi” obtuvo 93/100 de James Suckling y, en otras añadas, reconocimientos de Falstaff, Vinous, Asia Wine Trophy y Berliner Wine Trophy.',awardsNote:'Los premios citados se refieren a etiquetas y añadas concretas y no implican que la degustación incluya necesariamente esas mismas añadas.',
  tastingTitle:'Elige tu recorrido de degustación',tastingIntro:'Se puede elegir entre cuatro propuestas, con un único recorrido para todo el grupo:',tastings:[{name:'Nuevos Horizontes',wines:'Lugana DOC, Pinot Grigio delle Venezie DOC y Soave DOC.'},{name:'Inmersión en Valpolicella',wines:'Valpolicella Superiore DOC, Ripasso DOC y Amarone della Valpolicella DOCG.'},{name:'Doble Comparación',wines:'Lugana DOC, Soave DOC, Valpolicella Superiore DOC y Ripasso DOC.'},{name:'Recorrido Completo',wines:'Lugana DOC, Soave DOC, Pinot Grigio delle Venezie DOC, Valpolicella Superiore DOC, Ripasso DOC y Amarone della Valpolicella DOCG.'}],included:'La degustación incluye una selección de quesos y embutidos locales y, según la época de la visita, la posibilidad de visitar la bodega.',
  whyTitle:'Por qué la recomendamos',why:'Hemos elegido I Campi porque aquí la degustación se convierte en una forma de conocer realmente el territorio. No solo vinos, sino también una historia, una filosofía de producción y una bodega veronesa con una identidad clara y reconocida. Una experiencia ideal para descubrir un Véneto diferente, más allá de Venecia.',perfect:'Perfecta para: parejas • grupos de amigos • amantes del vino • quienes quieran descubrir el Véneto más allá de Venecia',adviceTitle:'Nuestro consejo',advice:'¿No sabes qué recorrido elegir? Escríbenos por WhatsApp y cuéntanos qué tipo de vinos prefieres: te ayudaremos a orientarte y a comprobar la disponibilidad con la bodega.',advance:'Reserva requerida con al menos 48 horas de antelación.',
  infoTitle:'Información práctica',info:[{label:'Dónde',value:'Azienda Agricola I Campi – Via delle Pezzole, 3, Località Allodola, Cellore d’Illasi (VR)'},{label:'Duración',value:'aprox. 1 hora y 30 minutos / 2 horas'},{label:'Reserva',value:'al menos 48 horas antes, sujeta a disponibilidad'},{label:'Grupo',value:'un único recorrido de degustación elegido para todo el grupo'},{label:'Incluye',value:'degustación, quesos y embutidos locales y visita a la bodega cuando la época lo permita'},{label:'Alergias o intolerancias',value:'deben comunicarse previamente'}],cta:'Pídenos información sobre la experiencia',official:'Web oficial de I Campi',back:'Volver a Experiencias'
 },
 zh:{
  home:'首页',experiences:'体验',kicker:'葡萄酒体验 • Val d’Illasi',title:'在 Valpolicella 与 Lessini 山之间的酒庄品鉴',subtitle:'Azienda Agricola I Campi – Flavio Prà',lead:'走进维罗纳葡萄酒世界，在葡萄园、酒窖与威尼托最具代表性的法定产区之间展开一次品鉴之旅。',
  sections:[{title:'一座讲述土地故事的酒庄',text:'Azienda Agricola I Campi 位于维罗纳省 Cellore d’Illasi，由酿酒师 Flavio Prà 经营。他是葡萄种植家族的第四代传人。酒庄以长期经验、研究与对土地的深厚联系为基础不断发展。'},{title:'“每一种酒都需要属于自己的土地”',text:'针对不同葡萄品种，酒庄寻找最适宜的葡萄园，包括高海拔丘陵地块，希望酿造出具有鲜明个性、优雅并与产地紧密相连的葡萄酒。'},{title:'Val d’Illasi：葡萄园与 Lessini 山之间',text:'酒庄位于 Valpolicella 东部的 Val d’Illasi。石材、木材、现代技术与酿酒专业知识在这里结合，围绕品质、葡萄酒的真实性与可持续性展开。'}],
  awardsTitle:'获奖葡萄酒与备受认可的风格',awards:'多年来，I Campi 获得多家意大利及国际指南与酒评家的认可。Soave Classico DOC “Campo Vulcano” 获得 Gambero Rosso Tre Bicchieri，并得到 James Suckling 94/100；Valpolicella Ripasso Superiore DOC “Campo Ciotoli” 获 James Suckling 93/100；Amarone della Valpolicella DOCG “Campi Lunghi” 获 James Suckling 93/100，并在其他年份获得 Falstaff、Vinous、Asia Wine Trophy 与 Berliner Wine Trophy 等认可。',awardsNote:'上述奖项对应特定酒款与年份，并不表示品鉴时一定包含相同年份。',
  tastingTitle:'选择您的品鉴路线',tastingIntro:'共有四种方案可选，同一团体需统一选择一种品鉴路线：',tastings:[{name:'新视野',wines:'Lugana DOC、Pinot Grigio delle Venezie DOC 和 Soave DOC。'},{name:'沉浸 Valpolicella',wines:'Valpolicella Superiore DOC、Ripasso DOC 和 Amarone della Valpolicella DOCG。'},{name:'双重对比',wines:'Lugana DOC、Soave DOC、Valpolicella Superiore DOC 和 Ripasso DOC。'},{name:'完整路线',wines:'Lugana DOC、Soave DOC、Pinot Grigio delle Venezie DOC、Valpolicella Superiore DOC、Ripasso DOC 和 Amarone della Valpolicella DOCG。'}],included:'品鉴包含当地奶酪与冷切肉品；视参观时期而定，也可能安排酒窖参观。',
  whyTitle:'为什么我们推荐',why:'我们选择 I Campi，是因为这里的品鉴不仅是喝酒，更是一种真正认识当地土地与文化的方式。您会接触到酒庄的故事、酿造理念，以及这家维罗纳酒庄清晰而受认可的身份。非常适合想在威尼斯之外探索另一面威尼托的旅客。',perfect:'适合：情侣 • 朋友团体 • 葡萄酒爱好者 • 想探索威尼斯之外威尼托地区的旅客',adviceTitle:'我们的建议',advice:'不知道该选哪一种路线？通过 WhatsApp 告诉我们您喜欢什么类型的葡萄酒，我们很乐意帮您了解不同方案，并与酒庄确认可用时间。',advance:'需至少提前 48 小时预约。',
  infoTitle:'实用信息',info:[{label:'地点',value:'Azienda Agricola I Campi – Via delle Pezzole, 3, Località Allodola, Cellore d’Illasi (VR)'},{label:'时长',value:'约 1 小时 30 分钟至 2 小时'},{label:'预约',value:'至少提前 48 小时，并需确认可用时间'},{label:'团体',value:'整个团体统一选择一种品鉴路线'},{label:'包含',value:'葡萄酒品鉴、当地奶酪与冷切肉品，以及在适合时期安排的酒窖参观'},{label:'过敏或不耐受',value:'请提前告知'}],cta:'向我们咨询此体验',official:'I Campi 官方网站',back:'返回体验'
 }
};

const experienceHref:Record<Lang,string>={it:'/collaborazioni',en:'/en/experiences',de:'/de/experiences',fr:'/fr/experiences',es:'/es/experiences',zh:'/zh/experiences'};
const homeHref:Record<Lang,string>={it:'/',en:'/en',de:'/de',fr:'/fr',es:'/es',zh:'/zh'};
const waText:Record<Lang,string>={
 it:'Ciao, vorrei informazioni sulla Wine Experience presso Azienda Agricola I Campi.',
 en:'Hello, I would like information about the Wine Experience at Azienda Agricola I Campi.',
 de:'Hallo, ich hätte gerne Informationen zur Wine Experience bei Azienda Agricola I Campi.',
 fr:'Bonjour, je souhaiterais des informations sur la Wine Experience chez Azienda Agricola I Campi.',
 es:'Hola, me gustaría recibir información sobre la Wine Experience en Azienda Agricola I Campi.',
 zh:'您好，我想了解 Azienda Agricola I Campi 葡萄酒体验的相关信息。'
};

export default function ICampiExperiencePage({lang}:{lang:Lang}){
 const t=copy[lang];
 const wa=`https://wa.me/393514462261?text=${encodeURIComponent(waText[lang])}`;
 return <><Header lang={lang}/><main><article>
  <section className="bg-navy pt-20 text-white">
   <div className="mx-auto max-w-7xl px-5 pb-10 pt-12 lg:px-8">
    <nav aria-label="Breadcrumb" className="mb-5 flex flex-wrap items-center gap-2 text-sm text-white/70"><Link href={homeHref[lang]}>{t.home}</Link><span>›</span><Link href={experienceHref[lang]}>{t.experiences}</Link><span>›</span><span className="text-gold">I Campi</span></nav>
    <p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.kicker}</p>
    <h1 className="mt-4 max-w-5xl break-words font-serif text-[clamp(3rem,8vw,5.5rem)] leading-none">{t.title}</h1>
    <p className="mt-5 font-serif text-2xl text-gold/90">{t.subtitle}</p>
    <p className="mt-6 max-w-3xl text-xl text-white/80">{t.lead}</p>
   </div>
   <div className="mx-auto max-w-7xl px-5 pb-16 lg:px-8"><div className="relative aspect-video overflow-hidden rounded-[2rem] bg-white shadow-soft"><Image src="/images/experience-i-campi-cover.webp" alt="Azienda Agricola I Campi tra i vigneti della Val d’Illasi" fill priority sizes="100vw" className="object-cover"/></div></div>
  </section>

  <section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><div className="space-y-12">{t.sections.map((s,i)=><section key={s.title} className="grid gap-5 md:grid-cols-[70px_1fr]"><div className="font-serif text-5xl text-gold">{String(i+1).padStart(2,'0')}</div><div><h2 className="font-serif text-4xl text-navy">{s.title}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{s.text}</p></div></section>)}</div></div></section>

  <section className="bg-cream py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><h2 className="font-serif text-4xl text-navy">{t.awardsTitle}</h2><p className="mt-5 text-lg leading-8 text-slate-600">{t.awards}</p><p className="mt-5 rounded-2xl bg-white p-5 text-sm leading-6 text-slate-600"><strong>{t.awardsNote}</strong></p></div></section>

  <section className="py-20"><div className="mx-auto max-w-5xl px-5 lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">Wine tasting</p><h2 className="mt-3 font-serif text-5xl text-navy">{t.tastingTitle}</h2><p className="mt-5 text-lg text-slate-600">{t.tastingIntro}</p><div className="mt-8 grid gap-5 md:grid-cols-2">{t.tastings.map(x=><div key={x.name} className="rounded-[2rem] border border-slate-200 bg-white p-7 shadow-soft"><h3 className="font-serif text-3xl text-navy">{x.name}</h3><p className="mt-3 leading-7 text-slate-600">{x.wines}</p></div>)}</div><p className="mt-8 rounded-[2rem] bg-cream p-7 text-lg leading-8 text-navy">{t.included}</p></div></section>

  <section className="bg-navy py-20 text-white"><div className="mx-auto grid max-w-5xl gap-8 px-5 lg:grid-cols-2 lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.2em] text-gold">Marghera Venice Apartments</p><h2 className="mt-3 font-serif text-5xl">{t.whyTitle}</h2><p className="mt-5 text-lg leading-8 text-white/75">{t.why}</p><p className="mt-6 font-semibold text-gold">{t.perfect}</p></div><aside className="rounded-[2rem] bg-white p-8 text-navy"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{t.adviceTitle}</p><p className="mt-4 text-lg leading-8">{t.advice}</p><p className="mt-5 font-bold">{t.advance}</p><a href={wa} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex rounded-full bg-gold px-6 py-4 font-bold text-navy">🍷 {t.cta} ↗</a></aside></div></section>

  <section className="py-20"><div className="mx-auto max-w-5xl px-5 lg:px-8"><h2 className="font-serif text-5xl text-navy">{t.infoTitle}</h2><div className="mt-8 overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-soft">{t.info.map((x,i)=><div key={x.label} className={`grid gap-2 p-5 sm:grid-cols-[190px_1fr] sm:p-6 ${i<t.info.length-1?'border-b border-slate-200':''}`}><strong className="text-navy">{x.label}</strong><span className="text-slate-600">{x.value}</span></div>)}</div><div className="mt-8 flex flex-wrap gap-3"><a href="https://www.icampi.it/" target="_blank" rel="noopener noreferrer" className="inline-flex rounded-full border border-navy px-6 py-3 font-bold text-navy">{t.official} ↗</a><Link href={experienceHref[lang]} className="inline-flex rounded-full bg-gold px-6 py-3 font-bold text-navy">{t.back}</Link></div></div></section>
 </article></main><Footer lang={lang}/></>;
}
