import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ImageCreditsClient from '@/components/ImageCreditsClient';
import StaticImageCredits from '@/components/StaticImageCredits';
type Lang='it'|'en'|'de'|'fr'|'es'|'zh';
const c={
 it:{title:'Crediti immagini',lead:'Qui raccogliamo autore, fonte e licenza delle fotografie di terzi usate nel sito, senza sovrapporre riquadri alle immagini.',commons:'Wikimedia Commons',commonsLead:'Le immagini delle guide culturali provenienti da Wikimedia Commons vengono registrate automaticamente sul dispositivo quando vengono visualizzate.'},
 en:{title:'Image credits',lead:'Author, source and licence information for third-party photography used on the site is collected here, without overlaying credit boxes on the images.',commons:'Wikimedia Commons',commonsLead:'Images from Wikimedia Commons used in the culture guides are recorded on this device automatically when they are viewed.'},
 de:{title:'Bildnachweise',lead:'Urheber, Quelle und Lizenz der auf der Website verwendeten Fremdfotografien werden hier gesammelt, ohne die Bilder mit Hinweisen zu überlagern.',commons:'Wikimedia Commons',commonsLead:'Wikimedia-Commons-Bilder aus den Kulturführern werden auf diesem Gerät automatisch erfasst, sobald sie angezeigt werden.'},
 fr:{title:'Crédits images',lead:'Les informations d’auteur, de source et de licence des photographies tierces utilisées sur le site sont regroupées ici, sans encadré superposé aux images.',commons:'Wikimedia Commons',commonsLead:'Les images Wikimedia Commons des guides culturels sont enregistrées automatiquement sur cet appareil lorsqu’elles sont affichées.'},
 es:{title:'Créditos de imágenes',lead:'Aquí reunimos la información de autor, fuente y licencia de las fotografías de terceros utilizadas en el sitio, sin superponer recuadros sobre las imágenes.',commons:'Wikimedia Commons',commonsLead:'Las imágenes de Wikimedia Commons utilizadas en las guías culturales se registran automáticamente en este dispositivo cuando se visualizan.'},
 zh:{title:'图片署名',lead:'此页面集中列出网站使用的第三方图片作者、来源与许可信息，同时不在图片上叠加署名框。',commons:'Wikimedia Commons',commonsLead:'文化指南中的 Wikimedia Commons 图片会在本设备浏览时自动记录署名信息。'}
} as const;
export default function ImageCreditsPage({lang}:{lang:Lang}){const t=c[lang];return <><Header lang={lang}/><main><section className="bg-navy px-5 pb-16 pt-36 text-white lg:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Marghera Venice Apartments</p><h1 className="mt-4 font-serif text-6xl md:text-8xl">{t.title}</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-white/75">{t.lead}</p></div></section><section className="py-20"><div className="mx-auto max-w-6xl px-5 lg:px-8"><StaticImageCredits lang={lang}/><div className="mt-16 border-t border-slate-200 pt-12"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{t.commons}</p><h2 className="mt-3 font-serif text-4xl text-navy">{t.commons}</h2><p className="mt-4 max-w-3xl leading-7 text-slate-600">{t.commonsLead}</p><div className="mt-8"><ImageCreditsClient lang={lang}/></div></div></div></section></main><Footer lang={lang}/></>}
