import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export type JournalDeData={slug:string;title:string;category:string;description:string;lead:string;image:string;imageAlt:string;sections:[string,string][];tip:string;official?:[string,string]};
export default function JournalArticleDe({data}:{data:JournalDeData}){return <><Header lang="de"/><main><article>
<section className="relative min-h-[72vh] overflow-hidden pt-20"><Image src={data.image} alt={data.imageAlt} fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/75 to-navy/20"/><div className="relative mx-auto flex min-h-[calc(72vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-20 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-5 flex flex-wrap gap-2 text-sm text-white/70"><Link href="/de">Startseite</Link><span>›</span><Link href="/de/journal">Journal</Link><span>›</span><span className="text-gold">{data.title}</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.category}</p><h1 className="mt-4 font-serif text-6xl leading-none md:text-8xl">{data.title}</h1><p className="mt-6 max-w-3xl text-xl text-white/80">{data.description}</p></div></div></section>
<section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><p className="font-serif text-3xl leading-relaxed text-navy">{data.lead}</p><div className="mt-14 space-y-12">{data.sections.map((s,i)=><section key={s[0]} className="grid gap-5 md:grid-cols-[70px_1fr]"><div className="font-serif text-5xl text-gold">{String(i+1).padStart(2,'0')}</div><div><h2 className="font-serif text-4xl text-navy">{s[0]}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{s[1]}</p></div></section>)}</div></div></section>
<section className="bg-cream py-16"><div className="mx-auto max-w-4xl px-5 lg:px-8"><div className="rounded-[2rem] bg-gold p-8 text-navy"><p className="text-xs font-black uppercase tracking-[.22em]">Tipp von Marghera Venice Apartments</p><p className="mt-4 font-serif text-3xl">{data.tip}</p></div>{data.official&&<div className="mt-8 rounded-[2rem] bg-white p-8 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">Offizielle Informationen</p><p className="mt-3 text-slate-600">Termine, Preise und Bedingungen können sich ändern. Prüfen Sie variable Informationen bitte immer kurz vor dem Besuch bei der offiziellen Quelle.</p><a href={data.official[1]} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex rounded-full bg-navy px-6 py-3 font-bold text-white">{data.official[0]} ↗</a></div>}</div></section>
<section className="py-20"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">Mehr entdecken</p><h2 className="mt-3 font-serif text-4xl text-navy">Weitere Tipps für Ihren Aufenthalt</h2><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/de/discover-venice" className="rounded-full border border-navy px-6 py-3 font-bold text-navy">Venedig entdecken</Link><Link href="/de/getting-to-venice" className="rounded-full border border-navy px-6 py-3 font-bold text-navy">Nach Venedig</Link><Link href="/de/journal" className="rounded-full bg-gold px-7 py-3 font-bold text-navy">Zurück zum Journal</Link></div></div></section>
</article></main><Footer lang="de"/></>}
