import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SectionTitle from '@/components/SectionTitle';
import WeChatCard from '@/components/WeChatCard';

type Lang='de'|'fr'|'es'|'zh';
export type RichCard={title:string;text:string;image?:string;alt?:string;href?:string;label?:string};
export type RichSection={eyebrow?:string;title:string;text?:string;image?:string;alt?:string;cards?:RichCard[];links?:[string,string][]};
export type RichPageData={title:string;subtitle:string;hero:string;heroAlt:string;sections:RichSection[]};

const home:Record<Lang,string>={de:'Startseite',fr:'Accueil',es:'Inicio',zh:'首页'};
const contact:Record<Lang,{eyebrow:string,title:string,text:string,button:string,message:string}>={
 de:{eyebrow:'DIREKTER KONTAKT',title:'Erzählen Sie uns von Ihrer Reise',text:'Senden Sie uns Ihre Reisedaten und die Anzahl der Gäste. Wir antworten persönlich mit Verfügbarkeit und allen wichtigen Informationen.',button:'Verfügbarkeit prüfen',message:'Hallo, ich möchte die Verfügbarkeit der Marghera Venice Apartments prüfen. Meine Reisedaten sind: '},
 fr:{eyebrow:'CONTACT DIRECT',title:'Parlez-nous de votre voyage',text:'Envoyez-nous vos dates et le nombre de voyageurs. Nous vous répondrons personnellement avec les disponibilités et les informations utiles.',button:'Vérifier les disponibilités',message:'Bonjour, je souhaite vérifier les disponibilités de Marghera Venice Apartments. Mes dates sont : '},
 es:{eyebrow:'CONTACTO DIRECTO',title:'Cuéntanos tu viaje',text:'Envíanos tus fechas y el número de huéspedes. Te responderemos personalmente con disponibilidad e información útil.',button:'Comprobar disponibilidad',message:'Hola, me gustaría comprobar la disponibilidad de Marghera Venice Apartments. Mis fechas son: '},
 zh:{eyebrow:'直接联系',title:'告诉我们您的旅行计划',text:'请通过微信告诉我们入住日期和人数，我们会亲自回复可订情况以及入住所需的信息。',button:'微信联系我们',message:''}
};

export function LocalizedRichPage({lang,data}:{lang:Lang;data:RichPageData}){
 const c=contact[lang];
 return <><Header lang={lang}/><main>
  <section className="relative min-h-[72vh] overflow-hidden pt-20">
   <Image src={data.hero} alt={data.heroAlt} fill priority sizes="100vw" className="object-cover"/>
   <div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/75 to-navy/20"/>
   <div className="relative mx-auto flex min-h-[calc(72vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-20 lg:px-8"><div className="max-w-4xl text-white">
    <nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-sm text-white/75"><Link href={`/${lang}`} className="hover:text-gold">{home[lang]}</Link><span>›</span><span className="text-gold">{data.title}</span></nav>
    <h1 className="mt-5 break-words font-serif text-5xl leading-[.98] sm:text-6xl md:text-8xl">{data.title}</h1>
    <p className="mt-6 max-w-3xl text-xl text-white/85">{data.subtitle}</p>
   </div></div>
  </section>
  {data.sections.map((s,i)=><section key={s.title} className={i%2?'bg-cream py-20':'py-20'}><div className="mx-auto max-w-7xl px-5 lg:px-8">
   <SectionTitle eyebrow={s.eyebrow||''} title={s.title} text={s.text||''}/>
   {s.image&&<div className="relative mt-10 h-[300px] overflow-hidden rounded-[2rem] shadow-soft sm:h-[420px]"><Image src={s.image} alt={s.alt||s.title} fill sizes="100vw" className="object-cover"/></div>}
   {s.cards&&<div className="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{s.cards.map(card=><article key={card.title} className="overflow-hidden rounded-[2rem] bg-white shadow-soft">
    {card.image&&<div className="relative h-60 overflow-hidden"><Image src={card.image} alt={card.alt||card.title} fill sizes="(min-width:1280px) 33vw, (min-width:768px) 50vw, 100vw" className="object-cover"/></div>}
    <div className="p-7"><h2 className="font-serif text-3xl text-navy">{card.title}</h2><p className="mt-3 leading-7 text-slate-600">{card.text}</p>{card.href&&<Link href={card.href} className="mt-6 inline-flex rounded-full bg-gold px-5 py-3 font-bold text-navy">{card.label||'→'}</Link>}</div>
   </article>)}</div>}
   {s.links&&<div className="mt-9 flex flex-wrap gap-3">{s.links.map(([label,href])=>href.startsWith('http')?<a key={href} href={href} target="_blank" rel="noopener noreferrer" className="rounded-full border border-navy px-6 py-3 font-bold text-navy hover:bg-navy hover:text-white">{label} ↗</a>:<Link key={href} href={href} className="rounded-full border border-navy px-6 py-3 font-bold text-navy hover:bg-navy hover:text-white">{label}</Link>)}</div>}
  </div></section>)}
  <section id="direct-contact" className="bg-navy py-20 text-white"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.28em] text-gold">{c.eyebrow}</p><h2 className="mt-4 font-serif text-4xl sm:text-6xl">{c.title}</h2><p className="mx-auto mt-6 max-w-3xl text-lg text-white/80">{c.text}</p>{lang==='zh'?<div className="mt-10"><WeChatCard dark title="添加我们的微信"/></div>:<a href={`https://wa.me/393514462261?text=${encodeURIComponent(c.message)}`} target="_blank" rel="noopener noreferrer" className="mt-9 inline-flex rounded-full bg-gold px-8 py-4 font-bold text-navy">{c.button}</a>}</div></section>
 </main><Footer lang={lang}/></>;
}

export type ApartmentData={name:string;subtitle:string;hero:string;heroAlt:string;guests:string;stats:[string,string,string][];gallery:[string,string][];livingTitle:string;living:string[];services:string[];transportTitle:string;transportText:string;transportHref:string;transportLabel:string;cta:string;message:string};
export function LocalizedApartment({lang,data}:{lang:Lang;data:ApartmentData}){
 const ui={
  de:{apartments:'Unsere Apartments',services:'Ausstattung',why:'Warum diese Unterkunft',whyTitle:'Mehr Komfort, mehr Freiheit',whyText:'Privater Parkplatz, großzügige Räume und einfache Verbindungen nach Venedig machen den Aufenthalt besonders unkompliziert.',day:'Ein typischer Tag',dayTitle:'So könnte Ihr Aufenthalt aussehen',dayItems:['Frühstück in Ruhe zu Hause','Mit Bus oder Zug nach Venedig','Am Abend ohne Parkplatzsuche zurückkehren'],reach:'Einfach erreichbar',reachText:'Marghera ist praktisch mit Auto, Bahn und Flugzeug erreichbar. Die vollständigen Hinweise finden Sie auf unserer Anreiseseite.',family:'Familienfreundlich',pet:'Haustierfreundlich',contact:'Verfügbarkeit prüfen'},
  fr:{apartments:'Nos appartements',services:'Équipements',why:'Pourquoi le choisir',whyTitle:'Plus de confort, plus de liberté',whyText:'Parking privé, beaux volumes et liaisons simples vers Venise rendent le séjour particulièrement pratique.',day:'Une journée type',dayTitle:'Imaginez votre séjour',dayItems:['Petit-déjeuner tranquillement à l’appartement','Rejoindre Venise en bus ou en train','Rentrer le soir sans chercher de parking'],reach:'Facile d’accès',reachText:'Marghera est facile à rejoindre en voiture, en train ou en avion. Retrouvez tous les détails sur notre page d’accès.',family:'Adapté aux familles',pet:'Animaux bienvenus',contact:'Vérifier les disponibilités'},
  es:{apartments:'Nuestros apartamentos',services:'Servicios',why:'Por qué elegirlo',whyTitle:'Más comodidad, más libertad',whyText:'Aparcamiento privado, espacios amplios y conexiones sencillas con Venecia hacen que la estancia sea especialmente cómoda.',day:'Un día típico',dayTitle:'Imagina tu estancia',dayItems:['Desayunar tranquilamente en el apartamento','Llegar a Venecia en autobús o tren','Volver por la noche sin buscar aparcamiento'],reach:'Fácil de alcanzar',reachText:'Marghera está bien conectada en coche, tren y avión. Consulta todos los detalles en nuestra página de llegada.',family:'Ideal para familias',pet:'Pet Friendly',contact:'Comprobar disponibilidad'},
  zh:{apartments:'我们的公寓',services:'设施服务',why:'为什么选择这里',whyTitle:'更多舒适，也更多自由',whyText:'私人停车位、宽敞空间以及前往威尼斯的便利交通，让住宿安排更加轻松。',day:'一天的节奏',dayTitle:'想象一下您的住宿',dayItems:['在公寓轻松享用早餐','乘公交或火车前往威尼斯','晚上无需寻找停车位即可返回'],reach:'抵达很方便',reachText:'马尔盖拉可通过汽车、火车或飞机轻松抵达。完整信息请查看交通页面。',family:'家庭友好',pet:'宠物友好',contact:'查询可订情况'}
 }[lang];
 const isDimora=data.name==='Dimora Castelli';
 const dimoraUi={de:{garden:'Der Garten hinter dem Haus',gardenText:'Ein ruhiger Außenbereich im gemeinschaftlichen Garten ergänzt die Wohnung und bietet eine angenehme Pause zwischen den Ausflügen.',ideal:'Ideal für einen entspannten Aufenthalt',idealText:'Paare, kleine Familien und Reisende mit Auto finden hier eine praktische Kombination aus Ruhe, Platz und guter Anbindung.',area:'Mitten in Margheras Gartenstadt',areaText:'Dimora Castelli liegt in einem grünen, ruhigen Teil von Marghera mit Geschäften und Verkehrsanbindungen in der Nähe.'},fr:{garden:'Le jardin à l’arrière',gardenText:'Un espace extérieur calme dans le jardin commun complète l’appartement et offre une vraie pause entre deux visites.',ideal:'Idéal pour un séjour détendu',idealText:'Couples, petites familles et voyageurs en voiture profitent d’un bon équilibre entre calme, espace et liaisons pratiques.',area:'Au cœur de la cité-jardin de Marghera',areaText:'Dimora Castelli se trouve dans un secteur vert et tranquille de Marghera, proche des commerces et des transports.'},es:{garden:'El jardín trasero',gardenText:'Una zona exterior tranquila en el jardín comunitario completa el apartamento y ofrece una pausa agradable entre excursiones.',ideal:'Ideal para una estancia tranquila',idealText:'Parejas, familias pequeñas y viajeros en coche encuentran un buen equilibrio entre tranquilidad, espacio y conexiones cómodas.',area:'En el corazón de la Ciudad Jardín de Marghera',areaText:'Dimora Castelli está en una zona verde y tranquila de Marghera, cerca de comercios y conexiones de transporte.'},zh:{garden:'后方花园',gardenText:'公寓楼的共享花园提供一处安静的户外空间，适合在一天的游览之间稍作休息。',ideal:'适合轻松舒适的住宿',idealText:'情侣、小家庭以及自驾客人都能在这里兼顾安静、空间与便利交通。',area:'位于马尔盖拉花园城市区',areaText:'Dimora Castelli 位于马尔盖拉绿意较多且安静的区域，附近有商店和公共交通。'}}[lang];
 const extraStats:[[string,string,string],[string,string,string]]=[['♥',ui.pet,data.services.find(x=>/pet|haustier|animaux|mascotas|宠物/i.test(x))||ui.pet],['★',ui.family,data.services.find(x=>/baby|kinder|enfant|cuna|家庭/i.test(x))||ui.family]];
 return <><Header lang={lang}/><main>
  <section className="relative min-h-[78vh] overflow-hidden pt-20"><Image src={data.hero} alt={data.heroAlt} fill priority sizes="100vw" className="object-cover"/><div className="hero-overlay absolute inset-0"/><div className="relative mx-auto flex min-h-[calc(78vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-24 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-sm text-white/75"><Link href={`/${lang}`} className="hover:text-gold">{home[lang]}</Link><span>›</span><Link href={`/${lang}/#case`} className="hover:text-gold">{ui.apartments}</Link><span>›</span><span className="text-gold">{data.name}</span></nav><p className="mt-6 text-xs font-black uppercase tracking-[.25em] text-gold">{data.guests} · Marghera</p><h1 className="mt-4 break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{data.name}</h1><p className="mt-6 max-w-2xl text-xl text-white/85">{data.subtitle}</p><a href={lang==='zh'?'/zh/#direct-contact':`https://wa.me/393514462261?text=${encodeURIComponent(data.message)}`} target={lang==='zh'?undefined:'_blank'} rel={lang==='zh'?undefined:'noopener noreferrer'} className="mt-8 inline-flex rounded-full bg-gold px-7 py-4 font-bold text-navy">{data.cta}</a></div></div></section>
  <section className="bg-cream py-10"><div className="mx-auto grid max-w-7xl gap-4 px-5 sm:grid-cols-2 lg:grid-cols-5 lg:px-8">{[...data.stats,...extraStats].map(([v,t,x])=><div key={t} className="rounded-2xl bg-white p-5 shadow-soft"><div className="text-3xl font-black text-gold">{v}</div><h2 className="mt-2 font-serif text-2xl text-navy">{t}</h2><p className="mt-2 text-sm text-slate-600">{x}</p></div>)}</div></section>
  <section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.name} title={data.livingTitle} text={data.subtitle}/><div className="grid gap-4 lg:grid-cols-12">{data.gallery.map(([src,alt],i)=><div key={src} className={`relative overflow-hidden rounded-3xl ${i===0?'h-[360px] lg:col-span-7 lg:row-span-2 lg:h-[500px]':'h-[240px] lg:col-span-5'}`}><Image src={src} alt={alt} fill sizes="(min-width:1024px) 55vw, 100vw" className="object-cover transition duration-700 hover:scale-[1.025]"/></div>)}</div></div></section>
  <section className="bg-cream py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:px-8"><div><h2 className="font-serif text-5xl text-navy">{data.livingTitle}</h2><div className="mt-7 space-y-5 text-lg leading-8 text-slate-600">{data.living.map(x=><p key={x}>{x}</p>)}</div></div><div className="relative min-h-[380px] overflow-hidden rounded-[2rem] shadow-soft"><Image src={data.gallery[1]?.[0]||data.hero} alt={data.gallery[1]?.[1]||data.heroAlt} fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover"/></div></div></section>
  <section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={ui.services} title={ui.services} text={data.subtitle}/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.services.map(x=><div key={x} className="rounded-2xl border border-slate-200 bg-white p-5 font-semibold text-navy">✓ {x}</div>)}</div></div></section>
  <section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={ui.why} title={ui.whyTitle} text={ui.whyText}/><div className="grid gap-5 md:grid-cols-3">{data.stats.map(([v,t,x])=><article key={t} className="rounded-[2rem] bg-white p-7 shadow-soft"><div className="text-3xl font-black text-gold">{v}</div><h2 className="mt-3 font-serif text-3xl text-navy">{t}</h2><p className="mt-3 text-slate-600">{x}</p></article>)}</div></div></section>
  {isDimora&&<section className="bg-navy py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:px-8"><div className="relative min-h-[380px] overflow-hidden rounded-[2rem]"><Image src="/images/dimora-castelli-giardino-reale.webp" alt={dimoraUi.garden} fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover"/></div><div className="flex flex-col justify-center"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Dimora Castelli</p><h2 className="mt-3 font-serif text-5xl">{dimoraUi.garden}</h2><p className="mt-6 text-lg text-white/75">{dimoraUi.gardenText}</p></div></div></section>}
  {isDimora&&<section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={ui.why} title={dimoraUi.ideal} text={dimoraUi.idealText}/><div className="grid gap-5 md:grid-cols-3">{data.services.slice(0,6).map(x=><div key={x} className="rounded-[2rem] bg-cream p-6 font-semibold text-navy">✓ {x}</div>)}</div></div></section>}
  {isDimora&&<section className="bg-cream py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div className="relative min-h-[360px] overflow-hidden rounded-[2rem] shadow-soft"><Image src="/images/dimora-castelli-edificio-storia.webp" alt={dimoraUi.area} fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover"/></div><div className="flex flex-col justify-center"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Marghera</p><h2 className="mt-3 font-serif text-5xl text-navy">{dimoraUi.area}</h2><p className="mt-6 text-lg text-slate-600">{dimoraUi.areaText}</p></div></div></section>}
  <section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={ui.day} title={ui.dayTitle} text={data.transportText}/><div className="grid gap-5 md:grid-cols-3">{ui.dayItems.map((x,i)=><article key={x} className="rounded-[2rem] border border-slate-200 bg-white p-7"><div className="font-serif text-5xl text-gold">0{i+1}</div><p className="mt-4 text-lg text-navy">{x}</p></article>)}</div></div></section>
  <section className="bg-navy py-24 text-white"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Venice & Veneto</p><h2 className="mt-3 font-serif text-5xl">{data.transportTitle}</h2><p className="mx-auto mt-5 max-w-3xl text-lg text-white/75">{data.transportText}</p><Link href={data.transportHref} className="mt-8 inline-flex rounded-full bg-gold px-7 py-4 font-bold text-navy">{data.transportLabel}</Link></div></section>
  <section className="py-24"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{ui.contact}</p><h2 className="mt-3 font-serif text-5xl text-navy">{data.name}</h2><p className="mx-auto mt-5 max-w-3xl text-lg text-slate-600">{data.subtitle}</p>{lang==='zh'?<div className="mt-8"><WeChatCard title={data.cta}/></div>:<a href={`https://wa.me/393514462261?text=${encodeURIComponent(data.message)}`} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex rounded-full bg-gold px-7 py-4 font-bold text-navy">{data.cta}</a>}</div></section>
  <section className="bg-cream py-24"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{ui.reach}</p><h2 className="mt-3 font-serif text-5xl text-navy">{ui.reach}</h2><p className="mx-auto mt-5 max-w-3xl text-lg text-slate-600">{ui.reachText}</p><Link href={data.transportHref} className="mt-8 inline-flex rounded-full border border-navy px-7 py-4 font-bold text-navy">{data.transportLabel}</Link></div></section>
 </main><Footer lang={lang}/></>;
}
export type GuideIndexItem={title:string;subtitle:string;text:string;image:string;alt:string;slug:string};
export function LocalizedGuideIndex({lang,title,subtitle,items,openLabel}:{lang:Lang;title:string;subtitle:string;items:GuideIndexItem[];openLabel:string}){return <><Header lang={lang}/><main><section className="bg-navy px-5 pb-20 pt-36 text-white lg:px-8"><div className="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-sm text-white/70"><Link href={`/${lang}`} className="hover:text-gold">{home[lang]}</Link><span>›</span><span className="text-gold">{title}</span></nav><p className="mt-6 text-xs font-black uppercase tracking-[.22em] text-gold">Marghera Venice Guide</p><h1 className="mt-4 max-w-5xl break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{title}</h1><p className="mt-6 max-w-3xl text-xl text-white/75">{subtitle}</p></div></section><section className="bg-cream py-24"><div className="mx-auto grid max-w-7xl gap-8 px-5 lg:grid-cols-2 lg:px-8">{items.map(g=><article key={g.slug} className="overflow-hidden rounded-[2rem] bg-white shadow-soft"><div className="relative h-72"><Image src={g.image} alt={g.alt} fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover"/></div><div className="p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{g.subtitle}</p><h2 className="mt-3 font-serif text-4xl text-navy">{g.title}</h2><p className="mt-4 text-lg text-slate-600">{g.text}</p><Link href={`/${lang}/guide/${g.slug}`} className="mt-7 inline-flex rounded-full bg-gold px-6 py-3 font-bold text-navy">{openLabel}</Link></div></article>)}</div></section></main><Footer lang={lang}/></>}

export type JournalItem={slug:string;title:string;category:string;description:string;image:string;imageAlt:string};
export function LocalizedJournalIndex({lang,title,subtitle,items,readLabel,guideLabel}:{lang:Lang;title:string;subtitle:string;items:JournalItem[];readLabel:string;guideLabel:string}){
 const ui={de:{eyebrow:'Venedig, Veranstaltungen und Lagunenleben',keep:'Weiter entdecken',more:'Suchen Sie ein bestimmtes Reiseziel?',text:'Unsere Reiseführer konzentrieren sich auf Venedig, die Inseln und Tagesausflüge in Venetien; das Journal behandelt Veranstaltungen, Traditionen und praktische Reisetipps.'},fr:{eyebrow:'Venise, événements et vie dans la lagune',keep:'Continuer à explorer',more:'Vous cherchez une destination précise ?',text:'Nos Guides sont consacrés à Venise, aux îles et aux excursions en Vénétie ; le Journal traite des événements, des traditions et des conseils pratiques.'},es:{eyebrow:'Venecia, eventos y vida en la laguna',keep:'Sigue explorando',more:'¿Buscas un destino concreto?',text:'Nuestras Guías se centran en Venecia, las islas y las excursiones por Véneto; el Journal reúne eventos, tradiciones y consejos prácticos.'},zh:{eyebrow:'威尼斯、活动与泻湖生活',keep:'继续探索',more:'正在寻找某个具体目的地？',text:'旅行指南主要介绍威尼斯、泻湖岛屿和威尼托一日游；旅行日志则涵盖活动、传统和实用旅行建议。'}}[lang];
 const categories=Array.from(new Set(items.map(x=>x.category)));
 return <><Header lang={lang}/><main>
 <section className="bg-navy px-5 pb-20 pt-36 text-white lg:px-8"><div className="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap items-center gap-2 text-sm text-white/70"><Link href={`/${lang}`} className="hover:text-gold">{home[lang]}</Link><span>›</span><span className="text-gold">{title}</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{ui.eyebrow}</p><h1 className="mt-4 max-w-5xl break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{title}</h1><p className="mt-6 max-w-3xl text-xl text-white/75">{subtitle}</p></div></section>
 <section className="bg-cream py-12"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-wrap gap-3">{categories.map(x=><span key={x} className="rounded-full border border-navy/15 bg-white px-4 py-2 text-sm font-bold text-navy">{x}</span>)}</div></div></section>
 <section className="bg-cream pb-24"><div className="mx-auto grid max-w-7xl gap-7 px-5 md:grid-cols-2 xl:grid-cols-3 lg:px-8">{items.map(a=><article key={a.slug} className="group overflow-hidden rounded-[2rem] bg-white shadow-soft"><Link href={`/${lang}/journal/${a.slug}`} className="block"><div className="relative h-64 overflow-hidden"><Image src={a.image} alt={a.imageAlt} fill sizes="(min-width:1280px) 33vw, (min-width:768px) 50vw, 100vw" className="card-image object-cover"/></div><div className="p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{a.category}</p><h2 className="mt-3 font-serif text-4xl text-navy">{a.title}</h2><p className="mt-4 text-slate-600">{a.description}</p><span className="mt-6 inline-flex rounded-full bg-gold px-5 py-3 font-bold text-navy">{readLabel}</span></div></Link></article>)}</div></section>
 <section className="py-20"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{ui.keep}</p><h2 className="mt-3 font-serif text-5xl text-navy">{ui.more}</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-slate-600">{ui.text}</p><Link href={`/${lang}/guide`} className="mt-7 inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white">{guideLabel}</Link></div></section>
 </main><Footer lang={lang}/></>;
}
export type JournalArticleData=JournalItem&{lead:string;sections:[string,string][];tip:string;official?:[string,string]};
const journalHome:Record<Lang,string>={de:'Startseite',fr:'Accueil',es:'Inicio',zh:'首页'};
const journalMore:Record<Lang,{official:string;sourceNote:string;more:string;moreTitle:string;venice:string;transport:string;back:string}>={
 de:{official:'Offizielle Informationen',sourceNote:'Termine, Preise und Bedingungen können sich ändern. Prüfen Sie variable Informationen bitte immer kurz vor dem Besuch bei der offiziellen Quelle.',more:'Mehr entdecken',moreTitle:'Weitere Tipps für Ihren Aufenthalt',venice:'Venedig entdecken',transport:'Nach Venedig',back:'Zurück zum Journal'},
 fr:{official:'Informations officielles',sourceNote:'Dates, tarifs et conditions peuvent évoluer. Vérifiez toujours les informations variables auprès de la source officielle avant votre visite.',more:'Continuer à découvrir',moreTitle:'D’autres conseils pour votre séjour',venice:'Découvrir Venise',transport:'Rejoindre Venise',back:'Retour au Journal'},
 es:{official:'Información oficial',sourceNote:'Las fechas, precios y condiciones pueden cambiar. Comprueba siempre la información variable en la fuente oficial antes de la visita.',more:'Seguir explorando',moreTitle:'Más consejos para tu estancia',venice:'Descubrir Venecia',transport:'Cómo llegar a Venecia',back:'Volver al Journal'},
 zh:{official:'官方信息',sourceNote:'日期、票价和条件可能变化。涉及实时信息时，请在出行前通过官方来源再次确认。',more:'继续探索',moreTitle:'更多住宿期间的实用内容',venice:'探索威尼斯',transport:'前往威尼斯',back:'返回旅行日志'}
};
const fallbackOfficial:Record<string,[string,string] | undefined>={
 'carnevale-di-venezia':['Venice Carnival','https://carnevale.venezia.it/en/'],
 'festa-del-redentore':['Comune di Venezia','https://www.comune.venezia.it/en'],
 'natale-capodanno-venezia':['Venezia Unica','https://www.veneziaunica.it/en'],
 'mostra-del-cinema':['La Biennale – Cinema','https://www.labiennale.org/en/cinema'],
 'biennale-di-venezia':['La Biennale di Venezia','https://www.labiennale.org/en'],
 'venezia-con-bambini':['Natural History Museum of Venice','https://msn.visitmuve.it/en/home/'],
 'venezia-con-il-cane':['ACTV / AVM','https://avm.avmspa.it/en/content/venice-urban-services-0'],
 'acqua-alta-a-venezia':['Tide Forecasting Centre – Comune di Venezia','https://www.comune.venezia.it/en/content/tide-forecasting-and-reporting-centre'],
 'spritz-veneziano':['Terrazza Aperol','https://terrazza.aperol.com/en/'],
 'buone-maniere-a-venezia':['Comune di Venezia','https://www.comune.venezia.it/en']
};
const extraOfficial:Record<string,[string,string][] | undefined>={
 'dove-parcheggiare-venezia':[['Autorimessa Comunale AVM','https://avm.avmspa.it/it/content/autorimessa-comunale-1'],['Garage San Marco','https://www.garagesanmarco.it/']]
};
export function LocalizedJournalArticle({lang,data,tipLabel,officialLabel,backLabel}:{lang:Lang;data:JournalArticleData;tipLabel:string;officialLabel:string;backLabel:string}){
 const t=journalMore[lang]; const official=data.official||fallbackOfficial[data.slug]; const extras=extraOfficial[data.slug]||[];
 return <><Header lang={lang}/><main><article>
 <section className="relative min-h-[72vh] overflow-hidden pt-20"><Image src={data.image} alt={data.imageAlt} fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/75 to-navy/20"/><div className="relative mx-auto flex min-h-[calc(72vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-20 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-5 flex flex-wrap items-center gap-2 text-sm text-white/70"><Link href={`/${lang}`} className="hover:text-gold">{journalHome[lang]}</Link><span>›</span><Link href={`/${lang}/journal`} className="hover:text-gold">Journal</Link><span>›</span><span className="text-gold">{data.title}</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.category}</p><h1 className="mt-4 break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{data.title}</h1><p className="mt-6 max-w-3xl text-xl text-white/80">{data.description}</p></div></div></section>
 <section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><p className="font-serif text-3xl leading-relaxed text-navy">{data.lead}</p><div className="mt-14 space-y-12">{data.sections.map(([title,text],i)=><section key={title} className="grid gap-5 md:grid-cols-[70px_1fr]"><div className="font-serif text-5xl text-gold">{String(i+1).padStart(2,'0')}</div><div><h2 className="font-serif text-4xl text-navy">{title}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{text}</p></div></section>)}</div></div></section>
 <section className="bg-cream py-16"><div className="mx-auto max-w-4xl px-5 lg:px-8"><div className="rounded-[2rem] bg-gold p-8 text-navy"><p className="text-xs font-black uppercase tracking-[.22em]">{tipLabel}</p><p className="mt-4 font-serif text-3xl">{data.tip}</p></div>{(official||extras.length>0)&&<div className="mt-8 rounded-[2rem] bg-white p-8 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{officialLabel||t.official}</p><p className="mt-3 text-slate-600">{t.sourceNote}</p><div className="mt-5 flex flex-wrap gap-3">{official&&<a href={official[1]} target="_blank" rel="noopener noreferrer" className="inline-flex rounded-full bg-navy px-6 py-3 font-bold text-white">{official[0]} ↗</a>}{extras.map(([label,url])=><a key={url} href={url} target="_blank" rel="noopener noreferrer" className="inline-flex rounded-full border border-navy px-6 py-3 font-bold text-navy">{label} ↗</a>)}</div></div>}</div></section>
 <section className="py-20"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{t.more}</p><h2 className="mt-3 font-serif text-4xl text-navy">{t.moreTitle}</h2><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href={`/${lang}/discover-venice`} className="rounded-full border border-navy px-6 py-3 font-bold text-navy">{t.venice}</Link><Link href={`/${lang}/getting-to-venice`} className="rounded-full border border-navy px-6 py-3 font-bold text-navy">{t.transport}</Link><Link href={`/${lang}/journal`} className="rounded-full bg-gold px-7 py-3 font-bold text-navy">{backLabel||t.back}</Link></div></div></section>
 </article></main><Footer lang={lang}/></>;
}
