import Link from 'next/link';
import Image from 'next/image';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SectionTitle from '@/components/SectionTitle';
import WeChatCard from '@/components/WeChatCard';
import type {RichPageData} from '@/components/LocalizedRich';
type Lang='de'|'fr'|'es'|'zh';
const home={de:'Startseite',fr:'Accueil',es:'Inicio',zh:'首页'} as const;
const exp={
 de:{eyebrow:'Auswahl in Arbeit',title:'Verlässliche Erlebnisse, sorgfältig ausgewählt.',text:'Dieser Bereich ist für echte lokale Partnerschaften vorbereitet. Partner, Rabatte oder Angebote werden erst veröffentlicht, wenn sie vereinbart und geprüft wurden.',cat:'Kategorien',catTitle:'Was wir unseren Gästen anbieten möchten',catText:'Eine kleine Auswahl nützlicher Services mit klaren Informationen.',pending:'Partner werden derzeit ausgewählt',criteria:'Unsere Kriterien',criteriaTitle:'So wählen wir eine Partnerschaft aus',criteriaItems:['Echte Servicequalität und klare Kommunikation.','Preise und Bedingungen vor der Buchung transparent.','Unterstützung, falls sich Pläne ändern oder Probleme auftreten.','Respekt für das Reiseziel und verantwortungsvolle Mobilität.'],operator:'Sind Sie ein lokaler Anbieter?',operatorTitle:'Partnerschaft vorschlagen',operatorText:'Diese Seite ist für geprüfte Partner vorbereitet und behauptet keine Vereinbarungen, die noch nicht bestehen.',contact:'Kontakt aufnehmen'},
 fr:{eyebrow:'Sélection en cours',title:'Des expériences fiables, choisies avec soin.',text:'Cette section est prête à accueillir de véritables partenariats locaux. Aucun partenaire, avantage ou offre ne sera publié avant d’avoir été convenu et vérifié.',cat:'Catégories',catTitle:'Ce que nous souhaitons proposer à nos hôtes',catText:'Une petite sélection de services utiles, avec des informations claires.',pending:'Partenaires en cours de sélection',criteria:'Nos critères',criteriaTitle:'Comment nous choisissons un partenariat',criteriaItems:['Qualité réelle du service et communication claire.','Prix et conditions annoncés avant la réservation.','Assistance disponible en cas de changement ou de problème.','Respect de la destination et mobilité responsable.'],operator:'Vous êtes un opérateur local ?',operatorTitle:'Proposer un partenariat',operatorText:'Cette page est prête à présenter des partenaires vérifiés, sans annoncer d’accord qui n’existe pas encore.',contact:'Nous contacter'},
 es:{eyebrow:'Selección en curso',title:'Experiencias fiables, elegidas con cuidado.',text:'Esta sección está preparada para colaboraciones locales reales. No publicaremos socios, descuentos u ofertas hasta que estén acordados y verificados.',cat:'Categorías',catTitle:'Lo que queremos ofrecer a nuestros huéspedes',catText:'Una pequeña selección de servicios útiles con información clara.',pending:'Colaboradores en proceso de selección',criteria:'Nuestros criterios',criteriaTitle:'Cómo elegimos una colaboración',criteriaItems:['Calidad real del servicio y comunicación clara.','Precios y condiciones indicados antes de reservar.','Asistencia si cambian los planes o surge un problema.','Respeto por el destino y movilidad responsable.'],operator:'¿Eres un operador local?',operatorTitle:'Proponer una colaboración',operatorText:'Esta página está preparada para mostrar colaboradores verificados, sin anunciar acuerdos que todavía no existan.',contact:'Contactar'},
 zh:{eyebrow:'正在筛选',title:'认真筛选值得信赖的旅行体验。',text:'此页面为真实的本地合作预留。只有在合作内容、价格和条件确认并核实之后，我们才会公开推荐。',cat:'体验类别',catTitle:'我们希望为客人提供什么',catText:'精选少量真正有用的服务，并清楚说明相关信息。',pending:'合作伙伴正在筛选中',criteria:'我们的标准',criteriaTitle:'我们如何选择合作伙伴',criteriaItems:['真实的服务质量和清晰沟通。','预订前明确说明价格和条件。','计划变化或出现问题时能够提供支持。','尊重目的地并重视负责任的出行方式。'],operator:'您是本地服务商吗？',operatorTitle:'提出合作建议',operatorText:'本页面用于展示经过核实的合作伙伴，不会宣称尚未达成的合作关系。',contact:'联系我们'}
} as const;
const useful={
 de:{eyebrow:'Offizielle Quellen',text:'Eine kleine Sammlung offizieller Websites für Verkehr, Tarife, Veranstaltungen, Museen und Services vor und während Ihres Aufenthalts.',resource:'Offizielle Ressourcen',visit:'Offizielle Website öffnen',groups:[
  {title:'Verkehr & Mobilität',text:'Fahrpläne, Tickets, Flughäfen und Verbindungen.',links:[['AVM / ACTV','Öffentlicher Verkehr und Mobilitätsdienste in Venedig.','https://avm.avmspa.it/'],['Venezia Unica','Offizielle touristische Services, Tickets und Pässe.','https://www.veneziaunica.it/'],['Trenitalia','Zugfahrpläne und Tickets.','https://www.trenitalia.com/'],['ATVO','Flughafen- und regionale Busverbindungen.','https://www.atvo.it/'],['RadioTaxi Venezia','Taxi-Informationen und Services in Venedig und auf dem Festland.','https://www.radiotaxivenezia.com/']]},
  {title:'Venedig: offizielle Informationen',text:'Quellen für Besucherinformationen, Regeln, Veranstaltungen und städtische Services.',links:[['Stadt Venedig','Institutionelle Informationen und Services.','https://www.comune.venezia.it/'],['Venezia Unica','Offizielle Informationen und Services für Besucher.','https://www.veneziaunica.it/'],['Karneval in Venedig','Offizielles Programm und Informationen zur aktuellen Ausgabe.','https://carnevale.venezia.it/']]},
  {title:'Kunst, Museen & Veranstaltungen',text:'Ausstellungen, Tickets, Programme und Öffnungszeiten prüfen.',links:[['La Biennale di Venezia','Kunst, Architektur, Film, Tanz, Musik und Theater.','https://www.labiennale.org/'],['MUVE – Städtische Museen Venedigs','Museen, Tickets, Ausstellungen und Besucherinformationen.','https://www.visitmuve.it/'],['Naturhistorisches Museum','Offizielle Informationen zum Museo di Storia Naturale Giancarlo Ligabue.','https://msn.visitmuve.it/']]},
  {title:'Venetien & Kulturerbe',text:'Entdecken Sie die Region, ihre Kultur und ihr Erbe über Venedig hinaus.',links:[['Veneto.eu','Offizielles Tourismusportal der Region Venetien.','https://www.veneto.eu/'],['UNESCO – Venedig und seine Lagune','Eintrag in die UNESCO-Welterbeliste.','https://whc.unesco.org/en/list/394/']]}
 ]},
 fr:{eyebrow:'Sources officielles',text:'Une petite sélection de sites officiels pour vérifier transports, tarifs, événements, musées et services avant et pendant votre séjour.',resource:'Ressources officielles',visit:'Ouvrir le site officiel',groups:[
  {title:'Transports & mobilité',text:'Horaires, billets, aéroports et liaisons.',links:[['AVM / ACTV','Transports publics et services de mobilité à Venise.','https://avm.avmspa.it/'],['Venezia Unica','Services touristiques officiels, billets et pass de transport.','https://www.veneziaunica.it/'],['Trenitalia','Horaires et billets de train.','https://www.trenitalia.com/'],['ATVO','Liaisons en bus avec les aéroports et la région.','https://www.atvo.it/'],['RadioTaxi Venezia','Informations et services de taxi à Venise et sur la terre ferme.','https://www.radiotaxivenezia.com/']]},
  {title:'Venise : informations officielles',text:'Sources pour les visiteurs, les règles, les événements et les services de la ville.',links:[['Ville de Venise','Informations institutionnelles et services.','https://www.comune.venezia.it/'],['Venezia Unica','Informations et services officiels pour les visiteurs.','https://www.veneziaunica.it/'],['Carnaval de Venise','Programme officiel et informations sur l’édition en cours.','https://carnevale.venezia.it/']]},
  {title:'Art, musées & événements',text:'Vérifiez expositions, billets, programmes et horaires d’ouverture.',links:[['La Biennale di Venezia','Art, architecture, cinéma, danse, musique et théâtre.','https://www.labiennale.org/'],['MUVE – Musées civiques de Venise','Musées, billets, expositions et informations de visite.','https://www.visitmuve.it/'],['Musée d’Histoire naturelle','Informations officielles sur le musée Giancarlo Ligabue.','https://msn.visitmuve.it/']]},
  {title:'Vénétie & patrimoine',text:'Explorez la région, sa culture et son patrimoine au-delà de Venise.',links:[['Veneto.eu','Portail touristique officiel de la Région Vénétie.','https://www.veneto.eu/'],['UNESCO – Venise et sa lagune','Inscription au patrimoine mondial de l’UNESCO.','https://whc.unesco.org/en/list/394/']]}
 ]},
 es:{eyebrow:'Fuentes oficiales',text:'Una pequeña selección de webs oficiales para consultar transporte, tarifas, eventos, museos y servicios antes y durante la estancia.',resource:'Recursos oficiales',visit:'Abrir web oficial',groups:[
  {title:'Transporte y movilidad',text:'Horarios, billetes, aeropuertos y conexiones.',links:[['AVM / ACTV','Transporte público y servicios de movilidad en Venecia.','https://avm.avmspa.it/'],['Venezia Unica','Servicios turísticos oficiales, billetes y pases de transporte.','https://www.veneziaunica.it/'],['Trenitalia','Horarios y billetes de tren.','https://www.trenitalia.com/'],['ATVO','Autobuses de aeropuerto y conexiones regionales.','https://www.atvo.it/'],['RadioTaxi Venezia','Información y servicios de taxi en Venecia y tierra firme.','https://www.radiotaxivenezia.com/']]},
  {title:'Venecia: información oficial',text:'Fuentes para visitantes, normas, eventos y servicios municipales.',links:[['Ayuntamiento de Venecia','Información institucional y servicios.','https://www.comune.venezia.it/'],['Venezia Unica','Información y servicios oficiales para visitantes.','https://www.veneziaunica.it/'],['Carnaval de Venecia','Programa oficial e información de la edición actual.','https://carnevale.venezia.it/']]},
  {title:'Arte, museos y eventos',text:'Consulta exposiciones, entradas, programas y horarios de apertura.',links:[['La Biennale di Venezia','Arte, arquitectura, cine, danza, música y teatro.','https://www.labiennale.org/'],['MUVE – Museos Cívicos de Venecia','Museos, entradas, exposiciones e información para visitantes.','https://www.visitmuve.it/'],['Museo de Historia Natural','Información oficial del museo Giancarlo Ligabue.','https://msn.visitmuve.it/']]},
  {title:'Véneto y patrimonio',text:'Explora la región, su cultura y su patrimonio más allá de Venecia.',links:[['Veneto.eu','Portal turístico oficial de la Región del Véneto.','https://www.veneto.eu/'],['UNESCO – Venecia y su laguna','Ficha del Patrimonio Mundial de la UNESCO.','https://whc.unesco.org/en/list/394/']]}
 ]},
 zh:{eyebrow:'官方来源',text:'精选官方信息网站，方便您在入住前和住宿期间查询交通、票价、活动、博物馆和城市服务。',resource:'官方资源',visit:'打开官方网站',groups:[
  {title:'交通与出行',text:'时刻表、车票、机场与交通连接。',links:[['AVM / ACTV','威尼斯公共交通与城市出行服务。','https://avm.avmspa.it/'],['Venezia Unica','官方旅游服务、公共交通车票与通票。','https://www.veneziaunica.it/'],['Trenitalia','火车时刻与购票。','https://www.trenitalia.com/'],['ATVO','机场及区域巴士服务。','https://www.atvo.it/'],['RadioTaxi Venezia','威尼斯及陆地区域出租车信息与服务。','https://www.radiotaxivenezia.com/']]},
  {title:'威尼斯官方信息',text:'游客信息、城市规则、活动与公共服务的官方来源。',links:[['威尼斯市政府','市政机构信息与服务。','https://www.comune.venezia.it/'],['Venezia Unica','面向游客的官方信息与服务。','https://www.veneziaunica.it/'],['威尼斯狂欢节','当前届次的官方日程与信息。','https://carnevale.venezia.it/']]},
  {title:'艺术、博物馆与活动',text:'查询展览、门票、节目和开放信息。',links:[['La Biennale di Venezia','艺术、建筑、电影、舞蹈、音乐与戏剧。','https://www.labiennale.org/'],['MUVE – 威尼斯市立博物馆','博物馆、门票、展览及参观信息。','https://www.visitmuve.it/'],['自然历史博物馆','Giancarlo Ligabue 自然历史博物馆官方信息。','https://msn.visitmuve.it/']]},
  {title:'威尼托与文化遗产',text:'从威尼斯出发，继续了解威尼托地区的文化与遗产。',links:[['Veneto.eu','威尼托大区官方旅游门户。','https://www.veneto.eu/'],['UNESCO – 威尼斯及其泻湖','联合国教科文组织世界遗产页面。','https://whc.unesco.org/en/list/394/']]}
 ]}
} as const;
export function LocalizedExperiencesPage({lang,data}:{lang:Lang;data:RichPageData}){const t=exp[lang],cards=data.sections.flatMap(s=>s.cards||[]);return <><Header lang={lang}/><main><section className="bg-navy px-5 pb-20 pt-36 text-white lg:px-8"><div className="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap gap-2 text-sm text-white/70"><Link href={`/${lang}`}>{home[lang]}</Link><span>›</span><span className="text-gold">{data.title}</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.eyebrow}</p><h1 className="mt-4 max-w-5xl break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{t.title}</h1><p className="mt-6 max-w-3xl text-xl text-white/75">{t.text}</p></div></section><section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={t.cat} title={t.catTitle} text={t.catText}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{cards.map(c=><article key={c.title} className="group overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-soft">{c.image&&<div className="relative h-64 overflow-hidden"><Image src={c.image} alt={c.alt||c.title} fill sizes="(min-width:1280px) 33vw, (min-width:768px) 50vw, 100vw" className="object-cover object-center transition duration-500 group-hover:scale-[1.03]"/></div>}<div className="p-8"><div className="text-2xl text-gold">✦</div><h2 className="mt-4 font-serif text-3xl text-navy">{c.title}</h2><p className="mt-3 text-slate-600">{c.text}</p>{c.href?<Link href={c.href} className="mt-6 inline-flex rounded-full bg-gold px-5 py-3 font-bold text-navy">{c.label||'→'}</Link>:<p className="mt-6 rounded-2xl bg-cream p-4 text-sm font-semibold text-navy">{t.pending}</p>}</div></article>)}</div></div></section><section className="bg-cream py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-2 lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.criteria}</p><h2 className="mt-3 font-serif text-5xl text-navy">{t.criteriaTitle}</h2><div className="mt-7 space-y-4 text-lg text-slate-600">{t.criteriaItems.map(x=><p key={x}>{x}</p>)}</div></div><aside className="rounded-[2rem] bg-navy p-8 text-white"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.operator}</p><h2 className="mt-3 font-serif text-4xl">{t.operatorTitle}</h2><p className="mt-5 text-white/75">{t.operatorText}</p>{lang==='zh'?<div className="mt-7"><WeChatCard dark title={t.contact}/></div>:<a href="https://wa.me/393514462261" target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex rounded-full bg-gold px-6 py-4 font-bold text-navy">{t.contact} ↗</a>}</aside></div></section></main><Footer lang={lang}/></>}
export function LocalizedUsefulLinksPage({lang,data}:{lang:Lang;data:RichPageData}){const t=useful[lang];return <><Header lang={lang}/><main><section className="bg-navy px-5 pb-20 pt-36 text-white lg:px-8"><div className="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap gap-2 text-sm text-white/70"><Link href={`/${lang}`}>{home[lang]}</Link><span>›</span><span className="text-gold">{data.title}</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.eyebrow}</p><h1 className="mt-4 max-w-4xl break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{data.title}</h1><p className="mt-6 max-w-3xl text-xl text-white/75">{t.text}</p></div></section><section className="bg-cream py-20"><div className="mx-auto max-w-7xl space-y-14 px-5 lg:px-8">{t.groups.map(group=><section key={group.title}><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{t.resource}</p><h2 className="mt-2 break-words font-serif text-4xl text-navy md:text-5xl">{group.title}</h2><p className="mt-3 max-w-3xl text-slate-600">{group.text}</p><div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{group.links.map(([name,desc,href])=><a key={name+href} href={href} target="_blank" rel="noopener noreferrer" className="group rounded-[2rem] bg-white p-7 shadow-soft transition hover:-translate-y-1"><h3 className="break-words font-serif text-3xl text-navy">{name}</h3><p className="mt-3 text-slate-600">{desc}</p><span className="mt-5 inline-block font-bold text-gold">{t.visit} ↗</span></a>)}</div></section>)}</div></section></main><Footer lang={lang}/></>}
