import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SectionTitle from '@/components/SectionTitle';
import WeChatCard from '@/components/WeChatCard';

type Lang='de'|'fr'|'es'|'zh';
export type RichCard={title:string;text:string;image?:string;alt?:string;href?:string;label?:string};
export type RichSection={eyebrow?:string;title:string;text?:string;image?:string;alt?:string;cards?:RichCard[];links?:[string,string][]};
export type RichPageData={title:string;subtitle:string;hero:string;heroAlt:string;sections:RichSection[]};

const home:Record<Lang,string>={de:'Startseite',fr:'Accueil',es:'Inicio',zh:'首页'};
const contact:Record<Lang,{eyebrow:string,title:string,text:string,button:string,message:string}>={
 de:{eyebrow:'DIREKTER KONTAKT',title:'Erzählen Sie uns von Ihrer Reise',text:'Senden Sie uns Ihre Reisedaten und die Anzahl der Gäste. Wir antworten persönlich mit Verfügbarkeit und allen wichtigen Informationen.',button:'Verfügbarkeit prüfen',message:'Hallo, ich möchte die Verfügbarkeit der Marghera Venice Apartments prüfen. Meine Reisedaten sind: '},
 fr:{eyebrow:'CONTACT DIRECT',title:'Parlez-nous de votre voyage',text:'Envoyez-nous vos dates et le nombre de voyageurs. Nous vous répondrons personnellement avec les disponibilités et les informations utiles.',button:'Vérifier les disponibilités',message:'Bonjour, je souhaite vérifier les disponibilités de Marghera Venice Apartments. Mes dates sont : '},
 es:{eyebrow:'CONTACTO DIRECTO',title:'Cuéntanos tu viaje',text:'Envíanos tus fechas y el número de huéspedes. Te responderemos personalmente con disponibilidad e información útil.',button:'Comprobar disponibilidad',message:'Hola, me gustaría comprobar la disponibilidad de Marghera Venice Apartments. Mis fechas son: '},
 zh:{eyebrow:'直接联系',title:'告诉我们您的旅行计划',text:'请通过微信告诉我们入住日期和人数，我们会亲自回复可订情况以及入住所需的信息。',button:'微信联系我们',message:''}
};

export function LocalizedRichPage({lang,data}:{lang:Lang;data:RichPageData}){
 const c=contact[lang];
 return <><Header lang={lang}/><main>
  <section className="relative min-h-[72vh] overflow-hidden pt-20">
   <Image src={data.hero} alt={data.heroAlt} fill priority sizes="100vw" className="object-cover"/>
   <div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/75 to-navy/20"/>
   <div className="relative mx-auto flex min-h-[calc(72vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-20 lg:px-8"><div className="max-w-4xl text-white">
    <Link href={`/${lang}`} className="text-sm text-white/75">{home[lang]}</Link>
    <h1 className="mt-5 break-words font-serif text-5xl leading-[.98] sm:text-6xl md:text-8xl">{data.title}</h1>
    <p className="mt-6 max-w-3xl text-xl text-white/85">{data.subtitle}</p>
   </div></div>
  </section>
  {data.sections.map((s,i)=><section key={s.title} className={i%2?'bg-cream py-20':'py-20'}><div className="mx-auto max-w-7xl px-5 lg:px-8">
   <SectionTitle eyebrow={s.eyebrow||''} title={s.title} text={s.text||''}/>
   {s.image&&<div className="relative mt-10 h-[300px] overflow-hidden rounded-[2rem] shadow-soft sm:h-[420px]"><Image src={s.image} alt={s.alt||s.title} fill sizes="100vw" className="object-cover"/></div>}
   {s.cards&&<div className="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{s.cards.map(card=><article key={card.title} className="overflow-hidden rounded-[2rem] bg-white shadow-soft">
    {card.image&&<div className="relative h-60 overflow-hidden"><Image src={card.image} alt={card.alt||card.title} fill sizes="(min-width:1280px) 33vw, (min-width:768px) 50vw, 100vw" className="object-cover"/></div>}
    <div className="p-7"><h2 className="font-serif text-3xl text-navy">{card.title}</h2><p className="mt-3 leading-7 text-slate-600">{card.text}</p>{card.href&&<Link href={card.href} className="mt-6 inline-flex rounded-full bg-gold px-5 py-3 font-bold text-navy">{card.label||'→'}</Link>}</div>
   </article>)}</div>}
   {s.links&&<div className="mt-9 flex flex-wrap gap-3">{s.links.map(([label,href])=>href.startsWith('http')?<a key={href} href={href} target="_blank" rel="noopener noreferrer" className="rounded-full border border-navy px-6 py-3 font-bold text-navy hover:bg-navy hover:text-white">{label} ↗</a>:<Link key={href} href={href} className="rounded-full border border-navy px-6 py-3 font-bold text-navy hover:bg-navy hover:text-white">{label}</Link>)}</div>}
  </div></section>)}
  <section id="direct-contact" className="bg-navy py-20 text-white"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.28em] text-gold">{c.eyebrow}</p><h2 className="mt-4 font-serif text-4xl sm:text-6xl">{c.title}</h2><p className="mx-auto mt-6 max-w-3xl text-lg text-white/80">{c.text}</p>{lang==='zh'?<div className="mt-10"><WeChatCard dark title="添加我们的微信"/></div>:<a href={`https://wa.me/393514462261?text=${encodeURIComponent(c.message)}`} target="_blank" rel="noopener noreferrer" className="mt-9 inline-flex rounded-full bg-gold px-8 py-4 font-bold text-navy">{c.button}</a>}</div></section>
 </main><Footer lang={lang}/></>;
}

export type ApartmentData={name:string;subtitle:string;hero:string;heroAlt:string;guests:string;stats:[string,string,string][];gallery:[string,string][];livingTitle:string;living:string[];services:string[];transportTitle:string;transportText:string;transportHref:string;transportLabel:string;cta:string;message:string};
export function LocalizedApartment({lang,data}:{lang:Lang;data:ApartmentData}){
 return <><Header lang={lang}/><main><section className="relative min-h-[78vh] overflow-hidden pt-20"><Image src={data.hero} alt={data.heroAlt} fill priority sizes="100vw" className="object-cover"/><div className="hero-overlay absolute inset-0"/><div className="relative mx-auto flex min-h-[calc(78vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-24 lg:px-8"><div className="max-w-4xl text-white"><Link href={`/${lang}`} className="text-sm text-white/75">{home[lang]}</Link><p className="mt-6 text-xs font-black uppercase tracking-[.25em] text-gold">{data.guests} · Marghera</p><h1 className="mt-4 font-serif text-6xl md:text-8xl">{data.name}</h1><p className="mt-6 max-w-2xl text-xl text-white/85">{data.subtitle}</p><a href={lang==='zh'?'/zh/#direct-contact':`https://wa.me/393514462261?text=${encodeURIComponent(data.message)}`} target={lang==='zh'?undefined:'_blank'} rel={lang==='zh'?undefined:'noopener noreferrer'} className="mt-8 inline-flex rounded-full bg-gold px-7 py-4 font-bold text-navy">{data.cta}</a></div></div></section>
 <section className="bg-cream py-10"><div className="mx-auto grid max-w-7xl gap-4 px-5 md:grid-cols-3 lg:px-8">{data.stats.map(([v,t,x])=><div key={t} className="rounded-2xl bg-white p-6 shadow-soft"><div className="text-3xl font-black text-gold">{v}</div><h2 className="mt-2 font-serif text-2xl text-navy">{t}</h2><p className="mt-2 text-slate-600">{x}</p></div>)}</div></section>
 <section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.name} title={data.livingTitle} text={data.subtitle}/><div className="grid gap-4 lg:grid-cols-12">{data.gallery.map(([src,alt],i)=><div key={src} className={`relative overflow-hidden rounded-3xl ${i===0?'h-[360px] lg:col-span-7 lg:row-span-2 lg:h-[500px]':'h-[240px] lg:col-span-5'}`}><Image src={src} alt={alt} fill sizes="(min-width:1024px) 55vw, 100vw" className="object-cover"/></div>)}</div></div></section>
 <section className="bg-cream py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:px-8"><div><h2 className="font-serif text-5xl text-navy">{data.livingTitle}</h2><div className="mt-7 space-y-5 text-lg leading-8 text-slate-600">{data.living.map(x=><p key={x}>{x}</p>)}</div></div><div><h2 className="font-serif text-5xl text-navy">Services</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{data.services.map(x=><div key={x} className="rounded-2xl bg-white p-4 font-semibold text-navy shadow-soft">✓ {x}</div>)}</div></div></div></section>
 <section className="py-20"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><h2 className="font-serif text-5xl text-navy">{data.transportTitle}</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-slate-600">{data.transportText}</p><Link href={data.transportHref} className="mt-8 inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white">{data.transportLabel}</Link></div></section>
 </main><Footer lang={lang}/></>;
}

export type GuideIndexItem={title:string;subtitle:string;text:string;image:string;alt:string;slug:string};
export function LocalizedGuideIndex({lang,title,subtitle,items,openLabel}:{lang:Lang;title:string;subtitle:string;items:GuideIndexItem[];openLabel:string}){return <><Header lang={lang}/><main><section className="bg-navy px-5 pb-20 pt-36 text-white lg:px-8"><div className="mx-auto max-w-7xl"><Link href={`/${lang}`} className="text-sm text-white/70">{home[lang]}</Link><p className="mt-6 text-xs font-black uppercase tracking-[.22em] text-gold">Marghera Venice Guide</p><h1 className="mt-4 max-w-5xl font-serif text-6xl leading-none md:text-8xl">{title}</h1><p className="mt-6 max-w-3xl text-xl text-white/75">{subtitle}</p></div></section><section className="bg-cream py-24"><div className="mx-auto grid max-w-7xl gap-8 px-5 lg:grid-cols-2 lg:px-8">{items.map(g=><article key={g.slug} className="overflow-hidden rounded-[2rem] bg-white shadow-soft"><div className="relative h-72"><Image src={g.image} alt={g.alt} fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover"/></div><div className="p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{g.subtitle}</p><h2 className="mt-3 font-serif text-4xl text-navy">{g.title}</h2><p className="mt-4 text-lg text-slate-600">{g.text}</p><Link href={`/${lang}/guide/${g.slug}`} className="mt-7 inline-flex rounded-full bg-gold px-6 py-3 font-bold text-navy">{openLabel}</Link></div></article>)}</div></section></main><Footer lang={lang}/></>}

export type JournalItem={slug:string;title:string;category:string;description:string;image:string;imageAlt:string};
export function LocalizedJournalIndex({lang,title,subtitle,items,readLabel,guideLabel}:{lang:Lang;title:string;subtitle:string;items:JournalItem[];readLabel:string;guideLabel:string}){return <><Header lang={lang}/><main><section className="bg-navy px-5 pb-20 pt-36 text-white lg:px-8"><div className="mx-auto max-w-7xl"><Link href={`/${lang}`} className="text-sm text-white/70">{home[lang]}</Link><p className="mt-6 text-xs font-black uppercase tracking-[.22em] text-gold">Journal</p><h1 className="mt-4 max-w-5xl font-serif text-6xl leading-none md:text-8xl">{title}</h1><p className="mt-6 max-w-3xl text-xl text-white/75">{subtitle}</p></div></section><section className="bg-cream py-24"><div className="mx-auto grid max-w-7xl gap-7 px-5 md:grid-cols-2 xl:grid-cols-3 lg:px-8">{items.map(a=><article key={a.slug} className="overflow-hidden rounded-[2rem] bg-white shadow-soft"><Link href={`/${lang}/journal/${a.slug}`} className="block"><div className="relative h-64"><Image src={a.image} alt={a.imageAlt} fill sizes="(min-width:1280px) 33vw, (min-width:768px) 50vw, 100vw" className="object-cover"/></div><div className="p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{a.category}</p><h2 className="mt-3 font-serif text-4xl text-navy">{a.title}</h2><p className="mt-4 text-slate-600">{a.description}</p><span className="mt-6 inline-flex rounded-full bg-gold px-5 py-3 font-bold text-navy">{readLabel}</span></div></Link></article>)}</div></section><section className="py-20"><div className="mx-auto max-w-5xl px-5 text-center"><Link href={`/${lang}/guide`} className="inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white">{guideLabel}</Link></div></section></main><Footer lang={lang}/></>}

export type JournalArticleData=JournalItem&{lead:string;sections:[string,string][];tip:string;official?:[string,string]};
export function LocalizedJournalArticle({lang,data,tipLabel,officialLabel,backLabel}:{lang:Lang;data:JournalArticleData;tipLabel:string;officialLabel:string;backLabel:string}){return <><Header lang={lang}/><main><article><section className="relative min-h-[72vh] overflow-hidden pt-20"><Image src={data.image} alt={data.imageAlt} fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/75 to-navy/20"/><div className="relative mx-auto flex min-h-[calc(72vh-5rem)] max-w-7xl items-end px-5 pb-16 lg:px-8"><div className="max-w-4xl text-white"><Link href={`/${lang}/journal`} className="text-sm text-white/70">Journal</Link><p className="mt-5 text-xs font-black uppercase tracking-[.22em] text-gold">{data.category}</p><h1 className="mt-4 font-serif text-6xl leading-none md:text-8xl">{data.title}</h1><p className="mt-6 max-w-3xl text-xl text-white/80">{data.description}</p></div></div></section><section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><p className="font-serif text-3xl leading-relaxed text-navy">{data.lead}</p><div className="mt-14 space-y-12">{data.sections.map(([t,x],i)=><section key={t} className="grid gap-5 md:grid-cols-[70px_1fr]"><div className="font-serif text-5xl text-gold">{String(i+1).padStart(2,'0')}</div><div><h2 className="font-serif text-4xl text-navy">{t}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{x}</p></div></section>)}</div><div className="mt-14 rounded-[2rem] bg-gold p-8 text-navy"><p className="text-xs font-black uppercase tracking-[.2em]">{tipLabel}</p><p className="mt-4 font-serif text-3xl">{data.tip}</p></div>{data.official&&<div className="mt-8 rounded-[2rem] bg-cream p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{officialLabel}</p><a href={data.official[1]} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex rounded-full bg-navy px-6 py-3 font-bold text-white">{data.official[0]} ↗</a></div>}<div className="mt-12"><Link href={`/${lang}/journal`} className="inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white">← {backLabel}</Link></div></div></section></article></main><Footer lang={lang}/></>}
