import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SectionTitle from '@/components/SectionTitle';
import WeChatCard from '@/components/WeChatCard';
import type {RichPageData} from '@/components/LocalizedRich';
type Lang='de'|'fr'|'es'|'zh';
const home={de:'Startseite',fr:'Accueil',es:'Inicio',zh:'首页'} as const;
const exp={
 de:{eyebrow:'Auswahl in Arbeit',title:'Verlässliche Erlebnisse, sorgfältig ausgewählt.',text:'Dieser Bereich ist für echte lokale Partnerschaften vorbereitet. Partner, Rabatte oder Angebote werden erst veröffentlicht, wenn sie vereinbart und geprüft wurden.',cat:'Kategorien',catTitle:'Was wir unseren Gästen anbieten möchten',catText:'Eine kleine Auswahl nützlicher Services mit klaren Informationen.',pending:'Partner werden derzeit ausgewählt',criteria:'Unsere Kriterien',criteriaTitle:'So wählen wir eine Partnerschaft aus',criteriaItems:['Echte Servicequalität und klare Kommunikation.','Preise und Bedingungen vor der Buchung transparent.','Unterstützung, falls sich Pläne ändern oder Probleme auftreten.','Respekt für das Reiseziel und verantwortungsvolle Mobilität.'],operator:'Sind Sie ein lokaler Anbieter?',operatorTitle:'Partnerschaft vorschlagen',operatorText:'Diese Seite ist für geprüfte Partner vorbereitet und behauptet keine Vereinbarungen, die noch nicht bestehen.',contact:'Kontakt aufnehmen'},
 fr:{eyebrow:'Sélection en cours',title:'Des expériences fiables, choisies avec soin.',text:'Cette section est prête à accueillir de véritables partenariats locaux. Aucun partenaire, avantage ou offre ne sera publié avant d’avoir été convenu et vérifié.',cat:'Catégories',catTitle:'Ce que nous souhaitons proposer à nos hôtes',catText:'Une petite sélection de services utiles, avec des informations claires.',pending:'Partenaires en cours de sélection',criteria:'Nos critères',criteriaTitle:'Comment nous choisissons un partenariat',criteriaItems:['Qualité réelle du service et communication claire.','Prix et conditions annoncés avant la réservation.','Assistance disponible en cas de changement ou de problème.','Respect de la destination et mobilité responsable.'],operator:'Vous êtes un opérateur local ?',operatorTitle:'Proposer un partenariat',operatorText:'Cette page est prête à présenter des partenaires vérifiés, sans annoncer d’accord qui n’existe pas encore.',contact:'Nous contacter'},
 es:{eyebrow:'Selección en curso',title:'Experiencias fiables, elegidas con cuidado.',text:'Esta sección está preparada para colaboraciones locales reales. No publicaremos socios, descuentos u ofertas hasta que estén acordados y verificados.',cat:'Categorías',catTitle:'Lo que queremos ofrecer a nuestros huéspedes',catText:'Una pequeña selección de servicios útiles con información clara.',pending:'Colaboradores en proceso de selección',criteria:'Nuestros criterios',criteriaTitle:'Cómo elegimos una colaboración',criteriaItems:['Calidad real del servicio y comunicación clara.','Precios y condiciones indicados antes de reservar.','Asistencia si cambian los planes o surge un problema.','Respeto por el destino y movilidad responsable.'],operator:'¿Eres un operador local?',operatorTitle:'Proponer una colaboración',operatorText:'Esta página está preparada para mostrar colaboradores verificados, sin anunciar acuerdos que todavía no existan.',contact:'Contactar'},
 zh:{eyebrow:'正在筛选',title:'认真筛选值得信赖的旅行体验。',text:'此页面为真实的本地合作预留。只有在合作内容、价格和条件确认并核实之后，我们才会公开推荐。',cat:'体验类别',catTitle:'我们希望为客人提供什么',catText:'精选少量真正有用的服务，并清楚说明相关信息。',pending:'合作伙伴正在筛选中',criteria:'我们的标准',criteriaTitle:'我们如何选择合作伙伴',criteriaItems:['真实的服务质量和清晰沟通。','预订前明确说明价格和条件。','计划变化或出现问题时能够提供支持。','尊重目的地并重视负责任的出行方式。'],operator:'您是本地服务商吗？',operatorTitle:'提出合作建议',operatorText:'本页面用于展示经过核实的合作伙伴，不会宣称尚未达成的合作关系。',contact:'联系我们'}
} as const;
const useful={
 de:{eyebrow:'Offizielle Quellen',text:'Eine kleine Sammlung offizieller Websites für Verkehr, Tarife, Veranstaltungen, Museen und Services vor und während Ihres Aufenthalts.',resource:'Offizielle Ressourcen',visit:'Offizielle Website öffnen'},
 fr:{eyebrow:'Sources officielles',text:'Une petite sélection de sites officiels pour vérifier transports, tarifs, événements, musées et services avant et pendant votre séjour.',resource:'Ressources officielles',visit:'Ouvrir le site officiel'},
 es:{eyebrow:'Fuentes oficiales',text:'Una pequeña selección de webs oficiales para consultar transporte, tarifas, eventos, museos y servicios antes y durante la estancia.',resource:'Recursos oficiales',visit:'Abrir web oficial'},
 zh:{eyebrow:'官方来源',text:'精选官方信息网站，方便您在入住前和住宿期间查询交通、票价、活动、博物馆和城市服务。',resource:'官方资源',visit:'打开官方网站'}
} as const;
export function LocalizedExperiencesPage({lang,data}:{lang:Lang;data:RichPageData}){const t=exp[lang],cards=data.sections.flatMap(s=>s.cards||[]);return <><Header lang={lang}/><main><section className="bg-navy px-5 pb-20 pt-36 text-white lg:px-8"><div className="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap gap-2 text-sm text-white/70"><Link href={`/${lang}`}>{home[lang]}</Link><span>›</span><span className="text-gold">{data.title}</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.eyebrow}</p><h1 className="mt-4 max-w-5xl break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{t.title}</h1><p className="mt-6 max-w-3xl text-xl text-white/75">{t.text}</p></div></section><section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={t.cat} title={t.catTitle} text={t.catText}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{cards.map(c=><article key={c.title} className="rounded-[2rem] border border-slate-200 bg-white p-8 shadow-soft"><div className="text-2xl text-gold">✦</div><h2 className="mt-4 font-serif text-3xl text-navy">{c.title}</h2><p className="mt-3 text-slate-600">{c.text}</p><p className="mt-6 rounded-2xl bg-cream p-4 text-sm font-semibold text-navy">{t.pending}</p></article>)}</div></div></section><section className="bg-cream py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-2 lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.criteria}</p><h2 className="mt-3 font-serif text-5xl text-navy">{t.criteriaTitle}</h2><div className="mt-7 space-y-4 text-lg text-slate-600">{t.criteriaItems.map(x=><p key={x}>{x}</p>)}</div></div><aside className="rounded-[2rem] bg-navy p-8 text-white"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.operator}</p><h2 className="mt-3 font-serif text-4xl">{t.operatorTitle}</h2><p className="mt-5 text-white/75">{t.operatorText}</p>{lang==='zh'?<div className="mt-7"><WeChatCard dark title={t.contact}/></div>:<a href="https://wa.me/393514462261" target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex rounded-full bg-gold px-6 py-4 font-bold text-navy">{t.contact} ↗</a>}</aside></div></section></main><Footer lang={lang}/></>}
export function LocalizedUsefulLinksPage({lang,data}:{lang:Lang;data:RichPageData}){const t=useful[lang];return <><Header lang={lang}/><main><section className="bg-navy px-5 pb-20 pt-36 text-white lg:px-8"><div className="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap gap-2 text-sm text-white/70"><Link href={`/${lang}`}>{home[lang]}</Link><span>›</span><span className="text-gold">{data.title}</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.eyebrow}</p><h1 className="mt-4 max-w-4xl break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{data.title}</h1><p className="mt-6 max-w-3xl text-xl text-white/75">{t.text}</p></div></section><section className="bg-cream py-20"><div className="mx-auto max-w-7xl space-y-14 px-5 lg:px-8">{data.sections.map(group=><section key={group.title}><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{t.resource}</p><h2 className="mt-2 font-serif text-4xl text-navy md:text-5xl">{group.title}</h2>{group.text&&<p className="mt-3 max-w-3xl text-slate-600">{group.text}</p>}<div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{(group.links||[]).map(([name,href])=><a key={name+href} href={href} target="_blank" rel="noopener noreferrer" className="group rounded-[2rem] bg-white p-7 shadow-soft transition hover:-translate-y-1"><h3 className="font-serif text-3xl text-navy">{name}</h3><p className="mt-3 text-slate-600">{t.eyebrow}</p><span className="mt-5 inline-block font-bold text-gold">{t.visit} ↗</span></a>)}</div></section>)}</div></section></main><Footer lang={lang}/></>}
