import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SectionTitle from '@/components/SectionTitle';
import WeChatCard from '@/components/WeChatCard';

export type ParityLang='de'|'fr'|'es'|'zh';
export type FAQData={home:string;page:string;eyebrow:string;title:string;subtitle:string;groupNote:string;groups:{title:string;items:[string,string][]}[];ctaTitle:string;ctaText:string;ctaLabel:string;ctaMessage:string};
export function LocalizedFAQFull({lang,data}:{lang:ParityLang;data:FAQData}){return <><Header lang={lang}/><main>
<section className="bg-navy px-5 pb-20 pt-36 text-white lg:px-8"><div className="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap items-center gap-2 text-sm text-white/70"><Link href={`/${lang}`} className="hover:text-gold">{data.home}</Link><span>›</span><span className="text-gold">{data.page}</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.eyebrow}</p><h1 className="mt-4 max-w-5xl break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{data.title}</h1><p className="mt-6 max-w-3xl text-xl text-white/75">{data.subtitle}</p></div></section>
<section className="py-24"><div className="mx-auto max-w-5xl px-5 lg:px-8">{data.groups.map(group=><section key={group.title} className="mb-16"><SectionTitle eyebrow="FAQ" title={group.title} text={data.groupNote}/><div className="space-y-4">{group.items.map(([q,a])=><details key={q} className="group rounded-3xl border border-slate-200 bg-white p-6 shadow-soft"><summary className="flex cursor-pointer list-none items-start justify-between gap-4 font-serif text-2xl text-navy"><span className="min-w-0">{q}</span><span className="shrink-0 text-gold transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 text-slate-600">{a}</p></details>)}</div></section>)}
<div className="rounded-[2rem] bg-gold p-8 text-center text-navy"><h2 className="font-serif text-4xl">{data.ctaTitle}</h2><p className="mx-auto mt-4 max-w-2xl">{data.ctaText}</p>{lang==='zh'?<div className="mt-7"><WeChatCard title={data.ctaLabel}/></div>:<a href={`https://wa.me/393514462261?text=${encodeURIComponent(data.ctaMessage)}`} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white">{data.ctaLabel} ↗</a>}</div></div></section>
</main><Footer lang={lang}/></>}

export type VeniceData={home:string;page:string;heroEyebrow:string;heroTitle:string;heroText:string;heroBtn1:string;heroBtn2:string;transport:{eyebrow:string;title:string;text:string;steps:[string,string,string][];infoTitle:string;infoText:string;infoLabel:string};itinerary:{eyebrow:string;title:string;text:string;items:[string,string,string][]};tips:{eyebrow:string;title:string;text:string;items:[string,string][]};map:{eyebrow:string;title:string;text:string;alt:string};family:{eyebrow:string;title:string;text:string;imageAlt:string;items:[string,string][]};pet:{eyebrow:string;title:string;text:string;items:[string,string][]};islands:{eyebrow:string;title:string;text:string;items:[string,string,string][];linkLabel:string};venetoCta:{eyebrow:string;title:string;text:string;label:string};homes:{eyebrow:string;title:string;text:string;rossi:string;dimora:string}};
export function LocalizedDiscoverVeniceFull({lang,data}:{lang:ParityLang;data:VeniceData}){return <><Header lang={lang}/><main>
<section className="relative min-h-[82vh] overflow-hidden pt-20"><Image src="/images/scopri-venezia-michael-heise.webp" alt={data.page} fill priority sizes="100vw" className="object-cover object-center"/><div className="hero-overlay absolute inset-0"/><div className="relative mx-auto flex min-h-[calc(82vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-24 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-6 flex items-center gap-2 text-sm text-white/75"><Link href={`/${lang}`} className="hover:text-gold">{data.home}</Link><span>›</span><span className="text-gold">{data.page}</span></nav><p className="text-xs font-black uppercase tracking-[.25em] text-gold">{data.heroEyebrow}</p><h1 className="mt-4 break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{data.heroTitle}</h1><p className="mt-6 max-w-3xl text-xl text-white/85">{data.heroText}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#getting-there" className="rounded-full bg-gold px-7 py-4 font-bold text-navy">{data.heroBtn1}</a><a href="#one-day" className="rounded-full border border-white/60 px-7 py-4 font-bold text-white">{data.heroBtn2}</a></div></div></div></section>
<section id="getting-there" className="bg-cream pb-12 pt-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.transport.eyebrow} title={data.transport.title} text={data.transport.text}/><div className="grid gap-5 lg:grid-cols-5">{data.transport.steps.map(([n,t,x])=><article key={n} className="rounded-[2rem] bg-white p-7 shadow-soft"><div className="grid h-12 w-12 place-items-center rounded-full bg-gold font-black text-navy">{n}</div><h2 className="mt-5 font-serif text-3xl text-navy">{t}</h2><p className="mt-3 text-slate-600">{x}</p></article>)}</div><div className="mt-8 rounded-[2rem] border-l-4 border-aqua bg-white p-7 shadow-soft"><p className="font-bold text-navy">{data.transport.infoTitle}</p><p className="mt-2 text-slate-600">{data.transport.infoText}</p><a href="https://avm.avmspa.it/en/content/venice-urban-services-0" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex rounded-full bg-navy px-5 py-3 font-bold text-white">{data.transport.infoLabel} ↗</a></div></div></section>
<section id="one-day" className="pb-20 pt-12"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.itinerary.eyebrow} title={data.itinerary.title} text={data.itinerary.text}/><div className="space-y-5">{data.itinerary.items.map(([time,t,x])=><article key={time} className="grid gap-4 rounded-[2rem] bg-cream p-7 md:grid-cols-[120px_1fr]"><div className="font-black tracking-[.12em] text-gold">{time}</div><div><h2 className="font-serif text-3xl text-navy">{t}</h2><p className="mt-2 text-slate-600">{x}</p></div></article>)}</div></div></section>
<section className="bg-navy py-24 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.tips.eyebrow} title={data.tips.title} text={data.tips.text}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data.tips.items.map(([t,x])=><article key={t} className="rounded-[2rem] bg-white/10 p-8"><div className="text-2xl text-gold">✦</div><h2 className="mt-4 font-serif text-3xl">{t}</h2><p className="mt-3 text-white/70">{x}</p></article>)}</div></div></section>
<section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.map.eyebrow} title={data.map.title} text={data.map.text}/><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-cream shadow-soft"><Image src="/images/mappa-venezia-finale.webp" alt={data.map.alt} width={1408} height={1056} className="h-auto w-full object-contain"/></div></div></section>
<section className="bg-cream py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[1fr_1.1fr] lg:px-8"><div className="relative min-h-[390px] overflow-hidden rounded-[2rem] shadow-soft lg:min-h-[470px]"><Image src="/images/venezia-bambini-campo-nuova.webp" alt={data.family.imageAlt} fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover object-center"/></div><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.family.eyebrow}</p><h2 className="mt-3 font-serif text-5xl text-navy">{data.family.title}</h2><p className="mt-6 text-lg text-slate-600">{data.family.text}</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{data.family.items.map(([t,x])=><article key={t} className="rounded-3xl bg-white p-6 shadow-soft"><h3 className="font-serif text-2xl text-navy">{t}</h3><p className="mt-2 text-sm text-slate-600">{x}</p></article>)}</div></div></div></section>
<section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.pet.eyebrow} title={data.pet.title} text={data.pet.text}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{data.pet.items.map(([t,x])=><article key={t} className="rounded-[2rem] border border-slate-200 bg-white p-7"><h2 className="font-serif text-3xl text-navy">{t}</h2><p className="mt-3 text-slate-600">{x}</p></article>)}</div></div></section>
<section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.islands.eyebrow} title={data.islands.title} text={data.islands.text}/><div className="grid gap-6 lg:grid-cols-3">{data.islands.items.map(([t,x,img])=><article key={t} className="overflow-hidden rounded-[2rem] bg-white shadow-soft"><div className="relative h-64"><Image src={img} alt={t} fill sizes="(min-width:1024px) 33vw, 100vw" className="object-cover"/></div><div className="p-7"><h2 className="font-serif text-4xl text-navy">{t}</h2><p className="mt-3 text-slate-600">{x}</p><a href="https://www.veneziaunica.it/en/things-to-do-in-venice/venice-areas" target="_blank" rel="noopener noreferrer" className="mt-5 inline-block font-bold text-gold">{data.islands.linkLabel} ↗</a></div></article>)}</div></div></section>
<section className="bg-gold py-20 text-navy"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em]">{data.venetoCta.eyebrow}</p><h2 className="mt-4 font-serif text-5xl">{data.venetoCta.title}</h2><p className="mx-auto mt-5 max-w-3xl text-lg text-navy/75">{data.venetoCta.text}</p><Link href={`/${lang}/discover-veneto`} className="mt-8 inline-block rounded-full bg-navy px-8 py-4 font-bold text-white">{data.venetoCta.label}</Link></div></section>
<section className="py-24"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.homes.eyebrow}</p><h2 className="mt-3 font-serif text-5xl text-navy">{data.homes.title}</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-slate-600">{data.homes.text}</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href={`/${lang}/apartments/rossi-apartment`} className="rounded-full bg-gold px-8 py-4 font-bold text-navy">{data.homes.rossi}</Link><Link href={`/${lang}/apartments/dimora-castelli`} className="rounded-full border border-navy px-8 py-4 font-bold text-navy">{data.homes.dimora}</Link></div></div></section>
</main><Footer lang={lang}/></>}

type VenetoTrainCity={name:string;time:string;why:string;sights:string;slug:string};
const venetoTrain:Record<ParityLang,{eyebrow:string;title:string;text:string;openGuide:string;note:string;cities:VenetoTrainCity[]}>={
de:{eyebrow:'Ohne Auto',title:'Kunststädte mit dem Zug erreichbar',text:'Marghera ist auch ohne Auto ein strategischer Ausgangspunkt: Vom Bahnhof Venezia Mestre erreichen Sie mehrere Kunststädte direkt mit dem Zug.',openGuide:'Guide öffnen',note:'Die Fahrzeiten sind Richtwerte und hängen von der Verbindung ab. Prüfen Sie vor der Abfahrt immer den aktuellen Fahrplan.',cities:[
{name:'Padua',time:'ca. 15–30 Min. ab Venezia Mestre',why:'Eine der einfachsten Zugausflüge: Kunst, lebendige Plätze und Stadtleben lassen sich bequem an einem Tag entdecken.',sights:'Scrovegni-Kapelle · Basilika des hl. Antonius · Prato della Valle · Piazza delle Erbe und Piazza della Frutta',slug:'padova'},
{name:'Treviso',time:'ca. 20–30 Min. ab Venezia Mestre',why:'Kompakt, elegant und entspannt – ideal für einen halben oder ganzen Tag zwischen Kanälen, Arkaden und Altstadt.',sights:'Piazza dei Signori · Canale dei Buranelli · Dom · Isola della Pescheria',slug:'treviso'},
{name:'Verona',time:'ca. 55–75 Min. ab Venezia Mestre, je nach Zug',why:'Ein ganzer Tag in einer der bedeutendsten Kunststädte Venetiens – ganz ohne Auto.',sights:'Arena · Piazza delle Erbe · Castelvecchio · Ponte Scaligero und Etschufer',slug:'verona'}]},
fr:{eyebrow:'Sans voiture',title:'Villes d’art accessibles en train',text:'Marghera est aussi une base stratégique sans voiture : depuis la gare de Venezia Mestre, plusieurs villes d’art sont accessibles directement en train.',openGuide:'Ouvrir le guide',note:'Les temps de trajet sont indicatifs et varient selon le service. Vérifiez toujours les horaires du jour avant de partir.',cities:[
{name:'Padoue',time:'environ 15–30 min depuis Venezia Mestre',why:'Une excursion en train très simple à organiser, entre art, grandes places et vie urbaine.',sights:'Chapelle des Scrovegni · Basilique Saint-Antoine · Prato della Valle · Piazza delle Erbe et Piazza della Frutta',slug:'padova'},
{name:'Trévise',time:'environ 20–30 min depuis Venezia Mestre',why:'Compacte, élégante et paisible : parfaite pour une demi-journée ou une journée entre canaux, portiques et centre historique.',sights:'Piazza dei Signori · Canale dei Buranelli · Cathédrale · Isola della Pescheria',slug:'treviso'},
{name:'Vérone',time:'environ 55–75 min depuis Venezia Mestre selon le train',why:'Une journée complète dans l’une des grandes villes d’art de Vénétie, sans avoir besoin de conduire.',sights:'Arènes · Piazza delle Erbe · Castelvecchio · Ponte Scaligero et quais de l’Adige',slug:'verona'}]},
es:{eyebrow:'Sin coche',title:'Ciudades de arte accesibles en tren',text:'Marghera también es una base estratégica sin coche: desde la estación Venezia Mestre puedes llegar directamente en tren a varias ciudades de arte.',openGuide:'Abrir guía',note:'Los tiempos de viaje son orientativos y cambian según el servicio. Comprueba siempre el horario del día antes de salir.',cities:[
{name:'Padua',time:'aprox. 15–30 min desde Venezia Mestre',why:'Una de las excursiones en tren más fáciles: arte, plazas animadas y vida urbana en un día sencillo de organizar.',sights:'Capilla de los Scrovegni · Basílica de San Antonio · Prato della Valle · Piazza delle Erbe y Piazza della Frutta',slug:'padova'},
{name:'Treviso',time:'aprox. 20–30 min desde Venezia Mestre',why:'Compacta, elegante y tranquila: ideal para medio día o una jornada entre canales, pórticos y centro histórico.',sights:'Piazza dei Signori · Canale dei Buranelli · Catedral · Isola della Pescheria',slug:'treviso'},
{name:'Verona',time:'aprox. 55–75 min desde Venezia Mestre, según el tren',why:'Una jornada completa en una de las grandes ciudades de arte del Véneto sin necesidad de conducir.',sights:'Arena · Piazza delle Erbe · Castelvecchio · Ponte Scaligero y ribera del Adigio',slug:'verona'}]},
zh:{eyebrow:'无需开车',title:'乘火车可达的艺术城市',text:'即使不开车，马尔盖拉也是探索威尼托的理想据点：从 Venezia Mestre 火车站可直达多座艺术城市。',openGuide:'打开指南',note:'车程仅供参考，会因列车类型而变化。出发前请务必查看当天时刻表。',cities:[
{name:'帕多瓦',time:'从 Venezia Mestre 约 15–30 分钟',why:'非常容易安排的一日火车之旅，可体验艺术、广场和充满活力的城市生活。',sights:'斯克罗维尼礼拜堂 · 圣安多尼圣殿 · Prato della Valle · Piazza delle Erbe 与 Piazza della Frutta',slug:'padova'},
{name:'特雷维索',time:'从 Venezia Mestre 约 20–30 分钟',why:'城市紧凑、优雅而悠闲，适合半日或一日游，漫步运河、拱廊与历史中心。',sights:'Piazza dei Signori · Buranelli 运河 · 主教座堂 · Isola della Pescheria',slug:'treviso'},
{name:'维罗纳',time:'从 Venezia Mestre 约 55–75 分钟，视列车而定',why:'无需开车即可安排完整的一天，探索威尼托最重要的艺术城市之一。',sights:'维罗纳竞技场 · Piazza delle Erbe · Castelvecchio · Ponte Scaligero 与阿迪杰河畔',slug:'verona'}]}
};

export type VenetoData={home:string;page:string;heroEyebrow:string;heroTitle:string;heroText:string;exploreLabel:string;mapLabel:string;reasonsTitle:string;reasonsText:string;reasons:[string,string][];mapTitle:string;mapText:string;mapAlt:string;destTitle:string;destText:string;destinations:{title:string;eyebrow:string;text:string;image:string;note:string}[];tipEyebrow:string;tipTitle:string;tipText:string;officialLabel:string;tips:string[];ctaEyebrow:string;ctaTitle:string;ctaText:string};
export function LocalizedDiscoverVenetoFull({lang,data}:{lang:ParityLang;data:VenetoData}){return <><Header lang={lang}/><main>
<section className="relative min-h-[78vh] overflow-hidden pt-20"><Image src="/images/veneto-hero-prosecco-final.webp" alt={data.page} fill priority sizes="100vw" className="object-cover object-center"/><div className="hero-overlay absolute inset-0"/><div className="relative mx-auto flex min-h-[calc(78vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-24 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-6 flex items-center gap-2 text-sm text-white/75"><Link href={`/${lang}`} className="hover:text-gold">{data.home}</Link><span>›</span><span className="text-gold">{data.page}</span></nav><p className="text-xs font-black uppercase tracking-[.25em] text-gold">{data.heroEyebrow}</p><h1 className="mt-4 break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{data.heroTitle}</h1><p className="mt-6 max-w-3xl text-xl text-white/85">{data.heroText}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#destinations" className="rounded-full bg-gold px-7 py-4 font-bold text-navy">{data.exploreLabel}</a><a href="#veneto-map" className="rounded-full border border-white/60 px-7 py-4 font-bold text-white">{data.mapLabel}</a></div></div></div></section>
<section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.heroEyebrow} title={data.reasonsTitle} text={data.reasonsText}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{data.reasons.map(([t,x])=><article key={t} className="rounded-[2rem] bg-white p-8 shadow-soft"><div className="text-2xl text-gold">✦</div><h2 className="mt-4 font-serif text-3xl text-navy">{t}</h2><p className="mt-3 text-slate-600">{x}</p></article>)}</div></div></section>
{(()=>{const train=venetoTrain[lang];return <section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={train.eyebrow} title={train.title} text={train.text}/><div className="grid gap-6 lg:grid-cols-3">{train.cities.map(city=><article key={city.slug} className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-7 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{city.time}</p><h2 className="mt-3 font-serif text-4xl text-navy">{city.name}</h2><p className="mt-4 text-slate-600">{city.why}</p><p className="mt-5 rounded-2xl bg-cream p-4 text-sm font-semibold leading-6 text-navy">{city.sights}</p><div className="mt-auto flex flex-wrap gap-3 pt-6"><Link href={`/${lang}/guide/${city.slug}`} className="rounded-full bg-gold px-5 py-3 font-bold text-navy">{train.openGuide}</Link><a href="https://www.trenitalia.com/" target="_blank" rel="noopener noreferrer" className="rounded-full border border-navy px-5 py-3 font-bold text-navy">Trenitalia ↗</a></div></article>)}</div><p className="mt-5 text-sm text-slate-500">{train.note}</p></div></section>})()}
<section id="veneto-map" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.mapLabel} title={data.mapTitle} text={data.mapText}/><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-cream shadow-soft"><Image src="/images/mappa-veneto-definitiva.webp" alt={data.mapAlt} width={1536} height={1024} className="h-auto w-full object-contain"/></div></div></section>
<section id="destinations" className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.exploreLabel} title={data.destTitle} text={data.destText}/><div className="space-y-8">{data.destinations.map((d,i)=><article key={d.title} className={`grid overflow-hidden rounded-[2rem] bg-white shadow-soft lg:grid-cols-2 ${i%2?'lg:[&>div:first-child]:order-2':''}`}><div className="relative min-h-[340px] lg:min-h-[460px]"><Image src={d.image} alt={d.title} fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover"/></div><div className="flex flex-col justify-center p-8 lg:p-12"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{d.eyebrow}</p><h2 className="mt-3 font-serif text-5xl text-navy">{d.title}</h2><p className="mt-5 text-lg text-slate-600">{d.text}</p><p className="mt-6 rounded-2xl bg-cream p-5 font-semibold text-navy">{d.note}</p></div></article>)}</div></div></section>
<section className="bg-navy py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.tipEyebrow}</p><h2 className="mt-3 font-serif text-5xl">{data.tipTitle}</h2><p className="mt-6 text-lg text-white/75">{data.tipText}</p><a href="https://www.veneto.eu/en/" target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex rounded-full border border-white/40 px-6 py-3 font-bold text-white">{data.officialLabel} ↗</a></div><div className="grid gap-4 sm:grid-cols-2">{data.tips.map((x,i)=><div key={x} className="rounded-3xl bg-white/10 p-6"><div className="text-gold">0{i+1}</div><p className="mt-3 text-white/80">{x}</p></div>)}</div></div></section>
<section className="py-24"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.ctaEyebrow}</p><h2 className="mt-3 font-serif text-5xl text-navy">{data.ctaTitle}</h2><p className="mx-auto mt-5 max-w-3xl text-lg text-slate-600">{data.ctaText}</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href={`/${lang}/apartments/rossi-apartment`} className="rounded-full bg-gold px-8 py-4 font-bold text-navy">Rossi Apartment</Link><Link href={`/${lang}/apartments/dimora-castelli`} className="rounded-full border border-navy px-8 py-4 font-bold text-navy">Dimora Castelli</Link></div></div></section>
</main><Footer lang={lang}/></>}

export type GettingData={home:string;page:string;heroEyebrow:string;heroTitle:string;heroText:string;apartmentsBtn:string;veniceBtn:string;introEyebrow:string;introTitle:string;introText:string;byCar:string;fromStation:string;fromAirport:string;openMap:string;rossi:[string,string,string];dimora:[string,string,string];taxiNote:string;veniceEyebrow:string;veniceTitle:string;veniceText:string;options:{title:string;text:string;rows:[string,string,string][]}[];officialAvm:string;officialTrain:string;taxiEyebrow:string;taxiTitle:string;taxiText:string;ticketsEyebrow:string;ticketsTitle:string;ticketsText:string;ticketCards:[string,string,string][];passesTitle:string;passesText:string;passes:[string,string][];familyNote:string;faresLabel:string;avmFaresLabel:string;buyEyebrow:string;buyTitle:string;buyText:string;buyCards:[string,string,string,string][];tipEyebrow:string;tipTitle:string;tipText:string;faqEyebrow:string;faqTitle:string;faqText:string;faq:[string,string][];allFaqLabel:string};
export function LocalizedGettingFull({lang,data}:{lang:ParityLang;data:GettingData}){return <><Header lang={lang}/><main>
<section className="relative min-h-[80vh] overflow-hidden pt-20"><Image src="/images/come-arrivare-hero-originale.webp" alt={data.page} fill priority sizes="100vw" className="object-cover object-top"/><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/80 to-navy/20"/><div className="relative mx-auto flex min-h-[calc(80vh-5rem)] max-w-7xl items-center px-5 py-20 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap gap-2 text-sm text-white/70"><Link href={`/${lang}`}>{data.home}</Link><span>›</span><span className="text-gold">{data.page}</span></nav><p className="text-xs font-black uppercase tracking-[.24em] text-gold">{data.heroEyebrow}</p><h1 className="mt-4 break-words font-serif text-[clamp(3rem,9vw,6rem)] leading-none">{data.heroTitle}</h1><p className="mt-6 max-w-3xl text-xl text-white/80">{data.heroText}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#apartments" className="rounded-full bg-gold px-7 py-4 font-bold text-navy">{data.apartmentsBtn}</a><a href="#venice" className="rounded-full border border-white/50 px-7 py-4 font-bold">{data.veniceBtn}</a></div></div></div></section>
<section id="apartments" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.introEyebrow} title={data.introTitle} text={data.introText}/><div className="grid gap-7 lg:grid-cols-2">{[['Via Cesare Rossarol 32','Rossi Apartment',data.rossi,'https://maps.app.goo.gl/RsR3uoKtqtVDwgcN6'],['Via Jacopo Castelli 22','Dimora Castelli',data.dimora,'https://maps.app.goo.gl/yX3pS9GXamZyoGvUA']].map(([address,name,texts,map])=><article key={String(name)} className="rounded-[2rem] bg-cream p-8 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{String(address)}</p><h2 className="mt-3 font-serif text-5xl text-navy">{String(name)}</h2><div className="mt-7 space-y-6 text-slate-600"><div><h3 className="font-serif text-2xl text-navy">🚗 {data.byCar}</h3><p className="mt-2">{(texts as string[])[0]}</p></div><div><h3 className="font-serif text-2xl text-navy">🚆 {data.fromStation}</h3><p className="mt-2">{(texts as string[])[1]}</p></div><div><h3 className="font-serif text-2xl text-navy">✈️ {data.fromAirport}</h3><p className="mt-2">{(texts as string[])[2]}</p></div></div><a href={String(map)} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex rounded-full bg-navy px-6 py-4 font-bold text-white">{data.openMap} ↗</a></article>)}</div><p className="mt-7 rounded-3xl border-l-4 border-aqua bg-white p-6 text-slate-600 shadow-soft">{data.taxiNote}</p></div></section>
<section id="venice" className="bg-navy py-24 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.veniceEyebrow} title={data.veniceTitle} text={data.veniceText}/><div className="grid gap-7 lg:grid-cols-2">{data.options.map(o=><article key={o.title} className="rounded-[2rem] bg-white/10 p-8"><h2 className="font-serif text-4xl">{o.title}</h2><p className="mt-4 text-white/70">{o.text}</p><div className="mt-7 overflow-hidden rounded-2xl border border-white/15">{o.rows.map(([a,b,c])=><div key={a} className="grid gap-1 border-b border-white/10 p-4 last:border-0 md:grid-cols-3"><strong className="text-gold">{a}</strong><span>{b}</span><span className="text-white/70">{c}</span></div>)}</div></article>)}</div><div className="mt-8 flex flex-wrap gap-3"><a href="https://avm.avmspa.it/en/content/avm-venezia-official-app-how-use-0" target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/30 px-5 py-3 text-sm font-bold text-white">{data.officialAvm} ↗</a><a href="https://www.trenitalia.com/en.html" target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/30 px-5 py-3 text-sm font-bold text-white">{data.officialTrain} ↗</a></div></div></section>
<section className="py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-8 rounded-[2rem] bg-navy p-8 text-white shadow-soft lg:grid-cols-[1fr_.8fr] lg:p-10"><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.taxiEyebrow}</p><h2 className="mt-3 font-serif text-4xl">{data.taxiTitle}</h2><p className="mt-5 text-white/75">{data.taxiText}</p></div><div className="flex items-center lg:justify-end"><a href="https://www.radiotaxivenezia.com/" target="_blank" rel="noopener noreferrer" className="inline-flex rounded-full bg-gold px-7 py-4 font-bold text-navy">RadioTaxi Venezia ↗</a></div></div></div></section>
<section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.ticketsEyebrow} title={data.ticketsTitle} text={data.ticketsText}/><div className="grid gap-5 md:grid-cols-3">{data.ticketCards.map(([t,p,n])=><article key={t} className="rounded-[2rem] border border-slate-200 bg-white p-8 text-center shadow-soft"><p className="text-sm font-black uppercase tracking-[.18em] text-gold">{t}</p><p className="mt-4 font-serif text-5xl text-navy">{p}</p><p className="mt-3 text-slate-600">{n}</p></article>)}</div><div className="mt-12 rounded-[2rem] bg-cream p-8"><h2 className="font-serif text-4xl text-navy">{data.passesTitle}</h2><p className="mt-3 text-slate-600">{data.passesText}</p><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{data.passes.map(([d,p])=><div key={d} className="rounded-2xl bg-white p-5 shadow-soft"><p className="font-bold text-navy">{d}</p><p className="mt-2 text-lg text-slate-600">{p}</p></div>)}</div><p className="mt-6 text-sm text-slate-500">{data.familyNote}</p><div className="mt-6 flex flex-wrap gap-3"><a href="https://www.veneziaunica.it/en/buy-tickets/public-trasport-in-venice" target="_blank" rel="noopener noreferrer" className="rounded-full bg-navy px-5 py-3 text-sm font-bold text-white">{data.faresLabel} ↗</a><a href="https://avm.avmspa.it/en/content/venice-urban-services-0" target="_blank" rel="noopener noreferrer" className="rounded-full border border-navy/20 px-5 py-3 text-sm font-bold text-navy">{data.avmFaresLabel} ↗</a></div></div></div></section>
<section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.buyEyebrow} title={data.buyTitle} text={data.buyText}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{data.buyCards.map(([t,x,url,label])=><a key={t} href={url} target="_blank" rel="noopener noreferrer" className="rounded-[2rem] bg-white p-7 shadow-soft"><h2 className="font-serif text-3xl text-navy">{t}</h2><p className="mt-3 text-slate-600">{x}</p><span className="mt-5 inline-block font-bold text-gold">{label} ↗</span></a>)}</div></div></section>
<section className="bg-gold py-20 text-navy"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em]">{data.tipEyebrow}</p><h2 className="mt-4 font-serif text-5xl">{data.tipTitle}</h2><p className="mx-auto mt-5 max-w-3xl text-lg text-navy/75">{data.tipText}</p></div></section>
<section className="py-24"><div className="mx-auto max-w-5xl px-5 lg:px-8"><SectionTitle eyebrow={data.faqEyebrow} title={data.faqTitle} text={data.faqText}/><div className="space-y-4">{data.faq.map(([q,a])=><details key={q} className="group rounded-3xl border border-slate-200 bg-white p-6"><summary className="flex cursor-pointer list-none items-start justify-between gap-4 font-serif text-2xl text-navy"><span className="min-w-0">{q}</span><span className="shrink-0 text-gold transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 text-slate-600">{a}</p></details>)}</div><div className="mt-8 text-center"><Link href={`/${lang}/faq`} className="inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white">{data.allFaqLabel}</Link></div></div></section>
</main><Footer lang={lang}/></>}
