import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SectionTitle from '@/components/SectionTitle';
import WeChatCard from '@/components/WeChatCard';
import HubCultureSection from '@/components/HubCultureSection';
import VenetoProvinceNavigator from '@/components/VenetoProvinceNavigator';

export type ParityLang='de'|'fr'|'es'|'zh';
export type FAQData={home:string;page:string;eyebrow:string;title:string;subtitle:string;groupNote:string;groups:{title:string;items:[string,string][]}[];ctaTitle:string;ctaText:string;ctaLabel:string;ctaMessage:string};
export function LocalizedFAQFull({lang,data}:{lang:ParityLang;data:FAQData}){return <><Header lang={lang}/><main>
<section className="bg-navy px-5 pb-20 pt-36 text-white lg:px-8"><div className="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap items-center gap-2 text-sm text-white/70"><Link href={`/${lang}`} className="hover:text-gold">{data.home}</Link><span>›</span><span className="text-gold">{data.page}</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.eyebrow}</p><h1 className="mt-4 max-w-5xl break-words font-serif text-[clamp(2.55rem,6vw,4.6rem)] leading-none">{data.title}</h1><p className="mt-6 max-w-3xl text-xl text-white/75">{data.subtitle}</p></div></section>
<section className="py-24"><div className="mx-auto max-w-5xl px-5 lg:px-8">{data.groups.map(group=><section key={group.title} className="mb-16"><SectionTitle eyebrow="FAQ" title={group.title} text={data.groupNote}/><div className="space-y-4">{group.items.map(([q,a])=><details key={q} className="group rounded-3xl border border-slate-200 bg-white p-6 shadow-soft"><summary className="flex cursor-pointer list-none items-start justify-between gap-4 font-serif text-2xl text-navy"><span className="min-w-0">{q}</span><span className="shrink-0 text-gold transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 text-slate-600">{a}</p></details>)}</div></section>)}
<div className="rounded-[2rem] bg-gold p-8 text-center text-navy"><h2 className="font-serif text-4xl">{data.ctaTitle}</h2><p className="mx-auto mt-4 max-w-2xl">{data.ctaText}</p>{lang==='zh'?<div className="mt-7"><WeChatCard title={data.ctaLabel}/></div>:<a href={`https://wa.me/393514462261?text=${encodeURIComponent(data.ctaMessage)}`} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white">{data.ctaLabel} ↗</a>}</div></div></section>
</main><Footer lang={lang}/></>}

export type VeniceData={home:string;page:string;heroEyebrow:string;heroTitle:string;heroText:string;heroBtn1:string;heroBtn2:string;transport:{eyebrow:string;title:string;text:string;steps:[string,string,string][];infoTitle:string;infoText:string;infoLabel:string};itinerary:{eyebrow:string;title:string;text:string;items:[string,string,string][]};tips:{eyebrow:string;title:string;text:string;items:[string,string][]};map:{eyebrow:string;title:string;text:string;alt:string};family:{eyebrow:string;title:string;text:string;imageAlt:string;items:[string,string][]};pet:{eyebrow:string;title:string;text:string;items:[string,string][]};islands:{eyebrow:string;title:string;text:string;items:[string,string,string][];linkLabel:string};venetoCta:{eyebrow:string;title:string;text:string;label:string};homes:{eyebrow:string;title:string;text:string;rossi:string;dimora:string}};
const discoverHubUi:Record<ParityLang,{
 chooseEyebrow:string;chooseTitle:string;chooseText:string;culture:string;cultureText:string;islandsText:string;familyText:string;petText:string;getting:string;gettingText:string;journal:string;journalText:string;
 familyLink:string;petLink:string;transportLink:string;official:string;firstVisit:string;firstVisitTitle:string;firstVisitText:string;tipsTitle:string;tipsText:string;mapText:string;moreTime:string;homesTitle:string;
 cultureHref:string;
}>={
 de:{chooseEyebrow:'Nach Interessen entdecken',chooseTitle:'Welches Venedig möchten Sie erleben?',chooseText:'Diese Seite ist Ihre Orientierung: Wählen Sie Kunst, Inseln, Familie, Hund, Veranstaltungen oder Mobilität und gehen Sie direkt zur passenden Vertiefung.',culture:'Museen, Monumente & Kirchen',cultureText:'Besuchsdauer, Preise und praktische Hinweise für die wichtigsten Kulturorte.',islandsText:'Murano, Burano, Lido, Pellestrina, Sant’Erasmo und Certosa passend zum Tagesrhythmus wählen.',familyText:'Museen, Vaporetto, Pausen und Ideen für einen entspannten Tag mit Kindern.',petText:'Transportregeln, ruhigere Spaziergänge und praktische Hinweise mit Hund.',getting:'Anreise & Mobilität',gettingText:'Bus, Bahn, Tickets und Nachtverbindungen ab den Apartments.',journal:'Events & Geschichten',journalText:'Ausstellungen, Feste, Traditionen und aktuelle Termine im Journal.',familyLink:'Guide für Familien öffnen',petLink:'Pet-Friendly-Guide öffnen',transportLink:'Verkehr, Tickets & Flughäfen',official:'Offizielle ACTV-Infos',firstVisit:'Erster Besuch',firstVisitTitle:'Venedig an einem Tag – ohne daraus ein Rennen zu machen',firstVisitText:'Eine einfache Reihenfolge für den Tag. Sie hilft bei der Orientierung, ohne jede Etappe zur Pflicht zu machen.',tipsTitle:'Sechs kleine Tipps, die einen großen Unterschied machen.',tipsText:'Keine starren Regeln – nur einfache Gewohnheiten, mit denen sich die Stadt angenehmer erleben lässt.',mapText:'Nutzen Sie die Karte, um Entfernungen zwischen Altstadt, Inseln und wichtigen Orten zu verstehen. Für die genaue Route öffnen Sie anschließend Maps.',moreTime:'Wenn Sie mehr Zeit haben',homesTitle:'Wo möchten Sie am Abend zurückkommen?',cultureHref:'/de/guide/museen-venedig'},
 fr:{chooseEyebrow:'Explorer selon vos envies',chooseTitle:'Quelle Venise avez-vous envie de vivre ?',chooseText:'Cette page devient votre boussole : choisissez art, îles, famille, chien, événements ou transports et accédez directement au guide utile.',culture:'Musées, monuments & églises',cultureText:'Durée de visite, tarifs et informations pratiques pour choisir les lieux qui méritent votre temps.',islandsText:'Murano, Burano, Lido, Pellestrina, Sant’Erasmo et Certosa selon le rythme de votre journée.',familyText:'Musées, vaporetto, pauses et idées pour une journée plus simple avec les enfants.',petText:'Transports, promenades tranquilles et conseils pratiques pour visiter avec un chien.',getting:'Accès & déplacements',gettingText:'Bus, train, billets et liaisons nocturnes depuis les appartements.',journal:'Événements & histoires',journalText:'Expositions, fêtes, traditions et rendez-vous dans le Journal.',familyLink:'Ouvrir le guide famille',petLink:'Ouvrir le guide Pet Friendly',transportLink:'Transports, billets & aéroports',official:'Infos ACTV officielles',firstVisit:'Première visite',firstVisitTitle:'Venise en une journée, sans transformer la visite en course',firstVisitText:'Un fil conducteur simple pour donner un ordre à la journée, sans rendre chaque étape obligatoire.',tipsTitle:'Six petits conseils qui changent vraiment la journée.',tipsText:'Pas de règles rigides : seulement quelques habitudes simples pour profiter davantage de la ville.',mapText:'Utilisez la carte pour comprendre les distances entre centre historique, îles et principaux sites. Pour le trajet exact, ouvrez ensuite Maps.',moreTime:'Si vous avez plus de temps',homesTitle:'Où voulez-vous rentrer le soir ?',cultureHref:'/fr/guide/musees-venise'},
 es:{chooseEyebrow:'Explora según tu viaje',chooseTitle:'¿Qué Venecia quieres vivir?',chooseText:'Esta página funciona como brújula: elige arte, islas, familia, perro, eventos o transporte y entra directamente en la guía que realmente necesitas.',culture:'Museos, monumentos e iglesias',cultureText:'Duración media, precios e información práctica para elegir qué merece tu tiempo.',islandsText:'Murano, Burano, Lido, Pellestrina, Sant’Erasmo y Certosa según el tipo de día.',familyText:'Museos, vaporetto, pausas e ideas para disfrutar la ciudad con niños sin correr.',petText:'Transporte, paseos tranquilos y consejos prácticos para visitar con perro.',getting:'Cómo llegar y moverse',gettingText:'Autobús, tren, billetes y conexiones nocturnas desde los apartamentos.',journal:'Eventos e historias',journalText:'Exposiciones, fiestas, tradiciones y citas en el Journal.',familyLink:'Abrir la guía para familias',petLink:'Abrir la guía Pet Friendly',transportLink:'Transporte, billetes y aeropuertos',official:'Información oficial ACTV',firstVisit:'Primera visita',firstVisitTitle:'Venecia en un día, sin convertirla en una carrera',firstVisitText:'Una ruta sencilla para dar orden al día, sin obligarte a completar cada parada.',tipsTitle:'Seis pequeños consejos que marcan una gran diferencia.',tipsText:'Nada de reglas rígidas: solo hábitos sencillos para disfrutar mejor de la ciudad.',mapText:'Usa el mapa para entender las distancias entre centro histórico, islas y principales puntos de interés. Para la ruta exacta, abre después Maps.',moreTime:'Si tienes más tiempo',homesTitle:'¿Dónde quieres volver por la noche?',cultureHref:'/es/guide/museos-venecia'},
 zh:{chooseEyebrow:'按旅行方式探索',chooseTitle:'你想体验怎样的威尼斯？',chooseText:'把这一页当作导航：艺术、岛屿、亲子、带狗出行、活动或交通，选择真正需要的主题后直接进入详细指南。',culture:'博物馆、古迹与教堂',cultureText:'用平均参观时长、票价和实用信息判断哪些地方值得安排时间。',islandsText:'根据当天节奏选择 Murano、Burano、Lido、Pellestrina、Sant’Erasmo 或 Certosa。',familyText:'博物馆、水上巴士、休息时间和亲子旅行建议，让一天不必赶行程。',petText:'公共交通、安静散步路线和带狗游览时需要知道的实用规则。',getting:'抵达与交通',gettingText:'从公寓出发的公交、火车、车票和夜间连接。',journal:'活动与故事',journalText:'展览、节庆、传统与近期活动都集中在 Journal。',familyLink:'打开亲子指南',petLink:'打开宠物友好指南',transportLink:'交通、车票与机场',official:'ACTV 官方信息',firstVisit:'第一次到访',firstVisitTitle:'一天看威尼斯，不必把旅行变成比赛',firstVisitText:'这只是给一天安排一个自然顺序，不需要把每一站都当成必须完成的任务。',tipsTitle:'六个简单建议，让一天舒服很多。',tipsText:'没有硬性规则，只是一些让城市体验更顺畅的小习惯。',mapText:'先用地图理解老城、岛屿和主要景点之间的距离，再用 Maps 查看精确路线。',moreTime:'如果时间更充裕',homesTitle:'晚上想回到怎样的家？',cultureHref:'/zh/guide/venice-museums'}
};

export function LocalizedDiscoverVeniceFull({lang,data}:{lang:ParityLang;data:VeniceData}){
 const u=discoverHubUi[lang];
 const explore:[string,string,string,string][]=[
  ['01',u.culture,u.cultureText,u.cultureHref],
  ['02',data.islands.title,u.islandsText,'#islands'],
  ['03',data.family.title,u.familyText,`/${lang}/journal/venezia-con-bambini`],
  ['04',data.pet.title,u.petText,`/${lang}/journal/venezia-con-il-cane`],
  ['05',u.getting,u.gettingText,`/${lang}/getting-to-venice`],
  ['06',u.journal,u.journalText,`/${lang}/journal`],
 ];
 const slugs=['murano','burano','lido-di-venezia','pellestrina','sant-erasmo','certosa'];
 return <><Header lang={lang}/><main className="editorial-page">
  <section className="relative min-h-[74vh] overflow-hidden pt-20"><Image src="/images/scopri-venezia-michael-heise.webp" alt={data.page} fill priority sizes="100vw" className="object-cover object-center"/><div className="hero-overlay absolute inset-0"/><div className="relative mx-auto flex min-h-[calc(74vh-5rem)] max-w-7xl items-end px-5 pb-14 pt-24 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-5 flex items-center gap-2 text-sm text-white/75"><Link href={`/${lang}`} className="hover:text-gold">{data.home}</Link><span>›</span><span className="text-gold">{data.page}</span></nav><p className="text-xs font-black uppercase tracking-[.25em] text-gold">{data.heroEyebrow}</p><h1 className="mt-4 break-words font-serif text-[clamp(2.55rem,6vw,4.6rem)] leading-none">{data.heroTitle}</h1><p className="mt-6 max-w-3xl text-xl text-white/85">{data.heroText}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#start" className="rounded-full bg-gold px-7 py-4 font-bold text-navy">{data.heroBtn1}</a><Link href={u.cultureHref} className="rounded-full border border-white/60 px-7 py-4 font-bold text-white">{u.culture}</Link></div></div></div></section>

  <section id="start" className="py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={u.chooseEyebrow} title={u.chooseTitle} text={u.chooseText}/><div className="mt-8 grid border-y border-navy/15 md:grid-cols-2">{explore.map(([n,t,x,href],i)=><Link key={t} href={href} className={`group grid grid-cols-[42px_1fr_auto] gap-3 py-6 transition hover:bg-cream md:px-6 ${i%2===0?'md:border-r md:border-navy/10':''} ${i<4?'border-b border-navy/10':''}`}><span className="pt-1 text-xs font-black tracking-[.16em] text-gold">{n}</span><span><span className="block font-serif text-2xl text-navy">{t}</span><span className="mt-2 block max-w-xl leading-7 text-slate-600">{x}</span></span><span className="pt-1 text-2xl text-gold transition group-hover:translate-x-1">→</span></Link>)}</div></div></section>

  <section className="bg-cream py-16 sm:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[1fr_.85fr] lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.transport.eyebrow}</p><h2 className="mt-3 max-w-3xl font-serif text-5xl text-navy">{data.transport.title}</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">{data.transport.text}</p><div className="mt-7 flex flex-wrap gap-3"><Link href={`/${lang}/getting-to-venice`} className="rounded-full bg-navy px-6 py-3.5 font-bold text-white">{u.transportLink} →</Link><a href="https://avm.avmspa.it/en/content/venice-urban-services-0" target="_blank" rel="noopener noreferrer" className="rounded-full border border-navy/25 px-6 py-3.5 font-bold text-navy">{u.official} ↗</a></div></div><div className="self-start border-y border-navy/15">{data.transport.steps.slice(0,3).map(([n,t,x])=><div key={n} className="grid grid-cols-[42px_1fr] gap-4 border-b border-navy/10 py-5 last:border-b-0"><span className="text-xs font-black tracking-[.14em] text-gold">{n}</span><span><strong className="block text-navy">{t}</strong><span className="mt-1 block text-sm text-slate-600">{x}</span></span></div>)}</div></div></section>

  <section className="py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={u.firstVisit} title={u.firstVisitTitle} text={u.firstVisitText}/><ol className="mt-8 border-y border-slate-200 lg:grid lg:grid-cols-2 lg:gap-x-10">{data.itinerary.items.map(([time,t,x])=><li key={time} className="grid grid-cols-[72px_1fr] gap-4 border-b border-slate-200 py-5 last:border-b-0 lg:[&:nth-last-child(-n+2)]:border-b-0"><span className="pt-1 text-xs font-black tracking-[.12em] text-gold">{time}</span><span><strong className="block font-serif text-2xl font-normal text-navy">{t}</strong><span className="mt-1.5 block leading-7 text-slate-600">{x}</span></span></li>)}</ol></div></section>

  <HubCultureSection scope="venice" lang={lang}/>

  <section className="py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-6 lg:grid-cols-2"><article className="group overflow-hidden rounded-[2rem] bg-cream"><div className="relative h-72"><Image src="/images/venezia-bambini-campo-nuova.webp" alt={data.family.imageAlt} fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover transition duration-700 group-hover:scale-[1.02]"/></div><div className="p-7 sm:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{data.family.eyebrow}</p><h2 className="mt-3 font-serif text-4xl text-navy">{data.family.title}</h2><p className="mt-4 leading-7 text-slate-600">{data.family.text}</p><Link href={`/${lang}/journal/venezia-con-bambini`} className="mt-6 inline-flex font-bold text-navy">{u.familyLink} →</Link></div></article><article className="group overflow-hidden rounded-[2rem] bg-navy text-white"><div className="relative h-72"><Image src="/images/journal-venezia-cane.webp" alt={data.pet.title} fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover transition duration-700 group-hover:scale-[1.02]"/></div><div className="p-7 sm:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{data.pet.eyebrow}</p><h2 className="mt-3 font-serif text-4xl">{data.pet.title}</h2><p className="mt-4 leading-7 text-white/75">{data.pet.text}</p><Link href={`/${lang}/journal/venezia-con-il-cane`} className="mt-6 inline-flex font-bold text-gold">{u.petLink} →</Link></div></article></div></div></section>

  <section className="bg-navy py-16 text-white sm:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.tips.eyebrow}</p><h2 className="mt-3 font-serif text-5xl">{u.tipsTitle}</h2><p className="mt-5 leading-7 text-white/70">{u.tipsText}</p></div><div className="divide-y divide-white/15 border-y border-white/15 sm:grid sm:grid-cols-2 sm:divide-x sm:divide-y-0">{data.tips.items.map(([t,x],i)=><div key={t} className={`py-5 sm:px-6 ${i<4?'sm:border-b sm:border-white/15':''}`}><p className="text-xs font-black tracking-[.14em] text-gold">0{i+1}</p><h3 className="mt-2 font-serif text-2xl">{t}</h3><p className="mt-2 text-sm leading-6 text-white/70">{x}</p></div>)}</div></div></section>

  <section id="islands" className="bg-cream py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.islands.eyebrow} title={data.islands.title} text={data.islands.text}/><div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{data.islands.items.map(([t,x,img],i)=><article key={t} className="group overflow-hidden rounded-[1.75rem] bg-white"><div className="relative h-56 overflow-hidden"><Image src={img} alt={t} fill sizes="(min-width:1280px) 33vw, (min-width:768px) 50vw, 100vw" className="object-cover transition duration-700 group-hover:scale-[1.03]"/></div><div className="p-6"><h2 className="font-serif text-3xl text-navy">{t}</h2><p className="mt-2.5 leading-7 text-slate-600">{x}</p><Link href={`/${lang}/guide/${slugs[i]}`} className="mt-5 inline-flex font-bold text-navy">{data.islands.linkLabel} →</Link></div></article>)}</div></div></section>

  <section className="py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid items-center gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.map.eyebrow}</p><h2 className="mt-3 font-serif text-5xl text-navy">{data.map.title}</h2><p className="mt-5 leading-7 text-slate-600">{u.mapText}</p></div><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-cream"><Image src="/images/mappa-venezia-finale.webp" alt={data.map.alt} width={1408} height={1056} className="h-auto w-full object-contain"/></div></div></div></section>

  <section className="bg-gold py-16 text-navy sm:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-2 lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em]">{u.moreTime}</p><h2 className="mt-3 font-serif text-5xl">{data.venetoCta.title}</h2><p className="mt-5 max-w-xl text-lg leading-8 text-navy/75">{data.venetoCta.text}</p><Link href={`/${lang}/discover-veneto`} className="mt-7 inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white">{data.venetoCta.label} →</Link></div><div className="border-t border-navy/20 pt-8 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><p className="text-xs font-black uppercase tracking-[.22em]">{data.homes.eyebrow}</p><h2 className="mt-3 font-serif text-4xl">{u.homesTitle}</h2><p className="mt-4 leading-7 text-navy/75">{data.homes.text}</p><div className="mt-7 flex flex-wrap gap-3"><Link href={`/${lang}/apartments/rossi-apartment`} className="rounded-full bg-white px-6 py-3 font-bold text-navy">{data.homes.rossi}</Link><Link href={`/${lang}/apartments/dimora-castelli`} className="rounded-full border border-navy px-6 py-3 font-bold text-navy">{data.homes.dimora}</Link></div></div></div></section>
 </main><Footer lang={lang}/></>;
}

type VenetoTrainCity={name:string;time:string;why:string;sights:string;slug:string};
const venetoTrain:Record<ParityLang,{eyebrow:string;title:string;text:string;openGuide:string;note:string;cities:VenetoTrainCity[]}>={
de:{eyebrow:'Ohne Auto',title:'Kunststädte mit dem Zug erreichbar',text:'Marghera ist auch ohne Auto ein strategischer Ausgangspunkt: Vom Bahnhof Venezia Mestre erreichen Sie mehrere Kunststädte direkt mit dem Zug.',openGuide:'Guide öffnen',note:'Die Fahrzeiten sind Richtwerte und hängen von der Verbindung ab. Prüfen Sie vor der Abfahrt immer den aktuellen Fahrplan.',cities:[
{name:'Padua',time:'ca. 15–30 Min. ab Venezia Mestre',why:'Eine der einfachsten Zugausflüge: Kunst, lebendige Plätze und Stadtleben lassen sich bequem an einem Tag entdecken.',sights:'Scrovegni-Kapelle · Basilika des hl. Antonius · Prato della Valle · Piazza delle Erbe und Piazza della Frutta',slug:'padova'},
{name:'Treviso',time:'ca. 20–30 Min. ab Venezia Mestre',why:'Kompakt, elegant und entspannt – ideal für einen halben oder ganzen Tag zwischen Kanälen, Arkaden und Altstadt.',sights:'Piazza dei Signori · Canale dei Buranelli · Dom · Isola della Pescheria',slug:'treviso'},
{name:'Verona',time:'ca. 55–75 Min. ab Venezia Mestre, je nach Zug',why:'Ein ganzer Tag in einer der bedeutendsten Kunststädte Venetiens – ganz ohne Auto.',sights:'Arena · Piazza delle Erbe · Castelvecchio · Ponte Scaligero und Etschufer',slug:'verona'}]},
fr:{eyebrow:'Sans voiture',title:'Villes d’art accessibles en train',text:'Marghera est aussi une base stratégique sans voiture : depuis la gare de Venezia Mestre, plusieurs villes d’art sont accessibles directement en train.',openGuide:'Ouvrir le guide',note:'Les temps de trajet sont indicatifs et varient selon le service. Vérifiez toujours les horaires du jour avant de partir.',cities:[
{name:'Padoue',time:'environ 15–30 min depuis Venezia Mestre',why:'Une excursion en train très simple à organiser, entre art, grandes places et vie urbaine.',sights:'Chapelle des Scrovegni · Basilique Saint-Antoine · Prato della Valle · Piazza delle Erbe et Piazza della Frutta',slug:'padova'},
{name:'Trévise',time:'environ 20–30 min depuis Venezia Mestre',why:'Compacte, élégante et paisible : parfaite pour une demi-journée ou une journée entre canaux, portiques et centre historique.',sights:'Piazza dei Signori · Canale dei Buranelli · Cathédrale · Isola della Pescheria',slug:'treviso'},
{name:'Vérone',time:'environ 55–75 min depuis Venezia Mestre selon le train',why:'Une journée complète dans l’une des grandes villes d’art de Vénétie, sans avoir besoin de conduire.',sights:'Arènes · Piazza delle Erbe · Castelvecchio · Ponte Scaligero et quais de l’Adige',slug:'verona'}]},
es:{eyebrow:'Sin coche',title:'Ciudades de arte accesibles en tren',text:'Marghera también es una base estratégica sin coche: desde la estación Venezia Mestre puedes llegar directamente en tren a varias ciudades de arte.',openGuide:'Abrir guía',note:'Los tiempos de viaje son orientativos y cambian según el servicio. Comprueba siempre el horario del día antes de salir.',cities:[
{name:'Padua',time:'aprox. 15–30 min desde Venezia Mestre',why:'Una de las excursiones en tren más fáciles: arte, plazas animadas y vida urbana en un día sencillo de organizar.',sights:'Capilla de los Scrovegni · Basílica de San Antonio · Prato della Valle · Piazza delle Erbe y Piazza della Frutta',slug:'padova'},
{name:'Treviso',time:'aprox. 20–30 min desde Venezia Mestre',why:'Compacta, elegante y tranquila: ideal para medio día o una jornada entre canales, pórticos y centro histórico.',sights:'Piazza dei Signori · Canale dei Buranelli · Catedral · Isola della Pescheria',slug:'treviso'},
{name:'Verona',time:'aprox. 55–75 min desde Venezia Mestre, según el tren',why:'Una jornada completa en una de las grandes ciudades de arte del Véneto sin necesidad de conducir.',sights:'Arena · Piazza delle Erbe · Castelvecchio · Ponte Scaligero y ribera del Adigio',slug:'verona'}]},
zh:{eyebrow:'无需开车',title:'乘火车可达的艺术城市',text:'即使不开车，马尔盖拉也是探索威尼托的理想据点：从 Venezia Mestre 火车站可直达多座艺术城市。',openGuide:'打开指南',note:'车程仅供参考，会因列车类型而变化。出发前请务必查看当天时刻表。',cities:[
{name:'帕多瓦',time:'从 Venezia Mestre 约 15–30 分钟',why:'非常容易安排的一日火车之旅，可体验艺术、广场和充满活力的城市生活。',sights:'斯克罗维尼礼拜堂 · 圣安多尼圣殿 · Prato della Valle · Piazza delle Erbe 与 Piazza della Frutta',slug:'padova'},
{name:'特雷维索',time:'从 Venezia Mestre 约 20–30 分钟',why:'城市紧凑、优雅而悠闲，适合半日或一日游，漫步运河、拱廊与历史中心。',sights:'Piazza dei Signori · Buranelli 运河 · 主教座堂 · Isola della Pescheria',slug:'treviso'},
{name:'维罗纳',time:'从 Venezia Mestre 约 55–75 分钟，视列车而定',why:'无需开车即可安排完整的一天，探索威尼托最重要的艺术城市之一。',sights:'维罗纳竞技场 · Piazza delle Erbe · Castelvecchio · Ponte Scaligero 与阿迪杰河畔',slug:'verona'}]}
};

export type VenetoData={home:string;page:string;heroEyebrow:string;heroTitle:string;heroText:string;exploreLabel:string;mapLabel:string;reasonsTitle:string;reasonsText:string;reasons:[string,string][];mapTitle:string;mapText:string;mapAlt:string;destTitle:string;destText:string;destinations:{title:string;eyebrow:string;text:string;image:string;note:string}[];tipEyebrow:string;tipTitle:string;tipText:string;officialLabel:string;tips:string[];ctaEyebrow:string;ctaTitle:string;ctaText:string};
export function LocalizedDiscoverVenetoFull({lang,data}:{lang:ParityLang;data:VenetoData}){return <><Header lang={lang}/><main>
<section className="relative min-h-[78vh] overflow-hidden pt-20"><Image src="/images/veneto-hero-prosecco-final.webp" alt={data.page} fill priority sizes="100vw" className="object-cover object-center"/><div className="hero-overlay absolute inset-0"/><div className="relative mx-auto flex min-h-[calc(78vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-24 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-6 flex items-center gap-2 text-sm text-white/75"><Link href={`/${lang}`} className="hover:text-gold">{data.home}</Link><span>›</span><span className="text-gold">{data.page}</span></nav><p className="text-xs font-black uppercase tracking-[.25em] text-gold">{data.heroEyebrow}</p><h1 className="mt-4 break-words font-serif text-[clamp(2.55rem,6vw,4.6rem)] leading-none">{data.heroTitle}</h1><p className="mt-6 max-w-3xl text-xl text-white/85">{data.heroText}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#destinations" className="rounded-full bg-gold px-7 py-4 font-bold text-navy">{data.exploreLabel}</a><a href="#veneto-map" className="rounded-full border border-white/60 px-7 py-4 font-bold text-white">{data.mapLabel}</a></div></div></div></section>
<section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.heroEyebrow} title={data.reasonsTitle} text={data.reasonsText}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{data.reasons.map(([t,x])=><article key={t} className="rounded-[2rem] bg-white p-8 shadow-soft"><div className="text-2xl text-gold">✦</div><h2 className="mt-4 font-serif text-3xl text-navy">{t}</h2><p className="mt-3 text-slate-600">{x}</p></article>)}</div></div></section>
{(()=>{const train=venetoTrain[lang];return <section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={train.eyebrow} title={train.title} text={train.text}/><div className="grid gap-6 lg:grid-cols-3">{train.cities.map(city=><article key={city.slug} className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-7 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{city.time}</p><h2 className="mt-3 font-serif text-4xl text-navy">{city.name}</h2><p className="mt-4 text-slate-600">{city.why}</p><p className="mt-5 rounded-2xl bg-cream p-4 text-sm font-semibold leading-6 text-navy">{city.sights}</p><div className="mt-auto flex flex-wrap gap-3 pt-6"><Link href={`/${lang}/guide/${city.slug}`} className="rounded-full bg-gold px-5 py-3 font-bold text-navy">{train.openGuide}</Link><a href="https://www.trenitalia.com/" target="_blank" rel="noopener noreferrer" className="rounded-full border border-navy px-5 py-3 font-bold text-navy">Trenitalia ↗</a></div></article>)}</div><p className="mt-5 text-sm text-slate-500">{train.note}</p></div></section>})()}
<section id="veneto-map" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.mapLabel} title={data.mapTitle} text={data.mapText}/><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-cream shadow-soft"><Image src="/images/mappa-veneto-definitiva.webp" alt={data.mapAlt} width={1536} height={1024} className="h-auto w-full object-contain"/></div></div></section>
<HubCultureSection scope="veneto" lang={lang}/><VenetoProvinceNavigator lang={lang}/><section id="destinations" className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.exploreLabel} title={data.destTitle} text={data.destText}/><div className="space-y-8">{data.destinations.map((d,i)=><article key={d.title} className={`grid overflow-hidden rounded-[2rem] bg-white shadow-soft lg:grid-cols-2 ${i%2?'lg:[&>div:first-child]:order-2':''}`}><div className="relative min-h-[340px] lg:min-h-[460px]"><Image src={d.image} alt={d.title} fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover"/></div><div className="flex flex-col justify-center p-8 lg:p-12"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{d.eyebrow}</p><h2 className="mt-3 font-serif text-5xl text-navy">{d.title}</h2><p className="mt-5 text-lg text-slate-600">{d.text}</p><p className="mt-6 rounded-2xl bg-cream p-5 font-semibold text-navy">{d.note}</p></div></article>)}</div></div></section>
<section className="bg-navy py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.tipEyebrow}</p><h2 className="mt-3 font-serif text-5xl">{data.tipTitle}</h2><p className="mt-6 text-lg text-white/75">{data.tipText}</p><a href="https://www.veneto.eu/en/" target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex rounded-full border border-white/40 px-6 py-3 font-bold text-white">{data.officialLabel} ↗</a></div><div className="grid gap-4 sm:grid-cols-2">{data.tips.map((x,i)=><div key={x} className="rounded-3xl bg-white/10 p-6"><div className="text-gold">0{i+1}</div><p className="mt-3 text-white/80">{x}</p></div>)}</div></div></section>
<section className="py-24"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">{data.ctaEyebrow}</p><h2 className="mt-3 font-serif text-5xl text-navy">{data.ctaTitle}</h2><p className="mx-auto mt-5 max-w-3xl text-lg text-slate-600">{data.ctaText}</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href={`/${lang}/apartments/rossi-apartment`} className="rounded-full bg-gold px-8 py-4 font-bold text-navy">Rossi Apartment</Link><Link href={`/${lang}/apartments/dimora-castelli`} className="rounded-full border border-navy px-8 py-4 font-bold text-navy">Dimora Castelli</Link></div></div></section>
</main><Footer lang={lang}/></>}

export type GettingData={home:string;page:string;heroEyebrow:string;heroTitle:string;heroText:string;apartmentsBtn:string;veniceBtn:string;introEyebrow:string;introTitle:string;introText:string;byCar:string;fromStation:string;fromAirport:string;openMap:string;rossi:[string,string,string];dimora:[string,string,string];taxiNote:string;veniceEyebrow:string;veniceTitle:string;veniceText:string;options:{title:string;text:string;rows:[string,string,string][]}[];officialAvm:string;officialTrain:string;taxiEyebrow:string;taxiTitle:string;taxiText:string;ticketsEyebrow:string;ticketsTitle:string;ticketsText:string;ticketCards:[string,string,string][];passesTitle:string;passesText:string;passes:[string,string][];familyNote:string;faresLabel:string;avmFaresLabel:string;buyEyebrow:string;buyTitle:string;buyText:string;buyCards:[string,string,string,string][];tipEyebrow:string;tipTitle:string;tipText:string;faqEyebrow:string;faqTitle:string;faqText:string;faq:[string,string][];allFaqLabel:string};
export function LocalizedGettingFull({lang,data}:{lang:ParityLang;data:GettingData}){return <><Header lang={lang}/><main className="editorial-page">
<section className="relative min-h-[72vh] overflow-hidden pt-20"><Image src="/images/come-arrivare-hero-originale.webp" alt={data.page} fill priority sizes="100vw" className="object-cover object-top"/><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/80 to-navy/20"/><div className="relative mx-auto flex min-h-[calc(72vh-5rem)] max-w-7xl items-end px-5 pb-14 pt-24 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap gap-2 text-sm text-white/70"><Link href={`/${lang}`}>{data.home}</Link><span>›</span><span className="text-gold">{data.page}</span></nav><p className="text-xs font-black uppercase tracking-[.24em] text-gold">{data.heroEyebrow}</p><h1 className="mt-4 break-words font-serif text-[clamp(2.55rem,6vw,4.6rem)] leading-none">{data.heroTitle}</h1><p className="mt-6 max-w-3xl text-xl text-white/80">{data.heroText}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#apartments" className="rounded-full bg-gold px-7 py-4 font-bold text-navy">{data.apartmentsBtn}</a><a href="#venice" className="rounded-full border border-white/50 px-7 py-4 font-bold">{data.veniceBtn}</a></div></div></div></section>
<section id="apartments" className="py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.introEyebrow} title={data.introTitle} text={data.introText}/><div className="mt-8 grid gap-10 lg:grid-cols-2">{[['Via Cesare Rossarol 32','Rossi Apartment',data.rossi,'https://maps.app.goo.gl/JRuHsc4BoKkYTUop9?g_st=ac'],['Via Jacopo Castelli 22','Dimora Castelli',data.dimora,'https://maps.app.goo.gl/JdPBaX8TaLqesNgM6?g_st=ac']].map(([address,name,texts,map])=><article key={String(name)} className="border-t border-navy/15 pt-6"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{String(address)}</p><h2 className="mt-2 font-serif text-4xl text-navy">{String(name)}</h2><div className="mt-6 divide-y divide-navy/10 text-slate-600">{[[`🚗 ${data.byCar}`,(texts as string[])[0]],[`🚆 ${data.fromStation}`,(texts as string[])[1]],[`✈️ ${data.fromAirport}`,(texts as string[])[2]]].map(([label,text])=><div key={label} className="grid gap-2 py-4 sm:grid-cols-[180px_1fr]"><h3 className="font-bold text-navy">{label}</h3><p>{text}</p></div>)}</div><a href={String(map)} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex rounded-full bg-navy px-5 py-3 text-sm font-bold text-white">{data.openMap} ↗</a></article>)}</div><p className="mt-9 border-l-4 border-aqua pl-5 text-sm text-slate-600">{data.taxiNote}</p></div></section>
<section id="venice" className="bg-navy py-20 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.veniceEyebrow} title={data.veniceTitle} text={data.veniceText}/><div className="mt-8 grid gap-10 lg:grid-cols-2">{data.options.map(o=><article key={o.title} className="border-t border-white/20 pt-6"><h2 className="font-serif text-4xl">{o.title}</h2><p className="mt-3 text-white/70">{o.text}</p><div className="mt-5 divide-y divide-white/15">{o.rows.map(([a,b,c])=><div key={a} className="grid gap-1 py-4 md:grid-cols-[110px_150px_1fr]"><strong className="text-gold">{a}</strong><span>{b}</span><span className="text-white/65">{c}</span></div>)}</div></article>)}</div><div className="mt-9 flex flex-wrap gap-3"><a href="https://avm.avmspa.it/en/content/avm-venezia-official-app-how-use-0" target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/30 px-5 py-3 text-sm font-bold text-white">{data.officialAvm} ↗</a><a href="https://www.trenitalia.com/en.html" target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/30 px-5 py-3 text-sm font-bold text-white">{data.officialTrain} ↗</a><a href="https://www.radiotaxivenezia.com/" target="_blank" rel="noopener noreferrer" className="rounded-full bg-gold px-5 py-3 text-sm font-bold text-navy">{data.taxiTitle} ↗</a></div></div></section>
<section className="py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow={data.ticketsEyebrow} title={data.ticketsTitle} text={data.ticketsText}/><div className="mt-8 border-y border-navy/15">{data.ticketCards.map(([t,p,n])=><div key={t} className="grid gap-2 border-b border-navy/10 py-5 last:border-0 sm:grid-cols-[180px_140px_1fr] sm:items-center"><strong className="font-serif text-2xl text-navy">{t}</strong><span className="font-serif text-2xl text-gold">{p}</span><span className="text-slate-600">{n}</span></div>)}</div><details className="group mt-8 border-b border-navy/15 pb-6" open><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-serif text-3xl text-navy"><span>{data.passesTitle}</span><span className="text-gold transition group-open:rotate-45">+</span></summary><p className="mt-3 text-slate-600">{data.passesText}</p><div className="mt-5 grid gap-x-8 sm:grid-cols-2">{data.passes.map(([d,p])=><div key={d} className="flex justify-between gap-4 border-b border-navy/10 py-3"><strong className="text-navy">{d}</strong><span className="text-slate-600">{p}</span></div>)}</div><p className="mt-5 text-sm text-slate-500">{data.familyNote}</p></details><div className="mt-9 grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{data.buyEyebrow}</p><h2 className="mt-2 font-serif text-4xl text-navy">{data.buyTitle}</h2><p className="mt-3 text-slate-600">{data.buyText}</p></div><div className="divide-y divide-navy/10 border-y border-navy/15">{data.buyCards.map(([t,x,url,label])=><a key={t} href={url} target="_blank" rel="noopener noreferrer" className="grid gap-2 py-4 sm:grid-cols-[180px_1fr_auto] sm:items-center"><strong className="text-navy">{t}</strong><span className="text-sm text-slate-600">{x}</span><span className="font-bold text-gold">{label} ↗</span></a>)}</div></div><div className="mt-9 flex flex-wrap gap-3"><a href="https://www.veneziaunica.it/en/buy-tickets/public-trasport-in-venice" target="_blank" rel="noopener noreferrer" className="rounded-full bg-navy px-5 py-3 text-sm font-bold text-white">{data.faresLabel} ↗</a><a href="https://avm.avmspa.it/en/content/venice-urban-services-0" target="_blank" rel="noopener noreferrer" className="rounded-full border border-navy/20 px-5 py-3 text-sm font-bold text-navy">{data.avmFaresLabel} ↗</a></div></div></section>
<section className="bg-gold py-16 text-navy"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em]">{data.tipEyebrow}</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">{data.tipTitle}</h2><p className="mx-auto mt-4 max-w-3xl text-navy/75">{data.tipText}</p></div></section>
<section className="py-20"><div className="mx-auto max-w-5xl px-5 lg:px-8"><SectionTitle eyebrow={data.faqEyebrow} title={data.faqTitle} text={data.faqText}/><div className="border-y border-navy/15">{data.faq.map(([q,a])=><details key={q} className="group border-b border-navy/10 py-5 last:border-0"><summary className="flex cursor-pointer list-none items-start justify-between gap-4 font-serif text-2xl text-navy"><span>{q}</span><span className="shrink-0 text-gold transition group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl text-slate-600">{a}</p></details>)}</div><div className="mt-7 text-center"><Link href={`/${lang}/faq`} className="inline-flex rounded-full bg-navy px-6 py-3 font-bold text-white">{data.allFaqLabel}</Link></div></div></section>
</main><Footer lang={lang}/></>}
