import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

type Lang='it'|'en'|'de'|'fr'|'es'|'zh';

const copy:Record<Lang,{
  home:string;experiences:string;title:string;subtitle:string;kicker:string;
  intro:string;sections:{title:string;text:string}[];tip:string;practical:string[];
  official:string;book:string;back:string;related:string;cicchetti:string;discover:string;practicalTitle:string;
}>={
 it:{home:'Home',experiences:'Esperienze',kicker:'Esperienza autentica • Cannaregio',title:'Voga alla veneta con Row Venice: Venezia vista dal remo',subtitle:'Non limitarti a guardare i gondolieri: prova in prima persona uno dei gesti più veneziani che esistano.',intro:'Row Venice nasce per mantenere viva e diffondere la cultura acquea veneziana. L’organizzazione è formata soprattutto da donne vogatrici e propone esperienze che permettono ai visitatori di avvicinarsi davvero alla voga alla veneta.',sections:[{title:'Una vera lezione di voga alla veneta',text:'La lezione privata classica dura 80 minuti e si svolge su una tradizionale batela costruita a mano. Si comincia imparando il gesto a prua, poi si parte nei canali tranquilli e si prova, quando le condizioni lo permettono, anche la posizione a poppa: quella da cui si governa la barca come fanno i gondolieri.'},{title:'Venezia dall’acqua, ma partecipando',text:'Non è un semplice giro in barca. Ogni partecipante può provare a vogare e capire quanto equilibrio, tecnica e sensibilità servano per muoversi sull’acqua veneziana. Il percorso parte da Cannaregio, nei pressi della Sacca della Misericordia.'},{title:'Un’esperienza adatta anche alle famiglie',text:'Row Venice indica che non ci sono limiti di età: i bambini possono provare a vogare da soli oppure con l’aiuto dell’istruttrice o di un genitore. È comunque sempre bene indicare l’età dei bambini al momento della prenotazione.'},{title:'Cicchetto Row e altre proposte',text:'Oltre alla lezione classica, Row Venice propone anche il Cicchetto Row, che abbina la voga a soste nei bàcari, e attività serali sul Canal Grande. Le formule disponibili possono cambiare: conviene verificare sempre il programma ufficiale.'}],tip:'Questa è una di quelle esperienze che fanno capire Venezia molto più di tante fotografie: per qualche minuto smetti di essere spettatore e impari a muoverti nella città usando il suo mezzo più antico.',practical:['Le lezioni classiche sono private e durano circa 80 minuti.','Punto d’incontro a Cannaregio, nell’area della Sacca della Misericordia.','Scarpe comode e abbigliamento sportivo sono consigliati.','Nei mesi caldi porta acqua e un cappello.','Orari, disponibilità, formule e tariffe possono cambiare: controlla sempre il sito ufficiale prima di prenotare.'],practicalTitle:'Informazioni pratiche',official:'Sito ufficiale Row Venice',book:'Vedi le lezioni e prenota',back:'Torna alle Esperienze',related:'Potrebbe interessarti anche',cicchetti:'Cicchetti veneziani',discover:'Scopri Venezia'},
 en:{home:'Home',experiences:'Experiences',kicker:'Authentic experience • Cannaregio',title:'Venetian rowing with Row Venice: see Venice from the oar',subtitle:'Do not just watch gondoliers at work: try one of Venice’s most distinctive traditions yourself.',intro:'Row Venice works to keep Venetian water culture alive and share it with visitors. The organisation is made up mainly of women rowers and offers hands-on experiences centred on voga alla veneta.',sections:[{title:'A real Venetian rowing lesson',text:'The classic private lesson lasts about 80 minutes aboard a traditional hand-crafted batela. You begin by learning the stroke at the bow, then set off through quieter canals and, when conditions allow, try rowing and steering from the stern just as a gondolier does.'},{title:'Venice from the water, as a participant',text:'This is not simply a boat ride. Each participant can try rowing and discover how much balance, technique and sensitivity are required to move through Venice by oar. The meeting point is in Cannaregio near the Sacca della Misericordia.'},{title:'A family-friendly experience',text:'Row Venice states that there is no fixed age limit: children can row on their own or with help from an instructor or parent. It is still a good idea to provide children’s ages when booking.'},{title:'Cicchetto Row and other options',text:'Alongside the classic lesson, Row Venice also offers Cicchetto Row, combining rowing with stops at bacari, as well as evening rowing experiences on the Grand Canal. Available formats may change, so check the official programme.'}],tip:'This is the kind of experience that explains Venice better than dozens of photos: for a while you stop being a spectator and learn how the city moves on water.',practical:['Classic lessons are private and last about 80 minutes.','Meeting point in Cannaregio, by the Sacca della Misericordia area.','Comfortable shoes and sports clothing are recommended.','Bring water and a hat on hot days.','Times, availability, formats and rates can change: always check the official website before booking.'],practicalTitle:'Practical information',official:'Official Row Venice website',book:'See lessons and book',back:'Back to Experiences',related:'You may also like',cicchetti:'Venetian cicchetti',discover:'Discover Venice'},
 de:{home:'Startseite',experiences:'Erlebnisse',kicker:'Authentisches Erlebnis • Cannaregio',title:'Voga alla veneta mit Row Venice: Venedig vom Ruder aus erleben',subtitle:'Nicht nur den Gondolieri zusehen: Probieren Sie eine der typischsten venezianischen Traditionen selbst aus.',intro:'Row Venice setzt sich dafür ein, die venezianische Wasserkultur lebendig zu halten und weiterzugeben. Die Organisation besteht überwiegend aus Ruderinnen und vermittelt die traditionelle Voga alla veneta aktiv an Besucher.',sections:[{title:'Eine echte Lektion in Voga alla veneta',text:'Die klassische private Lektion dauert etwa 80 Minuten und findet auf einer handgefertigten traditionellen Batela statt. Zuerst lernen Sie den Ruderschlag am Bug, danach geht es durch ruhigere Kanäle; wenn die Bedingungen passen, können Sie auch die Steuerposition am Heck ausprobieren – ähnlich wie ein Gondoliere.'},{title:'Venedig vom Wasser aus – nicht nur als Zuschauer',text:'Es ist keine gewöhnliche Bootsfahrt. Die Teilnehmenden können selbst rudern und erleben, wie viel Gleichgewicht, Technik und Feingefühl nötig sind. Treffpunkt ist in Cannaregio nahe der Sacca della Misericordia.'},{title:'Auch für Familien geeignet',text:'Row Venice gibt kein festes Mindestalter an: Kinder können selbst rudern oder von einer Instruktorin beziehungsweise einem Elternteil unterstützt werden. Das Alter der Kinder sollte bei der Buchung angegeben werden.'},{title:'Cicchetto Row und weitere Angebote',text:'Neben der klassischen Lektion gibt es auch den Cicchetto Row mit Stopps in Bàcari sowie Abendangebote auf dem Canal Grande. Verfügbare Formate können sich ändern; prüfen Sie daher das offizielle Programm.'}],tip:'Ein Erlebnis, das Venedig besser erklärt als viele Fotos: Für eine Weile sind Sie nicht nur Besucher, sondern lernen, wie sich die Stadt auf dem Wasser bewegt.',practical:['Klassische Lektionen sind privat und dauern etwa 80 Minuten.','Treffpunkt in Cannaregio im Bereich Sacca della Misericordia.','Bequeme Schuhe und sportliche Kleidung werden empfohlen.','An heißen Tagen Wasser und Kopfbedeckung mitnehmen.','Zeiten, Verfügbarkeit, Formate und Preise können sich ändern: vor der Buchung immer die offizielle Website prüfen.'],practicalTitle:'Praktische Informationen',official:'Offizielle Website von Row Venice',book:'Lektionen ansehen und buchen',back:'Zurück zu den Erlebnissen',related:'Das könnte Sie auch interessieren',cicchetti:'Venezianische Cicchetti',discover:'Venedig entdecken'},
 fr:{home:'Accueil',experiences:'Expériences',kicker:'Expérience authentique • Cannaregio',title:'Ramer à la vénitienne avec Row Venice : Venise au rythme de la rame',subtitle:'Ne vous contentez pas de regarder les gondoliers : essayez vous-même l’un des gestes les plus vénitiens qui soient.',intro:'Row Venice œuvre pour préserver et transmettre la culture nautique vénitienne. L’organisation est composée principalement de rameuses et propose des expériences pratiques autour de la voga alla veneta.',sections:[{title:'Une vraie leçon de rame vénitienne',text:'La leçon privée classique dure environ 80 minutes à bord d’une batela traditionnelle construite à la main. On commence par apprendre le geste à l’avant, puis on part dans des canaux plus calmes et, si les conditions le permettent, on essaie également la position à l’arrière pour diriger le bateau comme un gondolier.'},{title:'Venise depuis l’eau, en participant',text:'Ce n’est pas une simple promenade en bateau. Chaque participant peut essayer de ramer et comprendre l’équilibre, la technique et la sensibilité nécessaires pour se déplacer sur l’eau à Venise. Le rendez-vous se situe à Cannaregio, près de la Sacca della Misericordia.'},{title:'Une expérience adaptée aux familles',text:'Row Venice indique qu’il n’y a pas de limite d’âge fixe : les enfants peuvent ramer seuls ou avec l’aide d’une instructrice ou d’un parent. Il est conseillé d’indiquer leur âge lors de la réservation.'},{title:'Cicchetto Row et autres formules',text:'En plus de la leçon classique, Row Venice propose le Cicchetto Row avec des arrêts dans des bàcari, ainsi que des expériences du soir sur le Grand Canal. Les formules peuvent évoluer : vérifiez toujours le programme officiel.'}],tip:'Une expérience qui aide à comprendre Venise mieux que beaucoup de photos : pendant un moment, vous cessez d’être spectateur et apprenez comment la ville se vit sur l’eau.',practical:['Les leçons classiques sont privées et durent environ 80 minutes.','Rendez-vous à Cannaregio, dans le secteur de la Sacca della Misericordia.','Chaussures confortables et tenue sportive recommandées.','Par temps chaud, prévoyez de l’eau et un chapeau.','Horaires, disponibilités, formules et tarifs peuvent changer : consultez toujours le site officiel avant de réserver.'],practicalTitle:'Informations pratiques',official:'Site officiel Row Venice',book:'Voir les leçons et réserver',back:'Retour aux Expériences',related:'À découvrir aussi',cicchetti:'Cicchetti vénitiens',discover:'Découvrir Venise'},
 es:{home:'Inicio',experiences:'Experiencias',kicker:'Experiencia auténtica • Cannaregio',title:'Voga alla veneta con Row Venice: Venecia desde el remo',subtitle:'No te limites a mirar a los gondoleros: prueba tú mismo una de las tradiciones más venecianas.',intro:'Row Venice trabaja para mantener viva y difundir la cultura acuática veneciana. La organización está formada principalmente por mujeres remeras y ofrece experiencias prácticas centradas en la voga alla veneta.',sections:[{title:'Una auténtica clase de remo veneciano',text:'La clase privada clásica dura unos 80 minutos y se realiza en una batela tradicional hecha a mano. Primero se aprende el gesto en la proa; después se navega por canales tranquilos y, cuando las condiciones lo permiten, se prueba también la posición de popa para gobernar la embarcación como un gondolero.'},{title:'Venecia desde el agua, participando',text:'No es un simple paseo en barco. Cada participante puede probar a remar y descubrir cuánto equilibrio, técnica y sensibilidad hacen falta para moverse por Venecia a remo. El punto de encuentro está en Cannaregio, cerca de la Sacca della Misericordia.'},{title:'Una experiencia también para familias',text:'Row Venice indica que no existe un límite de edad fijo: los niños pueden remar solos o con ayuda de una instructora o de un progenitor. Conviene indicar sus edades al realizar la reserva.'},{title:'Cicchetto Row y otras propuestas',text:'Además de la clase clásica, Row Venice ofrece Cicchetto Row, que combina el remo con paradas en bàcari, y propuestas nocturnas en el Gran Canal. Las modalidades disponibles pueden variar: consulta siempre el programa oficial.'}],tip:'Es una de esas experiencias que explican Venecia mejor que muchas fotografías: durante un rato dejas de ser espectador y aprendes cómo se mueve la ciudad sobre el agua.',practical:['Las clases clásicas son privadas y duran unos 80 minutos.','Punto de encuentro en Cannaregio, zona Sacca della Misericordia.','Se recomienda calzado cómodo y ropa deportiva.','En días calurosos lleva agua y sombrero.','Horarios, disponibilidad, modalidades y precios pueden cambiar: consulta siempre la web oficial antes de reservar.'],practicalTitle:'Información práctica',official:'Web oficial de Row Venice',book:'Ver clases y reservar',back:'Volver a Experiencias',related:'También puede interesarte',cicchetti:'Cicchetti venecianos',discover:'Descubrir Venecia'},
 zh:{home:'首页',experiences:'精选体验',kicker:'地道体验 • Cannaregio',title:'跟着 Row Venice 学威尼斯传统划船：从船桨看威尼斯',subtitle:'不要只看贡多拉船夫划船，亲自体验威尼斯最具代表性的传统之一。',intro:'Row Venice 致力于保护并传播威尼斯的水上文化。团队以女性划手为主，通过亲身参与的方式，让游客真正接触传统的 voga alla veneta 站立式划船技艺。',sections:[{title:'真正的威尼斯传统划船课程',text:'经典私人课程约 80 分钟，使用手工制作的传统 batela 木船。先在船头学习基本划法，随后进入较安静的运河练习；天气和水况合适时，还可以尝试在船尾掌舵，体验类似贡多拉船夫的操船方式。'},{title:'从水上认识威尼斯，而且亲自参与',text:'这不是普通的乘船游览。每位参加者都有机会尝试划船，感受在威尼斯水面移动所需要的平衡、技巧与节奏。集合地点位于 Cannaregio，靠近 Sacca della Misericordia。'},{title:'家庭游客也可以参加',text:'Row Venice 表示课程没有固定年龄限制。儿童可以自己尝试，也可以在教练或家长帮助下划船。预订时建议注明儿童年龄。'},{title:'Cicchetto Row 与其他体验',text:'除了经典课程，Row Venice 还提供把划船与 bàcaro 小酒馆停靠结合起来的 Cicchetto Row，以及大运河夜间划船等活动。具体项目可能调整，请以官方网站为准。'}],tip:'这是那种能让人真正理解威尼斯的体验：短短一段时间里，你不再只是游客，而是在学习这座城市几百年来如何依靠水与船桨生活。',practical:['经典课程为私人课程，时长约 80 分钟。','集合地点在 Cannaregio 的 Sacca della Misericordia 一带。','建议穿舒适鞋子和运动服装。','炎热天气请携带饮用水和遮阳帽。','时间、名额、活动形式和价格可能变化，预订前请查看官方网站。'],practicalTitle:'实用信息',official:'Row Venice 官方网站',book:'查看课程与预订',back:'返回精选体验',related:'你可能还喜欢',cicchetti:'威尼斯 Cicchetti 小吃',discover:'探索威尼斯'}
};

const experienceHref:Record<Lang,string>={it:'/collaborazioni',en:'/en/experiences',de:'/de/experiences',fr:'/fr/experiences',es:'/es/experiences',zh:'/zh/experiences'};
const homeHref:Record<Lang,string>={it:'/',en:'/en',de:'/de',fr:'/fr',es:'/es',zh:'/zh'};
const cicchettiHref:Record<Lang,string>={it:'/journal/cicchetti-veneziani',en:'/en/journal/cicchetti-veneziani',de:'/de/journal/cicchetti-veneziani',fr:'/fr/journal/cicchetti-veneziani',es:'/es/journal/cicchetti-veneziani',zh:'/zh/journal/cicchetti-veneziani'};
const discoverHref:Record<Lang,string>={it:'/scopri-venezia',en:'/en/discover-venice',de:'/de/discover-venice',fr:'/fr/discover-venice',es:'/es/discover-venice',zh:'/zh/discover-venice'};
const officialHref:Record<Lang,string>={it:'https://rowvenice.org/it/',en:'https://rowvenice.org/',de:'https://rowvenice.org/',fr:'https://rowvenice.org/fr/',es:'https://rowvenice.org/',zh:'https://rowvenice.org/'};
const lessonHref:Record<Lang,string>={it:'https://rowvenice.org/it/rv-venetian-rowing-lessons/',en:'https://rowvenice.org/venetian-rowing-lessons/',de:'https://rowvenice.org/venetian-rowing-lessons/',fr:'https://rowvenice.org/fr/rv-venetian-rowing-lessons/',es:'https://rowvenice.org/venetian-rowing-lessons/',zh:'https://rowvenice.org/venetian-rowing-lessons/'};

export default function RowVeniceExperiencePage({lang}:{lang:Lang}){
 const t=copy[lang];
 return <><Header lang={lang==='it'?undefined:lang}/><main>
  <section className="bg-navy pt-20 text-white">
   <div className="mx-auto max-w-7xl px-5 pb-10 pt-12 lg:px-8">
    <nav aria-label="Breadcrumb" className="mb-5 flex flex-wrap gap-2 text-sm text-white/70"><Link href={homeHref[lang]}>{t.home}</Link><span>›</span><Link href={experienceHref[lang]}>{t.experiences}</Link><span>›</span><span className="text-gold">Row Venice</span></nav>
    <p className="text-xs font-black uppercase tracking-[.22em] text-gold">{t.kicker}</p>
    <h1 className="mt-4 max-w-5xl font-serif text-[clamp(3rem,8vw,5.5rem)] leading-none">{t.title}</h1>
    <p className="mt-6 max-w-3xl text-xl text-white/80">{t.subtitle}</p>
   </div>
   <div className="mx-auto max-w-7xl px-5 pb-16 lg:px-8"><div className="relative aspect-[3/2] overflow-hidden rounded-[2rem] bg-white shadow-soft"><Image src="/images/experience-row-venice-cover.webp" alt="Row Venice – voga alla veneta" fill priority sizes="100vw" className="object-cover"/></div></div>
  </section>
  <section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8">
   <p className="font-serif text-3xl leading-relaxed text-navy">{t.intro}</p>
   <div className="mt-14 space-y-12">{t.sections.map((s,i)=><section key={s.title} className="grid gap-5 md:grid-cols-[70px_1fr]"><div className="font-serif text-5xl text-gold">{String(i+1).padStart(2,'0')}</div><div><h2 className="font-serif text-4xl text-navy">{s.title}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{s.text}</p></div></section>)}</div>
  </div></section>
  <section className="bg-cream py-16"><div className="mx-auto max-w-4xl px-5 lg:px-8">
   <div className="rounded-[2rem] bg-gold p-8 text-navy"><p className="text-xs font-black uppercase tracking-[.22em]">Marghera Venice Apartments</p><p className="mt-4 font-serif text-3xl">{t.tip}</p></div>
   <div className="mt-8 rounded-[2rem] bg-white p-8 shadow-soft"><h2 className="font-serif text-3xl text-navy">{t.practicalTitle}</h2><div className="mt-5 space-y-3 text-slate-600">{t.practical.map(x=><p key={x}>• {x}</p>)}</div><div className="mt-7 flex flex-wrap gap-3"><a href={officialHref[lang]} target="_blank" rel="noopener noreferrer" className="rounded-full border border-navy px-6 py-3 font-bold text-navy">{t.official} ↗</a><a href={lessonHref[lang]} target="_blank" rel="noopener noreferrer" className="rounded-full bg-navy px-6 py-3 font-bold text-white">{t.book} ↗</a></div></div>
  </div></section>
  <section className="py-20"><div className="mx-auto max-w-5xl px-5 lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{t.related}</p><div className="mt-7 grid gap-4 md:grid-cols-2"><Link className="rounded-3xl border border-slate-200 p-6 font-serif text-2xl text-navy transition hover:-translate-y-1 hover:shadow-soft" href={cicchettiHref[lang]}>{t.cicchetti} <span className="text-gold">→</span></Link><Link className="rounded-3xl border border-slate-200 p-6 font-serif text-2xl text-navy transition hover:-translate-y-1 hover:shadow-soft" href={discoverHref[lang]}>{t.discover} <span className="text-gold">→</span></Link></div><div className="mt-10 text-center"><Link href={experienceHref[lang]} className="inline-flex rounded-full bg-gold px-7 py-4 font-bold text-navy">{t.back}</Link></div></div></section>
 </main><Footer lang={lang==='it'?undefined:lang}/></>;
}
