import Link from 'next/link';
import type {CultureLang,CulturePlace} from '@/data/culturePlaces';
import {culturePlaces} from '@/data/culturePlaces';
import {cityLabel,cultureDetailPath,cultureIndexPath,kindLabel,provinceOrder} from '@/data/cultureTranslations';
import SectionTitle from '@/components/SectionTitle';

const icon={museum:'🏛️',monument:'🏰',church:'⛪',panorama:'👀'} as const;
const copy:Record<CultureLang,{eyebrow:string;title:string;text:string;open:string;all:string;places:string;provinceIntro:Record<string,string>}>= {
 it:{eyebrow:'Esplora per provincia',title:'Sette province, sette modi diversi di vivere il Veneto',text:'Usa questa panoramica per scegliere una direzione, poi entra nelle singole schede per tempi di visita, prezzi, accesso e fonti ufficiali.',open:'Apri la scheda',all:'Vedi tutti i luoghi culturali',places:'luoghi',provinceIntro:{Venezia:'Ville, archeologia e luoghi culturali della terraferma veneziana.',Padova:'Giotto, università, basiliche, musei e grandi spazi monumentali.',Treviso:'Canova, ville venete, Asolo e musei tra città e colline.',Verona:'Arena, archeologia, musei civici, torri e grandi chiese.',Vicenza:'Il territorio di Palladio, tra architettura, musei e ville.',Belluno:'Musei, Dolomiti, Tiziano e storie di montagna.',Rovigo:'Polesine, archeologia, ville e patrimoni meno conosciuti.'}},
 en:{eyebrow:'Explore by province',title:'Seven provinces, seven different ways to experience Veneto',text:'Choose a direction here, then open each cultural entry for visit times, tickets, access and official sources.',open:'Open entry',all:'View all Veneto cultural sites',places:'places',provinceIntro:{Venezia:'Villas, archaeology and cultural sites across the Venetian mainland.',Padova:'Giotto, the university, basilicas, museums and monumental spaces.',Treviso:'Canova, Venetian villas, Asolo and museums between city and hills.',Verona:'The Arena, archaeology, civic museums, towers and major churches.',Vicenza:'Palladio’s territory, with architecture, museums and villas.',Belluno:'Museums, the Dolomites, Titian and mountain stories.',Rovigo:'Polesine, archaeology, villas and lesser-known heritage.'}},
 de:{eyebrow:'Nach Provinz entdecken',title:'Sieben Provinzen, sieben verschiedene Seiten Venetiens',text:'Wählen Sie hier eine Richtung und öffnen Sie anschließend die einzelnen Kulturorte mit Besuchsdauer, Eintritt, Zugang und offiziellen Quellen.',open:'Eintrag öffnen',all:'Alle Kulturorte in Venetien',places:'Orte',provinceIntro:{Venezia:'Villen, Archäologie und Kulturorte auf dem venezianischen Festland.',Padova:'Giotto, Universität, Basiliken, Museen und Monumentalbauten.',Treviso:'Canova, venezianische Villen, Asolo und Museen zwischen Stadt und Hügeln.',Verona:'Arena, Archäologie, städtische Museen, Türme und große Kirchen.',Vicenza:'Palladios Landschaft mit Architektur, Museen und Villen.',Belluno:'Museen, Dolomiten, Tizian und Geschichten aus den Bergen.',Rovigo:'Polesine, Archäologie, Villen und weniger bekannte Kulturschätze.'}},
 fr:{eyebrow:'Explorer par province',title:'Sept provinces, sept façons de découvrir la Vénétie',text:'Choisissez une direction puis ouvrez les fiches pour la durée de visite, les tarifs, l’accès et les sources officielles.',open:'Ouvrir la fiche',all:'Voir tous les lieux culturels de Vénétie',places:'lieux',provinceIntro:{Venezia:'Villas, archéologie et lieux culturels de la terre ferme vénitienne.',Padova:'Giotto, université, basiliques, musées et grands monuments.',Treviso:'Canova, villas vénitiennes, Asolo et musées entre ville et collines.',Verona:'Arènes, archéologie, musées civiques, tours et grandes églises.',Vicenza:'Le territoire de Palladio, entre architecture, musées et villas.',Belluno:'Musées, Dolomites, Titien et histoires de montagne.',Rovigo:'Polesine, archéologie, villas et patrimoine moins connu.'}},
 es:{eyebrow:'Explora por provincia',title:'Siete provincias, siete formas de vivir el Véneto',text:'Elige una dirección y después abre cada ficha para ver duración, entradas, acceso y fuentes oficiales.',open:'Abrir ficha',all:'Ver todos los lugares culturales del Véneto',places:'lugares',provinceIntro:{Venezia:'Villas, arqueología y lugares culturales de la tierra firme veneciana.',Padova:'Giotto, universidad, basílicas, museos y grandes espacios monumentales.',Treviso:'Canova, villas vénetas, Asolo y museos entre ciudad y colinas.',Verona:'Arena, arqueología, museos cívicos, torres y grandes iglesias.',Vicenza:'El territorio de Palladio, entre arquitectura, museos y villas.',Belluno:'Museos, Dolomitas, Tiziano e historias de montaña.',Rovigo:'Polesine, arqueología, villas y patrimonio menos conocido.'}},
 zh:{eyebrow:'按省份探索',title:'七个省，七种认识威尼托的方式',text:'先选择一个方向，再进入各文化景点页面查看参观时长、票价、入场信息和官方来源。',open:'打开详情',all:'查看全部威尼托文化景点',places:'个地点',provinceIntro:{Venezia:'威尼斯大陆地区的别墅、考古遗址与文化景点。',Padova:'乔托、大学、宗教建筑、博物馆与重要历史空间。',Treviso:'卡诺瓦、威尼托别墅、阿索洛以及城市与丘陵间的博物馆。',Verona:'竞技场、考古遗址、市立博物馆、塔楼与重要教堂。',Vicenza:'帕拉迪奥的土地：建筑、博物馆与别墅。',Belluno:'博物馆、多洛米蒂、提香与山地文化。',Rovigo:'波莱西内地区的考古、别墅与较少为人熟知的文化遗产。'}}
};

function score(p:CulturePlace){
 const priority=['cappella-scrovegni','arena-verona','teatro-olimpico','villa-pisani-stra','villa-emo','villa-barbaro-maser','museo-canova-possagno','palazzo-fulcis','villa-badoer','palazzo-roverella'];
 const i=priority.indexOf(p.slug); return i===-1?100:i;
}

export default function VenetoProvinceNavigator({lang='it'}:{lang?:CultureLang}){
 const t=copy[lang];
 const groups=provinceOrder.map(province=>{
   const items=culturePlaces.filter(p=>p.scope==='veneto'&&p.province===province).sort((a,b)=>score(a)-score(b)||a.name.localeCompare(b.name));
   return {province,items};
 }).filter(x=>x.items.length);
 return <section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8">
   <SectionTitle eyebrow={t.eyebrow} title={t.title} text={t.text}/>
   <div className="space-y-4 lg:hidden">{groups.map(({province,items},i)=><details key={province} open={i===0} className="group overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white shadow-soft"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-6"><span><span className="font-serif text-3xl text-navy">📍 {cityLabel(province,lang)}</span><span className="mt-1 block text-sm text-slate-500">{items.length} {t.places}</span></span><span className="text-2xl text-gold transition-transform group-open:rotate-45">+</span></summary><div className="border-t border-slate-100 bg-cream/50 p-5"><p className="mb-5 leading-7 text-slate-600">{t.provinceIntro[province]}</p><div className="grid gap-3">{items.slice(0,4).map(p=><Link key={p.slug} href={cultureDetailPath('veneto',lang,p.slug)} className="rounded-2xl bg-white p-4 ring-1 ring-black/5"><span className="text-xs font-black uppercase tracking-[.14em] text-gold">{icon[p.kind]} {kindLabel(p.kind,lang)} · {cityLabel(p.city,lang)}</span><span className="mt-1 block font-serif text-xl text-navy">{p.name}</span></Link>)}</div></div></details>)}</div>
   <div className="hidden grid-cols-2 gap-6 lg:grid xl:grid-cols-3">{groups.map(({province,items})=><article key={province} className="rounded-[2rem] bg-cream p-7 shadow-soft"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-gold">📍 {items.length} {t.places}</p><h3 className="mt-2 font-serif text-4xl text-navy">{cityLabel(province,lang)}</h3></div></div><p className="mt-4 min-h-[4.5rem] leading-7 text-slate-600">{t.provinceIntro[province]}</p><div className="mt-5 grid gap-3">{items.slice(0,3).map(p=><Link key={p.slug} href={cultureDetailPath('veneto',lang,p.slug)} className="rounded-2xl bg-white p-4 transition hover:-translate-y-0.5 hover:shadow-sm"><span className="text-xs font-black uppercase tracking-[.12em] text-gold">{icon[p.kind]} {cityLabel(p.city,lang)}</span><span className="mt-1 block font-serif text-xl text-navy">{p.name}</span></Link>)}</div></article>)}</div>
   <div className="mt-10 text-center"><Link href={cultureIndexPath('veneto',lang)} className="inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white hover:bg-gold hover:text-navy">{t.all} →</Link></div>
 </div></section>;
}
