import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import Script from 'next/script';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SectionTitle from '@/components/SectionTitle';
import HubCultureSection from '@/components/HubCultureSection';

export const metadata: Metadata={
 title:'Discover Venice | Local Tips & Venice in One Day',
 description:'Plan your Venice visit from Marghera: culture, islands, children, dogs, transport, events and a simple one-day itinerary.',
 openGraph:{title:'Discover Venice',description:'A practical hub for exploring Venice and its lagoon from Marghera.',images:['/images/scopri-venezia-michael-heise.webp'],locale:'en_GB'},
 twitter:{card:'summary_large_image',title:'Discover Venice | Local Tips',description:'Choose how you want to experience Venice: culture, islands, family, pets, transport or events.',images:['/images/scopri-venezia-michael-heise.webp']},
 alternates:{canonical:'/en/discover-venice',languages:{'it-IT':'/scopri-venezia','en-GB':'/en/discover-venice','de-DE':'/de/discover-venice','fr-FR':'/fr/discover-venice','es-ES':'/es/discover-venice','zh-CN':'/zh/discover-venice','x-default':'/scopri-venezia'}}
};
const itinerary=[['08:30','St Mark’s Square','Arrive early, when the light is beautiful and the city is still relatively quiet.'],['10:30',"Doge’s Palace",'Give yourself enough time for the rooms and the Bridge of Sighs.'],['12:30','Cicchetti','Walk a few streets away from the busiest tourist areas for a more relaxed stop.'],['14:00','Rialto','Cross the bridge and visit the market when it is open.'],['16:00','Castello & Libreria Acqua Alta','Discover a more lived-in and less predictable side of Venice.'],['18:30','Grand Canal at sunset','A vaporetto ride becomes one of the most memorable viewpoints in the city.'],['21:00','Head home at your own pace','Night connections take you back to Marghera.']];
const tips=[['Before 8:30 am','St Mark’s and Rialto are especially enjoyable early in the morning.'],['Carry a refillable bottle','Public drinking-water fountains can be found around the city.'],['Cicchetti beyond the main squares','Walking just a few streets away can make a real difference.'],['Vaporetto at sunset','A simple way to experience the Grand Canal from a special perspective.'],['Cannaregio in the evening','A more relaxed atmosphere with places also frequented by locals.'],['Comfortable shoes','Bridges and stone paving make good walking shoes essential.']];
const family=[['Natural History Museum','Dinosaurs, animals and displays that can engage both children and adults.'],['Vaporetto','For younger visitors, travelling on the water is already part of the adventure.'],['Libreria Acqua Alta','A quirky, colourful stop that children are likely to remember.'],['Campi & gelato','Build in regular breaks and leave room for spontaneous discoveries.']];
const pet=[['Public transport','Keep a muzzle available together with the lead and always check the latest ACTV rules.'],['Quieter walks','Castello, Sant’Elena and parts of the Lido offer a more relaxed pace.'],['Water & breaks','Bring a foldable bowl and plan extra stops during hot weather.'],['A pet-friendly home','Dog bed and bowls are available free of charge in our apartments.']];
const islands=[['Murano','Glassmaking, furnaces and a production history worth more than a quick stop.','/images/murano-glass.webp','/en/guide/murano'],['Burano','Colour, fishing and lace: much more than a photo backdrop.','/images/burano-canale.webp','/en/guide/burano'],['Lido','Sea, Liberty architecture, cinema, Malamocco and bicycles.','/images/lido-venezia-spiaggia.webp','/en/guide/lido-di-venezia'],['Pellestrina','Fishing villages, the Murazzi and a lagoon landscape best explored slowly.','/images/guide-pellestrina-final.webp','/en/guide/pellestrina'],["Sant’Erasmo","Venice's garden island: fields, artichokes, bicycles and the Bacan.",'/images/guide-sant-erasmo-final.webp','/en/guide/sant-erasmo'],['Certosa','A green pause close to the city, with open space and lagoon views.','/images/guide-certosa-final.webp','/en/guide/certosa']];
const hub=[
 ['01','Museums, monuments & churches','Average visit time, prices and practical information for the places that deserve your time.','/en/guide/venice-museums'],
 ['02','The lagoon islands','Murano, Burano, Lido, Pellestrina, Sant’Erasmo and Certosa: choose the island that suits your day.','#islands'],
 ['03','Venice with children','Museums, vaporetto rides, breaks and ideas for enjoying the city without turning the day into a race.','/en/journal/venezia-con-bambini'],
 ['04','Venice with your dog','Transport rules, quieter walks and useful tips for a pet-friendly day.','/en/journal/venezia-con-il-cane'],
 ['05','Getting there & around','Bus, train, tickets, airports and night connections from the apartments.','/en/getting-to-venice'],
 ['06','Events & stories','Exhibitions, festivals, traditions and current dates in our Journal.','/en/journal'],
];

export default function DiscoverVenice(){return <><Header lang="en"/><main className="editorial-page" data-build="discover-venice-refresh-2026-09-07">
<section className="relative min-h-[74vh] overflow-hidden pt-20"><Image src="/images/scopri-venezia-michael-heise.webp" alt="St Mark's Basin in Venice with the Doge's Palace and St Mark's Campanile" fill priority sizes="100vw" className="object-cover object-center"/><div className="hero-overlay absolute inset-0"/><div className="relative mx-auto flex min-h-[calc(74vh-5rem)] max-w-7xl items-end px-5 pb-14 pt-24 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-6 flex items-center gap-2 text-sm text-white/75"><Link href="/en" className="hover:text-gold">Home</Link><span>›</span><span className="text-gold">Discover Venice</span></nav><p className="text-xs font-black uppercase tracking-[.25em] text-gold">The city, the islands, your kind of trip</p><h1 className="mt-4 font-serif text-6xl leading-none md:text-8xl">Discover Venice at your own pace.</h1><p className="mt-6 max-w-3xl text-xl text-white/85">You do not need to read everything before you leave. Choose what interests you and use this page as your compass.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#choose" className="rounded-full bg-gold px-7 py-4 font-bold text-navy">Choose your Venice</a><a href="#one-day" className="rounded-full border border-white/60 px-7 py-4 font-bold text-white">First visit</a></div></div></div></section>

<section id="choose" className="bg-cream py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Explore by interest" title="What kind of Venice do you want to experience?" text="Art, islands, family, pets, events or transport: jump straight to the guide you actually need."/><div className="mt-10 border-y border-navy/15">{hub.map(([n,title,text,href])=><Link key={n} href={href} className="group grid gap-3 border-b border-navy/10 py-6 last:border-0 md:grid-cols-[72px_1fr_auto] md:items-center"><span className="font-serif text-3xl text-gold">{n}</span><span><strong className="block font-serif text-3xl text-navy transition group-hover:text-gold">{title}</strong><span className="mt-1 block max-w-3xl text-slate-600">{text}</span></span><span className="text-2xl text-gold">→</span></Link>)}</div></div></section>

<section id="getting-there" className="py-20"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">From Marghera to Venice</p><h2 className="mt-3 font-serif text-5xl text-navy">Leave the car at home. Venice starts with a simple ride.</h2><p className="mt-5 text-lg text-slate-600">Free private parking at the apartments means you can forget about parking in Venice. Bus and train are the practical choices, including a night connection.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/en/getting-to-venice" className="rounded-full bg-navy px-6 py-3 font-bold text-white">Transport, tickets & airports</Link><a href="https://avm.avmspa.it/en/content/venice-urban-services-0" target="_blank" rel="noopener noreferrer" className="rounded-full border border-navy/20 px-6 py-3 font-bold text-navy">Official ACTV information ↗</a></div></div><div className="border-y border-slate-200">{[['6 / 6L','Daytime buses to Venezia – Piazzale Roma'],['N2','Night connection between Venice and Marghera'],['Train','Venezia Mestre → Venezia Santa Lucia']].map(([title,text])=><div key={title} className="grid gap-2 border-b border-slate-200 py-5 last:border-0 sm:grid-cols-[130px_1fr]"><strong className="font-serif text-2xl text-navy">{title}</strong><span className="text-slate-600">{text}</span></div>)}</div></div></section>

<section id="one-day" className="bg-navy py-20 text-white"><div className="mx-auto max-w-6xl px-5 lg:px-8"><SectionTitle eyebrow="First visit" title="Venice in one day, without turning it into a race" text="A simple order for the day. Use it as orientation, not as a list you must complete."/><div className="mt-10 border-y border-white/20">{itinerary.map(([time,title,text])=><div key={time} className="grid gap-2 border-b border-white/15 py-5 last:border-0 md:grid-cols-[110px_230px_1fr]"><strong className="text-gold">{time}</strong><h3 className="font-serif text-2xl">{title}</h3><p className="text-white/70">{text}</p></div>)}</div></div></section>

<HubCultureSection scope="venice" lang="en"/>

<section className="bg-cream py-20"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-2 lg:px-8"><div className="relative min-h-[360px] overflow-hidden rounded-[1.75rem]"><Image src="/images/venezia-bambini-campo-nuova.webp" alt="Children playing football in a traditional Venetian campo" fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover object-center"/></div><div className="flex flex-col justify-center"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Venice with children</p><h2 className="mt-3 font-serif text-5xl text-navy">Turn the city into an adventure, not a timetable.</h2><p className="mt-5 text-lg text-slate-600">{family[0][1]} {family[3][1]}</p><Link href="/en/journal/venezia-con-bambini" className="mt-7 inline-flex w-fit rounded-full bg-navy px-6 py-3 font-bold text-white">Open the family guide</Link></div></div></section>
<section className="py-20"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[1fr_.95fr] lg:px-8"><div className="flex flex-col justify-center"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Pet Friendly</p><h2 className="mt-3 font-serif text-5xl text-navy">Venice with your dog, with a little planning.</h2><p className="mt-5 text-lg text-slate-600">{pet[0][1]} {pet[2][1]}</p><Link href="/en/journal/venezia-con-il-cane" className="mt-7 inline-flex w-fit rounded-full bg-navy px-6 py-3 font-bold text-white">Open the Pet Friendly guide</Link></div><div className="relative min-h-[350px] overflow-hidden rounded-[1.75rem]"><Image src="/images/journal-venezia-cane.webp" alt="Visiting Venice with a dog" fill sizes="(min-width:1024px) 48vw, 100vw" className="object-cover"/></div></div></section>

<section className="bg-navy py-20 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Our local touch" title="Six small tips that can make a big difference" text="No rigid rules, just simple habits that make the city easier to enjoy."/><div className="mt-8 grid sm:grid-cols-2">{tips.map(([title,text],i)=><div key={title} className={`grid grid-cols-[40px_1fr] gap-3 py-6 ${i<4?'border-b border-white/15':''} ${i%2===0?'sm:pr-8':'sm:border-l sm:border-white/15 sm:pl-8'}`}><span className="font-serif text-2xl text-gold">0{i+1}</span><div><h3 className="font-serif text-2xl">{title}</h3><p className="mt-2 text-white/70">{text}</p></div></div>)}</div></div></section>

<section id="islands" className="bg-cream py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="If you have more time" title="The lagoon beyond historic Venice" text="Choose an island for the kind of day you want, rather than trying to collect them all."/><div className="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{islands.map(([title,text,image,href])=><article key={title} className="overflow-hidden rounded-[1.75rem] bg-white"><div className="relative h-56"><Image src={image} alt={`${title} in the Venetian Lagoon`} fill sizes="(min-width:1024px) 33vw, 100vw" className="object-cover"/></div><div className="p-6"><h2 className="font-serif text-3xl text-navy">{title}</h2><p className="mt-2 text-slate-600">{text}</p><Link href={href} className="mt-4 inline-block font-bold text-gold">Open the island guide →</Link></div></article>)}</div></div></section>

<section className="py-20"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.75fr_1.25fr] lg:px-8"><div className="flex flex-col justify-center"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Find your bearings</p><h2 className="mt-3 font-serif text-5xl text-navy">Venice and the lagoon on one map</h2><p className="mt-5 text-lg text-slate-600">Use the map to understand the relationship between historic Venice, the lagoon islands and the main landmarks. Then open Maps for the exact route.</p></div><div className="overflow-hidden rounded-[1.75rem] bg-cream"><Image src="/images/mappa-venezia-finale.webp" alt="Illustrated map of Venice showing the Grand Canal, St Mark's Square, Rialto, Murano, Burano and the Lido" width={1408} height={1056} className="h-auto w-full"/></div></div></section>

<section className="bg-gold py-20 text-navy"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-2 lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em]">More than Venice</p><h2 className="mt-3 font-serif text-5xl">If you have at least three days, look beyond the lagoon.</h2><p className="mt-5 text-lg text-navy/75">Free private parking makes it easy to dedicate a day to the Brenta Riviera, Prosecco Hills or one of Veneto's art cities.</p><Link href="/en/discover-veneto" className="mt-7 inline-flex rounded-full bg-navy px-7 py-4 font-bold text-white">Discover Veneto</Link></div><div className="border-t border-navy/20 pt-8 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><p className="text-xs font-black uppercase tracking-[.22em]">Choose your home</p><h2 className="mt-3 font-serif text-4xl">Where do you want to come home to?</h2><p className="mt-4 text-navy/75">Rossi Apartment for families and groups of up to 7 guests; Dimora Castelli for couples, smaller families and guests looking for a quieter stay.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/en/apartments/rossi-apartment" className="rounded-full bg-navy px-6 py-3 font-bold text-white">Rossi Apartment</Link><Link href="/en/apartments/dimora-castelli" className="rounded-full border border-navy px-6 py-3 font-bold text-navy">Dimora Castelli</Link></div></div></div></section>
</main><Footer lang="en"/><Script id="tourist-destination-schema-en" type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'TouristDestination',name:'Venice',description:'Practical English guide to Venice and the lagoon from Marghera Venice Apartments.',touristType:['Families','Couples','Travellers with pets'],containedInPlace:{'@type':'AdministrativeArea',name:'Veneto'}})}}/></>}
