import type {Metadata} from 'next';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
export const metadata:Metadata={title:'Useful official links for Venice',description:'Official English-language resources for Venice transport, tickets, museums, events, tides and travel across Veneto.',alternates:{canonical:'/en/useful-links',languages:{'it-IT':'/link-utili','en-GB':'/en/useful-links','de-DE':'/de/useful-links','fr-FR':'/fr/useful-links','es-ES':'/es/useful-links','zh-CN':'/zh/useful-links','x-default':'/link-utili'}},openGraph:{type:'website',images:['/images/home-rialto-vincenzo-landino.webp']},twitter:{card:'summary_large_image',images:['/images/home-rialto-vincenzo-landino.webp']}};
const groups=[
 {title:'Transport & mobility',text:'Timetables, tickets, airports and connections.',links:[['AVM/ACTV','Public transport and mobility services in Venice.','https://avm.avmspa.it/en'],['Venezia Unica','Official tourist services, public transport tickets and passes.','https://www.veneziaunica.it/en'],['Trenitalia','Train timetables and tickets.','https://www.trenitalia.com/en.html'],['ATVO','Airport and regional coach services.','https://www.atvo.it/en.html'],['RadioTaxi Venezia','Taxi information and services in Venice and the mainland.','https://www.radiotaxivenezia.com/'] ]},
 {title:'Venice: official information',text:'Sources for visitor information, rules, events and city services.',links:[['City of Venice','Institutional information and services.','https://www.comune.venezia.it/en'],['Venezia Unica','Official information and services for visitors.','https://www.veneziaunica.it/en'],['Venice Carnival','Official programme and information for the current edition.','https://carnevale.venezia.it/en/']]},
 {title:'Art, museums & events',text:'Check exhibitions, tickets, programmes and opening information.',links:[['La Biennale di Venezia','Art, architecture, cinema, dance, music and theatre.','https://www.labiennale.org/en'],['MUVE – Civic Museums of Venice','Museums, tickets, exhibitions and visitor information.','https://www.visitmuve.it/en/'],['Natural History Museum','Official information about the Giancarlo Ligabue museum.','https://msn.visitmuve.it/en/']]},
 {title:'Veneto & heritage',text:'Explore the region, its culture and heritage beyond Venice.',links:[['Veneto.eu','Official tourism portal of the Veneto Region.','https://www.veneto.eu/en/'],['UNESCO – Venice and its Lagoon','UNESCO World Heritage listing.','https://whc.unesco.org/en/list/394/']]}
];
export default function UsefulLinks(){return <><Header lang="en"/><main><section className="bg-navy px-5 pb-20 pt-36 text-white lg:px-8"><div className="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="mb-6 flex gap-2 text-sm text-white/70"><Link href="/en">Home</Link><span>›</span><span className="text-gold">Useful links</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Official sources</p><h1 className="mt-4 max-w-4xl font-serif text-6xl leading-none md:text-8xl">Useful links</h1><p className="mt-6 max-w-3xl text-xl text-white/75">A small library of official websites for checking transport, fares, events, museums and services before and during your stay.</p></div></section><section className="bg-cream py-20"><div className="mx-auto max-w-7xl space-y-14 px-5 lg:px-8">{groups.map(group=><section key={group.title}><p className="text-xs font-black uppercase tracking-[.2em] text-gold">Official resources</p><h2 className="mt-2 font-serif text-4xl text-navy md:text-5xl">{group.title}</h2><p className="mt-3 max-w-3xl text-slate-600">{group.text}</p><div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{group.links.map(([name,desc,href])=><a key={name+href} href={href} target="_blank" rel="noopener noreferrer" className="group rounded-[2rem] bg-white p-7 shadow-soft transition hover:-translate-y-1"><h3 className="font-serif text-3xl text-navy">{name}</h3><p className="mt-3 text-slate-600">{desc}</p><span className="mt-5 inline-block font-bold text-gold">Visit official website ↗</span></a>)}</div></section>)}</div></section></main><Footer lang="en"/></>}
