import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import Script from 'next/script';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SectionTitle from '@/components/SectionTitle';

export const metadata: Metadata = {
  title: 'Discover Veneto from Venice | Day Trips from Marghera',
  description: 'Explore Veneto from Marghera: Brenta Riviera, Prosecco Hills, Padua, Treviso, Verona, Chioggia and the Dolomites, with free private parking at your apartment.',
  openGraph: {title:'Discover Veneto from Venice',description:'Day-trip ideas across Veneto with Marghera as your convenient base near Venice.',images:['/images/veneto-colline-prosecco-final.webp'],locale:'en_GB'},
  twitter:{card:'summary_large_image',title:'Discover Veneto from Venice',description:'Day trips across Veneto from your apartment in Marghera.',images:['/images/veneto-colline-prosecco-final.webp']},
  alternates:{canonical:'/en/discover-veneto',languages:{'it-IT':'/scopri-il-veneto','en-GB':'/en/discover-veneto','de-DE':'/de/discover-veneto','fr-FR':'/fr/discover-veneto','es-ES':'/es/discover-veneto','zh-CN':'/zh/discover-veneto','x-default':'/scopri-il-veneto'}}
};

const destinations=[
 {title:'Brenta Riviera',eyebrow:'Villas, waterways and landscapes',text:'A route through Venetian villas, small towns, historic gardens and views along the Brenta Canal. It is one of our favourite day trips for guests travelling by car.',image:'/images/veneto-riviera-brenta-final.webp',note:'Ideal for half a day or a full day.'},
 {title:'Prosecco Hills',eyebrow:'Valdobbiadene and beyond',text:'Panoramic roads, vineyards, small villages and wineries. Take it slowly, combining landscapes, tastings and stops in the hill towns.',image:'/images/veneto-colline-prosecco-final.webp',note:'Perfect for wine, nature and photography lovers.'},
 {title:'Padua',eyebrow:'Art and city life',text:"Arcaded streets, lively squares and markets, St Anthony's Basilica and a vibrant historic centre make Padua an easy addition to a longer stay in Veneto.",image:'/images/veneto-padova-final.webp',note:'Allow a full day for art, walking and local food.'},
 {title:'Treviso',eyebrow:'Canals and porticoes',text:'An elegant, compact city of canals, squares and porticoes, with a relaxed atmosphere that rewards an unhurried walk.',image:'/images/veneto-treviso-final.webp',note:'Also suitable for a shorter half-day visit.'},
 {title:'Chioggia & Pellestrina',eyebrow:'Authentic lagoon life',text:'Canals, fish markets, beaches and a more everyday side of lagoon life. A rewarding route for travellers looking for the sea and local traditions.',image:'/images/veneto-chioggia-pellestrina-final.webp',note:'Especially enjoyable in the warmer months.'},
 {title:'Verona',eyebrow:'History and romance',text:"The Arena, historic squares, bridges and atmospheric streets. It is farther from Marghera, but makes an excellent full-day trip to one of Veneto's best-known art cities.",image:'/images/veneto-verona-final.webp',note:'Leave in the morning and plan a full day.'},
 {title:'Dolomites',eyebrow:'A day in the mountains',text:'Alpine lakes, mountain passes and dramatic scenery for guests travelling by car. Choose one area, leave early and always check weather and road conditions before setting out.',image:'/images/guide-dolomiti-final.webp',note:'Our longest suggested excursion: plan a full day carefully.'},
];
const reasons=[
 ['Free private parking','Set off directly from your apartment without searching for parking every morning.'],
 ['Freedom to explore','Combine Venice with art cities, vineyards, beaches, mountains and the lagoon.'],
 ['A comfortable return','After your day trip, come back to a quiet apartment with a kitchen and home comforts.'],
 ['Travel at your pace','Choose each day according to the weather, season and your own rhythm.'],
];
const trainCities=[
 {name:'Padua',time:'about 15–30 min from Venezia Mestre',why:'One of the easiest rail day trips: art, lively squares and city life in a very straightforward day out.',sights:'Scrovegni Chapel · Basilica of St Anthony · Prato della Valle · Piazza delle Erbe and Piazza della Frutta',href:'/en/guide/padova'},
 {name:'Treviso',time:'about 20–30 min from Venezia Mestre',why:'Compact, elegant and relaxed: an excellent half-day or full-day trip among canals, porticoes and the historic centre.',sights:'Piazza dei Signori · Buranelli Canal · Cathedral · Isola della Pescheria',href:'/en/guide/treviso'},
 {name:'Verona',time:'about 55–75 min from Venezia Mestre, depending on the train',why:'A full day in one of Veneto’s great art cities, without needing to drive.',sights:'Arena · Piazza delle Erbe · Castelvecchio · Ponte Scaligero and the Adige riverfront',href:'/en/guide/verona'}
];
const tips=['Do not overfill every day: leave room for stops, detours and small towns.','Book winery visits and guided experiences in advance and always check opening times.','Check traffic, parking and weather conditions before setting off.','When travelling with children or pets, plan regular breaks and shorter stops.'];

export default function DiscoverVeneto(){return <><Header lang="en"/><main>
<section className="relative min-h-[78vh] overflow-hidden pt-20"><Image src="/images/veneto-hero-prosecco-final.webp" alt="Prosecco Hills in Veneto, Italy, with vineyards and rolling countryside" fill priority sizes="100vw" className="object-cover object-center"/><div className="hero-overlay absolute inset-0"/><div className="relative mx-auto flex min-h-[calc(78vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-24 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-6 flex items-center gap-2 text-sm text-white/75"><Link href="/en" className="hover:text-gold">Home</Link><span>›</span><span className="text-gold">Discover Veneto</span></nav><p className="text-xs font-black uppercase tracking-[.25em] text-gold">Your car, our convenient starting point</p><h1 className="mt-4 font-serif text-6xl leading-none md:text-8xl">Discover Veneto beyond Venice.</h1><p className="mt-6 max-w-3xl text-xl text-white/85">From the villas of the Brenta Riviera to the Prosecco Hills, art cities, the lagoon and the Dolomites: free private parking gives you the freedom to explore more of Veneto.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#destinations" className="rounded-full bg-gold px-7 py-4 font-bold text-navy">Explore destinations</a><a href="#veneto-map" className="rounded-full border border-white/60 px-7 py-4 font-bold text-white">View the map</a></div></div></div></section>
<section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Why stay in Marghera" title="A strategic base for exploring Veneto" text="You do not have to choose between Venice and the rest of Veneto: enjoy both during the same stay."/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{reasons.map(([title,text])=><article key={title} className="rounded-[2rem] bg-white p-8 shadow-soft"><div className="text-2xl text-gold">✦</div><h2 className="mt-4 font-serif text-3xl text-navy">{title}</h2><p className="mt-3 text-slate-600">{text}</p></article>)}</div></div></section>
<section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="No car needed" title="Art cities you can reach by train" text="Marghera is also a strategic base when you want to explore Veneto without driving: several art cities are directly accessible from Venezia Mestre station."/><div className="grid gap-6 lg:grid-cols-3">{trainCities.map(city=><article key={city.name} className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-7 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{city.time}</p><h2 className="mt-3 font-serif text-4xl text-navy">{city.name}</h2><p className="mt-4 text-slate-600">{city.why}</p><p className="mt-5 rounded-2xl bg-cream p-4 text-sm font-semibold leading-6 text-navy">{city.sights}</p><div className="mt-auto flex flex-wrap gap-3 pt-6"><Link href={city.href} className="rounded-full bg-gold px-5 py-3 font-bold text-navy">Open guide</Link><a href="https://www.trenitalia.com/" target="_blank" rel="noopener noreferrer" className="rounded-full border border-navy px-5 py-3 font-bold text-navy">Trenitalia ↗</a></div></article>)}</div><p className="mt-5 text-sm text-slate-500">Journey times are indicative and vary by service. Always check the timetable for your travel day.</p></div></section>
<section id="veneto-map" className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Find your way" title="Marghera at the centre of your trip" text="Our illustrated map highlights destinations to consider during your stay. Journey times vary with traffic, transport choice and season."/><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-cream shadow-soft"><Image src="/images/mappa-veneto-definitiva.webp" alt="Illustrated map of Veneto showing Marghera, Venice, Brenta Riviera, Padua, Treviso, Valdobbiadene, Verona, the Dolomites, Jesolo, Pellestrina and Chioggia" width={1536} height={1024} className="h-auto w-full"/></div></div></section>
<section id="destinations" className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Suggested day trips" title="Choose the Veneto that suits your journey" text="Each destination has a different character: villas and gardens, vineyards, art cities, beaches, mountains or lagoon landscapes."/><div className="space-y-8">{destinations.map((d,index)=><article key={d.title} className={`grid overflow-hidden rounded-[2rem] bg-white shadow-soft lg:grid-cols-2 ${index%2?'lg:[&>div:first-child]:order-2':''}`}><div className="relative min-h-[340px] lg:min-h-[460px]"><Image src={d.image} alt={`${d.title}, a day-trip destination in Veneto`} fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover"/></div><div className="flex flex-col justify-center p-8 lg:p-12"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{d.eyebrow}</p><h2 className="mt-3 font-serif text-5xl text-navy">{d.title}</h2><p className="mt-5 text-lg text-slate-600">{d.text}</p><p className="mt-6 rounded-2xl bg-cream p-5 font-semibold text-navy">{d.note}</p></div></article>)}</div></div></section>
<section className="bg-navy py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em] text-gold">A tip from Marghera Venice Apartments</p><h2 className="mt-3 font-serif text-5xl">Make room for the Brenta Riviera.</h2><p className="mt-6 text-lg text-white/75">Close to Marghera yet often overlooked by visitors focused only on Venice, its villas, gardens and waterways reveal a completely different side of Veneto.</p><a href="https://www.veneto.eu/en/" target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex rounded-full border border-white/40 px-6 py-3 font-bold text-white">Official Veneto tourism website ↗</a></div><div className="grid gap-4 sm:grid-cols-2">{tips.map((tip,i)=><div key={tip} className="rounded-3xl bg-white/10 p-6"><div className="text-gold">0{i+1}</div><p className="mt-3 text-white/80">{tip}</p></div>)}</div></div></section>
<section className="py-24"><div className="mx-auto max-w-5xl px-5 text-center lg:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Your base for exploring</p><h2 className="mt-3 font-serif text-5xl text-navy">Venice is the destination. Veneto is the journey.</h2><p className="mx-auto mt-5 max-w-3xl text-lg text-slate-600">Choose the apartment that suits you and use Marghera as your base for discovering something different every day.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/en/apartments/rossi-apartment" className="rounded-full bg-gold px-8 py-4 font-bold text-navy">Rossi Apartment</Link><Link href="/en/apartments/dimora-castelli" className="rounded-full border border-navy px-8 py-4 font-bold text-navy">Dimora Castelli</Link></div></div></section>
</main><Footer lang="en"/><Script id="veneto-destination-schema-en" type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'TouristDestination',name:'Veneto',description:'English guide to exploring Veneto from Marghera, near Venice.',containedInPlace:{'@type':'Country',name:'Italy'}})}}/></>}
