from pathlib import Path
import re

def rw(path, fn):
    p=Path(path); s=p.read_text(); n=fn(s); p.write_text(n)
def set_title(path,title):
    p=Path(path); s=p.read_text(); i=s.index('export const metadata'); m=re.search(r"title\s*:\s*([^,\n]+)",s[i:]);
    if not m: raise RuntimeError(f'metadata title not found: {path}')
    a=i+m.start(1); b=i+m.end(1); p.write_text(s[:a]+repr(title)+s[b:])

for path,title in {
'app/page.tsx':'Appartamenti vicino a Venezia con parcheggio privato | Marghera','app/en/page.tsx':'Apartments Near Venice with Free Private Parking | Marghera','app/de/page.tsx':'Ferienwohnungen bei Venedig mit Privatparkplatz | Marghera','app/fr/page.tsx':'Appartements près de Venise avec parking privé | Marghera','app/es/page.tsx':'Apartamentos cerca de Venecia con aparcamiento privado | Marghera','app/zh/page.tsx':'威尼斯附近公寓｜免费私人停车｜Marghera','app/case/rossi-apartment/page.tsx':'Rossi Apartment | 7 ospiti e parcheggio privato vicino a Venezia','app/en/apartments/rossi-apartment/page.tsx':'Rossi Apartment | 7 Guests & Free Parking Near Venice','app/de/apartments/rossi-apartment/page.tsx':'Rossi Apartment | 7 Gäste & Privatparkplatz bei Venedig','app/fr/apartments/rossi-apartment/page.tsx':'Rossi Apartment | 7 voyageurs & parking privé près de Venise','app/es/apartments/rossi-apartment/page.tsx':'Rossi Apartment | 7 huéspedes y parking privado cerca de Venecia','app/zh/apartments/rossi-apartment/page.tsx':'Rossi Apartment｜最多7人・免费私人停车・近威尼斯','app/case/dimora-castelli/page.tsx':'Dimora Castelli | 5 ospiti e parcheggio privato vicino a Venezia','app/en/apartments/dimora-castelli/page.tsx':'Dimora Castelli | 5 Guests & Free Parking Near Venice','app/de/apartments/dimora-castelli/page.tsx':'Dimora Castelli | 5 Gäste & Privatparkplatz bei Venedig','app/fr/apartments/dimora-castelli/page.tsx':'Dimora Castelli | 5 voyageurs & parking privé près de Venise','app/es/apartments/dimora-castelli/page.tsx':'Dimora Castelli | 5 huéspedes y parking privado cerca de Venecia','app/zh/apartments/dimora-castelli/page.tsx':'Dimora Castelli｜最多5人・免费私人停车・近威尼斯','app/come-raggiungere-venezia/page.tsx':'Da Marghera a Venezia: bus, treno, biglietti e parcheggio','app/en/getting-to-venice/page.tsx':'Marghera to Venice: Bus, Train, Tickets & Parking','app/de/getting-to-venice/page.tsx':'Von Marghera nach Venedig: Bus, Zug, Tickets & Parken','app/fr/getting-to-venice/page.tsx':'De Marghera à Venise : bus, train, billets et parking','app/es/getting-to-venice/page.tsx':'De Marghera a Venecia: bus, tren, billetes y aparcamiento','app/zh/getting-to-venice/page.tsx':'从马尔盖拉到威尼斯：公交、火车、车票与停车'}.items(): set_title(path,title)

guide_titles={'murano':['Guida a Murano: vetro, cosa vedere e come arrivare','Murano Guide: Glass, Things to Do & How to Visit','Murano Reiseführer: Glaskunst, Sehenswürdigkeiten & Anreise','Guide de Murano : verre, visites et comment y aller','Guía de Murano: vidrio, qué ver y cómo llegar','穆拉诺岛指南｜玻璃艺术、景点与交通'],'burano':['Guida a Burano: cosa vedere e come arrivare','Burano Guide: Things to See & How to Get There','Burano Reiseführer: Sehenswürdigkeiten & Anreise','Guide de Burano : que voir et comment y aller','Guía de Burano: qué ver y cómo llegar','布拉诺岛指南｜景点与交通'],'lido-di-venezia':['Lido di Venezia: spiagge, bici e cosa fare | Guida','Venice Lido Guide: Beaches, Bikes & Things to Do','Lido di Venezia: Strände, Fahrrad & Tipps | Reiseführer','Lido de Venise : plages, vélo et que faire | Guide','Lido de Venecia: playas, bici y qué hacer | Guía','威尼斯丽都岛指南｜海滩、骑行与游玩'],'dolomiti':['Dolomiti da Venezia: escursione in giornata | Guida','Dolomites Day Trip from Venice | Complete Guide','Dolomiten ab Venedig | Tagesausflug & Reiseführer','Dolomites depuis Venise | Excursion à la journée','Dolomitas desde Venecia | Excursión de un día','从威尼斯去多洛米蒂｜一日游完整指南'],'colline-del-prosecco':['Colline del Prosecco da Venezia | Guida per un giorno','Prosecco Hills from Venice | Day Trip Guide','Prosecco-Hügel ab Venedig | Tagesausflug','Collines du Prosecco depuis Venise | Excursion à la journée','Colinas del Prosecco desde Venecia | Excursión de un día','从威尼斯去普罗塞克丘陵｜一日游指南'],'riviera-del-brenta':['Riviera del Brenta da Venezia | Ville e gita in giornata','Brenta Riviera from Venice | Villas & Day Trip Guide','Brenta-Riviera ab Venedig | Villen & Tagesausflug','Riviera del Brenta depuis Venise | Villas et excursion','Riviera del Brenta desde Venecia | Villas y excursión','从威尼斯去布伦塔河沿岸｜别墅与一日游指南']}; langs=['it','en','de','fr','es','zh']
for slug,titles in guide_titles.items():
    for lang,title in zip(langs,titles): set_title(f'app/guide/{slug}/page.tsx' if lang=='it' else f'app/{lang}/guide/{slug}/page.tsx',title)
for path,lang in [('app/case/rossi-apartment/page.tsx','it'),('app/case/dimora-castelli/page.tsx','it'),('app/en/apartments/rossi-apartment/page.tsx','en'),('app/en/apartments/dimora-castelli/page.tsx','en')]: rw(path,lambda s,lang=lang:re.sub(r'(<ReviewSection\s+property="[^"]+"\s+reviews=\{[^}]+\})(/>)',rf'\1 lang="{lang}"\2',s))
rw('app/layout.tsx',lambda s:s if "email:'info@margheraveniceapartments.com'" in s else s.replace("    logo:'https://www.margheraveniceapartments.com/images/logo.png',\n    sameAs:[","    logo:'https://www.margheraveniceapartments.com/images/logo.png',\n    email:'info@margheraveniceapartments.com',\n    telephone:'+39 351 446 2261',\n    sameAs:["))

def veneto_it(s):
    for a,b in {"title:'Riviera del Brenta'":"title:'Riviera del Brenta',href:'/guide/riviera-del-brenta'","title:'Colline del Prosecco'":"title:'Colline del Prosecco',href:'/guide/colline-del-prosecco'","title:'Padova'":"title:'Padova',href:'/guide/padova'","title:'Treviso'":"title:'Treviso',href:'/guide/treviso'","title:'Chioggia e Pellestrina'":"title:'Chioggia e Pellestrina',href:'/guide/chioggia'","title:'Verona'":"title:'Verona',href:'/guide/verona'","title:'Dolomiti'":"title:'Dolomiti',href:'/guide/dolomiti'"}.items(): s=s.replace(a,b,1)
    return s.replace('<p className="mt-6 rounded-2xl bg-cream p-5 font-semibold text-navy">{d.note}</p>{d.title===\'Dolomiti\'&&<Link href="/guide/dolomiti" className="mt-6 inline-flex w-fit rounded-full bg-gold px-6 py-3 font-bold text-navy">Apri la guida Dolomiti</Link>}','<p className="mt-6 rounded-2xl bg-cream p-5 font-semibold text-navy">{d.note}</p><Link href={d.href} className="mt-6 inline-flex w-fit rounded-full bg-gold px-6 py-3 font-bold text-navy">Leggi la guida completa</Link>')
rw('app/scopri-il-veneto/page.tsx',veneto_it)
def veneto_en(s):
    for a,b in {"title:'Brenta Riviera'":"title:'Brenta Riviera',href:'/en/guide/riviera-del-brenta'","title:'Prosecco Hills'":"title:'Prosecco Hills',href:'/en/guide/colline-del-prosecco'","title:'Padua'":"title:'Padua',href:'/en/guide/padova'","title:'Treviso'":"title:'Treviso',href:'/en/guide/treviso'","title:'Chioggia and Pellestrina'":"title:'Chioggia and Pellestrina',href:'/en/guide/chioggia'","title:'Verona'":"title:'Verona',href:'/en/guide/verona'","title:'Dolomites'":"title:'Dolomites',href:'/en/guide/dolomiti'"}.items(): s=s.replace(a,b,1)
    return s.replace('<p className="mt-6 rounded-2xl bg-cream p-5 font-semibold text-navy">{d.note}</p></div></article>)}</div></div></section>','<p className="mt-6 rounded-2xl bg-cream p-5 font-semibold text-navy">{d.note}</p><Link href={d.href} className="mt-6 inline-flex w-fit rounded-full bg-gold px-6 py-3 font-bold text-navy">Read the full guide</Link></div></article>)}</div></div></section>',1)
rw('app/en/discover-veneto/page.tsx',veneto_en)
def parity(s):
    if 'venetoGuideSlugs' not in s:
        marker='export function LocalizedDiscoverVenetoFull'; i=s.index(marker); s=s[:i]+"const venetoGuideSlugs=['riviera-del-brenta','colline-del-prosecco','padova','treviso','chioggia','verona','dolomiti'] as const;\nconst venetoGuideLabel:Record<ParityLang,string>={de:'Vollständigen Reiseführer lesen',fr:'Lire le guide complet',es:'Leer la guía completa',zh:'阅读完整指南'};\n"+s[i:]
    return s.replace('<p className="mt-6 rounded-2xl bg-cream p-5 font-semibold text-navy">{d.note}</p></div></article>)}</div></div></section>','<p className="mt-6 rounded-2xl bg-cream p-5 font-semibold text-navy">{d.note}</p>{venetoGuideSlugs[i]&&<Link href={`/${lang}/guide/${venetoGuideSlugs[i]}`} className="mt-6 inline-flex w-fit rounded-full bg-gold px-6 py-3 font-bold text-navy">{venetoGuideLabel[lang]}</Link>}</div></article>)}</div></div></section>',1)
rw('components/LocalizedParityPages.tsx',parity)
for path in ['app/journal/page.tsx','app/en/journal/page.tsx']: rw(path,lambda s:s.replace("import JournalFilterGrid from '@/components/JournalFilterGrid';","import JournalDynamicGrid from '@/components/JournalDynamicGrid';").replace('<JournalFilterGrid ','<JournalDynamicGrid '))
def local_rich(s):
    s=s.replace("import JournalFilterGrid from '@/components/JournalFilterGrid';","import JournalDynamicGrid from '@/components/JournalDynamicGrid';").replace('<JournalFilterGrid lang={lang}','<JournalDynamicGrid lang={lang}')
    if "EditorialStayCta" not in s:
        lines=s.splitlines(); i=0
        while i<len(lines) and lines[i].startswith('import '): i+=1
        lines.insert(i,"import EditorialStayCta from '@/components/EditorialStayCta';"); s='\n'.join(lines)+'\n'
    return s.replace(' <section className="py-20"><div className="mx-auto max-w-5xl px-5 lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{t.more}</p>',' <EditorialStayCta lang={lang} context="journal"/>\n <section className="py-20"><div className="mx-auto max-w-5xl px-5 lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">{t.more}</p>',1)
rw('components/LocalizedRich.tsx',local_rich)
for lang,root in [('it',Path('app/journal')),('en',Path('app/en/journal'))]:
    for p in root.glob('*/page.tsx'):
        if p.parent.name=='[eventSlug]': continue
        s=p.read_text()
        if '</article>' not in s or 'EditorialStayCta' in s: continue
        lines=s.splitlines(); i=0
        while i<len(lines) and lines[i].startswith('import '): i+=1
        lines.insert(i,"import EditorialStayCta from '@/components/EditorialStayCta';"); s='\n'.join(lines)+'\n'; pos=s.rfind('</article>'); p.write_text(s[:pos]+f'<EditorialStayCta lang="{lang}" context="journal"/>\n'+s[pos:])
for name in ['GlassWeek2026Article.tsx','HomoFaber2026Article.tsx','BiennaleArte2026Article.tsx','MostraCinema2026Article.tsx','AmerigoVespucciArticle.tsx']:
    p=Path('components')/name
    if not p.exists(): continue
    s=p.read_text()
    if 'EditorialStayCta' not in s:
        lines=s.splitlines(); i=0
        while i<len(lines) and lines[i].startswith('import '): i+=1
        lines.insert(i,"import EditorialStayCta from '@/components/EditorialStayCta';"); s='\n'.join(lines)+'\n'
    if 'EditorialStayCta lang={lang}' not in s:
        pos=s.rfind('<section className="py-')
        if pos!=-1: s=s[:pos]+'<EditorialStayCta lang={lang} context="journal"/>\n'+s[pos:]
    p.write_text(s)
p=Path('data/journal-events-2026.ts'); s=p.read_text(); s=s.replace("export type EventArticle={slug:string;title:string;metaTitle?:string;category:string;description:string;image:string;fallbackImage:string;imageAlt:string;commonsQuery:string;eventDate:string;lead:string;sections:readonly (readonly [string,string])[];tip:string;official:readonly [string,string];relatedSlugs:readonly string[];relatedLinks?:readonly (readonly [string,string])[];internalLink?:{text:string;label:string;href:string;tail:string};eventLocation?:EventLocation;eventLocations?:readonly EventLocation[]};","export type EventArticle={slug:string;title:string;metaTitle?:string;category:string;description:string;image:string;fallbackImage:string;imageAlt:string;commonsQuery:string;eventDate:string;lead:string;sections:readonly (readonly [string,string])[];tip:string;official:readonly [string,string];relatedSlugs:readonly string[];relatedLinks?:readonly (readonly [string,string])[];internalLink?:{text:string;label:string;href:string;tail:string};startDate?:string;endDate?:string;datePublished?:string;dateModified?:string;eventLocation?:EventLocation;eventLocations?:readonly EventLocation[]};")
marker="export const eventSlugs=['venicemarathon-2026','veleziana-2026','venice-cocktail-week-2026','venice-fashion-week-2026','venice-hospitality-challenge-2026','venice-design-week-2026','biennale-musica-2026','salone-alto-artigianato-italiano-2026','venice-noir-2026'] as const;"
if 'eventTechnicalData' not in s: s=s.replace(marker,marker+"\nconst eventTechnicalData:Record<(typeof eventSlugs)[number],{startDate:string;endDate:string;eventLocation?:EventLocation}>={\n'venicemarathon-2026':{startDate:'2026-10-25',endDate:'2026-10-25',eventLocation:{name:'Venezia',addressLocality:'Venezia',addressCountry:'IT'}},'veleziana-2026':{startDate:'2026-10-10',endDate:'2026-10-18',eventLocation:{name:'Bacino di San Marco',addressLocality:'Venezia',addressCountry:'IT'}},'venice-cocktail-week-2026':{startDate:'2026-10-21',endDate:'2026-10-25',eventLocation:{name:'Venezia',addressLocality:'Venezia',addressCountry:'IT'}},'venice-fashion-week-2026':{startDate:'2026-10-19',endDate:'2026-10-24',eventLocation:{name:'Venezia',addressLocality:'Venezia',addressCountry:'IT'}},'venice-hospitality-challenge-2026':{startDate:'2026-10-17',endDate:'2026-10-17',eventLocation:{name:'Bacino di San Marco',addressLocality:'Venezia',addressCountry:'IT'}},'venice-design-week-2026':{startDate:'2026-10-09',endDate:'2026-10-18',eventLocation:{name:'Venezia',addressLocality:'Venezia',addressCountry:'IT'}},'biennale-musica-2026':{startDate:'2026-10-10',endDate:'2026-10-24'},'salone-alto-artigianato-italiano-2026':{startDate:'2026-10-01',endDate:'2026-10-04'},'venice-noir-2026':{startDate:'2026-11-12',endDate:'2026-11-15',eventLocation:{name:'Venezia',addressLocality:'Venezia',addressCountry:'IT'}}};")
s=s.replace("  const local=journalEventImagePair(slug);","  const local=journalEventImagePair(slug);\n  if(item)Object.assign(item,eventTechnicalData[slug]);"); p.write_text(s)
Path('data/journal-event-summaries.ts').unlink(missing_ok=True)
