import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import EditorialStayCta from '@/components/EditorialStayCta';

const BASE='https://www.margheraveniceapartments.com';
const URL=`${BASE}/en/journal/carnevale-di-venezia`;
const IMAGE=`${BASE}/images/journal-carnevale.webp`;

export const metadata:Metadata={title:'Venice Carnival 2027: Dates, Programme & Practical Guide',description:'Venice Carnival 2027 runs from 23 January to 9 February. Official dates, confirmed events, Fat Tuesday, family tips, transport and where to stay.',alternates:{canonical:'/en/journal/carnevale-di-venezia',languages:{'it-IT':'/journal/carnevale-di-venezia','en-GB':'/en/journal/carnevale-di-venezia','de-DE':'/de/journal/carnevale-di-venezia','fr-FR':'/fr/journal/carnevale-di-venezia','es-ES':'/es/journal/carnevale-di-venezia','zh-CN':'/zh/journal/carnevale-di-venezia','x-default':'/journal/carnevale-di-venezia'}},openGraph:{title:'Venice Carnival 2027: Dates, Programme & Practical Guide',description:'What is already official for Venice Carnival 2027 and how to plan your visit.',url:'/en/journal/carnevale-di-venezia',locale:'en_GB',type:'article',images:[{url:'/images/journal-carnevale.webp',alt:'Masks during Venice Carnival'}]},twitter:{card:'summary_large_image',title:'Venice Carnival 2027: Dates & Practical Guide',description:'Official dates and practical planning tips for Venice Carnival 2027.',images:['/images/journal-carnevale.webp']}};

const sections=[
 {title:'Official Venice Carnival 2027 dates',text:'Venice Carnival 2027 runs from 23 January to 9 February. Shrove Tuesday is 9 February, the final day of the edition. These dates are already published by the official Carnival website; the full 2027 public programme is still being completed, so 2026 events should not be copied into the new edition.'},
 {title:'Which weekends are likely to be busiest?',text:'The weekends of 23–24 January, 30–31 January and 6–7 February will naturally attract more visitors. Weekdays usually give you more room to move between calli, museums and campi. For the final weekend and Shrove Tuesday, leave Marghera early and keep your schedule flexible.'},
 {title:'What is already confirmed?',text:'The Official Dinner Show at Ca’ Vendramin Calergi has already published 2027 dates: 30 and 31 January, then 4–9 February, starting at 21:00. The official site lists prices from €650 and requires period costume. These details refer specifically to the Dinner Show, not to the wider Carnival programme.'},
 {title:'Venice Carnival with children',text:'Masks, street performers and events around the city can work very well for families, but do not build the entire day around St Mark’s Square. Combine one main event with quieter campi, a vaporetto ride and proper breaks. Our Venice with children guide has more practical ideas.'},
 {title:'Getting to Venice and parking',text:'If you stay in Marghera, you do not need to drive into Venice. Leave the car at the apartment and use bus or train. On the busiest Carnival days this avoids the cost and uncertainty of Piazzale Roma or Tronchetto parking. Check evening transport times before staying late.'},
 {title:'Venice Access Fee in 2027',text:'There is not yet an official 2027 Access Fee calendar. Do not assume that 2026 dates, prices or exemption rules will automatically return. Check the dedicated guide and the official City of Venice portal before travelling.'},
 {title:'What to eat during Carnival',text:'Frittelle and galani are the classic seasonal sweets. Cicchetti and a bacaro stop can make an easy lunch, but avoid turning the day into a rigid list of famous venues: popular areas can be exceptionally busy during Carnival weekends.'},
 {title:'Where to stay for Venice Carnival',text:'Marghera is practical for families, groups and travellers arriving by car. Rossi Apartment and Dimora Castelli let you keep the car outside the historic centre, use public transport for the day and return to a quieter area in the evening.'},
 {title:'Check the 2027 programme before you leave',text:'The official calendar will continue to change as performances, parades, access rules and bookings are announced. Check the programme for your exact day shortly before travelling. Do not rely on the 2026 timetable for the 2027 edition.'}
];
const faq=[['When is Venice Carnival 2027?','From 23 January to 9 February 2027.'],['When is Shrove Tuesday in 2027?','Shrove Tuesday falls on 9 February 2027 and is the final day of Carnival.'],['Is the full 2027 programme available?','Not yet in complete form. Some events are already confirmed, while the official calendar is still being updated.'],['Is Venice Carnival suitable for children?','Yes, especially if you mix busy events with quieter routes and regular breaks.'],['Should I drive into Venice during Carnival?','If you are staying in Marghera, leaving the car at your accommodation and using bus or train is usually easier.'],['Will the Venice Access Fee apply during Carnival 2027?','No official 2027 calendar has been published yet, so check again before travelling.']] as const;
const related=[['Venice with children','/en/journal/venezia-con-bambini'],['Getting to Venice','/en/getting-to-venice'],['Where to park for Venice','/en/journal/dove-parcheggiare-venezia'],['Venice Access Fee','/en/journal/contributo-accesso-venezia'],['Hidden Venice','/en/guide/venezia-nascosta'],['Venetian cicchetti','/en/journal/cicchetti-veneziani'],['Rossi Apartment','/en/apartments/rossi-apartment'],['Dimora Castelli','/en/apartments/dimora-castelli']] as const;

export default function Article(){const articleSchema={'@context':'https://schema.org','@type':'Article',headline:'Venice Carnival 2027',description:'Official dates, confirmed information and practical planning advice for Venice Carnival 2027.',inLanguage:'en-GB',dateModified:'2026-09-11',image:IMAGE,mainEntityOfPage:{'@type':'WebPage','@id':URL},author:{'@type':'Organization',name:'Marghera Venice Apartments',url:BASE},publisher:{'@type':'Organization',name:'Marghera Venice Apartments',url:BASE}};const breadcrumbSchema={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:`${BASE}/en`},{'@type':'ListItem',position:2,name:'Journal',item:`${BASE}/en/journal`},{'@type':'ListItem',position:3,name:'Venice Carnival 2027',item:URL}]};const faqSchema={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))};return <><Header lang="en"/><main><article className="editorial-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>
<section className="relative min-h-[64svh] overflow-hidden pt-20 sm:min-h-[72vh]"><Image src="/images/journal-carnevale.webp" alt="Masks during Venice Carnival" fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 editorial-cover-shade"/><div className="relative mx-auto flex min-h-[calc(64svh-5rem)] max-w-7xl items-end px-5 pb-16 pt-20 sm:min-h-[calc(72vh-5rem)] lg:px-8"><div className="max-w-5xl text-white"><nav aria-label="Breadcrumb" className="mb-5 flex flex-wrap gap-2 text-sm text-white/70"><Link href="/en">Home</Link><span>›</span><Link href="/en/journal">Journal</Link><span>›</span><span className="text-gold">Venice Carnival 2027</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Events • 23 January – 9 February 2027</p><h1 className="mt-4 font-serif text-[clamp(2.8rem,7vw,5.8rem)] leading-none">Venice Carnival 2027</h1><p className="mt-6 max-w-3xl text-xl text-white/80">Official dates, what is already confirmed and how to plan the visit without carrying 2026 information into 2027.</p></div></div></section>
<section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><p className="font-serif text-3xl leading-relaxed text-navy">Venice Carnival 2027 is officially scheduled for <strong>23 January to 9 February</strong>. The full programme is still evolving, so this guide separates confirmed information from practical advice.</p><div className="mt-14 space-y-12">{sections.map((s,i)=><section key={s.title} className="editorial-section-row grid grid-cols-[34px_1fr] gap-3 sm:grid-cols-[42px_1fr] sm:gap-4"><div className="font-serif text-5xl text-gold">{String(i+1).padStart(2,'0')}</div><div><h2 className="font-serif text-4xl text-navy">{s.title}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{s.text}</p></div></section>)}</div></div></section>
<section className="bg-cream py-16"><div className="mx-auto max-w-4xl px-5 lg:px-8"><div className="rounded-[2rem] bg-gold p-8 text-navy"><p className="text-xs font-black uppercase tracking-[.22em]">Marghera Venice Apartments tip</p><p className="mt-4 font-serif text-3xl">On busy weekends, leave early, choose one must-see event and keep the rest flexible. Carnival is easier to enjoy when you are not chasing ten different appointments.</p></div><div className="mt-8 rounded-[2rem] bg-white p-8 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">Official source</p><p className="mt-3 text-slate-600">The 23 January–9 February 2027 dates and Official Dinner Show details come from the official Venice Carnival website. Check the site again as the public programme is completed.</p><a href="https://carnevale.venezia.it/en/" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex rounded-full bg-navy px-6 py-3 font-bold text-white">Official Venice Carnival website ↗</a></div></div></section>
<section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><h2 className="font-serif text-4xl text-navy">Venice Carnival 2027 FAQs</h2><div className="mt-8 divide-y divide-slate-200 rounded-[2rem] bg-cream px-6 sm:px-8">{faq.map(([q,a])=><details key={q} className="py-5"><summary className="cursor-pointer list-none pr-6 font-serif text-2xl text-navy">{q}</summary><p className="mt-3 leading-7 text-slate-600">{a}</p></details>)}</div></div></section>
<section className="bg-cream py-16"><div className="mx-auto max-w-5xl px-5 lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">Keep planning</p><h2 className="mt-3 font-serif text-4xl text-navy">Useful guides for Carnival</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{related.map(([title,href])=><Link key={href} href={href} className="rounded-3xl bg-white p-6 font-serif text-2xl text-navy shadow-soft">{title} <span className="text-gold">→</span></Link>)}</div></div></section><EditorialStayCta lang="en" context="journal"/></article></main><Footer lang="en"/></>}
