import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata:Metadata = {
  title:'Venice Film Festival 2026: Dates, Tickets & Lido Guide',
  description:'The 83rd Venice Film Festival runs 2–12 September 2026. Discover public screenings, Venice Immersive, red-carpet atmosphere and how to reach the Lido.',
  alternates:{canonical:'/en/journal/mostra-del-cinema',languages:{'it-IT':'/journal/mostra-del-cinema','en-GB':'/en/journal/mostra-del-cinema','de-DE':'/de/journal/mostra-del-cinema','fr-FR':'/fr/journal/mostra-del-cinema','es-ES':'/es/journal/mostra-del-cinema','zh-CN':'/zh/journal/mostra-del-cinema','x-default':'/journal/mostra-del-cinema'}},
  openGraph:{type:'article',images:['/images/journal-mostra-cinema.webp']},twitter:{card:'summary_large_image',images:['/images/journal-mostra-cinema.webp']}
};

const sections = [
  {title:'The 83rd edition: 2–12 September 2026',text:'For eleven days, the Venice Lido becomes one of the centres of international cinema. The main venues are clustered around the Palazzo del Cinema, Palazzo del Casinò, Sala Darsena and other Biennale spaces.'},
  {title:'You can attend without accreditation',text:'The Festival is not only for film professionals and invited guests. Many screenings are open to the public with tickets sold online, while selected gala premieres remain invitation-only. Always check the official daily programme.'},
  {title:'Venice Immersive: cinema beyond the screen',text:'On the Isola del Lazzaretto Vecchio, opposite Riva di Corinto on the Lido, Venice Immersive presents 68 XR projects from 26 countries, including virtual and mixed reality, virtual worlds and immersive installations.'},
  {title:'Red carpet and special moments',text:'On 2 September, George Clooney will receive the Golden Lion for Lifetime Achievement during the opening ceremony. Guest arrivals and red-carpet timings change every day, so check the official calendar shortly before you go.'},
  {title:'How to reach the Lido from Marghera',text:'From Marghera Venice Apartments, travel to Venice by bus or train and continue by vaporetto to the Lido. On the busiest Festival days, allow extra time for connections, queues and heavier passenger traffic.'},
  {title:'Sunday 6 September: two major Venice events',text:'The Festival weekend overlaps with the Regata Storica on the Grand Canal. If you want to experience both on the same day, plan your route carefully and keep an eye on temporary changes to water-bus services.'}
];

export default function Article(){return <><Header lang="en"/><main><article>
  <section className="relative min-h-[72vh] overflow-hidden pt-20"><Image src="/images/journal-mostra-cinema.webp" alt="Venice International Film Festival on the Lido" fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/75 to-navy/20"/><div className="relative mx-auto flex min-h-[calc(72vh-5rem)] max-w-7xl items-end px-5 pb-16 pt-20 lg:px-8"><div className="max-w-4xl text-white"><nav aria-label="Breadcrumb" className="mb-5 flex flex-wrap gap-2 text-sm text-white/70"><Link href="/en">Home</Link><span>›</span><Link href="/en/journal">Journal</Link><span>›</span><span className="text-gold">Venice Film Festival 2026</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Art & Culture</p><h1 className="mt-4 font-serif text-[clamp(3rem,8vw,6rem)] leading-none">Venice Film Festival 2026</h1><p className="mt-6 max-w-3xl text-xl text-white/80">From 2 to 12 September, the Lido returns to the spotlight with premieres, screenings, the red carpet and an entire island dedicated to immersive media.</p></div></div></section>
  <section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><p className="font-serif text-3xl leading-relaxed text-navy">The 83rd Venice International Film Festival is organised by La Biennale di Venezia and directed by Alberto Barbera. Even without an exclusive invitation, visitors can experience the Festival through public screenings, the Lido atmosphere and a programme that turns the island into a global cinema hub for eleven days.</p><div className="mt-14 space-y-12">{sections.map((s,i)=><section key={s.title} className="grid gap-5 md:grid-cols-[70px_1fr]"><div className="font-serif text-5xl text-gold">{String(i+1).padStart(2,'0')}</div><div><h2 className="font-serif text-4xl text-navy">{s.title}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{s.text}</p></div></section>)}</div></div></section>
  <section className="bg-cream py-16"><div className="mx-auto max-w-4xl px-5 lg:px-8"><div className="rounded-[2rem] bg-gold p-8 text-navy"><p className="text-xs font-black uppercase tracking-[.22em]">Marghera Venice Apartments tip</p><p className="mt-4 font-serif text-3xl">Choose a screening you genuinely want to see, leave time to walk around the Lido, and check the programme and transport again on the day. The Festival is often best enjoyed without overplanning every hour.</p></div><div className="mt-8 rounded-[2rem] bg-white p-8 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">Official information</p><p className="mt-3 text-slate-600">Programmes, ticket availability and access conditions may change. Always check La Biennale before your visit.</p><div className="mt-5 flex flex-wrap gap-3"><a href="https://www.labiennale.org/en/cinema/2026" target="_blank" rel="noopener noreferrer" className="inline-flex rounded-full bg-navy px-6 py-3 font-bold text-white">Biennale Cinema 2026 ↗</a><a href="https://www.labiennale.org/en/cinema/2026/program-cinema-2026-public" target="_blank" rel="noopener noreferrer" className="inline-flex rounded-full border border-navy px-6 py-3 font-bold text-navy">Public programme ↗</a></div></div></div></section>
  <section className="py-20"><div className="mx-auto max-w-5xl px-5 lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">September in Venice</p><h2 className="mt-3 font-serif text-4xl text-navy">You may also like</h2><div className="mt-7 grid gap-4 md:grid-cols-2"><Link href="/en/journal/regata-storica-2026" className="rounded-3xl border border-slate-200 p-6 font-serif text-2xl text-navy transition hover:-translate-y-1 hover:shadow-soft">Venice Historical Regatta 2026 <span className="text-gold">→</span></Link><Link href="/en/journal/homo-faber-2026" className="rounded-3xl border border-slate-200 p-6 font-serif text-2xl text-navy transition hover:-translate-y-1 hover:shadow-soft">Homo Faber 2026 <span className="text-gold">→</span></Link></div><div className="mt-10 text-center"><Link href="/en/journal" className="inline-flex rounded-full bg-gold px-7 py-4 font-bold text-navy">Back to Journal</Link></div></div></section>
</article></main><Footer lang="en"/></>}
