import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata:Metadata={
  title:'Homo Faber 2026 Venezia: An Island of Light | Guida',
  description:'Homo Faber 2026 torna a Venezia dal 1 al 30 settembre alla Fondazione Giorgio Cini: 15 installazioni immersive, artigianato contemporaneo, workshop e dimostrazioni.',
  alternates:{canonical:'/journal/homo-faber-2026',languages:{'it-IT':'/journal/homo-faber-2026','en-GB':'/en/journal/homo-faber-2026','de-DE':'/de/journal/homo-faber-2026','fr-FR':'/fr/journal/homo-faber-2026','es-ES':'/es/journal/homo-faber-2026','zh-CN':'/zh/journal/homo-faber-2026','x-default':'/journal/homo-faber-2026'}},
  openGraph:{type:'article',images:['/images/journal-homo-faber-2026-cover.webp']},twitter:{card:'summary_large_image',images:['/images/journal-homo-faber-2026-cover.webp']}
};

const sections=[
  ['Cos’è Homo Faber','Homo Faber è una biennale internazionale dedicata all’eccellenza dell’artigianato contemporaneo. L’edizione 2026 riunisce centinaia di oggetti realizzati a mano da artigiani e creatori provenienti da tutto il mondo.'],
  ['An Island of Light','Sotto la direzione artistica di Es Devlin, la quarta edizione esplora il rapporto tra luce, materiali e mano umana. Quindici installazioni immersive attraversano gli spazi storici e i giardini della Fondazione Giorgio Cini.'],
  ['Non solo una mostra','Il programma comprende dimostrazioni dal vivo, workshop partecipativi, esperienze culinarie e visite speciali: un modo per vedere non soltanto l’oggetto finito, ma anche i gesti, le tecniche e il tempo necessari per realizzarlo.'],
  ['San Giorgio Maggiore','L’isola si trova a pochi minuti di vaporetto da San Marco, ma ha un ritmo molto più tranquillo. La visita a Homo Faber si può abbinare alla Basilica di San Giorgio Maggiore e alla splendida vista sul Bacino di San Marco.'],
  ['Homo Faber in Città','Il progetto prosegue anche fuori da San Giorgio con iniziative diffuse a Venezia dedicate ad artigianato, design, materiali e maestri del territorio. Un’occasione per scoprire luoghi e botteghe che spesso restano fuori dagli itinerari più classici.'],
  ['Informazioni pratiche','Homo Faber 2026 si svolge dal 1 al 30 settembre alla Fondazione Giorgio Cini. Orari, biglietti, workshop e programma giornaliero possono variare: prima della visita controlla sempre il sito ufficiale.']
];

export default function Article(){return <><Header/><main><article>
  <section className="bg-navy pt-20 text-white"><div className="mx-auto max-w-7xl px-5 pb-10 pt-12 lg:px-8"><nav aria-label="Breadcrumb" className="mb-5 flex flex-wrap gap-2 text-sm text-white/70"><Link href="/">Home</Link><span>›</span><Link href="/journal">Journal</Link><span>›</span><span className="text-gold">Homo Faber 2026</span></nav><p className="text-xs font-black uppercase tracking-[.22em] text-gold">Arte & Cultura</p><h1 className="mt-4 max-w-5xl font-serif text-[clamp(3rem,8vw,5.5rem)] leading-none">Homo Faber 2026: An Island of Light</h1><p className="mt-6 max-w-3xl text-xl text-white/80">Dal 1 al 30 settembre, San Giorgio Maggiore diventa un’isola dedicata alla luce, ai materiali e all’eccellenza del saper fare contemporaneo.</p></div><div className="mx-auto max-w-7xl px-5 pb-16 lg:px-8"><div className="relative aspect-video overflow-hidden rounded-[2rem] bg-white shadow-soft"><Image src="/images/journal-homo-faber-2026-cover.webp" alt="Homo Faber 2026 An Island of Light, immagine ufficiale dell’evento" fill priority sizes="100vw" className="object-contain"/></div></div></section>
  <section className="py-20"><div className="mx-auto max-w-4xl px-5 lg:px-8"><p className="font-serif text-3xl leading-relaxed text-navy">Homo Faber 2026: <em>An Island of Light</em> invita a scoprire il rapporto tra luce, materiali e mano umana. La quarta edizione della biennale, curata dalla Michelangelo Foundation e con direzione artistica di Es Devlin, si svolge negli spazi della Fondazione Giorgio Cini sull’Isola di San Giorgio Maggiore.</p><div className="mt-14 space-y-12">{sections.map(([title,text],i)=><section key={title} className="grid gap-5 md:grid-cols-[70px_1fr]"><div className="font-serif text-5xl text-gold">{String(i+1).padStart(2,'0')}</div><div><h2 className="font-serif text-4xl text-navy">{title}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{text}</p></div></section>)}</div></div></section>
  <section className="bg-cream py-16"><div className="mx-auto max-w-4xl px-5 lg:px-8"><div className="rounded-[2rem] bg-gold p-8 text-navy"><p className="text-xs font-black uppercase tracking-[.22em]">Il consiglio di Marghera Venice Apartments</p><p className="mt-4 font-serif text-3xl">Dedica almeno mezza giornata a San Giorgio. Se ami arte, design e processi artigianali, controlla prima il programma giornaliero: dimostrazioni e workshop possono rendere la visita ancora più interessante.</p></div><div className="mt-8 rounded-[2rem] bg-white p-8 shadow-soft"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">Informazioni ufficiali</p><p className="mt-3 text-slate-600">Date, orari, biglietti e attività possono cambiare. Consulta il sito ufficiale prima della visita.</p><a href="https://www.homofaber.com/it/biennial/homofaber-2026" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex rounded-full bg-navy px-6 py-3 font-bold text-white">Homo Faber 2026 – sito ufficiale ↗</a></div></div></section>
  <section className="py-20"><div className="mx-auto max-w-5xl px-5 lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-gold">Settembre a Venezia</p><h2 className="mt-3 font-serif text-4xl text-navy">Potrebbe interessarti anche</h2><div className="mt-7 grid gap-4 md:grid-cols-2"><Link href="/journal/mostra-del-cinema" className="rounded-3xl border border-slate-200 p-6 font-serif text-2xl text-navy transition hover:-translate-y-1 hover:shadow-soft">Mostra del Cinema 2026 <span className="text-gold">→</span></Link><Link href="/journal/venice-glass-week-2026" className="rounded-3xl border border-slate-200 p-6 font-serif text-2xl text-navy transition hover:-translate-y-1 hover:shadow-soft">The Venice Glass Week 2026 <span className="text-gold">→</span></Link></div><div className="mt-10 text-center"><Link href="/journal" className="inline-flex rounded-full bg-gold px-7 py-4 font-bold text-navy">Torna al Journal</Link></div></div></section>
</article></main><Footer/></>}
